PROGFILES =	

PROG = ${PROGFILES:.f90=}

SRCS =	

OBJS =	

LIBS =	
CC = cc
CFLAGS = -O
FC = f90
FFLAGS = -O
F90 = f90
F90FLAGS = -O
LDFLAGS = -s
all: $(PROG)

$(PROG): $(OBJS)
	$(???) $(LDFLAGS) $@.f90 -o $@ $(OBJS) $(LIBS)

clean:
	rm -f $(PROG) $(OBJS) *.mod

.SUFFIXES: $(SUFFIXES) .f90 .F90

.f90.o:
	$(F90) $(F90FLAGS) -c $<

.F90.o:
	$(F90) $(F90FLAGS) -c $<

