subroutine help_version(l_version)
implicit none
character(len=*),parameter     :: ident="@(#)help_version(3f): prints version information"
logical,intent(in)             :: l_version
character(len=:),allocatable   :: help_text(:)
integer                        :: i
logical                        :: stopit=.false.
stopit=.false.
if(l_version)then
help_text=[ CHARACTER(LEN=128) :: &
'@(#)PRODUCT:        GPF (General Purpose Fortran) utilities and examples>',&
'@(#)PROGRAM:        recipes(1)>',&
'@(#)DESCRIPTION:    basic recipes>',&
'@(#)VERSION:        1.0, 20180519>',&
'@(#)AUTHOR:         John S. Urban>',&
'@(#)COMPILED:       Thu, Sep 20th, 2018 1:01:51 PM>',&
'']
   WRITE(*,'(a)')(trim(help_text(i)(5:len_trim(help_text(i))-1)),i=1,size(help_text))
   stop ! if -version was specified, stop
endif
end subroutine help_version
!-----------------------------------------------------------------------------------------------------------------------------------
subroutine help_usage(l_help)
implicit none
character(len=*),parameter     :: ident="@(#)help_usage(3f): prints help information"
logical,intent(in)             :: l_help
character(len=:),allocatable :: help_text(:)
integer                        :: i
logical                        :: stopit=.false.
stopit=.false.
if(l_help)then
help_text=[ CHARACTER(LEN=128) :: &
'NAME                                                                            ',&
'   recipes(7f) - [RECIPES] list recipes                                         ',&
'                                                                                ',&
'DESCRIPTION                                                                     ',&
'  recipes as man pages                                                          ',&
'                                                                                ',&
'']
   WRITE(*,'(a)')(trim(help_text(i)),i=1,size(help_text))
   stop ! if -help was specified, stop
endif
end subroutine help_usage
!-----------------------------------------------------------------------------------------------------------------------------------
!>
!!##NAME
!!    recipes(7f) - [RECIPES] list recipes
!!
!!##DESCRIPTION
!!   recipes as man pages
!===================================================================================================================================
!===================================================================================================================================
!()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()!
!===================================================================================================================================
program recipes_man_pages
use ISO_FORTRAN_ENV, only : io => OUTPUT_UNIT
use M_kracken,only : kracken, lget                          ! add command-line parser module
implicit none
                                                            ! define command arguments, default values and crack command line
   call kracken('recipes','-help .false. -version .false.')
   call help_usage(lget('recipes_help'))                    ! if -help option is present, display help text and exit
   call help_version(lget('recipes_version'))               ! if -version option is present, display version text and exit
!-----------------------------------------------------------------------------------------------------------------------------------
write(io,'(a)')'NAME'
write(io,'(a)')'    deviled_eggs(5) - [RECIPES] Million Dollar Deviled Eggs'
write(io,'(a)')''
write(io,'(a)')'DESCRIPTION'
write(io,'(a)')'   The best deviled egg recipe, made slightly sweet and extra creamy'
write(io,'(a)')'   thanks to the addition of butter.'
write(io,'(a)')''
write(io,'(a)')'   * Prep Time   20 minutes'
write(io,'(a)')'   * Cook Time   15 minutes'
write(io,'(a)')'   * Total Time  20 minutes'
write(io,'(a)')''
write(io,'(a)')'   * Servings    24 deviled eggs'
write(io,'(a)')''
write(io,'(a)')'INGREDIENTS'
write(io,'(a)')''
write(io,'(a)')'   * 12 large eggs'
write(io,'(a)')'   * 1/4 cup mayo (55g)'
write(io,'(a)')'   * 1 Tablespoon butter softened to room temperature'
write(io,'(a)')'   * 2 teaspoons yellow mustard'
write(io,'(a)')'   * 2 teaspoons dijon mustard'
write(io,'(a)')'   * 2 teaspoons sweet gherkin pickle juice'
write(io,'(a)')'   * 1 teaspoon sugar'
write(io,'(a)')'   * 1/8 teaspoon salt'
write(io,'(a)')'   * 1/8 teaspoon pepper'
write(io,'(a)')'   * dash Tabasco sauce optional'
write(io,'(a)')'   * paprika for sprinkling'
write(io,'(a)')'   * bacon pieces optional'
write(io,'(a)')''
write(io,'(a)')'INSTRUCTIONS'
write(io,'(a)')''
write(io,'(a)')'How To Hard Boil Eggs'
write(io,'(a)')''
write(io,'(a)')'   1. Place eggs in a large saucepan and cover with water.'
write(io,'(a)')'   2. Transfer to stovetop over high heat until water begins to boil.'
write(io,'(a)')'   3. Boil for one minute, cover with lid, and remove from heat. Allow to'
write(io,'(a)')'      sit for 17 minutes and then drain and transfer to an ice bath.'
write(io,'(a)')'   4. Peel eggs and set aside.'
write(io,'(a)')''
write(io,'(a)')'How To Make Deviled Eggs'
write(io,'(a)')''
write(io,'(a)')'   1. Slice eggs in half lengthwise.'
write(io,'(a)')'   2. Remove yolks and transfer to a medium-sized bowl.'
write(io,'(a)')'   3. Add mayo, butter, mustards, pickle juice, sugar, salt, pepper,'
write(io,'(a)')'      and Tabasco sauce. Use a fork to mash well.'
write(io,'(a)')'   4. Spoon filling into each egg white. Sprinkle with paprika and bacon'
write(io,'(a)')'      (if using) and serve.'
write(io,'(a)')'   5. If desired, top with a small slice of sweet gherkin pickle, as'
write(io,'(a)')'      seen in pictures.'
write(io,'(a)')''
write(io,'(a)')'NUTRITION FACTS'
write(io,'(a)')''
write(io,'(a)')'   120 Calories per serving'
write(io,'(a)')''
write(io,'(a)')'AUTHOR'
write(io,'(a)')'   Samantha Merritt'
write(io,'(a)')'NAME'
write(io,'(a)')'    pancakes(5) - [RECIPES] pancakes'
write(io,'(a)')''
write(io,'(a)')'DESCRIPTION'
write(io,'(a)')''
write(io,'(a)')'   A pancake is a thin cake of batter fried in a pan or on a griddle;'
write(io,'(a)')'   a griddlecake; a flapjack.'
write(io,'(a)')''
write(io,'(a)')'INGREDIENTS'
write(io,'(a)')''
write(io,'(a)')'  * 1 1/2 cups all-purpose flour'
write(io,'(a)')'  * 3 1/2 teaspoons baking powder'
write(io,'(a)')'  * 1 teaspoon salt'
write(io,'(a)')'  * 1 tablespoon white sugar'
write(io,'(a)')'  * 1 1/4 cups milk'
write(io,'(a)')'  * 1 egg'
write(io,'(a)')'  * 3 tablespoons butter, melted'
write(io,'(a)')''
write(io,'(a)')'DIRECTIONS'
write(io,'(a)')''
write(io,'(a)')'In a large bowl, sift together the flour, baking powder, salt and'
write(io,'(a)')'sugar. Make a well in the center and pour in the milk, egg and melted'
write(io,'(a)')'butter; mix until smooth.'
write(io,'(a)')''
write(io,'(a)')'Heat a lightly oiled griddle or frying pan over medium high heat. Pour'
write(io,'(a)')'or scoop the batter onto the griddle, using approximately 1/4 cup for'
write(io,'(a)')'each pancake. Brown on both sides and serve hot.'
write(io,'(a)')''
write(io,'(a)')'yields 8 pancakes'
write(io,'(a)')''
write(io,'(a)')'NUTRITIONAL INFORMATION PER SERVING'
write(io,'(a)')''
write(io,'(a)')'  * Calories: 150'
write(io,'(a)')'  * Fat: 5.9g'
write(io,'(a)')'  * Cholesterol: 41mg'
write(io,'(a)')''
write(io,'(a)')'NAME'
write(io,'(a)')'    cincinatti_chili(5) - [RECIPES] cincinatti chili'
write(io,'(a)')''
write(io,'(a)')'DESCRIPTION'
write(io,'(a)')''
write(io,'(a)')'   Authentic Cincinnati Chili Recipe'
write(io,'(a)')''
write(io,'(a)')'   This is the actual recipe from Skyline. It was printed in the Cincy'
write(io,'(a)')'   Inquirer in the early 70s.'
write(io,'(a)')''
write(io,'(a)')'   "This was handed down to me by Mom, a Cincinnati native. Skimming the'
write(io,'(a)')'   fat makes this a healthier version than most, and gives it the right'
write(io,'(a)')'   consistency. I like mine 4-way, with spaghetti, raw chopped onions,'
write(io,'(a)')'   grated mild cheddar, and oyster crackers!" — Melissa Hamilton'
write(io,'(a)')''
write(io,'(a)')'INGREDIENTS'
write(io,'(a)')''
write(io,'(a)')'  •o 2 pounds lean ground beef'
write(io,'(a)')'  •o 1 quart water, or amount to cover'
write(io,'(a)')'  •o 2 onions, finely chopped'
write(io,'(a)')'  •o 1 (15 ounce) can tomato sauce'
write(io,'(a)')'  •o 2 tablespoons vinegar'
write(io,'(a)')'  •o 2 teaspoons Worcestershire sauce'
write(io,'(a)')'  •o 4 cloves garlic, minced'
write(io,'(a)')'  •o 1/2 (1 ounce) square unsweetened chocolate'
write(io,'(a)')'  •o 1/4 cup chili powder'
write(io,'(a)')'  •o 1 1/2 teaspoons salt'
write(io,'(a)')'  •o 1 teaspoon ground cumin'
write(io,'(a)')'  •o 1 teaspoon ground cinnamon'
write(io,'(a)')'  •o 1/2 teaspoon ground cayenne pepper'
write(io,'(a)')'  •o 5 whole cloves'
write(io,'(a)')'  •o 5 whole allspice berries. FYI- 1t. of ground=5 berries-- so you need 1t. ground allspice'
write(io,'(a)')'  •o 1 bay leaf'
write(io,'(a)')''
write(io,'(a)')'DIRECTIONS'
write(io,'(a)')''
write(io,'(a)')' 1. Place the ground beef in a large pan, cover with about 1 quart of cold'
write(io,'(a)')'    water, and bring to a boil, stirring and breaking up the beef with a fork'
write(io,'(a)')'    to a fine texture. Slowly boil until the meat is thoroughly cooked, about'
write(io,'(a)')'    30 minutes, then remove from heat and refrigerate in the pan overnight.'
write(io,'(a)')' 2. The next day, skim the solid fat from the top of the pan, and discard the'
write(io,'(a)')'    fat. Place the beef mixture over medium heat, and stir in the onions,'
write(io,'(a)')'    tomato sauce, vinegar, Worcestershire sauce, garlic, chocolate, chili'
write(io,'(a)')'    powder, salt, cumin, cinnamon, cayenne pepper, cloves, allspice berries,'
write(io,'(a)')'    and bay leaf. Bring to a boil, reduce heat to a simmer, and cook, stirring'
write(io,'(a)')'    occasionally, for 3 hours. Add water if necessary to prevent the chili from'
write(io,'(a)')'    burning.'
write(io,'(a)')''
write(io,'(a)')'Kitchen-Friendly View'
write(io,'(a)')''
write(io,'(a)')'  • PREP      15 mins'
write(io,'(a)')'  • COOK      3 hrs 30 mins'
write(io,'(a)')'  • READY IN  11 hrs 45 mins'
write(io,'(a)')''
write(io,'(a)')'Serving Size:         1/10 of a recipe'
write(io,'(a)')'Servings Per Recipe:  10'
write(io,'(a)')''
write(io,'(a)')'Amount Per Serving'
write(io,'(a)')''
write(io,'(a)')'Calories:             225'
write(io,'(a)')'Calories from Fat:    113'
write(io,'(a)')''
write(io,'(a)')'   % Daily Value *'
write(io,'(a)')''
write(io,'(a)')'  •o Total Fat 12.6g 19 %'
write(io,'(a)')'  •o Saturated Fat 4.9g 25 %'
write(io,'(a)')'  •o Cholesterol 59mg 20 %'
write(io,'(a)')'  •o Sodium 674mg 27 %'
write(io,'(a)')'  •o Potassium 515mg 14 %'
write(io,'(a)')'  •o Total Carbohydrates 10.1g 3 %'
write(io,'(a)')'  •o Dietary Fiber 3.1g 12 %'
write(io,'(a)')'  •o Protein 19.1g 38 %'
write(io,'(a)')'  •o Sugars 4g'
write(io,'(a)')'  •o Vitamin A 23 %'
write(io,'(a)')'  •o Vitamin C 15 %'
write(io,'(a)')'  •o Calcium 6 %'
write(io,'(a)')'  •o Iron 31 %'
write(io,'(a)')'  •o Thiamin 10 %'
write(io,'(a)')'  •o Niacin 59 %'
write(io,'(a)')'  •o Vitamin B6 27 %'
write(io,'(a)')'  •o Magnesium 14 %'
write(io,'(a)')'  •o Folate 13 %'
write(io,'(a)')''
write(io,'(a)')'  • * Percent Daily Values are based on a 2,000 calorie diet. Your daily values'
write(io,'(a)')'    may be higher or lower depending on your calorie needs.'
write(io,'(a)')'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━�'
write(io,'(a)')''
write(io,'(a)')'I grew up in Cincinnati and our chili of choice was Gold Star. For close to 20'
write(io,'(a)')'years I have been searching for a decent Cincy chili recipe to no avail...until'
write(io,'(a)')'I found this one! I did augment the recipe to make it more like Gold Stars.'
write(io,'(a)')'(Skyline is more "earthy" than I like) I added hot water every 1/2 hour or so-'
write(io,'(a)')'maybe 1/2 cup every time to mellow it out and keep it from getting too thick. I'
write(io,'(a)')'also added ~ 2 teaspoons of light brown sugar, 1 teaspoon cardamom, and 1/2'
write(io,'(a)')'teaspoon ground cloves. The result was more like Gold Star''s chili recipe which'
write(io,'(a)')'is my preference. Thank you for posting this recipe...it quells my craving at'
write(io,'(a)')'least until I make the trip back home to Cincinnati!'
write(io,'(a)')''
write(io,'(a)')'—Patty'
write(io,'(a)')''
write(io,'(a)')'This was awesome and tasted soooo much like the real thing, but without the'
write(io,'(a)')'grease! I did not have whole cloves or the allspice berries, so I used 1 1/2'
write(io,'(a)')'tsp of ground. I did take another''s advice and used beef broth instead of'
write(io,'(a)')'water, and it was saltier than I''d like. I will use water next time! THANK YOU'
write(io,'(a)')'THANK YOU Melissa for this great recipe!!'
write(io,'(a)')'NAME'
write(io,'(a)')'    lasagna(5) - [RECIPES] lasagna'
write(io,'(a)')''
write(io,'(a)')'INGREDIENTS'
write(io,'(a)')''
write(io,'(a)')'   * 1 pound sweet Italian sausage'
write(io,'(a)')'   * 3/4 pound lean ground beef'
write(io,'(a)')'   * 1/2 cup minced onion'
write(io,'(a)')'   * 2 cloves garlic, crushed'
write(io,'(a)')'   * 1 (28 ounce) can crushed tomatoes'
write(io,'(a)')'   * 2 (6 ounce) cans tomato paste'
write(io,'(a)')'   * 2 (6.5 ounce) cans canned tomato sauce'
write(io,'(a)')'   * 1/2 cup water'
write(io,'(a)')'   * 2 tablespoons white sugar'
write(io,'(a)')'   * 1 1/2 teaspoons dried basil leaves'
write(io,'(a)')'   * 1/2 teaspoon fennel seeds'
write(io,'(a)')'   * 1 teaspoon Italian seasoning'
write(io,'(a)')'   * 1 tablespoon salt'
write(io,'(a)')'   * 1/4 teaspoon ground black pepper'
write(io,'(a)')'   * 4 tablespoons chopped fresh parsley'
write(io,'(a)')'   * 12 lasagna noodles'
write(io,'(a)')'   * 16 ounces ricotta cheese'
write(io,'(a)')'   * 1 egg'
write(io,'(a)')'   * 1/2 teaspoon salt'
write(io,'(a)')'   * 3/4 pound mozzarella cheese, sliced'
write(io,'(a)')'   * 3/4 cup grated Parmesan cheese'
write(io,'(a)')''
write(io,'(a)')'DIRECTIONS'
write(io,'(a)')''
write(io,'(a)')'1. In a Dutch oven, cook sausage, ground beef, onion, and garlic over'
write(io,'(a)')'   medium heat until well browned. Stir in crushed tomatoes, tomato paste,'
write(io,'(a)')'   tomato sauce, and water. Season with sugar, basil, fennel seeds, Italian'
write(io,'(a)')'   seasoning, 1 tablespoon salt, pepper, and 2 tablespoons parsley. Simmer,'
write(io,'(a)')'   covered, for about 1 1/2 hours, stirring occasionally.'
write(io,'(a)')''
write(io,'(a)')'2. Bring a large pot of lightly salted water to a boil. Cook lasagna'
write(io,'(a)')'   noodles in boiling water for 8 to 10 minutes. Drain noodles, and rinse'
write(io,'(a)')'   with cold water. In a mixing bowl, combine ricotta cheese with egg,'
write(io,'(a)')'   remaining parsley, and 1/2 teaspoon salt.'
write(io,'(a)')''
write(io,'(a)')'3. Preheat oven to 375 degrees F (190 degrees C).'
write(io,'(a)')''
write(io,'(a)')'4. To assemble, spread 1 1/2 cups of meat sauce in the bottom of a 9x13'
write(io,'(a)')'   inch baking dish. Arrange 6 noodles lengthwise over meat sauce. Spread'
write(io,'(a)')'   with one half of the ricotta cheese mixture. Top with a third of'
write(io,'(a)')'   mozzarella cheese slices. Spoon 1 1/2 cups meat sauce over mozzarella,'
write(io,'(a)')'   and sprinkle with 1/4 cup Parmesan cheese. Repeat layers, and top with'
write(io,'(a)')'   remaining mozzarella and Parmesan cheese. Cover with foil: to prevent'
write(io,'(a)')'   sticking, either spray foil with cooking spray, or make sure the foil'
write(io,'(a)')'   does not touch the cheese.'
write(io,'(a)')''
write(io,'(a)')'5. Bake in preheated oven for 25 minutes. Remove foil, and bake an'
write(io,'(a)')'   additional 25 minutes. Cool for 15 minutes before serving.'
write(io,'(a)')''
write(io,'(a)')'NAME'
write(io,'(a)')'    mac_and_cheese(5) - [RECIPES] mac and cheese'
write(io,'(a)')''
write(io,'(a)')'DESCRIPTIONS'
write(io,'(a)')''
write(io,'(a)')'What You Need'
write(io,'(a)')''
write(io,'(a)')' o  1/4 cup  butter or margarine, divided'
write(io,'(a)')' o  1/4 cup  flour'
write(io,'(a)')' o    1 cup  milk'
write(io,'(a)')' o  1/2 lb.  (8 oz.) VELVEETA®, cut into 1/2-inch cubes'
write(io,'(a)')' o    2 cups  elbow macaroni, cooked'
write(io,'(a)')' o  1/2 cup  KRAFT Shredded Cheddar Cheese'
write(io,'(a)')' o    6 RITZ Crackers, crushed (about 1/4 cup)'
write(io,'(a)')''
write(io,'(a)')'MAKE IT'
write(io,'(a)')''
write(io,'(a)')'   HEAT oven to 350°F.'
write(io,'(a)')''
write(io,'(a)')'   MELT 3 Tbsp. butter in medium saucepan on medium heat. Whisk'
write(io,'(a)')'   in flour; cook 2 min., stirring constantly. Gradually stir'
write(io,'(a)')'   in milk. Bring to boil; cook and stir 3 to 5 min. or until'
write(io,'(a)')'   thickened. Add VELVEETA; cook 3 min. or until melted, stirring'
write(io,'(a)')'   frequently. Stir in macaroni.'
write(io,'(a)')''
write(io,'(a)')'   SPOON into 2-qt. casserole sprayed with cooking spray;'
write(io,'(a)')'   sprinkle with Cheddar. Melt remaining butter; toss with cracker'
write(io,'(a)')'   crumbs. Sprinkle over casserole.'
write(io,'(a)')''
write(io,'(a)')'BAKE 20 min. or until heated through.'
write(io,'(a)')''
write(io,'(a)')'KRAFT KITCHENS TIPS'
write(io,'(a)')''
write(io,'(a)')'   HEALTHY LIVING'
write(io,'(a)')''
write(io,'(a)')'        Save 50 calories and 8g of fat, including 5g of saturated fat, per'
write(io,'(a)')'        serving by preparing with fat-free milk, 2% Milk VELVEETA, KRAFT'
write(io,'(a)')'        2% Milk Shredded Cheddar Cheese and RITZ Reduced Fat Crackers.'
write(io,'(a)')''
write(io,'(a)')'   SPECIAL EXTRA'
write(io,'(a)')''
write(io,'(a)')'        Stir in 1/4 cup OSCAR MAYER Real Bacon Bits with the cooked macaroni.'
write(io,'(a)')''
write(io,'(a)')'   SUBSTITUTE'
write(io,'(a)')''
write(io,'(a)')'        Substitute KRAFT Deluxe Pasteurized Process American Cheese for the VELVEETA.'
write(io,'(a)')'NAME'
write(io,'(a)')'    pumpkin_roll(5) - [RECIPES] pumpkin roll'
write(io,'(a)')''
write(io,'(a)')'DESCRIPTION'
write(io,'(a)')'Libby''s Pumpkin Roll'
write(io,'(a)')''
write(io,'(a)')'Pumpkin cake, also called pumpkin roll, is easy to make and sure to please,'
write(io,'(a)')'perfect for Thanksgiving or Christmas parties. Try this pumpkin cream cheese'
write(io,'(a)')'recipe once and you''ll be making it often!'
write(io,'(a)')''
write(io,'(a)')'   o 45 min.prep time 2:30total time'
write(io,'(a)')'   o 10 servings'
write(io,'(a)')'   o 33533 Ratings'
write(io,'(a)')''
write(io,'(a)')'   CAKE'
write(io,'(a)')''
write(io,'(a)')'    o Powdered sugar'
write(io,'(a)')'    o 3/4 cup all-purpose flour'
write(io,'(a)')'    o 1/2 teaspoon baking powder'
write(io,'(a)')'    o 1/2 teaspoon baking soda'
write(io,'(a)')'    o 1/2 teaspoon ground cinnamon'
write(io,'(a)')'    o 1/2 teaspoon ground cloves'
write(io,'(a)')'    o 1/4 teaspoon salt'
write(io,'(a)')'    o 3 Land O Lakes^(R) All-Natural Eggs'
write(io,'(a)')'    o 1 cup sugar'
write(io,'(a)')'    o 2/3 cup LIBBY''S 100% Pure Pumpkin'
write(io,'(a)')'    o 1 cup chopped walnuts, if desired'
write(io,'(a)')''
write(io,'(a)')'   FILLING'
write(io,'(a)')''
write(io,'(a)')'    o 1 (8-ounce) package cream cheese, softened'
write(io,'(a)')'    o 1 cup sifted powdered sugar'
write(io,'(a)')'    o 6 tablespoons Land O Lakes^(R) Butter, softened'
write(io,'(a)')'    o 1 teaspoon vanilla'
write(io,'(a)')'    o Powdered sugar, if desired'
write(io,'(a)')''
write(io,'(a)')'DIRECTIONS'
write(io,'(a)')''
write(io,'(a)')'   Heat oven to 375DEGF. Grease 15x10x1-inch jelly-roll pan; line with'
write(io,'(a)')'   parchment or waxed paper. Grease and flour paper; set aside. Arrange'
write(io,'(a)')'   clean thin, cotton kitchen towel on counter; sprinkle with powdered'
write(io,'(a)')'   sugar.'
write(io,'(a)')''
write(io,'(a)')'   Combine flour, baking powder, baking soda, cinnamon, cloves and'
write(io,'(a)')'   salt in small bowl. Combine eggs and sugar in large bowl; beat'
write(io,'(a)')'   until thickened. Add pumpkin; beat until well mixed. Stir in flour'
write(io,'(a)')'   mixture. Spread batter evenly into prepared pan. Sprinkle with walnuts,'
write(io,'(a)')'   if desired.'
write(io,'(a)')''
write(io,'(a)')'   Bake for 13 to 15 minutes or until center springs back when lightly'
write(io,'(a)')'   touched. Immediately loosen cake from edges of pan; invert onto'
write(io,'(a)')'   prepared towel. Remove pan; carefully peel off paper. Roll up cake'
write(io,'(a)')'   in towel while hot, starting with 10-inch side. Cool completely on'
write(io,'(a)')'   wire rack.'
write(io,'(a)')''
write(io,'(a)')'   Beat cream cheese, 1 cup powdered sugar, softened butter and vanilla in'
write(io,'(a)')'   small bowl until smooth. Carefully unroll cake; remove towel. Spread'
write(io,'(a)')'   cream cheese mixture over cake. Reroll cake. Wrap in plastic food'
write(io,'(a)')'   wrap; refrigerate at least one hour. Sprinkle with powdered sugar'
write(io,'(a)')'   before serving, if desired..'
write(io,'(a)')''
write(io,'(a)')'RECIPE TIP'
write(io,'(a)')''
write(io,'(a)')'- Be sure to put enough powdered sugar on the towel before rolling up cake so'
write(io,'(a)')'it will not stick.'
write(io,'(a)')''
write(io,'(a)')'Recipe courtesy of NESTLÉ® USA and www.VeryBestBaking.com.'
write(io,'(a)')''
write(io,'(a)')'Nutrition Facts (1 serving)'
write(io,'(a)')''
write(io,'(a)')'o Calories: 400'
write(io,'(a)')'o Fat: 24g'
write(io,'(a)')'o Cholesterol: 105mg'
write(io,'(a)')'o Sodium: 290mg'
write(io,'(a)')'o Carbohydrates: 41g'
write(io,'(a)')'o Dietary Fiber: 2g'
write(io,'(a)')'o Protein: 7g'
write(io,'(a)')''
write(io,'(a)')'    I was running short of time so I let the baked pumpkin cool flat on the'
write(io,'(a)')'    towel and then cut it in 3 pieces and layered it will the filling!! SO EASY'
write(io,'(a)')'    if you are afraid of making a pumpkin roll! and always a hit!!'
write(io,'(a)')''
write(io,'(a)')'Posted Dec 09 2013 by jo'
write(io,'(a)')''
write(io,'(a)')'    Fantastic treat to have for Thanksgiving week. I also make toasted cinnamon'
write(io,'(a)')'    pecans to sprinkle over the roll and around the serving plate, which adds a'
write(io,'(a)')'    nice autumn flavor to it as well.'
write(io,'(a)')''
write(io,'(a)')'    i added 2-4 drops of orange extract instead of vanilla, and it was'
write(io,'(a)')'    excellent, made it seem a little "lighter" when eating it, and sooo'
write(io,'(a)')'    refreshing.'
write(io,'(a)')''
write(io,'(a)')'Posted Dec 17 2011 by Kim'
write(io,'(a)')''
write(io,'(a)')'    This cake was delicious!! I made it for Thanksgiving, and there was none'
write(io,'(a)')'    left. However, I only added 2/3 cups sugar to the cake, and added an extra'
write(io,'(a)')'    1/4 cup pumpkin. Also, for the frosting, I added a little more milk to make'
write(io,'(a)')'    it more creamy. It was very good and delicious though.'
write(io,'(a)')''
write(io,'(a)')'Posted Nov 24 2011 by Nadja'
write(io,'(a)')''
write(io,'(a)')'    I make this pumpkin roll every holiday, and Birthdays and it is the best'
write(io,'(a)')'    out there! I usually double stuff it with the cream cheese and walnut'
write(io,'(a)')'    filling tho.'
write(io,'(a)')''
write(io,'(a)')'    I have been making these for years! I make several for the holidays'
write(io,'(a)')'    starting with Thanksgiving and freeze them, this makes slicing so much'
write(io,'(a)')'    easier. I can slice off what I need and keep the rest frozen, doesn''t take'
write(io,'(a)')'    long for it to thaw and be enjoyed. One thing is that the cake always'
write(io,'(a)')'    cracks, sometime splitting completely when unrolling, not sure why but it'
write(io,'(a)')'    doesn''t affect the flavor'
write(io,'(a)')''
write(io,'(a)')'Posted Nov 20 2011 by Sandra'
write(io,'(a)')''
write(io,'(a)')'    I have been making these pumpkin rolls for years. I add crushed walnuts to'
write(io,'(a)')'    some for a twist. I slice them and freeze them so that they can be pulled'
write(io,'(a)')'    out and thawed with ease.'
write(io,'(a)')''
write(io,'(a)')'    THis is really not difficult to make, just time consuming. Preparation of'
write(io,'(a)')'    the pans and towels before beginning is key. 1 Large can of Libby''s pumpkin'
write(io,'(a)')'    makes 5 rolls.'
write(io,'(a)')''
write(io,'(a)')'Posted Oct 15 2011 by Ginger'
write(io,'(a)')''
write(io,'(a)')'    I have been doing this roll for about 8 years and my kids love it. Gotta'
write(io,'(a)')'    watch the calories though. Definitely not for a low fat diet. I also freeze'
write(io,'(a)')'    my sliced rolls and put them in Tupperware to protect flavor. They come out'
write(io,'(a)')'    awesome with a little defrost and are even great a little frozen.'
write(io,'(a)')''
write(io,'(a)')'    Tips for ease: Use a 100% cotton flat wrinkle free kitchen dish towel.'
write(io,'(a)')'    Using a sifter, cover the towel liberally with powdered sugar--about 1/4'
write(io,'(a)')'    inch. The more powdered sugar on the towel, the easier it is to unroll the'
write(io,'(a)')'    pumpkin roll without cracks. Make sure you allow the roll to cool for at'
write(io,'(a)')'    least 30 to 35 minutes before unrolling. If the roll should crack...not to'
write(io,'(a)')'    worry....sprinkle the roll with powdered sugar and nobody will see the'
write(io,'(a)')'    crack.'
write(io,'(a)')'NAME'
write(io,'(a)')'    soft_pretzel(5) - [RECIPES] soft pretzels'
write(io,'(a)')'DESCRIPTION'
write(io,'(a)')''
write(io,'(a)')'  Alton''s Homemade Soft Pretzels'
write(io,'(a)')''
write(io,'(a)')'  Alton adapts an old bagel recipe and voila: homemade soft pretzels!'
write(io,'(a)')''
write(io,'(a)')'INGREDIENTS'
write(io,'(a)')''
write(io,'(a)')' o 1 1/2 cups warm (110 to 115 degrees F) water'
write(io,'(a)')' o 1 tablespoon sugar'
write(io,'(a)')' o 2 teaspoons kosher salt'
write(io,'(a)')' o 1 package active dry yeast'
write(io,'(a)')' o 22 ounces all-purpose flour, approximately 4 1/2 cups'
write(io,'(a)')' o 2 ounces unsalted butter, melted'
write(io,'(a)')' o Vegetable oil, for pan'
write(io,'(a)')' o 10 cups water'
write(io,'(a)')' o 2/3 cup baking soda'
write(io,'(a)')' o 1 large egg yolk beaten with 1 tablespoon water'
write(io,'(a)')' o Pretzel salt'
write(io,'(a)')''
write(io,'(a)')'DIRECTIONS'
write(io,'(a)')''
write(io,'(a)')'   Combine the water, sugar and kosher salt in the bowl of a stand mixer'
write(io,'(a)')'   and sprinkle the yeast on top. Allow to sit for 5 minutes or until the'
write(io,'(a)')'   mixture begins to foam. Add the flour and butter and, using the dough'
write(io,'(a)')'   hook attachment, mix on low speed until well combined. Change to medium'
write(io,'(a)')'   speed and knead until the dough is smooth and pulls away from the side'
write(io,'(a)')'   of the bowl, approximately 4 to 5 minutes. Remove the dough from the'
write(io,'(a)')'   bowl, clean the bowl and then oil it well with vegetable oil. Return'
write(io,'(a)')'   the dough to the bowl, cover with plastic wrap and sit in a warm place'
write(io,'(a)')'   for approximately 50 to 55 minutes or until the dough has doubled in size.'
write(io,'(a)')''
write(io,'(a)')'   Preheat the oven to 450 degrees F. Line 2 half-sheet pans with parchment'
write(io,'(a)')'   paper and lightly brush with the vegetable oil. Set aside.'
write(io,'(a)')''
write(io,'(a)')'   Bring the 10 cups of water and the baking soda to a rolling boil in an'
write(io,'(a)')'   8-quart saucepan or roasting pan.'
write(io,'(a)')''
write(io,'(a)')'   In the meantime, turn the dough out onto a slightly oiled work surface and'
write(io,'(a)')'   divide into 8 equal pieces. Roll out each piece of dough into a 24-inch'
write(io,'(a)')'   rope. Make a U-shape with the rope, holding the ends of the rope, cross'
write(io,'(a)')'   them over each other and press onto the bottom of the U in order to form'
write(io,'(a)')'   the shape of a pretzel. Place onto the parchment-lined half sheet pan.'
write(io,'(a)')''
write(io,'(a)')'   Place the pretzels into the boiling water, 1 by 1, for 30 seconds. Remove'
write(io,'(a)')'   them from the water using a large flat spatula. Return to the half sheet'
write(io,'(a)')'   pan, brush the top of each pretzel with the beaten egg yolk and water'
write(io,'(a)')'   mixture and sprinkle with the pretzel salt. Bake until dark golden brown'
write(io,'(a)')'   in color, approximately 12 to 14 minutes. Transfer to a cooling rack'
write(io,'(a)')'   for at least 5 minutes before serving.'
write(io,'(a)')''
write(io,'(a)')'   Recipe courtesy of Alton Brown, 2007'
end program recipes_man_pages

