      PROGRAM STMTST
C@(#) TEST 2 OF 3 FOR (W) STEAM PROPERTY FUNCTIONS. the short tests
C
C     PREPARED BY C.P.SAALBACH, 09/17/79.
C     STMTST IS USED TO ASSURE THAT INDIVIDUAL RESULTS WHICH ARE
C     RETURNED BY THE STEAM PROPERTY FUNCTIONS ARE CORRECT.
C     THE RESULTS ARE PRINTED AND MAY BE COMPARED WITH THE STEAM
C     PROPERTY TABLE VALUES WHICH APPEAR IN THE STANDARD REFERENCE,
C     "ASME STEAM TABLES 1967", PUBLISHED BY THE AMERICAN SOCIETY
C     OF MECHANICAL ENGINEERS.  ALSO PRINTED, AS A CONVENIENCE TO
C     QUICKLY CHECK THAT THE RESULTS HAVE NOT CHANGED, ARE PERIODIC
C     CHECKSUMS AND A TOTAL OF ALL CHECKSUMS.
C     INPUT CONSISTS OF UPPER AND LOWER LIMITS OF TEMPERATURE AND
C     PRESSURE, AND INCREMENTS OF SAME AT WHICH STEAM PROPERTY RESULTS
C     ARE CALCULATED AND DISPLAYED.  CURRENT VALUES USED ARE RECOMMENDED
C     SINCE THEY PROVIDE A SAMPLE OF VALUES THROUGHOUT THE TOTAL
C     REGIONS IN WHICH THE ROUTINES ARE APPLICABLE.
C
      implicit double precision(a-h, o-z)
      DIMENSION P(500),T(500),H(500),S(500),V(500),Z1(500),Z2(500)
      DIMENSION Z3(500)
      WRITE(6,1001)
1001  FORMAT(1H1,16HTESTS STARTED.   //)
      SUMT=0.d0
      P32=PSL(32.0d0)
      PCT=PSL(705.47d0)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(P32,PCT,PMIN,PMAX,DELP)
      CALL LIMITS(32.0d0,705.47d0,TMIN,TMAX,DELT)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      CALL XARRAY(T,TMIN,TMAX,DELT,NT)
C
C CALCULATE HSL(T),PSL(T),SSL(T),VSL(T)
C
      SUM=0.d0
      WRITE(6,201)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      DO 1 I=1,NT
      Z1(I)=PSL(T(I))
      H(I)=HSL(T(I))
      S(I)=SSL(T(I))
      V(I)=VSL(T(I))
      Z2(I)=0.d0
      IF(H(I).LE.906.d0) Z2(I)=TSLH(H(I))
      WRITE(6,105) T(I),Z1(I),H(I),S(I),V(I),Z2(I)
      SUM=SUM+T(I)+Z1(I)+H(I)+S(I)+V(I)+Z2(I)
    1 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
C
C CALCULATE PSV(S)
C
      SUM=0.d0
      WRITE(6,202)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      HX=HSS(PMIN,TMIN,S(1),VX)
      HX=HSS(PMAX,TMAX,S(NT),VX)
      CALL HSARRY(S,NT)
      DO 2 I=1,NT
      Z1(I)=PSV(S(I))
      WRITE(6,103) S(I),Z1(I)
      SUM=SUM+S(I)+Z1(I)
    2 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
C
C CALCULATE P,HSV(P),TSL(P)
C
      SUM=0.d0
      WRITE(6,204)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      DO 3 I=1,NP
      H(I)=HSV(P(I),TX,SX,VX)
      Z1(I)=TSL(P(I))
      WRITE(6,103) P(I),H(I),Z1(I)
      SUM=SUM+P(I)+H(I)+Z1(I)
    3 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
C
C CALCULATE CONDL(P,T),PRLIQ(P,T)
C
      N=0
    4 CONTINUE
      SUM=0.d0
      WRITE(6,205)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(P32,15500.d0,PMIN,PMAX,DELP)
      CALL LIMITS(32.0d0,705.47d0,TMIN,TMAX,DELT)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      DO 6 I=1,NP
      TMX=705.47d0
      IF(P(I).LT.PCT) TMX=TSL(P(I))
      IF(TMIN.GT.TMX) GO TO 6
      CALL XARRAY(T,TMIN,TMX,DELT,NT)
      DO 5 J=1,NT
      Z1(J)=CONDL(P(I),T(J))
      Z2(J)=PRLIQ(P(I),T(J))
      WRITE(6,104) P(I),T(J),Z1(J),Z2(J)
      SUM=SUM+P(I)+T(J)+Z1(J)+Z2(J)
    5 CONTINUE
    6 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
      N=N+1
      IF(N.LT.2) GO TO 4
C
C CALCULATE VISL(P,T)
C
      N=0
    7 CONTINUE
      SUM=0.d0
      WRITE(6,206)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(P32,15500.d0,PMIN,PMAX,DELP)
      CALL LIMITS(32.0d0,705.47d0,TMIN,TMAX,DELT)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      DO 9 I=1,NP
      TMX=705.47d0
      IF(P(I).LT.PCT) TMX=TSL(P(I))
      IF(TMIN.GT.TMX) GO TO 9
      CALL XARRAY(T,TMIN,TMX,DELT,NT)
      DO 8 J=1,NT
      Z1(J)=VISL(P(I),T(J))
      WRITE(6,103) P(I),T(J),Z1(J)
      SUM=SUM+P(I)+T(J)+Z1(J)
    8 CONTINUE
    9 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
      N=N+1
      IF(N.LT.2) GO TO 7
C
C CALCULATE CPL(P,T),HCL(P,T),VCL(P,T)
C
      N=0
   10 CONTINUE
      SUM=0.d0
      WRITE(6,207)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(P32,15500.d0,PMIN,PMAX,DELP)
      CALL LIMITS(32.0d0,705.47d0,TMIN,TMAX,DELT)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      DO 12 I=1,NP
      TMX=705.47d0
      IF(P(I).LT.PCT) TMX=TSL(P(I))
      IF(TMIN.GT.TMX) GO TO 12
      CALL XARRAY(T,TMIN,TMX,DELT,NT)
      DO 11 J=1,NT
      Z1(J)=CPL(P(I),T(J))
      H(J)=HCL(P(I),T(J),SX)
      V(J)=VCL(P(I),T(J))
      WRITE(6,102) P(I),T(J),Z1(J),H(J),V(J)
      SUM=SUM+P(I)+T(J)+Z1(J)+H(J)+V(J)
   11 CONTINUE
   12 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
      N=N+1
      IF(N.LT.2) GO TO 10
C
C CALCULATE HSSICL(P,S),SSSICL(P,H)
C
      N=0
   13 CONTINUE
      SUM=0.0d0
      WRITE(6,208)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(P32,15500.d0,PMIN,PMAX,DELP)
      CALL LIMITS(32.0d0,705.47d0,TMIN,TMAX,DELT)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      DO 15 I=1,NP
      TMX=TMAX
      IF(P(I).LT.PCT) TMX=TSL(P(I))
      IF(TMIN.GT.TMX) GO TO 15
      CALL XARRAY(T,TMIN,TMX,DELT,NT)
      H(1)=HCL(P(I),TMIN,S(1))
      H(NT)=HCL(P(I),TMX,S(NT))
      CALL HSARRY(S,NT)
      CALL HSARRY(H,NT)
      DO 14 J=1,NT
      Z1(J)=HSSICL(P(I),S(J),T1)
      Z2(J)=SSSICL(P(I),H(J),T2)
      WRITE(6,106) P(I),T1,S(J),Z1(J),T2,H(J),Z2(J)
      SUM=SUM+P(I)+T1+S(J)+Z1(J)+T2+H(J)+Z2(J)
   14 CONTINUE
   15 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
      N=N+1
      IF(N.LT.2) GO TO 13
C
C CALCULATE CONDV(P,T),PRSTM(P,T)
C
      N=0
   16 CONTINUE
      SUM=0.0d0
      WRITE(6,209)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(0.01d0,15500.d0,PMIN,PMAX,DELP)
      CALL LIMITS(32.0d0,1600.d0,TMIN,TMAX,DELT)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      DO 18 I=1,NP
      TMN=0.0d0
      IF(P(I).LT.P32) TMN=32.0d0
      IF(P(I).GT.PCT) TMN=705.47d0
      IF(TMN.EQ.0.0d0) TMN=TSL(P(I))
      IF(TMN.LT.TMIN) TMN=TMIN
      IF(TMN.GT.TMAX) GO TO 18
      CALL XARRAY(T,TMN,TMAX,DELT,NT)
      DO 17 J=1,NT
      Z1(J)=CONDV(P(I),T(J))
      Z2(J)=0.d0
      IF(T(J).GE.36.0d0.AND.T(J).LE.1596.d0) Z2(J)=PRSTM(P(I),T(J))
      WRITE(6,104) P(I),T(J),Z1(J),Z2(J)
      SUM=SUM+P(I)+T(J)+Z1(J)+Z2(J)
   17 CONTINUE
   18 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
      N=N+1
      IF(N.LT.2) GO TO 16
C
C CALCULATE CPV(P,T),HSS(P,T),HSSISS(P,S),SSSISS(P,H)
C
      N=0
   19 CONTINUE
      SUM=0.0d0
      WRITE(6,210)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(0.01d0,15500.0d0,PMIN,PMAX,DELP)
      CALL LIMITS(32.d0,1600.d0,TMIN,TMAX,DELT)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      DO 21 I=1,NP
      TMN=0.0d0
      IF(P(I).LT.P32) TMN=32.0d0
      IF(P(I).GT.PCT) TMN=705.47d0
      IF(TMN.EQ.0.0d0) TMN=TSL(P(I))
      IF(TMN.LT.TMIN) TMN=TMIN
      IF(TMN.GT.TMAX) GO TO 21
      CALL XARRAY(T,TMN,TMAX,DELT,NT)
      H(1)=HSS(P(I),TMN,S(1),VX)
      H(NT)=HSS(P(I),TMAX,S(NT),VX)
      CALL HSARRY(H,NT)
      CALL HSARRY(S,NT)
      DO 20 J=1,NT
      Z1(J)=HSS(P(I),T(J),SX,VX)
      Z2(J)=HSSISS(P(I),S(J),T1,VX,XX)
      Z3(J)=0.0d0
      IF(H(J).LE.1800.d0) Z3(J)=SSSISS(P(I),H(J),T2,VX,XX)
      WRITE(6,107) P(I),T(J),Z1(J),T1,S(J),Z2(J),T2,H(J),Z3(J)
      SUM=SUM+P(I)+T(J)+Z1(J)+T1+S(J)+Z2(J)+T2+H(J)+Z3(J)
   20 CONTINUE
   21 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
      N=N+1
      IF(N.LT.2) GO TO 19
C
C CALCULATE VISV(P,T)
C
      N=0
   22 CONTINUE
      SUM=0.0d0
      WRITE(6,211)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(0.01d0,15500.d0,PMIN,PMAX,DELP)
      CALL LIMITS(32.0d0,1600.d0,TMIN,TMAX,DELT)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      DO 24 I=1,NP
      TMN=0.0d0
      IF(P(I).LT.P32) TMN=32.0d0
      IF(P(I).GT.PCT) TMN=705.47d0
      IF(TMN.EQ.0.d0) TMN=TSL(P(I))
      IF(TMN.LT.TMIN) TMN=TMIN
      IF(TMN.GT.TMAX) GO TO 24
      CALL XARRAY(T,TMN,TMAX,DELT,NT)
      DO 23 J=1,NT
      Z1(J)=0.0d0
      IF(T(J).GE.36.0d0.AND.T(J).LE.1596.d0) Z1(J)=CPV(P(I),T(J),VX)
      Z2(J)=VISV(P(I),T(J))
      WRITE(6,104) P(I),T(J),Z1(J),Z2(J)
      SUM=SUM+P(I)+T(J)+Z1(J)+Z2(J)
   23 CONTINUE
   24 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
      N=N+1
      IF(N.LT.2) GO TO 22
C
C CALCULATE CRFLO(P,H)
C
      N=0
      SUM=0.
      WRITE(6,212)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(0.01d0,15500.d0,PMIN,PMAX,DELP)
      CALL LIMITS(32.0d0,1600.d0,TMIN,TMAX,DELT)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      DO 26 I=1,NP
      TMN=0.0d0
      IF(P(I).LT.P32) TMN=32.0d0
      IF(P(I).GT.PCT) TMN=705.47d0
      IF(TMN.EQ.0.0d0) TMN=TSL(P(I))
      IF(TMN.LT.TMIN) TMN=TMIN
      IF(TMN.GT.TMAX) GO TO 26
      CALL XARRAY(T,TMN,TMAX,DELT,NT)
      DO 25 J=1,NT
      Z1(J)=0.d0
      HX=HSS(P(I),T(J),SX,VX)
      IF(HX.LE.1800.d0) Z1(J)=CRFLO(P(I),HX,D)/P(I)
      WRITE(6,103) P(I),HX,Z1(J)
      SUM=SUM+P(I)+HX+Z1(J)
   25 CONTINUE
   26 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
C
C CALCULATE CRVEL(P,H)
C
      N=0
      SUM=0.0d0
      WRITE(6,213)
      READ(5,100) PMIN,PMAX,DELP
      READ(5,100) TMIN,TMAX,DELT
      CALL LIMITS(0.01d0,15500.d0,PMIN,PMAX,DELP)
      CALL LIMITS(32.0d0,1600.d0,TMIN,TMAX,DELT)
      WRITE(6,214) PMIN,PMAX,DELP
      WRITE(6,215) TMIN,TMAX,DELT
      WRITE(6,101)
      CALL XARRAY(P,PMIN,PMAX,DELP,NP)
      DO 28 I=1,NP
      TMN=0.0d0
      IF(P(I).LT.P32) TMN=32.0d0
      IF(P(I).GT.PCT) TMN=705.47d0
      IF(TMN.EQ.0.0d0) TMN=TSL(P(I))
      IF(TMN.LT.TMIN) TMN=TMIN
      IF(TMN.GT.TMAX) GO TO 28
      CALL XARRAY(T,TMN,TMAX,DELT,NT)
      IF(P(I).LE.PCT) H(1)=HCL(P(I),TMN,SX)
      IF(P(I).GT.PCT) H(1)=HSS(P(I),TMN,SX,VX)
      H(NT)=HSS(P(I),TMAX,SX,VX)
      CALL HSARRY(H,NT)
      DO 27 J=1,NT
      Z1(J)=0.0d0
      HX=H(J)
      IF(HX.LE.1800.d0) Z1(J)=CRVEL(P(I),HX,G)
      WRITE(6,103) P(I),HX,Z1(J)
      SUM=SUM+P(I)+HX+Z1(J)
   27 CONTINUE
   28 CONTINUE
      SUMT=SUMT+SUM
      WRITE(6,216) SUM
      WRITE(6,217) SUMT
      WRITE(6,1002)
1002  FORMAT(1H0,16HTESTS COMPLETED. )
      STOP
  100 FORMAT(3D20.8)
  101 FORMAT(1H0)
  102 FORMAT(5D20.8)
  103 FORMAT(3D20.8)
  104 FORMAT(4D20.8)
  105 FORMAT(6D18.8)
  106 FORMAT(7D15.6)
  107 FORMAT(9D13.6)
  201 FORMAT(1H1,9X,38H T,PSL(T),HSL(T),SSL(T),VSL(T),TSLH(H))
  202 FORMAT(1H1,9X,10H S,PSV(S) )
C  203 FORMAT(1H1,9X,23H P,T,H=HCL(P,T),TSLH(H))
  204 FORMAT(1H1,9X,21H P,HSV(P),TSL(P)     )
  205 FORMAT(1H1,9X,26H P,T,CONDL(P,T),PRLIQ(P,T))
  206 FORMAT(1H1,9X,14H P,T,VISL(P,T))
  207 FORMAT(1H1,9X,31H P,T,CPL(P,T),HCL(P,T),VCL(P,T))
  208 FORMAT(1H1,9X,34H P,T,S,HSSICL(P,S),T,H,SSSICL(P,H))
  209 FORMAT(1H1,9X,26H P,T,CONDV(P,T),PRSTM(P,T))
  210 FORMAT(1H1,9X,45H P,T,HSS(P,T),T,S,HSSISS(P,S),T,H,SSSISS(P,H))
  211 FORMAT(1H1,9X,23H P,T,CPV(P,T),VISV(P,V))
  212 FORMAT(1H1,9X,15H P,H,CRFLO(P,H))
  213 FORMAT(1H1,9X,15H P,H,CRVEL(P,H))
  214 FORMAT(1H0,9X,5HPMIN=,E16.6,4X,5HPMAX=,E16.6,4X,5HDELP=,E16.6)
  215 FORMAT(1H ,9X,5HTMIN=,E16.6,4X,5HTMAX=,E16.6,4X,5HDELT=,E16.6)
  216 FORMAT(1H0,9X,4HSUM=,E24.16)
  217 FORMAT(1H1,9X,10HTOTAL SUM=,E24.16)
      END
C      SUBROUTINE XARRAY(X,XMIN,XMAX,DELX,N)
C      DIMENSION X(500)
C      IF((XMAX-XMIN).GT.DELX) GO TO 2
C    1 X(1)=XMIN
C      X(2)=XMAX
C      N=2
C      RETURN
C    2 K1=XMIN/DELX+1.0
C      FK1=DELX*K1
C      FK=MOD(XMAX,DELX)
C      K2=XMAX/DELX
C      IF(FK.EQ.0.) K2=K2-1
C      FK2=DELX*K2
C      IF(FK1.GT.FK2) GO TO 1
C      N1=(FK2-FK1)/DELX+1.0
C      X(1)=XMIN
C      DO 3 I=1,N1
C    3 X(I+1)=FK1+(I-1)*DELX
C      N=N1+2
C      X(N)=XMAX
C      RETURN
C      END
c---      subroutine xarray(x,xmin,xmax,delx,n)
c---c       given an array to fill, a minimum, maximum,
c---c       and delta, put min in x(1), find a "nice"
c---c       number for x(2), then fill incrementing by
c---c       delx until reach just below xmax. fill last
c---c       value with xmax. return number of elements
c---c       filled in n.
c---      implicit double precision(a-h, o-z)
c---      dimension x(500)
c---      if((xmax-xmin).gt.delx) go to 2
c---    1 x(1)=xmin
c---      x(2)=xmax
c---      n=2
c---      return
c---    2 k1=int(xmin/delx)+1
c---      fk1=delx*k1
c---      k2=int(xmax/delx)
c---      fk=mod(xmax,delx)
c---      fk2=delx*k2
c---      if(fk1.gt.fk2) go to 1
c---      n1=int((fk2-fk1)/delx+0.5)+1
c---      x(1)=xmin
c---      do 3 i=1,n1
c---    3 x(i+1)=fk1+(i-1)*delx
c---c     if(x(n1+1).lt.xmax)then
c---         n=n1+2
c---c     endif
c---      x(n)=xmax
c---      return
c---      end
      SUBROUTINE XARRAY(X,XMIN,XMAX,DELX,N)
C       GIVEN AN ARRAY TO FILL, A MINIMUM, A MAXIMUM,
C       AND DELTA; PUT MIN IN X(1), FIND A "NICE"
C       NUMBER FOR X(2), THEN FILL INCREMENTTING BY
C       DELS UNTIL REACH JUST BELOW XMAX. FILL LAST
C       VALUE WITH XMAX, RETURN NUMBER OF  ELEMENTS
C       FILLED IN N.
C       ASSUME XMAX IS GREATER THAN XMIN AND
C       THAT DELX IS GREATER THAN ZERO AND IS A "NICE"
C       VALUE TO INCREMENT BY.
C       JOHN S. URBAN. AVOIDS SOME ROUND-OFF ERRORS
C       IN THE ORIGINAL
       implicit double precision (a-h, o-z)
       dimension X(500)
       IDELS=INT(XMIN/DELX)+1
       RIGHT2=DELX*IDELS
       RIGHT=RIGHT2-XMIN
       IF(RIGHT.LE. DELX/1000.0)THEN
          FK1=RIGHT2+DELX
        ELSE
          FK1=RIGHT2
        ENDIF
        N=INT((XMAX-FK1+0.5*DELX)/DELX)
        IF(FK1+DELX*(N-1)+DELX.LT.(XMAX-DELX*0.001))N=N+1
        IF(FK1+DELX*(N-1)+DELX*0.001.GE.XMAX)N=N-1
        IF(N+2.GT.500)THEN
           WRITE(*,*)'*XARRAY* NEEDED ',N+2,' VALUES, ONLY 500 ALLOWED'
           N=498
        ENDIF
        DO 30 I30=0,N-1
        X(I30+2)=FK1+I30*DELX
30      CONTINUE
        X(1)=XMIN
        X(MAX(2,N+2))=XMAX
        N=MAX(2,N+2)
        IF(DELX.LE.0)WRITE(*,*)'*XARRAY* DELX.LE.0'
        IF(XMAX.LE.XMIN)WRITE(*,*)'*XARRAY* XMAX.LE.XMIN'
        RETURN
        END
      SUBROUTINE LIMITS(FCMN,FCMX,FMIN,FMAX,FDEL)
      implicit double precision(a-h, o-z)
      IF(FMAX.GE.FMIN) GO TO 3
      X=FMAX
      FMAX=FMIN
      FMIN=X
    3 FDEL=ABS(FDEL)
      IF(FMIN.GT.FCMN) GO TO 1
      FMIN=FCMN
      IF(FMIN.GT.FMAX) FMAX=FMIN
    1 IF(FMAX.LT.FCMX) GO TO 2
      FMAX=FCMX
      IF(FMIN.GT.FMAX) FMIN=FMAX
    2 RETURN
      END
      SUBROUTINE HSARRY(X,N)
      implicit double precision(a-h, o-z)
      DIMENSION X(N)
      IF(N.LE.2) RETURN
      FN=N-1
      DELX=(X(N)-X(1))/FN
      NX=N-2
      DO 1 I=1,NX
      X(I+1)=X(I)+DELX
    1 CONTINUE
      RETURN
      END
