GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/_dirname.f90 File Reference
_dirname.f90 File Reference
Functions/Subroutines
program demo_dirname
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
_dirname(1f) - [FUNIX:FILESYSTEM] strip last component from file name
Function/Subroutine Documentation
demo_dirname()
program demo_dirname ()
References help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_kracken::sgets(), and m_strings::split().
help_usage()
subroutine demo_dirname::help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine demo_dirname::help_version (logical, intent(in) l_version)
NAME
_dirname(1f) - [FUNIX:FILESYSTEM] strip last component from file name
SYNOPSIS
_dirname NAME... [-zero]|-help|-version]
DESCRIPTION
Output each NAME with its last non-slash component and trailing slashes removed. if NAME contains no /'s, output '.' (meaning the current directory).
OPTIONS
-zero end each output line with NUL, not newline -help display this help and exit -version output version information and exit
EXAMPLES
Sample program executions:
  _dirname /usr/bin/          -> "/usr"
  _dirname dir1/str dir2/str  -> "dir1" followed by "dir2"
  _dirname stdio.h            -> "."
SEE ALSO
dirname(1), basename(1), readlink(1), realpath(1)
References false().