GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/_echo.f90 File Reference
_echo.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
_echo(1f) - [FUNIX] display a line of text
SYNOPSIS
program echo
Function/Subroutine Documentation
echo()
program echo ()
References m_strings::expand(), help_usage(), help_version(), m_kracken::iget(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), and m_kracken::sget().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
_echo(1f) - [FUNIX] display a line of text
SYNOPSIS
_echo [OPTION]... [STRING]...
DESCRIPTION
Echo the STRING(s) to standard output.
OPTIONS
-n do not output the trailing newline -E write message to stderr instead of stdout -ne disable interpretation of escape escapes -r [n] output a string repeatedly until killed if n is blank or n <= 0, else repeat output "n" times. Default value is "1". -x escape character. Default is % –help display this help and exit –version output version information and exit
Escape sequences
%% escape character a alert (BEL) b backspace c suppress further output e escape E escape f form feed n new line r carriage return t horizontal tab v vertical tab oNNN byte with octal value NNN (1 to 3 digits) dNNN byte with decimal value NNN (1 to 3 digits) xHH byte with hexadecimal value HH (1 to 2 digits)
EXAMPLES
 Example invocations:
      _echo Echo this text to stderr -E
      _echo y -r 0  # repeat "y" until interrupted
      _echo ''"#"'' -r 80 -n # create 80-character break line
      _echo %e[2J  # clear screen on vt102-compatible terminal or emulator
References false().