GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/_ln.f90 File Reference
_ln.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
_ln(1f) - [FUNIX:FILESYSTEM] create hard links to a file
SYNOPSIS
program demo_system_link
Function/Subroutine Documentation
demo_system_link()
program demo_system_link ()
References help_usage(), help_version(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), m_kracken::sgets(), m_system::system_link(), and m_system::system_perror().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
_ln(1f) - [FUNIX:FILESYSTEM] create hard links to a file
SYNOPSIS
Formats:
_ln TARGET LINK_NAME # create a link to TARGET with the name LINK_NAME. _ln TARGET # create a link to TARGET in the current directory. _ln TARGET... DIRECTORY # create links to each TARGET in DIRECTORY.
DESCRIPTION
Create hard links (not symbolic links) each destination (name of new link) should not already exist. When creating hard links, each TARGET must exist. Symbolic links can hold arbitrary text; if later resolved, a relative link is interpreted in relation to its parent directory.
OPTIONS
TARGET name of existing file LINK_NAME if LINK_NAME follows TARGET create a link called LINK_NAME that points to TARGET DIRECTORY if last option is a directory previous filenames on command are linked into DIRECTORY –help display this help and exit –version output version information and exit
References false().