GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/_ls.f90 File Reference
_ls.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
_ls(1f) - [FUNIX:FILESYSTEM] list files in a directory
SYNOPSIS
program demo_system_readdir
subroutine printit
subroutine print_csv
Function/Subroutine Documentation
demo_system_readdir()
program demo_system_readdir ()
References help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), print_csv(), printit(), m_kracken::rget(), m_kracken::sgets(), m_system::system_closedir(), m_system::system_opendir(), m_system::system_readdir(), and m_system::system_stat().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
_ls(1f) - [FUNIX:FILESYSTEM] list files in a directory
SYNOPSIS
_ls [directory|–version|–help] [-a] [-l|-csv]
DESCRIPTION
Given a directory name list files in the directory
OPTIONS
pathname name of directory or pathname to display contents of. Defaults to current directory. -a show hidden files (files beginning with "."). -l long listing -csv generate output as a CSV file. Filenames should not have ,"' characters in them. Very useful for use with sqlite3(1) and making a file that can be read into most spreadsheets, –help display command help and exit –version output version information and exit
EXAMPLES
Sample command lines ...
   _ls
   _ls . /tmp -l
EXTENDED SQLITE EXAMPLE
The CSV output can often just be read by spreadsheets. Typically the file suffix ".csv" is required. Assuming you have bash(1), sqlite3(1) and column(1) on your platform this is an example script that shows how SQL statements can be used to generate many kinds of file reports (number of bytes owned by users, number of files, sorting, ... It assumes you or somone who will assist you is familiar with SQL and sqlite3(1):
#!/bin/bash #@(#) list files accessed today in current directory export SCRATCH=/tmp/.csv # create scratch file name trap "/bin/rm -f $SCRATCH" EXIT # ensure scratch file is removed _ls -csv – . |tail -n +2>$SCRATCH # generate CSV file (
read CSV file into an SQLite file and generate a report as HTML table
sqlite3 \ -cmd 'CREATE TABLE directory("Inode_number" INT, "Number_of_blocks_allocated" INT, "File_mode" TEXT, "Number_of_links" INT, "Owner" TEXT, "Groupname" TEXT, "File_size" INT, "Last_access" DATE, "Last_modification" DATE, "Last_status_change" DATE, "Pathname" TEXT);' \ -cmd '.mode csv' \ -cmd ".import $SCRATCH directory" << – .schema .mode column .header on SELECT Pathname, File_mode, Owner, Groupname, File_size, strftime('Y-m-d H:M:S', Last_access) as "Last_Access" FROM directory WHERE DATE('now', 'start of day') < Last_access ORDER BY Pathname ASC; EOF)| column -t -s '|' exit
References false().
print_csv()
subroutine demo_system_readdir::print_csv ()
References fmtdate, m_system::system_getgrgid(), m_system::system_getpwuid(), m_system::system_perm(), true(), and u2d.
printit()
subroutine demo_system_readdir::printit ()
References fmtdate, m_system::system_getgrgid(), m_system::system_getpwuid(), m_system::system_perm(), and u2d.