GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/_sleep.f90 File Reference
_sleep.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
_sleep - [TIME] pause for specified duration
SYNOPSIS
program demo_system_sleep
Function/Subroutine Documentation
demo_system_sleep()
program demo_system_sleep ()
References m_time::days2sec(), help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_time::realtime, m_kracken::sgets(), size(), m_strings::substitute(), and m_time::system_sleep().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
_sleep - [TIME] pause for specified duration
SYNOPSIS
_sleep [dd-hh:mm:ss[.xxx]|xxx.yyy[s|m|h|d]] –version|–help
DESCRIPTION
Given a duration in the form dd-hh:mm:ss.xxx where dd is days, hh hours, mm minutes and ss.xxx seconds pause for the specified amount of time.
Alternatively, the time may be specified by a number of seconds immediately followed by a unit letter, where s is seconds, m is minutes, h is hours and d is days.
If the suffix r is used, a random time between zero and the specified number of seconds is used. This is useful for spreading out cron(1) tasks in a HPC cluster.
Given multiple arguments, pause for the time specified by the sum of the values.
OPTIONS
dd-hh:mm:ss Given a string representing a duration of time in the following forms:
dd-hh:mm:ss[.xx] hh:mm:ss[.xx] mm:ss[.xx] ss[.xx] or xx[.yy]SUFFIX where Suffix may be s for seconds, m for minutes, h for hours, or d for days. –help display this help and exit –version output version information and exit
EXAMPLE
usage:
_sleep 0.10 # pause one tenth of a second _sleep 3m 10s # pause three minutes and 10 seconds _sleep 1:00:00 # pause for one hour
References false().