GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/_stat.f90 File Reference
_stat.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
_stat(1f) - [FUNIX:FILESYSTEM] list file properties
SYNOPSIS
program demo_system_stat
subroutine printit
Function/Subroutine Documentation
demo_system_stat()
program demo_system_stat ()
References help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), printit(), m_kracken::rget(), m_kracken::sgets(), and m_system::system_stat().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
_stat(1f) - [FUNIX:FILESYSTEM] list file properties
SYNOPSIS
_stat pathnames|–version|–help
DESCRIPTION
Given pathnames list properties
OPTIONS
pathnames pathnames to display properties of. –help display command help and exit –version output version information and exit
EXAMPLES
Sample command lines ...
_stat _stat.ff
Results
Pathname: _stat.ff Residence: Inode:18295873486224096 Device ID(hex/decimal):3E6BE045h/1047257157d Device where located:0 Size: File size(bytes):4267 No. of blocks allocated:8 Preferred block size(bytes):65536 File mode octal/decimal/str: 100744o/33252d/-rwxr–r– — Number of links: 1 Owner's uid/username: 197609/JSU Owner's gid/group: 197121/None Last access time: 1507483493 2017-10-08 13:24:53 Last modification time: 1507483493 2017-10-08 13:24:53 Last status change time: 1507483494 2017-10-08 13:24:54
References false().
printit()
subroutine demo_system_stat::printit ()
References fmtdate, m_system::system_getgrgid(), m_system::system_getpwuid(), m_system::system_perm(), and u2d.