GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/_uname.f90 File Reference
_uname.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
_uname(1f) - [FUNIX] print system information
program testit
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
_uname(1f) - [FUNIX] print system information
SYNOPSIS
    _uname [OPTION]...
DESCRIPTION
Print certain system information. With no OPTION, print all information, one value per line.
-a, –all print all information, in the following order:
-s, –kernel-name print the kernel name -n, –nodename print the network node hostname -r, –kernel-release print the kernel release -v, –kernel-version print the kernel version -m, –machine print the machine hardware name
–help display this help and exit –version output version information and exit
EXAMPLE
Sample usage:
>_uname
>kernel-name    : CYGWIN_NT-10.0
>nodename       : buzz
>kernel-release : 2.6.0(0.304/5/3)
>kernel-version : 2016-08-31 14:32
>machine        : x86_64
>_uname -all
>CYGWIN_NT-10.0 buzz 2.6.0(0.304/5/3) 2016-08-31 14:32 x86_64
>_uname -machine
>x86_64
References false().
testit()
program testit ()
References false(), help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_system::system_uname(), and true().