GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/_yes.f90 File Reference
_yes.f90 File Reference
Functions/Subroutines
program yes
subroutine help_version (l_version)
subroutine help_usage (l_help)
Function/Subroutine Documentation
help_usage()
subroutine yes::help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine yes::help_version (logical, intent(in) l_version)
References false().
yes()
program yes ()
References help_usage(), help_version(), m_kracken::iget(), m_kracken::kracken(), m_kracken::lget(), rep(), and m_kracken::sget().