GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/alphabet.f90 File Reference
alphabet.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
alphabet - [CONVERT] print numeric values or a string as decimal, hexadecimal, octal and binary values
SYNOPSIS
program hexd
subroutine process_option (option, fmt)
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
alphabet - [CONVERT] print numeric values or a string as decimal, hexadecimal, octal and binary values
SYNOPSIS
alphabet [values] [-h values][-z values][-o values][ -t text]
DESCRIPTION
Write positive whole number 32-bit values (0 to 2147483647) in base 10(decimal), base 16(hexadecimal), base 2(binary) and base 8(octal) Allowable range of values is from 0 to 2147483647 decimal.
Alternatively, given a text string show the ASCII values for each character in the string.
OPTIONS
value(s) Values are treated as octal if they start with "o", binary if they start with "b", and hexadecimal if they start with "z" or "h". Otherwise, the values are assumed to be decimal.
-b values(s) Values without a "b" prefix are assumed to be binary values. -d values(s) Values are assumed to be decimal values. -o values(s) Values without an "o" prefix are assumed to be octal values. -z|-h values(s) Values without a "z" prefix are assumed to be hexadecimal values. -t literal_text –help display this help and exit –version output version information and exit
EXAMPLE
Sample commands:
alphabet 2147483647 0 # decimal values >Decimal Hex Octal Binary >2147483647 Z"7FFFFFFF" O"17777777777" B"1111111111111111111111111111111" >0 Z"0" O"0" B"0"
alphabet o144 z64 100 b1100100 # values with a prefix >Decimal Hex Octal Binary >100 Z"64" O"144" B"1100100" >100 Z"64" O"144" B"1100100" >100 Z"64" O"144" B"1100100" >100 Z"64" O"144" B"1100100"
alphabet -o 144 -h 64 -d 100 -b 1100100 # values with a keyword >Decimal Hex Octal Binary >100 Z"64" O"144" B"1100100" >100 Z"64" O"144" B"1100100" >100 Z"64" O"144" B"1100100" >100 Z"64" O"144" B"1100100"
alphabet -t Hello # a string >Decimal Hex Octal Binary Description >72 Z"48" O"110" B"1001000" majuscule H >101 Z"65" O"145" B"1100101" miniscule e >108 Z"6C" O"154" B"1101100" miniscule l >108 Z"6C" O"154" B"1101100" miniscule l >111 Z"6F" O"157" B"1101111" miniscule o
SEE ALSO
ascii(1),iprint(1)
References false().
hexd()
program hexd ()
References m_strings::describe(), help_usage(), help_version(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), process_option(), m_kracken::sget(), m_kracken::sgets(), and true().
process_option()
subroutine hexd::process_option (character(len=*) option, character(len=*) fmt)
References m_kracken::sgets().