GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/C-jucolor.c File Reference
C-jucolor.c File Reference
#include <stdio.h>
#include <string.h>
Functions
void jucolor (modei, float clr1i, float clr2i, float clr3i, char *modei *modeo, float *clr1o, float *clr2o, float *clr3o, int *status)
Function Documentation
jucolor()
void jucolor (modei , float clr1i, float clr2i, float clr3i, char *modei* modeo, float * clr1o, float* clr2o, float* clr3o, int * status)
References hlsrgb(), hvsrgb(), m_journal::ident, m_anyscalar::r, rgbhls(), and rgbhvs().