GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/C-M_readline.c File Reference
C-M_readline.c File Reference
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <readline/readline.h>
#include <readline/history.h>
Functions
void show_history_list ()
void FCreadline (int len, char *myline, char prompt[])
Function Documentation
FCreadline()
void FCreadline (int len, char * myline, char prompt[])
References m_pixel::line(), m_io::readline(), and show_history_list().
show_history_list()
void show_history_list ()
References state().