GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/calc_NC.f90 File Reference
calc_NC.f90 File Reference
Functions/Subroutines
subroutine calc_nc (name, args, iargs_type, n, fval, i, ier)
Function/Subroutine Documentation
calc_nc()
subroutine calc_nc (character(len=*), intent(in) name, real(kind=kind(0.0d0)), dimension(100), intent(in) args, integer, dimension(100), intent(in) iargs_type, integer, intent(in) n, real(kind=kind(0.0d0)), intent(inout) fval, integer, intent(inout) i, integer, intent(out) ier)
References echo(), m_calculator::getvalue(), m_calculator::iclen_calc, m_calculator::icname_calc, m_calculator::stuffa(), m_calculator::valuer, m_calculator::values, m_calculator::x, and m_calculator::y.