GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/change.f90 File Reference
change.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
change(1f) - [FILE EDIT] replace old fixed string with new fixed string in filenames
program demo_change
Function/Subroutine Documentation
demo_change()
program demo_change ()
References m_strings::change(), help_usage(), help_version(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), m_kracken::sget(), and m_kracken::sgets().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
change(1f) - [FILE EDIT] replace old fixed string with new fixed string in filenames
SYNOPSIS
change c/old/new/ FILENAMES [-dryrun][-cmd COMMAND]| --version| --help
DESCRIPTION
Given a change directive and a list of filenames replace all occurrences of the original string with the new string.
OPTIONS
c/old/new/ change occurrences of old string to new string in filenames. The first character after the c is the delimiter for the strings. Spaces are not allowed in the expression. FILENAMES names of files to rename -dryrun write the commands to stdout instead of executing them -verbose echo the commands to be executed -cmd COMMAND change command from "mv" to specified command name –help display this help and exit –version output version information and exit
EXAMPLE
Sample commands:
change all files with .f90 in their name to *.F90
change c/.f90/.F90/ *.f90
copy all files with .f90 in their name to *.F90
change c.f90.F90@ *.f90 -cmd cp
References false().