GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/colors.f90 File Reference
colors.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
colors - [CONVERT] list colors and their values using common color models
program colors
Function/Subroutine Documentation
colors()
program colors ()
References m_color::closest_color_name(), m_color::color_name2rgb(), help_usage(), help_version(), m_color::hue(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), m_kracken::rget(), m_strings::s2v(), m_kracken::sget(), m_strings::split(), and m_debug::stderr().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
colors - [CONVERT] list colors and their values using common color models
SYNOPSIS
colors [color_name | R G B | model_name_A V1 V2 V3 model_name_B ]
DESCRIPTION
Display colors using common color models; or convert color values to a different color model
list known color names and their RGB values
colors
show values for a known named color
colors COLOR_NAME
find closest named color
colors R G B #convert color between models colors INPUT_MODEL_NAME VALUE1 VALUE2 VALUE3 OUTPUT_MODEL_NAME
OPTIONS
Model Names(case sensitive):
rgb color TV monitors (RGB values in range 0 to 100) hls Hue (0 to 360 degrees), Lightness (0 to 100), Saturation (0 to 100) cmy Cyan, Magenta, Yellow : pigment-based printing devices (values in range 0 to 100) hsv Hue (0 to 360 degrees), Saturation (0 to 100), Value (0 to 100) yiq Broadcast TV color system (y ranges from 0 to 100, i ranges from -60 to 60, q ranges from -52 to 52)
–help display this help and exit
–version output version information and exit
EXAMPLE
 Common forms of use:
  # list named colors
  colors
  # convert RGB values to HLS value
  colors rgb 0 100 0 hls
  # display RGB values for named color
  colors green
References false().