GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/compute.f90 File Reference
compute.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
compute(1f) - [MATH] evaluate a calculator expression
SYNOPSIS
program compute
subroutine processit
Function/Subroutine Documentation
compute()
program compute ()
References help_usage(), help_version(), m_calculator::iclen_calc, m_calculator::jucalc(), m_kracken::kracken(), m_kracken::lget(), processit(), m_io::readline(), and m_kracken::sget().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
compute(1f) - [MATH] evaluate a calculator expression
SYNOPSIS
compute [STRING] [-verbose]| [-help| -version]
DESCRIPTION
Given any expression call the JUCALC(3f) calculator function and evaluate it. If no expression is present, read expressions from stdin until a line composed of a period(".") or end of data is encountered.
Expressions are similar to Fortran77 syntax except powers are processed from left to right.
OPTIONS
STRING calculator expression to evaluate –help display this help and exit –version output version information and exit
EXAMPLES
    Sample commands:
     $ compute '(sin(30.33333)*2)**2+40.0/2.3-1.23e3'
     $ compute funcs # list available functions
SEE ALSO
M_calculator(3fm)
References false().
processit()
subroutine compute::processit ()
References m_calculator::jucalc().