GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/cprint.f90 File Reference
cprint.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
cprint(1f) - [FILE FILTER] filter prints specified columns
SYNOPSIS
program cprint
Function/Subroutine Documentation
cprint()
program cprint ()
References help_usage(), help_version(), m_kracken::igets(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), m_kracken::sget(), m_kracken::sgets(), and m_strings::split().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
cprint(1f) - [FILE FILTER] filter prints specified columns
SYNOPSIS
cprint [columns ][-delimiters delim] |-help|-version
DESCRIPTION
cprint is a filter that prints the specified columns
OPTIONS
columns numbers indicating which columns to print -delimiters input column delimiter character(s) (default: whitespace) -help display command help and exit -version display command metadata and exit
EXAMPLES
Sample usage:
>echo d e h l o r w|cprint 3 2 4 4 5 7 5 6 4 1
h e l l o w o r l d
References false().