GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/days2sec.f90 File Reference
days2sec.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
days2sec - [TIME] Convert [[-]dd-][[hh:]mm:]ss to seconds
program demo_days2sec
Function/Subroutine Documentation
demo_days2sec()
program demo_days2sec ()
References m_time::days2sec(), help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), and m_kracken::sget().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
days2sec - [TIME] Convert [[-]dd-][[hh:]mm:]ss to seconds
SYNOPSIS
days2sec dd-hh:mm:ss | --version| --help
days2sec NNdNNhNNmNNs
DESCRIPTION
Given a duration in the form dd-hh:mm:ss where dd is days, hh hours, mm minutes and ss seconds convert it to seconds. Many utilities (ps(1), for example) show times in this format to make it more intelligible; but it generally easier to perform math on values represented in seconds.
OPTIONS
dd-hh:mm:ss Given a string representing a duration of time in the following forms:
dd-hh:mm:ss hh:mm:ss mm:ss ss
convert it to seconds.
The numeric values may represent floating point numbers.
Spaces are ignored.
NNdNNhNNmNNs Simple numeric values may also be used with unit suffixes; where s,m,h, or d represents seconds, minutes, hours or days and w represents weeks. Allowed aliases for w,d,h,m, and s units are
w - weeks,week,wk,wks d - days,day m - minutes,minute,min h - hours,hour,hrs,hr s - seconds,second,sec,secs
The numeric values may represent floating point numbers.
Spaces, commas and case are ignored.
–help display this help and exit –version output version information and exit
EXAMPLE
Usage
days2sec 1-12:04:20 129860 days2sec 1.5 days 129600 days2sec 1.5 days 4hrs 30minutes 145800 days2sec 10s 10S 10s # DUPLICATES WITH UNITS ARE ALLOWED 30 days2sec 1 1 1 # SPACES ARE IGNORED 111
SEE ALSO
sec2days(1)
References false().