GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/dparanoia.f90 File Reference
dparanoia.f90 File Reference
Functions/Subroutines
subroutine dparanoia ()
subroutine runtests ()
subroutine commut (NUMTRY)
subroutine random (X, Y, X9, R9)
subroutine extra
subroutine guard
subroutine intro (MILES)
subroutine logit (MILE)
subroutine cmpxy (X, Y, Z, Q, N)
subroutine prt2 (N, MILES)
subroutine pwrcmp (X, Z, I, M, N)
subroutine prtcnt (N)
subroutine badsqr (SFLAG, Z, Y)
subroutine overf (MILES, FROM)
subroutine page (MILE)
subroutine partuf (Z, ZNAME, MILES, PARTU, RESTRT)
subroutine power (MILES, FROM)
subroutine radx (MILES)
subroutine round (MILES)
subroutine smlint (MILES, FROM)
subroutine square (FROM, MILES, NUMTRY)
subroutine sqrerr (X, U, J, E5, E7, SEROUS)
subroutine newd (X, Z1, Q, Z, D)
subroutine sqrtdx (X, Z2, I, D, Y2, Y, X8, E5, E7)
subroutine underf (MILES, NUMTRY, FROM)
subroutine zeros (MILES, FROM)
subroutine badmil
integer function idint (X)
Function/Subroutine Documentation
badmil()
subroutine dparanoia::badmil ()
badsqr()
subroutine dparanoia::badsqr (integer SFLAG, double precision Z, double precision Y)
cmpxy()
subroutine dparanoia::cmpxy (double precision X, double precision Y, double precision Z, integer Q, integer N)
commut()
subroutine dparanoia::commut (integer NUMTRY)
References random().
dparanoia()
subroutine dparanoia ()
References runtests().
extra()
subroutine dparanoia::extra ()
guard()
subroutine dparanoia::guard ()
idint()
integer function dparanoia::idint (double precision X)
intro()
subroutine dparanoia::intro (integer MILES)
References page().
logit()
subroutine dparanoia::logit (integer MILE)
newd()
subroutine dparanoia::newd (double precision X, double precision Z1, double precision Q, double precision Z, double precision D)
overf()
subroutine dparanoia::overf (integer MILES, integer FROM)
References badmil(), badsqr(), logit(), and page().
page()
subroutine dparanoia::page (integer MILE)
partuf()
subroutine dparanoia::partuf (double precision Z, character(len=8) ZNAME, integer MILES, integer PARTU, logical RESTRT)
References logit(), and page().
power()
subroutine dparanoia::power (integer MILES, integer FROM)
References badmil(), idint(), prt2(), prtcnt(), and pwrcmp().
prt2()
subroutine dparanoia::prt2 (integer N, integer MILES)
References page().
prtcnt()
subroutine dparanoia::prtcnt (integer N)
pwrcmp()
subroutine dparanoia::pwrcmp (double precision X, double precision Z, integer I, integer M, integer N)
References cmpxy().
radx()
subroutine dparanoia::radx (integer MILES)
random()
subroutine dparanoia::random (double precision X, double precision Y, double precision X9, double precision R9)
round()
subroutine dparanoia::round (integer MILES)
runtests()
subroutine dparanoia::runtests ()
References badmil(), commut(), extra(), file(), form, guard(), intro(), overf(), page(), power(), radx(), round(), smlint(), square(), underf(), and zeros().
smlint()
subroutine dparanoia::smlint (integer MILES, integer FROM)
References badmil(), and partuf().
sqrerr()
subroutine dparanoia::sqrerr (double precision X, double precision U, integer J, double precision E5, double precision E7, logical SEROUS)
sqrtdx()
subroutine dparanoia::sqrtdx (double precision X, double precision Z2, integer I, double precision D, double precision Y2, double precision Y, double precision X8, double precision E5, double precision E7)
square()
subroutine dparanoia::square (integer FROM, integer MILES, integer NUMTRY)
References badmil(), false(), logit(), newd(), page(), sqrerr(), sqrtdx(), and true().
underf()
subroutine dparanoia::underf (integer MILES, integer NUMTRY, integer FROM)
References badmil(), cmpxy(), idint(), logit(), page(), partuf(), prt2(), and prtcnt().
zeros()
subroutine dparanoia::zeros (integer MILES, integer FROM)
References badmil(), and logit().