GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/dtu.f90 File Reference
dtu.f90 File Reference
Modules
module global
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
dtu(1) - [FILE FILTER] convert files between Unix and DOS line terminator conventions
integer function global::readchar (char1)
integer function global::writechar (char1)
subroutine dos_to_unix ()
subroutine unix_to_dos ()
program dtu_exe
subroutine writefile ()
Variables
character(len=1), parameter global::cz =char(26)
character(len=1), parameter global::nl =char(10)
character(len=1), parameter global::cr =char(13)
character(len=1), parameter global::lf =char(10)
integer global::iunit =15
integer global::ounit =16
logical global::process_ctrl_z = .false.
logical global::noisy = .false.
integer global::chars_read = 0
integer global::chars_written = 0
integer global::lines_written = 0
Function/Subroutine Documentation
dos_to_unix()
subroutine dos_to_unix ()
References global::cr, global::cz, global::lf, global::lines_written, global::nl, global::noisy, global::process_ctrl_z, global::readchar(), and global::writechar().
dtu_exe()
program dtu_exe ()
References false(), help_usage(), help_version(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), global::noisy, global::process_ctrl_z, true(), and writefile().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
dtu(1) - [FILE FILTER] convert files between Unix and DOS line terminator conventions
SYNOPSIS
    dtu [[-make dos|unix] [-z] [-n] -i input -o output ]|--help|--version
DESCRIPTION
Convert DOS end-of-line (CR-LF or <carriage-return><line-feed>) to a Unix end-of-line (LF or <line-feed>, often called "newline"); or vice-versa.
OPTIONS
-make unix (default) convert DOS file to Unix (CR-LF to newline) -make dos convert Unix file to DOS (newline to CR-LF) -z guarantee last character of DOS file is ^Z, guarantee last character of Unix file is not ^Z otherwise, ^Z in input is copied or not as-is -n noisy mode reports character and line counts on stderr -i input_file required -o output_file required –help display this help and exit –version output version information and exit
References false().
unix_to_dos()
subroutine unix_to_dos ()
References global::chars_read, global::cr, global::cz, global::lf, global::lines_written, global::nl, global::noisy, global::process_ctrl_z, global::readchar(), and global::writechar().
writefile()
subroutine writefile ()
References global::chars_read, global::chars_written, dos_to_unix(), file(), m_kracken::ipvalue, global::iunit, global::lines_written, global::noisy, global::ounit, m_kracken::sget(), unit(), and unix_to_dos().