GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/exchange.f90 File Reference
exchange.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
exchange - [CONVERT] test of basic unit conversion functions
program testit
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
exchange - [CONVERT] test of basic unit conversion functions
SYNOPSIS
 exchange [-feet VALUES] [-meters VALUES]
          [-celsius VALUES] [-fahrenheit VALUES]
          [-degrees VALUES] [-radians VALUES]
          [--help] -[-version]
DESCRIPTION
Makes common unit conversions such as between feet and meters, celsius and fahrenheit, and degrees and radians.
OPTIONS
-feet VALUES convert feet to meters -meters VALUES convert meters to feet -fahrenheit VALUES convert fahrenheit to celsius -celsius VALUES convert celsius to fahrenheit -radians VALUES convert radians to degrees -degrees VALUES convert degrees to radians –help display this help and exit –version output version information and exit
EXAMPLES
 Sample commands:
  exchange -degrees 0 90 180 360
  > 0.00000000      degrees is    0.00000000      radians
  > 90.0000000      degrees is    1.57079637      radians
  > 180.000000      degrees is    3.14159274      radians
  > 360.000000      degrees is    6.28318548      radians
  exchange -fahrenheit -40 32 98.6 212 -celsius -40 0 37 100
  > -40.0000000      celsius is   -40.0000000      fahrenheit
  >  0.00000000      celsius is    32.0000000      fahrenheit
  >  37.0000000      celsius is    98.6000061      fahrenheit
  >  100.000000      celsius is    212.000000      fahrenheit
  > -40.0000000      fahrenheit is   -40.0000000      celsius
  >  32.0000000      fahrenheit is    0.00000000      celsius
  >  98.5999985      fahrenheit is    37.0000000      celsius
  >  212.000000      fahrenheit is    100.000000      celsius
References false().
testit()
program testit ()
References m_units::c2f(), d2r(), m_units::f2c(), m_units::feet_to_meters(), help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_units::meters_to_feet(), r2d(), and m_kracken::rgets().