GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/factors.f90 File Reference
factors.f90 File Reference
Functions/Subroutines
program find_prime_factors
subroutine printme (ii, jj)
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
factors(1f) - [NUMBERS]display prime factors of numbers
Function/Subroutine Documentation
find_prime_factors()
program find_prime_factors ()
References help_usage(), help_version(), m_kracken::iget(), m_kracken::igets(), m_kracken::kracken(), m_kracken::lget(), m_factor::prime_factors(), and printme().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
factors(1f) - [NUMBERS]display prime factors of numbers
SYNOPSIS
    factors [NUMBER]...
    factors -start N -end M
DESCRIPTION
Print the prime factors of each specified integer NUMBER. If none are specified on the command line, read them from standard input.
Typically, the numbers must be positive integers where
2 <= NUMBER <= (2**31)-1 or 2147483647.
OPTIONS
-start N if specified factor a range of numbers starting with this value. If -end is specified defaults to 2. -end M if specified factor a range of numbers ending with this value. If -start is specified defaults to huge(0). –help display this help and exit –version output version information and exit –verbose verbose output
EXAMPLE
Sample Usage:
factors 512 512: 2 2 2 2 2 2 2 2 2
factors 512 -verbose 512 factors as (2**9)
factors 202023 2147483647 -verbose 202023 factors as (3**2)*22447 2147483647 IS A PRIME NUMBER
factors -start 2 -end 12 -verbose 2 IS A PRIME NUMBER 3 IS A PRIME NUMBER 4 factors as (2**2) 5 IS A PRIME NUMBER 6 factors as 2*3 7 IS A PRIME NUMBER 8 factors as (2**3) 9 factors as (3**2) 10 factors as 2*5 11 IS A PRIME NUMBER 12 factors as (2**2)*3
References false().
printme()
subroutine find_prime_factors::printme (integer, intent(in) ii, integer, intent(in) jj)
References m_factor::prime_factors().