GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/huegif.f90 File Reference
huegif.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
huegif(1) - generate color wheels as GIF pixmap files
program demo_mapcolor
subroutine wheel ()
subroutine slice (hue_val)
Function/Subroutine Documentation
demo_mapcolor()
program demo_mapcolor ()
References m_pixel::biggest_ortho2(), m_pixel::clear(), m_pixel::color(), m_units::cosd(), help_usage(), help_version(), m_color::hue(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), m_pixel::p_colormap, m_pixel::p_pixel, m_pixel::prefsize(), m_kracken::rget(), m_kracken::sget(), m_units::sind(), m_pixel::vexit(), m_pixel::vinit(), wheel(), and m_writegif::writegif().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
huegif(1) - generate color wheels as GIF pixmap files
SYNOPSIS
huegif
DESCRIPTION
 Generates color wheels using the HSL (Hue Lightness, Saturation)
 model as GIF pixel files.
OPTIONS
–help display this help and exit
–version output version information and exit
References false().
slice()
subroutine demo_mapcolor::slice (real hue_val)
References m_pixel::closepoly(), m_pixel::color(), m_units::cosd(), m_pixel::draw2(), m_pixel::drawstr(), m_color::hue(), m_pixel::linewidth(), m_pixel::makepoly(), m_pixel::mapcolor(), m_pixel::move2(), m_units::sind(), and m_pixel::textang().
wheel()
subroutine demo_mapcolor::wheel ()
References m_pixel::centertext(), m_pixel::color(), m_pixel::drawstr(), false(), m_pixel::font(), m_pixel::linewidth(), m_pixel::move2(), slice(), m_pixel::textang(), m_pixel::textsize(), and true().