GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/intrinsics.f90 File Reference
intrinsics.f90 File Reference
Functions/Subroutines
subroutine help_version (l_version)
NAME
INTRINSIC(3f) - intrinsic man(1) pages
subroutine help_usage (l_help)
program intrinsics_man_pages
NAME
intrinsics(1f) - [FUNIX] output text versions of Fortran intrinsic man(1) pages
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
INTRINSIC(3f) - intrinsic man(1) pages
DESCRIPTION
This is a project to provide a standard set of man(1) pages for Fortran
and the Fortran intrinsics, ultimately with a working example program
for each intrinsic.
The manpage source is maintained as a single flat-text file (intrinsics.ff) which is
run thru ufpp(1) and txt2man(1) to create the program intrinsics(1f).
That program generates all the text as plain text as well as being used
as the source for the man(1) pages. The program intrinsics(1f) is
very useful for scanning for keywords.
Note that the vim(1) editor will call up a man(1) page for a word if
the letter "K" is pressed over the word.
Integration with the editor is a powerful tool when inspecting code
that uses unfamiliar procedures and to verify correct usage when
creating code.
*Note*: In many cases the descriptions of these intrinsics were
originally taken from the [[GFortran|GNU Fortran]] manual to make
descriptions on the Fortran Wiki by Jason Blevins (which were then
used to start this collection). Like the Fortran Wiki itself, the
[[GFortran|GNU Fortran]] manual is licensed under the [[GNU Free
Documentation License]].
These documents are at the state of "good enough considering the
alternative is nothing", but are still actively being completed.
References false().
intrinsics_man_pages()
program intrinsics_man_pages ()
NAME
intrinsics(1f) - [FUNIX] output text versions of Fortran intrinsic man(1) pages
SYNOPSIS
 intrinsics [--help|--version]
DESCRIPTION
This program outputs all the source of the man(1) pages of the Fortran intrinsics procedures.
OPTIONS
–help display this help and exit –version output version information and exit
EXAMPLES
 Sample commands
    intrinsics >x;vi x
NAME
include(7f) - [FORTRAN] including source text
SYNOPSIS
 INCLUDE char-literal-constant
DESCRIPTION
Additional text may be incorporated into the source text of a program unit during processing. This is accomplished with the INCLUDE line, which has the form
   INCLUDE char-literal-constant
An INCLUDE line is not a Fortran statement.
The char-literal-constant shall not have a kind type parameter value that is a named-constant. The interpretation of char-literal-constant is processor dependent. An example of a possible valid interpretation is that char-literal-constant is the name of a file that contains the source text to be included.
An INCLUDE line shall appear on a single source line where a statement may appear; it shall be the only nonblank text on this line other than an optional trailing comment. Thus, a statement label is not allowed.
The effect of the INCLUDE line is as if the referenced source text physically replaced the INCLUDE line prior to program processing. Included text may contain any source text, including additional INCLUDE lines; such nested INCLUDE lines are similarly replaced with the specified source text. The maximum depth of nesting of any nested INCLUDE lines is processor dependent. Inclusion of the source text referenced by an INCLUDE line shall not, at any level of nesting, result in inclusion of the same source text.
When an INCLUDE line is resolved, the first included statement line shall not be a continuation line and the last included statement line shall not be continued.
NOTE
    In some circumstances, for example where source code is
    maintained in an INCLUDE file for use in programs whose source
    form might be either fixed or free, observing the following
    rules allows the code to be used with either source form.
    *   Confine statement labels to character positions 1 to
        5 and statements to character positions 7 to 72.
    *   Treat blanks as being significant.
    *   Use only the exclamation mark (!) to indicate
        a comment, but do not start the comment in character
        position 6.
    *   For continued statements, place an ampersand (&) in
        both character position 73 of a continued line and character
        position 6 of a continuation line.
EXAMPLE
NAME
scratch(7f) - [FORTRAN:OPEN] where scratch files are typically written by OPEN(3f)
SYNOPSIS
 open( .... status='scratch')
DESCRIPTION
Where files opened with status='scratch' are written is implementation-dependent. Often the file is unlinked so that it goes away unconditionally when the program starts, so in many *nix environments you cannot see the scratch file that is often used. So the compiler documentation should be referred to, but typically a scratch file is opened with a unique filename in one of the following directories:
o in the directory pointed to by the environment variable $TMPDIR, if defined. o next directories pointed to by $TMP and $TEMP are used if the variables are defined. o if none of the variables are defined, then the /tmp directory is typically used on *nix systems, and the current directory is often used on other systems.
This can be important if you are generating large scratch files, as you may want to specify they are created in a secure directory or on a high-speed server such as a Lustre file server or memory-resident file system. Consider
o Scratch files are often opened using the current permission mask (umask) combined with possible operating-system or kernel defaults and file-system-dependent attributes, so make sure scratch files are properly secure o files are written in an area that you can write to and have sufficient space in o that the scratch space provides optimal performance o make sure the system cleans up properly when programs are aborted.
The behavior is very system-dependent.
EXAMPLE:
System-dependent example:
open(newunit=lun,status='scratch') inquire(unit=lun,file=filename) write(*,*)'filename=',filename) end
NAME
initialize_arrays(7f) - [FORTRAN:FAQ] Initializing small 2D numeric arrays with array constructors
DESCRIPTION
Intuitively, one might assume that if one wants to initialize a small array by rows that something like the following will work:
! DOES NOT WORK integer :: xx(3,5)= [ 1, 2, 3, 4, 5], & [10,20,30,40,50], & [11,22,33,44,55]
or perhaps
! DOES NOT WORK integer :: xx(3,5)= [ [ 1, 2, 3, 4, 5], & [10,20,30,40,50], & [11,22,33,44,55] ]
Someday something simpler might work, but currently the following syntax is required to specify the values in an intuitive row-column sequence using an array constructor:
integer,save :: xx(3,5)= reshape([&
1, 2, 3, 4, 5, &
10,20,30,40,50, & 11,22,33,44,55 &
],shape(xx),order[2,1])
This is because an array constructor can be used to create and assign values only to rank-one arrays. To define arrays of more than one dimension with an array constructor, you must use the RESHAPE(3f) intrinsic function.
Note that the ORDER= option on RESHAPE(3f) is used to allow the values to be specified in row-column order instead of the default behavior, which fills columns first.
Also note that if the expressions are of type character, Fortran 95/90 requires each expression to have the same character length (there is a common compiler extension that extends all strings to the length of the longest value specified, but depending on it reduces portability).
Printing small arrays in row-column format
When working with small arrays the issue that there is no default Fortran routine for printing an array in row-column order becomes apparent. So lets create a simple solution for integer arrays (PRINT_MATRIX_INT(3f)):
program demo_array_constructor ! initializing small arrays implicit none integer,save :: xx(3,5)= reshape([&
1, 2, 3, 4, 5, &
10,20,30,40,50, & 11,22,33,44,-1055 &
],shape(xx),order=[2,1])
call print_matrix_int('xx array:',xx)
contains
subroutine print_matrix_int(title,arr) implicit none
character(len=*),parameter::ident= "@(#)print_matrix_int(3f) - print small 2d integer arrays in row-column format"
character(len=*),intent(in) :: title integer,intent(in) :: arr(:,:) integer :: i character(len=:),allocatable :: biggest
write(*,*)trim(title) ! print title biggest=' ' ! make buffer to write integer into write(biggest,'(i0)')ceiling(log10(real(maxval(abs(arr)))))+1 ! find how many characters to use for integers biggest='(" > [",*(i'//trim(biggest)//':,","))' ! use this format to write a row do i=1,size(arr,dim=1) ! print one row of array at a time write(*,fmt=biggest,advance='no')arr(i,:) write(*,'(" ]")') enddo
end subroutine print_matrix_int
end program demo_array_constructor
Results:
xx array: > [ 1, 2, 3, 4, 5 ] > [ 10, 20, 30, 40, 50 ] > [ 11, 22, 33, 44, 55 ]
We could do a more robust version that handles REAL and COMPLEX values as well as NaN values, but it has already been done. If you need to print a variety of small matrices see:
dispmodule(3f), "A Fortran 95 module for pretty-printing matrices". Kristjan Jonasson, Department of Computer Science, School of Science and Engineering, University of Iceland, Hjardarhaga 4, 107 Reykjavik, Iceland (jonas.nosp@m.son@.nosp@m.hi.is).
#Initializing a 2D array using DATA statements
Note that DATA statements are very flexible, and allow for perhaps the most intelligible way of specifying small arrays row by row. For example:
! fill rows using DATA statements integer,save,dimension(3,5) :: gg data gg(1,:)/ 1, 2, 3, 4, 5 / data gg(2,:)/ 10, 20, 30, 40, 50 / data gg(3,:)/ 11, 22, 33, 44, 55 /
There are other ways to use a DATA statement to fill in row-column order, including use of the SIZE(3f) function and an implied-DO:
! use implied-DO so data can be declared in row-column order integer, dimension(3,5) :: ff DATA ((ff(J,I), I=1,size(ff,dim=2)), J=1,size(ff,dim=1)) / & 01,02,03,04,05, & 10,20,30,40,50, & 11,22,33,44,55 /
Initializing a 2D array from a vector using EQUIVALENCE
Sometimes instead of using RESHAPE(3f) you will see someone initialize a vector and then equivalence it to a multi-dimensional array; especially if the code has a reason to access the data as both a vector and a matrix:
! multi-dimensional row1, row2, .... by equivalence integer,parameter :: d1=3,d2=5 integer :: ee(d1,d2) ! note that the DATA statements could be used to initialize the array instead integer :: e(d1*d2) =[1,10,11, 2,20,22, 3,30,33, 4,40,44, 5,50,55] equivalence (e(1),ee(1,1))
Notes
Remember that for simple initializations vector statements can be used
real :: arr(10,20)=0.0 ! array constructors can be used to define constants, not just vectors integer,parameter :: ii(10,10)=[(i,i=1,size(ii))] ! odd numbers using implied-DO
and that if things are too complicated you can just set the values in the executable body of the code.
References arguments, echo(), help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), the(), and to.