GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/juown1.f90 File Reference
juown1.f90 File Reference
Functions/Subroutines
subroutine juown1 (func, iflen, args, iargstp, n, fval, ctmp, ier)
Function/Subroutine Documentation
juown1()
subroutine juown1 (character(len=*) func, integer iflen, real(kind=dp), dimension(100) args, integer, dimension(100) iargstp, integer n, real(kind=dp) fval, character(len=*) ctmp, integer ier)
References calc_nc(), m_calculator::icname_calc, m_strings::lower(), m_process::process_readall(), m_calculator::valuer, m_calculator::values, m_calculator::x, and m_calculator::y.