GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/M_time.f90 File Reference
M_time.f90 File Reference
Data Types
interface m_time_oop::date_time
interface m_time_oop::date_time
Modules
module m_time
module m_time_oop
Functions/Subroutines
subroutine, public m_time::date_to_julian (dat, julian, ierr)
NAME
date_to_julian - [M_time] converts DAT date-time array to Julian Date
subroutine, public m_time::julian_to_date (julian, dat, ierr)
NAME
julian_to_date - [M_time] converts a JED(Julian Ephemeris Date) to a DAT date-time array.
subroutine, public m_time::date_to_unix (dat, unixtime, ierr)
NAME
date_to_unix - [M_time] converts DAT date-time array to Unix Epoch Time
subroutine, public m_time::unix_to_date (unixtime, dat, ierr)
NAME
unix_to_date - [M_time] converts Unix Epoch Time to DAT date-time array
integer function, public m_time::d2o (dat)
NAME
d2o - [M_time] converts DAT date-time array to Ordinal day
subroutine, public m_time::ordinal_to_date (yyyy, ddd, dat)
NAME
ordinal_to_date(3f) - [M_time] when given a valid year and day of the year returns the DAT array for the date
SYNOPSIS
integer function, dimension(8), public m_time::o2d (ordinal, year)
NAME
o2d - [M_time] converts Ordinal day to DAT date-time array
character(len=:) function, allocatable, public m_time::v2mo (imonth)
NAME
v2mo - [M_time] returns the month name of a Common month number
integer function, dimension(8), public m_time::mo2d (month_name)
NAME
mo2d - [M_time] given month name return DAT date-time array for beginning of that month in current year
integer function, public m_time::mo2v (month_name)
NAME
mo2v - [M_time] given month name return month number (1-12) of that month
character(len=:) function, allocatable, public m_time::now (format)
NAME
now - [M_time] return string representing current time given format
character(len=:) function, allocatable, public m_time::fmtdate (values, format)
NAME
fmtdate - [M_time] given DAT date-time array return date as string using specified format
subroutine, public m_time::fmtdate_usage (indent)
NAME
fmtdate_usage - [M_time] display macros recognized by fmtdate(3f) and now(3f)
subroutine, public m_time::guessdate (datestring, dat, ier)
NAME
guessdate - [M_time] reads in a date, in various formats
subroutine, public m_time::dow (values, weekday, day, ierr)
NAME
dow - [M_time] given a date-time array DAT return the day of the week
subroutine, public m_time::d2w (dat, iso_year, iso_week, iso_weekday, iso_name)
NAME
d2w - [M_time] calculate iso-8601 Week-numbering year date yyyy-Www-d given DAT date-time array
integer function uncorrected_week_of_year (datin)
subroutine, public m_time::w2d (iso_year, iso_week, iso_weekday, dat)
NAME
w2d - [M_time] calculate DAT date-time array from iso-8601 Week-numbering year date yyyy-Www-d
subroutine, public m_time::box_month (dat, calen)
NAME
box_month - [M_time] create specified month in a character array
real(kind=realtime) function, public m_time::d2j (dat)
NAME
d2j - [M_time] given DAT date-time array returns Julian Date
integer function, dimension(8), public m_time::j2d (julian)
NAME
j2d - [M_time] given a JED (Julian Ephemeris Date) returns a date-time array DAT.
real(kind=realtime) function, public m_time::d2u (dat)
NAME
d2u - [M_time] given DAT date-time array returns Unix Epoch Time (UET starts at 0000 on 1 Jan. 1970, UTC)
integer function, dimension(8), public m_time::u2d (unixtime)
NAME
u2d - [M_time] given Unix Epoch Time returns DAT date-time array
integer function m_time::get_timezone ()
character(len=:) function, allocatable, public m_time::sec2days (seconds, crop)
NAME
sec2days - [M_time] convert seconds to string of form dd-hh:mm:ss
real(kind=realtime) function, public m_time::days2sec (str)
NAME
days2sec - [M_time] convert string of form [[-]dd-]hh:mm:ss.nn to seconds
character(len=:) function, allocatable, public m_time::phase_of_moon (datin)
NAME
phase_of_moon(3f) - [M_time] return name for phase of moon for given date
SYNOPSIS
integer function, public m_time::moon_fullness (datin)
NAME
moon_fullness(3f) - [M_time] return percentage of moon phase from new to full
SYNOPSIS
subroutine, public m_time::easter (year, month, day)
NAME
easter(3f) - [M_time] calculate date for Easter given a year
subroutine, public m_time::ephemeris (itime, planet, declination_d, declination_m, declination_compass, ascent_hours, ascent_minutes)
NAME
subroutine planet_coordinates (planet_number, t, x, y, z)
subroutine, public m_time::system_sleep (seconds)
NAME
system_sleep - [M_time] call C sleep(3c) or usleep(3c) procedure
SYNOPSIS
subroutine, private m_time::call_sleep (wait_seconds)
subroutine, private m_time::call_usleep (wait_seconds)
character(len=:) function, allocatable now_ex (format)
type(date_time) function m_time_oop::construct_from_dat (dat)
type(date_time) function m_time_oop::construct_from_jed (jed)
type(date_time) function m_time_oop::construct_from_uet (uet)
integer function, dimension(8), private m_time_oop::dt2d (self)
real(kind=realtime) function, private m_time_oop::epoch (self)
character(len=:) function, allocatable, private m_time_oop::format (self, fmt)
real(kind=realtime) function, private m_time_oop::julian (self)
integer function, private m_time_oop::ordinal (self)
integer function, private m_time_oop::weekday (self)
type(date_time) function, private m_time_oop::delta (self, year, month, day, tz, hour, minute, second, millisecond, week, duration)
subroutine, private m_time_oop::init_dt (self, year, month, day, tz, hour, minute, second, millisecond, type, dat)
type(date_time) function m_time_oop::plus_seconds (self, seconds)
type(date_time) function m_time_oop::minus_seconds (self, seconds)
real(kind=realtime) function m_time_oop::minus_date_time (self, other)
logical function m_time_oop::eq (self, other)
logical function m_time_oop::lt (self, other)
logical function m_time_oop::gt (self, other)
logical function m_time_oop::le (self, other)
logical function m_time_oop::ge (self, other)
logical function m_time_oop::ne (self, other)
Variables
integer, parameter, public m_time::realtime =kind(0.0d0)
real(kind=realtime), parameter, private m_time::secday =86400.0d0
real(kind=realtime), parameter, public m_time::dt_minute =60.0d0
real(kind=realtime), parameter, public m_time::dt_hour =3600.0d0
real(kind=realtime), parameter, public m_time::dt_day =86400.0d0
real(kind=realtime), parameter, public m_time::dt_week =dt_day*7.0d0
Function/Subroutine Documentation
now_ex()
character(len=:) function, allocatable now_ex (character(len=*), intent(in), optional format) private
References m_time::now().
planet_coordinates()
subroutine ephemeris::planet_coordinates (integer, intent(in) planet_number, real(kind=dp), intent(in) t, real(kind=dp), intent(out) x, real(kind=dp), intent(out) y, real(kind=dp), intent(out) z) private
uncorrected_week_of_year()
integer function d2w::uncorrected_week_of_year (integer, dimension(8), intent(in) datin) private
References m_time::d2o(), and m_time::dow().