GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/M_writegif_animated.f90 File Reference
M_writegif_animated.f90 File Reference
Modules
module m_writegif_animated
NAME
write_animated_gif(3f) - [M_writegif_animated] Codes pixel-maps with palette into animated GIF format. Optional transparent color
Functions/Subroutines
subroutine, public m_writegif_animated::write_animated_gif (filename, pixel, colormap, transparent, delay)
author: Jacob Williams
character(len=2) function char2 (ival)
subroutine flushbuffer (iunit)
subroutine giflzw (iunit, pixel)
subroutine inittable ()
subroutine slicewrite (iunit, code)
Function/Subroutine Documentation
char2()
character(len=2) function write_animated_gif::char2 (integer, intent(in) ival) private
flushbuffer()
subroutine write_animated_gif::flushbuffer (integer, intent(in) iunit) private
giflzw()
subroutine write_animated_gif::giflzw (integer, intent(in) iunit, integer, dimension(:,:), intent(in) pixel) private
References flushbuffer(), inittable(), and slicewrite().
inittable()
subroutine write_animated_gif::inittable () private
References follow.
slicewrite()
subroutine write_animated_gif::slicewrite (integer, intent(in) iunit, integer, intent(in) code) private
References flushbuffer().