GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/makeout.f90 File Reference
makeout.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
makeout(1f) - [DEVELOPER] Generate a Makefile from the sources (C, Fortran) in the current directory
SYNOPSIS
program makeout
subroutine pretty_print (prefix, string)
subroutine printmakevar (varname, default)
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
makeout(1f) - [DEVELOPER] Generate a Makefile from the sources (C, Fortran) in the current directory
SYNOPSIS
makeout program_files [-o [filename]] [-v][–version|–help]
DESCRIPTION
If all the source for a set of programs exists in a single directory, with a subdirectory containing the files with main programs, then makeout(1) creates a make(1) file for the current directory and the specified programs. A mixture of C and Fortran files is allowed. makeout(1) looks for dependencies created by INCLUDE(7f), "#include", and USE(3f) statements in their most common forms.
The resulting makefile is quite simple, with few comments. The targets and rules are explicit. The goal is to provide a well defined starting point for your Fortran makefile. You will most certainly need to edit the resultant makefile, but doing so is intended to be quite simple.
For more complex dependencies see your compiler information, as several compilers have switches that will generate a very complete list of dependencies.
 gfortran  -M        # GNU/Linux GCC, Free Software Foundation, Inc.
 ifort     -gen-dep  # Intel Compiler Suite
OPTIONS
program_files optional name of program files Defaults to current directory. -o output file. If not present, defaults to stdout. If present but no value is given "Makefile" is used. -v verbose mode. Shows lines in input files that were used to create the dependencies. -mode profile|production|debug If the default gfortran options are being used (ie. environment variables overide defaults) different compile and loader options are selected. profile adds -pg option for gprof(1) production good options for optimized performance debug typical debug options
–help display command help and exit –version output version information and exit EXAMPLES
ENVIRONMENT
CC defaults to "cc" CFLAGS defaults to "-O"
F90 defaults to "gfortran" F90FLAGS defaults to "-O"
FC defaults to "f90" FFLAGS defaults to "-O"
LDFLAGS defaults to "-s" LIBS defaults to "-lncurses -lreadline"
EXAMPLES
 Common usage
     env F90=f90 makeout PROGRAMS/testit.f90 -o;make
SEE ALSO
If your project needs exceeds the capabilities of makeout(1), see the documentation for gmake(1), make(1), cmake(1), cpp(1), fpp(1), automake(1), create_makefile(1), create_makefiles(1), gccmakedep(1), imake(1), makedepend(1), xmkmf(1) and many resources on the WWW.
References false().
makeout()
program makeout ()
References m_strings::chomp(), m_strings::expand(), file(), form, help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_strings::lower(), m_time::now(), only, pretty_print(), printmakevar(), m_io::readline(), m_kracken::rget(), m_kracken::sget(), m_kracken::sgets(), m_strings::split(), m_io::splitpath(), m_strings::substitute(), m_system::system_closedir(), m_system::system_opendir(), m_system::system_readdir(), m_system::system_stat(), and use.
pretty_print()
subroutine makeout::pretty_print (character(len=*), intent(in) prefix, character(len=*), intent(in) string)
References array, c(), m_strings::chomp(), file(), in, m_strings::lower(), m_strings::split(), m_io::splitpath(), and unit().
printmakevar()
subroutine makeout::printmakevar (character(len=*), intent(in) varname, character(len=*), intent(in) default)
Parameters
[in] varname given environment variable name and default value look in environment table for the variable and if it is set override the default, then print the value as "VARNAME = VALUE" in makefile