GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/manup.f90 File Reference
manup.f90 File Reference
Modules
module m_manup
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
manup - [DEVELOPER] Simple markup of text to a man(1) page
subroutine, public m_manup::manup (table, title, section, product)
subroutine printname (nameline)
subroutine printsynopsis (inline)
subroutine putline (lineout)
subroutine sh (line)
subroutine th (title, section, product)
program test_manup
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
manup - [DEVELOPER] Simple markup of text to a man(1) page
SYNOPSIS
manup FILE -cmd -section 1 -product "CLI utilities" -help .F. -version .F.
DESCRIPTION
FILE The input filename
-section N N is the man(1) section number. Typically the following categories are used:
User Commands 1 Executable programs or shell commands System Calls 2 System calls (functions provided by the kernel) Library Calls 3 Library calls (functions within program libraries) Special Files 4 Special files (usually found in /dev) File Formats 5 File formats and conventions (eg. /etc/passwd) Games 6 Games Miscellaneous 7 Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7) System Admin. 8 System administration commands (usually only for root) Kernel Extensions 9 Kernel routines [Non standard]
See the man(1) page for man(1) for further details.
-product -asis no formatting except for header lines.
-help display help and exit -version display version information and exit
References false().
printname()
subroutine manup::printname (character(len=*), intent(in) nameline)
References m_strings::substitute().
printsynopsis()
subroutine manup::printsynopsis (character(len=*), intent(in) inline) private
References m_strings::substitute().
putline()
subroutine manup::putline (character(len=*), intent(in) lineout) private
sh()
subroutine manup::sh (character(len=*) line) private
test_manup()
program test_manup ()
References file(), files, help_usage(), help_version(), m_kracken::iget(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), m_manup::manup(), m_kracken::sget(), m_kracken::sgets(), and unit().
th()
subroutine manup::th (character(len=*), intent(in) title, integer, intent(in) section, character(len=*), intent(in) product)
References m_time::now().