GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/month.f90 File Reference
month.f90 File Reference
Functions/Subroutines
program month_exe
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
month - [TIME] display a calendar
Function/Subroutine Documentation
help_usage()
subroutine month_exe::help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine month_exe::help_version (logical, intent(in) l_version)
NAME
month - [TIME] display a calendar
SYNOPSIS
month [[-year] NNNN] [-month NN|month_name]
DESCRIPTION
month(1) displays a simple calendar. If no arguments are specified, the current year is displayed.
OPTIONS
-month Display single month output. The month is numeric (1-12) or a month name or blank. If blank the current month is assumed.
-year NNNN Display a calendar for the whole year NNNN. A year starts on Jan 1st.
-help Display help text and exit. -version Display version information and exit.
EXAMPLES
   month -month 12
    >    December 2015
    >Mo Tu We Th Fr Sa Su
    >    1  2  3  4  5  6
    > 7  8  9 10 11 12 13
    >14 15 16 17 18 19 20
    >21 22 23 24 25 26 27
    >28 29 30 31
   month -month April # month names may be given instead of numbers
References false().
month_exe()
program month_exe ()
References m_time::box_month(), help_usage(), help_version(), m_kracken::iget(), m_kracken::kracken(), m_kracken::lget(), m_time::mo2v(), and m_kracken::sget().