GeneralPurposeFortran: m_manup Module Reference
m_manup Module Reference
Functions/Subroutines
subroutine, public manup (table, title, section, product)
Function/Subroutine Documentation
manup()
subroutine, public m_manup::manup (character(len=*), dimension(:), intent(in) table, character(len=*), intent(in) title, integer, intent(in) section, character(len=*), intent(in) product)
References m_strings::indent(), m_strings::notabs(), m_time::now(), printname(), printsynopsis(), putline(), m_strings::s2v(), sh(), m_strings::substitute(), th(), and m_strings::upper().