GeneralPurposeFortran: m_compare_float_numbers Module Reference
m_compare_float_numbers Module Reference
NAME
M_Compare_Float_Numbers - [M_Compare_Float_Numbers] perform relational comparisons on real numbers
Data Types
interface compare_float
interface operator(.equalto.)
interface operator(.greaterthan.)
interface operator(.lessthan.)
Functions/Subroutines
elemental logical function is_equal_to_single (x, y)
elemental logical function is_equal_to_double (x, y)
elemental logical function is_greater_than_single (x, y)
elemental logical function is_greater_than_double (x, y)
elemental logical function is_less_than_single (x, y)
elemental logical function is_less_than_double (x, y)
elemental logical function compare_float_single (x, y, ulp)
elemental logical function compare_float_double (x, y, ulp)
Variables
integer, parameter, private ifp = 2
integer, parameter, private iip = 3
integer, parameter, public byte = SELECTED_INT_KIND(1)
integer, parameter, public short = SELECTED_INT_KIND(4)
integer, parameter, public long = SELECTED_INT_KIND(8)
integer, parameter, private llong_t = SELECTED_INT_KIND(16)
integer, parameter, public llong = (((1 + SIGN(1, LLong_t)) / 2) * LLong_t) + (((1 - SIGN(1, LLong_t)) / 2) * Long)
integer, parameter, public n_bytes_byte = 1
integer, parameter, public n_bytes_short = 2
integer, parameter, public n_bytes_long = 4
integer, parameter, public n_bytes_llong = 8
integer, parameter, private n_ip_kinds = 4
integer, dimension(n_ip_kinds), parameter, private ip_kind_types = (/ Byte, Short, Long, LLong /)
integer, dimension(n_ip_kinds), parameter, private ip_byte_sizes = (/ n_Bytes_Byte, n_Bytes_Short, n_Bytes_Long, n_Bytes_LLong /)
integer, parameter, public ip_kind = IP_KIND_TYPES(IIP)
integer, parameter, public n_bytes_ip_kind = IP_BYTE_SIZES(IIP)
integer, parameter, public single = SELECTED_REAL_KIND(6)
integer, parameter, public double = SELECTED_REAL_KIND(15)
integer, parameter, private quad_t = SELECTED_REAL_KIND(20)
integer, parameter, public quad = (((1 + SIGN(1, Quad_t)) / 2) * Quad_t) + (((1 - SIGN(1, Quad_t)) / 2) * Double)
integer, parameter, public n_bytes_single = 4
integer, parameter, public n_bytes_double = 8
integer, parameter, public n_bytes_quad = 16
integer, parameter, private n_fp_kinds = 3
integer, dimension(n_fp_kinds), parameter, private fp_kind_types = (/ Single, Double, Quad /)
integer, dimension(n_fp_kinds), parameter, private fp_byte_sizes = (/ n_Bytes_Single, n_Bytes_Double, n_Bytes_Quad /)
integer, parameter, public fp_kind = FP_KIND_TYPES(IFP)
integer, parameter, public n_bytes_fp_kind = FP_BYTE_SIZES(IFP)
character(len= *), parameter, private module_rcs_id = '$Id: M_Compare_Float_Numbers.f90,v 2.3 2004/10/06 19:00:23 paulv Exp $'
Detailed Description
NAME
M_Compare_Float_Numbers - [M_Compare_Float_Numbers] perform relational comparisons on real numbers
PURPOSE
Module containing routines to perform equality and relational comparisons on floating point numbers.
CATEGORY
Utility
LANGUAGE
Fortran-95
CALLING SEQUENCE
USE M_Compare_Float_Numbers
CONTAINS
.EqualTo. Relational operator to test the equality of floating point numbers.
.GreaterThan. Relational operator to test if one operand is greater than another.
.LessThan. Relational operator to test if one operand is less than another.
Compare_Float: Function to compare floating point scalars and arrays with adjustable precision tolerance.
INCLUDE FILES
None.
EXTERNALS
None.
COMMON BLOCKS
None.
CREATION HISTORY
Written by: Paul van Delst, CIMSS/SSEC 01-Apr-2003 paul..nosp@m.vand.nosp@m.elst@.nosp@m.ssec.nosp@m..wisc.nosp@m..edu
Copyright: (C) 2003 Paul van Delst
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
Function/Subroutine Documentation
compare_float_double()
elemental logical function m_compare_float_numbers::compare_float_double (real(double), intent(in) x, real(double), intent(in) y, integer, intent(in), optional ulp) private
compare_float_single()
elemental logical function m_compare_float_numbers::compare_float_single (real(single), intent(in) x, real(single), intent(in) y, integer, intent(in), optional ulp) private
is_equal_to_double()
elemental logical function m_compare_float_numbers::is_equal_to_double (real(double), intent(in) x, real(double), intent(in) y) private
is_equal_to_single()
elemental logical function m_compare_float_numbers::is_equal_to_single (real(single), intent(in) x, real(single), intent(in) y) private
is_greater_than_double()
elemental logical function m_compare_float_numbers::is_greater_than_double (real(double), intent(in) x, real(double), intent(in) y) private
References false(), and true().
is_greater_than_single()
elemental logical function m_compare_float_numbers::is_greater_than_single (real(single), intent(in) x, real(single), intent(in) y) private
References false(), and true().
is_less_than_double()
elemental logical function m_compare_float_numbers::is_less_than_double (real(double), intent(in) x, real(double), intent(in) y) private
References false(), and true().
is_less_than_single()
elemental logical function m_compare_float_numbers::is_less_than_single (real(single), intent(in) x, real(single), intent(in) y) private
References false(), and true().
Variable Documentation
byte
integer, parameter, public m_compare_float_numbers::byte = SELECTED_INT_KIND(1)
double
integer, parameter, public m_compare_float_numbers::double = SELECTED_REAL_KIND(15)
fp_byte_sizes
integer, dimension(n_fp_kinds), parameter, private m_compare_float_numbers::fp_byte_sizes = (/ n_Bytes_Single, n_Bytes_Double, n_Bytes_Quad /) private
fp_kind
integer, parameter, public m_compare_float_numbers::fp_kind = FP_KIND_TYPES(IFP)
fp_kind_types
integer, dimension(n_fp_kinds), parameter, private m_compare_float_numbers::fp_kind_types = (/ Single, Double, Quad /) private
ifp
integer, parameter, private m_compare_float_numbers::ifp = 2 private
iip
integer, parameter, private m_compare_float_numbers::iip = 3 private
ip_byte_sizes
integer, dimension(n_ip_kinds), parameter, private m_compare_float_numbers::ip_byte_sizes = (/ n_Bytes_Byte, n_Bytes_Short, n_Bytes_Long, n_Bytes_LLong /) private
ip_kind
integer, parameter, public m_compare_float_numbers::ip_kind = IP_KIND_TYPES(IIP)
ip_kind_types
integer, dimension(n_ip_kinds), parameter, private m_compare_float_numbers::ip_kind_types = (/ Byte, Short, Long, LLong /) private
llong
integer, parameter, public m_compare_float_numbers::llong = (((1 + SIGN(1, LLong_t)) / 2) * LLong_t) + (((1 - SIGN(1, LLong_t)) / 2) * Long)
llong_t
integer, parameter, private m_compare_float_numbers::llong_t = SELECTED_INT_KIND(16) private
long
integer, parameter, public m_compare_float_numbers::long = SELECTED_INT_KIND(8)
module_rcs_id
character(len=*), parameter, private m_compare_float_numbers::module_rcs_id = '$Id: M_Compare_Float_Numbers.f90,v 2.3 2004/10/06 19:00:23 paulv Exp $' private
n_bytes_byte
integer, parameter, public m_compare_float_numbers::n_bytes_byte = 1
n_bytes_double
integer, parameter, public m_compare_float_numbers::n_bytes_double = 8
n_bytes_fp_kind
integer, parameter, public m_compare_float_numbers::n_bytes_fp_kind = FP_BYTE_SIZES(IFP)
n_bytes_ip_kind
integer, parameter, public m_compare_float_numbers::n_bytes_ip_kind = IP_BYTE_SIZES(IIP)
n_bytes_llong
integer, parameter, public m_compare_float_numbers::n_bytes_llong = 8
n_bytes_long
integer, parameter, public m_compare_float_numbers::n_bytes_long = 4
n_bytes_quad
integer, parameter, public m_compare_float_numbers::n_bytes_quad = 16
n_bytes_short
integer, parameter, public m_compare_float_numbers::n_bytes_short = 2
n_bytes_single
integer, parameter, public m_compare_float_numbers::n_bytes_single = 4
n_fp_kinds
integer, parameter, private m_compare_float_numbers::n_fp_kinds = 3 private
n_ip_kinds
integer, parameter, private m_compare_float_numbers::n_ip_kinds = 4 private
quad
integer, parameter, public m_compare_float_numbers::quad = (((1 + SIGN(1, Quad_t)) / 2) * Quad_t) + (((1 - SIGN(1, Quad_t)) / 2) * Double)
quad_t
integer, parameter, private m_compare_float_numbers::quad_t = SELECTED_REAL_KIND(20) private
short
integer, parameter, public m_compare_float_numbers::short = SELECTED_INT_KIND(4)
single
integer, parameter, public m_compare_float_numbers::single = SELECTED_REAL_KIND(6)