GeneralPurposeFortran: m_stopwatch Module Reference
m_stopwatch Module Reference
M_StopWatch Version 1.1.
Data Types
type clocks
interface create_watch
interface create_watchgroup
interface destroy_watch
interface end_pause_watch
interface join_watchgroup
interface leave_watchgroup
interface option_stopwatch
interface pause_watch
interface print_watch
interface read_watch
interface reset_watch
interface start_watch
type status_type
interface stop_watch
type watch_actual
type watch_list
type watch_pointer
type watchgroup
type watchtype
interface which_clocks
Functions/Subroutines
subroutine, private create_watch_actual (watch, clock, name, err)
subroutine, private create_watch_aa (watch, clock, name, err)
subroutine, private create_watch_as (watch, clock, name, err)
subroutine, private create_watch_sa (watch, clock, name, err)
subroutine, private create_watch_ss (watch, clock, name, err)
subroutine, private destroy_watch_actual (watch, clock, err)
subroutine, private destroy_watch_aa (watch, clock, err)
subroutine, private destroy_watch_as (watch, clock, err)
subroutine, private destroy_watch_sa (watch, clock, err)
subroutine, private destroy_watch_ss (watch, clock, err)
subroutine, private start_watch_actual (watch, clock, err)
subroutine, private start_watch_ga (watch, clock, err)
subroutine, private start_watch_gs (watch, clock, err)
subroutine, private start_watch_aa (watch, clock, err)
subroutine, private start_watch_as (watch, clock, err)
subroutine, private start_watch_sa (watch, clock, err)
subroutine, private start_watch_ss (watch, clock, err)
subroutine, private stop_watch_actual (watch, clock, err)
subroutine, private stop_watch_ga (watch, clock, err)
subroutine, private stop_watch_gs (watch, clock, err)
subroutine, private stop_watch_aa (watch, clock, err)
subroutine, private stop_watch_as (watch, clock, err)
subroutine, private stop_watch_sa (watch, clock, err)
subroutine, private stop_watch_ss (watch, clock, err)
subroutine, private reset_watch_actual (watch, clock, err)
subroutine, private reset_watch_ga (watch, clock, err)
subroutine, private reset_watch_gs (watch, clock, err)
subroutine, private reset_watch_aa (watch, clock, err)
subroutine, private reset_watch_as (watch, clock, err)
subroutine, private reset_watch_sa (watch, clock, err)
subroutine, private reset_watch_ss (watch, clock, err)
subroutine, private pause_watch_actual (watch, clock, err)
subroutine, private pause_watch_ga (watch, clock, err)
subroutine, private pause_watch_gs (watch, clock, err)
subroutine, private pause_watch_aa (watch, clock, err)
subroutine, private pause_watch_as (watch, clock, err)
subroutine, private pause_watch_sa (watch, clock, err)
subroutine, private pause_watch_ss (watch, clock, err)
subroutine, private end_pause_watch_actual (watch, clock, err)
subroutine, private end_pause_watch_ga (watch, clock, err)
subroutine, private end_pause_watch_gs (watch, clock, err)
subroutine, private end_pause_watch_aa (watch, clock, err)
subroutine, private end_pause_watch_as (watch, clock, err)
subroutine, private end_pause_watch_sa (watch, clock, err)
subroutine, private end_pause_watch_ss (watch, clock, err)
subroutine, private read_watch_actual (read_result, watch, clock, err)
subroutine, private read_watch_aa (read_result, watch, clock, err)
subroutine, private read_watch_ax (read_result, watch, err)
subroutine, private read_watch_as (read_result, watch, clock, err)
subroutine, private read_watch_sa (read_result, watch, clock, err)
subroutine, private read_watch_sx (read_result, watch, err)
subroutine, private read_watch_ss (read_result, watch, clock, err)
subroutine, private print_watch_actual (watch, clock, title, form, err)
subroutine, private print_time (str, time, form)
subroutine, private print_watch_ga (watch, clock, title, form, err)
subroutine, private print_watch_gs (watch, clock, title, form, err)
subroutine, private print_watch_aa (watch, clock, title, form, err)
subroutine, private print_watch_as (watch, clock, title, form, err)
subroutine, private print_watch_sa (watch, clock, title, form, err)
subroutine, private print_watch_ss (watch, clock, title, form, err)
subroutine, private option_stopwatch_a (default_clock, io_unit_print, io_unit_error, print_errors, abort_errors, print_form, err)
subroutine, private option_stopwatch_s (default_clock, io_unit_print, io_unit_error, print_errors, abort_errors, print_form, err)
subroutine, public inquiry_stopwatch (default_clock, io_unit_print, io_unit_error, print_errors, abort_errors, print_form, cpu_avail, user_avail, sys_avail, wall_avail, cpu_prec, wall_prec, version, err)
subroutine, private create_watchgroup_actual (watch, handle, err)
subroutine, private create_watchgroup_a (watch, handle, err)
subroutine, private create_watchgroup_s (watch, handle, err)
subroutine, public destroy_watchgroup (handle, err)
recursive subroutine, private free_watch_list (list_entry, err)
subroutine, private join_watchgroup_actual (watch, handle, err)
subroutine, private join_watchgroup_a (watch, handle, err)
subroutine, private join_watchgroup_s (watch, handle, err)
subroutine, private leave_watchgroup_actual (watch, handle, err)
subroutine, private leave_watchgroup_a (watch, handle, err)
subroutine, private leave_watchgroup_s (watch, handle, err)
subroutine, private which_clocks_a (clock, from, err)
subroutine, private which_clocks_s (clock, from, err)
subroutine, private err_handler_watch (code, routine, string1, string2, err)
Variables
character(len= *), parameter ident ="@(#)M_stopwatch::M_stopwatch(3f): package for measuring cpu and wall clock"
character(len=16), parameter, private sw_version = "1.1"
integer, parameter, private stopped = 1
integer, parameter, private running = 2
integer, parameter, private paused = 3
integer, parameter, private omitted = 4
integer, parameter, private err_create = 1
integer, parameter, private err_bad_state = 2
integer, parameter, private err_unk_state = 4
integer, parameter, private err_clock = 8
integer, parameter, private err_tmc = 16
integer, parameter, private err_names = 32
integer, parameter, private err_c2long = 64
integer, parameter, private err_group = 128
integer, parameter, private err_io = 256
integer, parameter, private err_alloc = 512
integer, parameter, private err_dealloc = 1024
integer, parameter, private err_form = 2048
integer, parameter, private clock_len = 4
integer, parameter, private name_len = 132
integer, parameter, private form_len = 12
logical, private do_cpu
logical, private do_user
logical, private do_sys
logical, private do_wall
character(len=clock_len), dimension(:), allocatable, private default_clocks
integer, save, private iounit = 6
integer, save, private errunit = 6
logical, save, private errprint = .true.
logical, save, private errabort = .false.
character(len=form_len), save, private default_form = "sec"
Detailed Description
M_StopWatch Version 1.1.
M_StopWatch is a Fortran 90 module for portable, easy-to-use measurement of execution time. It supports four clocks
o wall clock o CPU clock o user CPU clock o system CPU clock
and returns all times in seconds.
It provides a simple means of determining which clocks are available, and the precision of those clocks.
M_StopWatch is used by instrumenting your code with subroutine calls that mimic the operation of a stop watch. M_StopWatch supports multiple watches, and provides the concept of watch groups to allow functions to operate on multiple watches simultaneously.
For further information on using M_StopWatch, see the User Guide or man pages.
The M_StopWatch software and documentation have been produced as part of work done by the U.S. Government, and are not subject to copyright in the United States.
William F. Mitchell mitch.nosp@m.ell@.nosp@m.cam.n.nosp@m.ist..nosp@m.gov National Institute of Standards and Technology December 2, 1996
The research software provided on this web site (software) is provided by NIST as a public service. You may use, copy and distribute copies of the software in any medium, provided that you keep intact this entire notice. You may improve, modify and create derivative works of the software or any portion of the software, and you may copy and distribute such modifications or works. Modified works should carry a notice stating that you changed the software and should note the date and nature of any such change. Please explicitly acknowledge the National Institute of Standards and Technology as the source of the software.
The software is expressly provided AS IS. NIST MAKES NO WARRANTY OF ANY KIND,
EXPRESS, IMPLIED, IN FACT OR ARISING BY OPERATION OF LAW, INCLUDING, WITHOUT
LIMITATION, THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE, NON-INFRINGEMENT AND DATA ACCURACY. NIST NEITHER REPRESENTS NOR
WARRANTS THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED OR ERROR-FREE,
OR THAT ANY DEFECTS WILL BE CORRECTED. NIST DOES NOT WARRANT OR MAKE ANY
REPRESENTATIONS REGARDING THE USE OF THE SOFTWARE OR THE RESULTS THEREOF,
INCLUDING BUT NOT LIMITED TO THE CORRECTNESS, ACCURACY, RELIABILITY, OR
USEFULNESS OF THE SOFTWARE.
You are solely responsible for determining the appropriateness of using and distributing the software and you assume all risks associated with its use, including but not limited to the risks and costs of program errors, compliance with applicable laws, damage to or loss of data, programs or equipment, and the unavailability or interruption of operation. This software is not intended to be used in any situation where a failure could cause risk of injury or damage to property. The software was developed by NIST employees. NIST employee contributions are not subject to copyright protection within the United States.
Function/Subroutine Documentation
create_watch_aa()
subroutine, private m_stopwatch::create_watch_aa (type (watchtype), dimension(:), intent(out) watch, character(len=*), dimension(:), intent(in) clock, character(len=*), dimension(:), intent(in), optional name, integer, intent(out), optional err) private
References create_watch_actual(), err_alloc, err_dealloc, err_handler_watch(), err_names, type(), watch, and watches.
create_watch_actual()
subroutine, private m_stopwatch::create_watch_actual (type (watch_pointer), dimension(:), intent(out) watch, character(len=*), dimension(:), intent(in) clock, character(len=*), dimension(:), intent(in) name, integer, intent(out), optional err) private
References default_clocks, do_cpu, do_sys, do_user, do_wall, err_alloc, err_c2long, err_handler_watch(), omitted, stopped, type(), and watch.
create_watch_as()
subroutine, private m_stopwatch::create_watch_as (type (watchtype), dimension(:), intent(out) watch, character(len=*), intent(in), optional clock, character(len=*), dimension(:), intent(in), optional name, integer, intent(out), optional err) private
References create_watch_aa(), default_clocks, type(), and watch.
create_watch_sa()
subroutine, private m_stopwatch::create_watch_sa (type (watchtype), intent(out) watch, character(len=*), dimension(:), intent(in) clock, character(len=*), intent(in), optional name, integer, intent(out), optional err) private
References create_watch_actual(), type(), watch, and watches.
create_watch_ss()
subroutine, private m_stopwatch::create_watch_ss (type (watchtype), intent(out) watch, character(len=*), intent(in), optional clock, character(len=*), intent(in), optional name, integer, intent(out), optional err) private
References create_watch_actual(), default_clocks, type(), watch, and watches.
create_watchgroup_a()
subroutine, private m_stopwatch::create_watchgroup_a (type (watchtype), dimension(:), intent(in) watch, type (watchgroup), intent(out) handle, integer, intent(out), optional err) private
References create_watchgroup_actual(), err_alloc, err_dealloc, err_handler_watch(), handle, type(), watch, and watches.
create_watchgroup_actual()
subroutine, private m_stopwatch::create_watchgroup_actual (type (watch_pointer), dimension(:), intent(in), optional watch, type (watchgroup), intent(out), optional handle, integer, intent(out), optional err) private
References err_alloc, err_create, err_handler_watch(), handle, type(), and watch.
create_watchgroup_s()
subroutine, private m_stopwatch::create_watchgroup_s (type (watchtype), intent(in), optional watch, type (watchgroup), intent(out), optional handle, integer, intent(out), optional err) private
References create_watchgroup_actual(), handle, type(), watch, and watches.
destroy_watch_aa()
subroutine, private m_stopwatch::destroy_watch_aa (type (watchtype), dimension(:), intent(inout) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References destroy_watch_actual(), err_alloc, err_dealloc, err_handler_watch(), type(), watch, and watches.
destroy_watch_actual()
subroutine, private m_stopwatch::destroy_watch_actual (type (watch_pointer), dimension(:), intent(inout) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References do_cpu, do_sys, do_user, do_wall, err_create, err_dealloc, err_handler_watch(), omitted, type(), and watch.
destroy_watch_as()
subroutine, private m_stopwatch::destroy_watch_as (type (watchtype), dimension(:), intent(inout) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, destroy_watch_aa(), type(), and watch.
destroy_watch_sa()
subroutine, private m_stopwatch::destroy_watch_sa (type (watchtype), intent(inout) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References destroy_watch_actual(), type(), watch, and watches.
destroy_watch_ss()
subroutine, private m_stopwatch::destroy_watch_ss (type (watchtype), intent(inout) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, destroy_watch_actual(), type(), watch, and watches.
destroy_watchgroup()
subroutine, public m_stopwatch::destroy_watchgroup (type (watchgroup), intent(inout) handle, integer, intent(out), optional err)
References err_dealloc, err_handler_watch(), free_watch_list(), handle, and type().
end_pause_watch_aa()
subroutine, private m_stopwatch::end_pause_watch_aa (type (watchtype), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References end_pause_watch_actual(), err_alloc, err_dealloc, err_handler_watch(), type(), watch, and watches.
end_pause_watch_actual()
subroutine, private m_stopwatch::end_pause_watch_actual (type (watch_pointer), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References do_cpu, do_sys, do_user, do_wall, err_bad_state, err_create, err_handler_watch(), err_unk_state, omitted, paused, running, stopped, type(), and watch.
end_pause_watch_as()
subroutine, private m_stopwatch::end_pause_watch_as (type (watchtype), dimension(:), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, end_pause_watch_aa(), type(), and watch.
end_pause_watch_ga()
subroutine, private m_stopwatch::end_pause_watch_ga (type (watchgroup), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References end_pause_watch_actual(), err_alloc, err_dealloc, err_handler_watch(), type(), watch, and watches.
end_pause_watch_gs()
subroutine, private m_stopwatch::end_pause_watch_gs (type (watchgroup), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, end_pause_watch_ga(), type(), and watch.
end_pause_watch_sa()
subroutine, private m_stopwatch::end_pause_watch_sa (type (watchtype), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References end_pause_watch_actual(), type(), watch, and watches.
end_pause_watch_ss()
subroutine, private m_stopwatch::end_pause_watch_ss (type (watchtype), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, end_pause_watch_actual(), type(), watch, and watches.
err_handler_watch()
subroutine, private m_stopwatch::err_handler_watch (integer, intent(in) code, character(len=*), intent(in) routine, character(len=*), intent(in) string1, character(len=*), intent(in) string2, integer, intent(inout), optional err) private
References err_alloc, err_bad_state, err_c2long, err_clock, err_create, err_dealloc, err_form, err_group, err_io, err_names, err_tmc, err_unk_state, errabort, errprint, errunit, iounit, and unit().
free_watch_list()
recursive subroutine, private m_stopwatch::free_watch_list (type (watch_list), intent(inout) list_entry, integer, intent(out), optional err) private
References err_dealloc, err_handler_watch(), and type().
inquiry_stopwatch()
subroutine, public m_stopwatch::inquiry_stopwatch (character(len=*), dimension(:), intent(out), optional default_clock, integer, intent(out), optional io_unit_print, integer, intent(out), optional io_unit_error, logical, intent(out), optional print_errors, logical, intent(out), optional abort_errors, character(len=*), intent(out), optional print_form, logical, intent(out), optional cpu_avail, logical, intent(out), optional user_avail, logical, intent(out), optional sys_avail, logical, intent(out), optional wall_avail, real, intent(out), optional cpu_prec, real, intent(out), optional wall_prec, character(len=*), intent(out), optional version, integer, intent(out), optional err)
References default_clocks, default_form, errabort, errprint, errunit, false(), iounit, sw_version, and true().
join_watchgroup_a()
subroutine, private m_stopwatch::join_watchgroup_a (type (watchtype), dimension(:), intent(in) watch, type (watchgroup), intent(inout) handle, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), handle, join_watchgroup_actual(), type(), watch, and watches.
join_watchgroup_actual()
subroutine, private m_stopwatch::join_watchgroup_actual (type (watch_pointer), dimension(:), intent(in) watch, type (watchgroup), intent(inout) handle, integer, intent(out), optional err) private
References err_alloc, err_create, err_handler_watch(), handle, type(), and watch.
join_watchgroup_s()
subroutine, private m_stopwatch::join_watchgroup_s (type (watchtype), intent(in) watch, type (watchgroup), intent(inout) handle, integer, intent(out), optional err) private
References handle, join_watchgroup_actual(), type(), watch, and watches.
leave_watchgroup_a()
subroutine, private m_stopwatch::leave_watchgroup_a (type (watchtype), dimension(:), intent(in) watch, type (watchgroup), intent(inout) handle, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), handle, leave_watchgroup_actual(), type(), watch, and watches.
leave_watchgroup_actual()
subroutine, private m_stopwatch::leave_watchgroup_actual (type (watch_pointer), dimension(:), intent(in) watch, type (watchgroup), intent(inout) handle, integer, intent(out), optional err) private
References err_dealloc, err_group, err_handler_watch(), handle, type(), and watch.
leave_watchgroup_s()
subroutine, private m_stopwatch::leave_watchgroup_s (type (watchtype), intent(in) watch, type (watchgroup), intent(inout) handle, integer, intent(out), optional err) private
References handle, leave_watchgroup_actual(), type(), watch, and watches.
option_stopwatch_a()
subroutine, private m_stopwatch::option_stopwatch_a (character(len=*), dimension(:), intent(in) default_clock, integer, intent(in), optional io_unit_print, integer, intent(in), optional io_unit_error, logical, intent(in), optional print_errors, logical, intent(in), optional abort_errors, character(len=*), intent(in), optional print_form, integer, intent(out), optional err) private
References default_clocks, default_form, err_alloc, err_clock, err_dealloc, err_form, err_handler_watch(), err_io, err_tmc, errabort, errprint, errunit, iounit, and unit().
option_stopwatch_s()
subroutine, private m_stopwatch::option_stopwatch_s (character(len=*), intent(in), optional default_clock, integer, intent(in), optional io_unit_print, integer, intent(in), optional io_unit_error, logical, intent(in), optional print_errors, logical, intent(in), optional abort_errors, character(len=*), intent(in), optional print_form, integer, intent(out), optional err) private
References option_stopwatch_a().
pause_watch_aa()
subroutine, private m_stopwatch::pause_watch_aa (type (watchtype), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), pause_watch_actual(), type(), watch, and watches.
pause_watch_actual()
subroutine, private m_stopwatch::pause_watch_actual (type (watch_pointer), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References do_cpu, do_sys, do_user, do_wall, err_bad_state, err_create, err_handler_watch(), err_unk_state, omitted, paused, running, stopped, type(), and watch.
pause_watch_as()
subroutine, private m_stopwatch::pause_watch_as (type (watchtype), dimension(:), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, pause_watch_aa(), type(), and watch.
pause_watch_ga()
subroutine, private m_stopwatch::pause_watch_ga (type (watchgroup), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), pause_watch_actual(), type(), watch, and watches.
pause_watch_gs()
subroutine, private m_stopwatch::pause_watch_gs (type (watchgroup), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, pause_watch_ga(), type(), and watch.
pause_watch_sa()
subroutine, private m_stopwatch::pause_watch_sa (type (watchtype), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References pause_watch_actual(), type(), watch, and watches.
pause_watch_ss()
subroutine, private m_stopwatch::pause_watch_ss (type (watchtype), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, pause_watch_actual(), type(), watch, and watches.
print_time()
subroutine, private m_stopwatch::print_time (character(len=*), intent(in) str, real, intent(in) time, character(len=*), intent(in) form) private
References iounit, and unit().
print_watch_aa()
subroutine, private m_stopwatch::print_watch_aa (type (watchtype), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, character(len=*), intent(in), optional title, character(len=*), intent(in), optional form, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), print_watch_actual(), type(), watch, and watches.
print_watch_actual()
subroutine, private m_stopwatch::print_watch_actual (type (watch_pointer), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, character(len=*), intent(in), optional title, character(len=*), intent(in), optional form, integer, intent(out), optional err) private
References default_form, do_cpu, do_sys, do_user, do_wall, err_create, err_form, err_handler_watch(), err_io, iounit, omitted, print_time(), type(), unit(), and watch.
print_watch_as()
subroutine, private m_stopwatch::print_watch_as (type (watchtype), dimension(:), intent(in) watch, character(len=*), intent(in), optional clock, character(len=*), intent(in), optional title, character(len=*), intent(in), optional form, integer, intent(out), optional err) private
References default_clocks, print_watch_aa(), type(), and watch.
print_watch_ga()
subroutine, private m_stopwatch::print_watch_ga (type (watchgroup), intent(in) watch, character(len=*), dimension(:), intent(in) clock, character(len=*), intent(in), optional title, character(len=*), intent(in), optional form, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), print_watch_actual(), type(), watch, and watches.
print_watch_gs()
subroutine, private m_stopwatch::print_watch_gs (type (watchgroup), intent(in) watch, character(len=*), intent(in), optional clock, character(len=*), intent(in), optional title, character(len=*), intent(in), optional form, integer, intent(out), optional err) private
References default_clocks, print_watch_ga(), type(), and watch.
print_watch_sa()
subroutine, private m_stopwatch::print_watch_sa (type (watchtype), intent(in) watch, character(len=*), dimension(:), intent(in) clock, character(len=*), intent(in), optional title, character(len=*), intent(in), optional form, integer, intent(out), optional err) private
References print_watch_actual(), type(), watch, and watches.
print_watch_ss()
subroutine, private m_stopwatch::print_watch_ss (type (watchtype), intent(in) watch, character(len=*), intent(in), optional clock, character(len=*), intent(in), optional title, character(len=*), intent(in), optional form, integer, intent(out), optional err) private
References default_clocks, print_watch_actual(), type(), watch, and watches.
read_watch_aa()
subroutine, private m_stopwatch::read_watch_aa (real, dimension(:,:), pointer read_result, type (watchtype), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), read_watch_actual(), type(), watch, and watches.
read_watch_actual()
subroutine, private m_stopwatch::read_watch_actual (real, dimension(:,:), pointer read_result, type (watch_pointer), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References do_cpu, do_sys, do_user, do_wall, err_alloc, err_create, err_handler_watch(), err_unk_state, omitted, paused, running, stopped, type(), and watch.
read_watch_as()
subroutine, private m_stopwatch::read_watch_as (real, dimension(:), pointer read_result, type (watchtype), dimension(:), intent(in) watch, character(len=*), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), read_watch_actual(), type(), watch, and watches.
read_watch_ax()
subroutine, private m_stopwatch::read_watch_ax (real, dimension(:,:), pointer read_result, type (watchtype), dimension(:), intent(in) watch, integer, intent(out), optional err) private
References default_clocks, err_alloc, err_dealloc, err_handler_watch(), read_watch_actual(), type(), watch, and watches.
read_watch_sa()
subroutine, private m_stopwatch::read_watch_sa (real, dimension(:), pointer read_result, type (watchtype), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References read_watch_actual(), type(), watch, and watches.
read_watch_ss()
subroutine, private m_stopwatch::read_watch_ss (real, intent(out) read_result, type (watchtype), intent(in) watch, character(len=*), intent(in) clock, integer, intent(out), optional err) private
References read_watch_actual(), type(), watch, and watches.
read_watch_sx()
subroutine, private m_stopwatch::read_watch_sx (real, dimension(:), pointer read_result, type (watchtype), intent(in) watch, integer, intent(out), optional err) private
References default_clocks, read_watch_actual(), type(), watch, and watches.
reset_watch_aa()
subroutine, private m_stopwatch::reset_watch_aa (type (watchtype), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), reset_watch_actual(), type(), watch, and watches.
reset_watch_actual()
subroutine, private m_stopwatch::reset_watch_actual (type (watch_pointer), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References do_cpu, do_sys, do_user, do_wall, err_bad_state, err_create, err_handler_watch(), err_unk_state, omitted, paused, running, stopped, type(), and watch.
reset_watch_as()
subroutine, private m_stopwatch::reset_watch_as (type (watchtype), dimension(:), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, reset_watch_aa(), type(), and watch.
reset_watch_ga()
subroutine, private m_stopwatch::reset_watch_ga (type (watchgroup), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), reset_watch_actual(), type(), watch, and watches.
reset_watch_gs()
subroutine, private m_stopwatch::reset_watch_gs (type (watchgroup), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, reset_watch_ga(), type(), and watch.
reset_watch_sa()
subroutine, private m_stopwatch::reset_watch_sa (type (watchtype), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References reset_watch_actual(), type(), watch, and watches.
reset_watch_ss()
subroutine, private m_stopwatch::reset_watch_ss (type (watchtype), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, reset_watch_actual(), type(), watch, and watches.
start_watch_aa()
subroutine, private m_stopwatch::start_watch_aa (type (watchtype), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), start_watch_actual(), type(), watch, and watches.
start_watch_actual()
subroutine, private m_stopwatch::start_watch_actual (type (watch_pointer), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References do_cpu, do_sys, do_user, do_wall, err_bad_state, err_create, err_handler_watch(), err_unk_state, omitted, paused, running, stopped, type(), and watch.
start_watch_as()
subroutine, private m_stopwatch::start_watch_as (type (watchtype), dimension(:), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, start_watch_aa(), type(), and watch.
start_watch_ga()
subroutine, private m_stopwatch::start_watch_ga (type (watchgroup), intent(inout) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), start_watch_actual(), type(), watch, and watches.
start_watch_gs()
subroutine, private m_stopwatch::start_watch_gs (type (watchgroup), intent(inout) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, start_watch_ga(), type(), and watch.
start_watch_sa()
subroutine, private m_stopwatch::start_watch_sa (type (watchtype), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References start_watch_actual(), type(), watch, and watches.
start_watch_ss()
subroutine, private m_stopwatch::start_watch_ss (type (watchtype), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, start_watch_actual(), type(), watch, and watches.
stop_watch_aa()
subroutine, private m_stopwatch::stop_watch_aa (type (watchtype), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), stop_watch_actual(), type(), watch, and watches.
stop_watch_actual()
subroutine, private m_stopwatch::stop_watch_actual (type (watch_pointer), dimension(:), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References do_cpu, do_sys, do_user, do_wall, err_bad_state, err_create, err_handler_watch(), err_unk_state, omitted, paused, running, stopped, type(), and watch.
stop_watch_as()
subroutine, private m_stopwatch::stop_watch_as (type (watchtype), dimension(:), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, stop_watch_aa(), type(), and watch.
stop_watch_ga()
subroutine, private m_stopwatch::stop_watch_ga (type (watchgroup), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References err_alloc, err_dealloc, err_handler_watch(), stop_watch_actual(), type(), watch, and watches.
stop_watch_gs()
subroutine, private m_stopwatch::stop_watch_gs (type (watchgroup), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, stop_watch_ga(), type(), and watch.
stop_watch_sa()
subroutine, private m_stopwatch::stop_watch_sa (type (watchtype), intent(in) watch, character(len=*), dimension(:), intent(in) clock, integer, intent(out), optional err) private
References stop_watch_actual(), type(), watch, and watches.
stop_watch_ss()
subroutine, private m_stopwatch::stop_watch_ss (type (watchtype), intent(in) watch, character(len=*), intent(in), optional clock, integer, intent(out), optional err) private
References default_clocks, stop_watch_actual(), type(), watch, and watches.
which_clocks_a()
subroutine, private m_stopwatch::which_clocks_a (character(len=*), dimension(:), intent(in) clock, character(len=*), intent(in) from, integer, intent(inout), optional err) private
References do_cpu, do_sys, do_user, do_wall, err_clock, err_handler_watch(), false(), and true().
which_clocks_s()
subroutine, private m_stopwatch::which_clocks_s (character(len=*), intent(in) clock, character(len=*), intent(in) from, integer, intent(inout), optional err) private
References which_clocks_a().
Variable Documentation
clock_len
integer, parameter, private m_stopwatch::clock_len = 4 private
default_clocks
character(len=clock_len), dimension(:), allocatable, private m_stopwatch::default_clocks private
default_form
character(len=form_len), save, private m_stopwatch::default_form = "sec" private
do_cpu
logical, private m_stopwatch::do_cpu private
do_sys
logical, private m_stopwatch::do_sys private
do_user
logical, private m_stopwatch::do_user private
do_wall
logical, private m_stopwatch::do_wall private
err_alloc
integer, parameter, private m_stopwatch::err_alloc = 512 private
err_bad_state
integer, parameter, private m_stopwatch::err_bad_state = 2 private
err_c2long
integer, parameter, private m_stopwatch::err_c2long = 64 private
err_clock
integer, parameter, private m_stopwatch::err_clock = 8 private
err_create
integer, parameter, private m_stopwatch::err_create = 1 private
err_dealloc
integer, parameter, private m_stopwatch::err_dealloc = 1024 private
err_form
integer, parameter, private m_stopwatch::err_form = 2048 private
err_group
integer, parameter, private m_stopwatch::err_group = 128 private
err_io
integer, parameter, private m_stopwatch::err_io = 256 private
err_names
integer, parameter, private m_stopwatch::err_names = 32 private
err_tmc
integer, parameter, private m_stopwatch::err_tmc = 16 private
err_unk_state
integer, parameter, private m_stopwatch::err_unk_state = 4 private
errabort
logical, save, private m_stopwatch::errabort = .false. private
errprint
logical, save, private m_stopwatch::errprint = .true. private
errunit
integer, save, private m_stopwatch::errunit = 6 private
form_len
integer, parameter, private m_stopwatch::form_len = 12 private
ident
character(len=*), parameter m_stopwatch::ident ="@(#)M_stopwatch::M_stopwatch(3f): package for measuring cpu and wall clock" private
iounit
integer, save, private m_stopwatch::iounit = 6 private
name_len
integer, parameter, private m_stopwatch::name_len = 132 private
omitted
integer, parameter, private m_stopwatch::omitted = 4 private
paused
integer, parameter, private m_stopwatch::paused = 3 private
running
integer, parameter, private m_stopwatch::running = 2 private
stopped
integer, parameter, private m_stopwatch::stopped = 1 private
sw_version
character(len=16), parameter, private m_stopwatch::sw_version = "1.1" private