GeneralPurposeFortran: m_system Module Reference
m_system Module Reference
NAME
M_system(3fm) - [M_system] Fortran interface to C system interface
SYNOPSIS
Data Types
interface c_flush
type dirent_cygwin
type dirent_systema
interface system_errno
interface system_getegid
interface system_geteuid
interface system_getgid
interface system_getpid
interface system_getppid
interface system_getsid
interface system_getuid
interface system_initenv
interface system_kill
interface system_rand
interface system_srand
interface system_umask
Functions/Subroutines
logical function, public system_access (pathname, amode)
NAME
system_access(3f) - [M_system] checks accessibility or existence of a pathname
logical function, public system_issock (pathname)
NAME
system_issock(3f) - [M_system] checks if argument is a socket
logical function, public system_isfifo (pathname)
NAME
system_isfifo(3f) - [M_system] checks if argument is a fifo - named pipe
logical function, public system_ischr (pathname)
NAME
system_ischr(3f) - [M_system] checks if argument is a character device
logical function, public system_isreg (pathname)
NAME
system_isreg(3f) - [M_system] checks if argument is a regular file
logical function, public system_islnk (pathname)
NAME
system_islnk(3f) - [M_system] checks if argument is a link
logical function, public system_isblk (pathname)
NAME
system_isblk(3f) - [M_system] checks if argument is a block device
logical function, public system_chown (dirname, owner, group)
NAME
system_chown(3f) - [M_system] change file owner and group
logical function, public system_isdir (dirname)
NAME
system_isdir(3f) - [M_system] checks if argument is a directory path
subroutine, public system_cpu_time (total, user, system)
NAME
system_cpu_time(3f) - [M_system] get processor time by calling times(3c)
integer function, public system_link (oldname, newname)
NAME
system_link(3f) - [M_system] link one file to another file relative to two directory file descriptors
integer function, public system_unlink (fname)
NAME
system_unlink(3f) - [M_system] remove a directory entry relative to directory file descriptor
integer function, public system_setumask (umask_value)
NAME
system_setumask(3f) - [M_system] set the file mode creation umask
SYNOPSIS
integer function, public system_getumask ()
NAME
system_getumask(3f) - [M_system] get current umask
SYNOPSIS
subroutine, public system_perror (prefix)
NAME
perror(3f) - [M_system] print error message for last C error on stderr
SYNOPSIS
subroutine, public system_chdir (path, err)
NAME
system_chdir(3f) - [M_system] call chdir(3c) from Fortran to change working directory
SYNOPSIS
integer(c_int) function, public system_remove (path)
NAME
system_remove(3f) - [M_system] call remove(3c) to remove file
SYNOPSIS
integer function, public system_rename (input, output)
NAME
system_rename(3f) - [M_system] call rename(3c) to rename a system file
SYNOPSIS
integer function, public system_chmod (filename, mode)
NAME
system_chmod(3f) - [M_system] call chmod(3c) to change permission mode of a file relative to directory file descriptor
SYNOPSIS
subroutine, public system_getcwd (output, ierr)
NAME
system_getcwd(3f) - [M_system] call getcwd(3c) to get the pathname of the current working directory
SYNOPSIS
integer(c_int) function, public system_rmdir (dirname)
NAME
system_rmdir(3f) - [M_system] call rmdir(3c) to remove empty directories
SYNOPSIS
integer function, public system_mkfifo (dirname, mode)
NAME
system_mkfifo(3f) - [M_system] make a FIFO special file relative to directory file descriptor
SYNOPSIS
integer function, public system_mkdir (dirname, mode)
NAME
system_mkdir(3f) - [M_system] call mkdir(3c) to create a new directory
SYNOPSIS
subroutine, public system_opendir (dirname, dir, ierr)
NAME
system_opendir(3f) - [M_system] open directory stream by calling opendir(3c)
SYNOPSIS
subroutine, public system_readdir (dir, filename, ierr)
NAME
system_readdir(3f) - [M_system] read a directory using readdir(3c)
SYNOPSIS
subroutine, public system_rewinddir (dir)
NAME
system_rewinddir(3f) - [M_system] call rewinddir(3c) to rewind directory stream
SYNOPSIS
subroutine, public system_closedir (dir, ierr)
NAME
system_closedir(3f) - [M_system] close a directory stream by calling closedir(3c)
SYNOPSIS
subroutine, public system_putenv (string, err)
NAME
system_putenv(3f) - [M_system] set environment variable from Fortran by calling putenv(3c)
subroutine, public set_environment_variable (NAME, VALUE, STATUS)
NAME
set_environment_variable(3f) - [M_system] call setenv(3c) to set environment variable
SYNOPSIS
subroutine, public system_clearenv (ierr)
NAME
system_clearenv(3f) - [M_system] clear environment by calling clearenv(3c)
subroutine, public system_unsetenv (name, ierr)
NAME
system_unsetenv(3f) - [M_system] change or add an environment variable by calling unsetenv(3c)
SYNOPSIS
character(len=:) function, allocatable, public system_readenv ()
NAME
system_readenv(3f) - [M_system] step thru and read environment table
SYNOPSIS
subroutine, public fileglob (glob, list)
NAME
fileglob(3f) - [M_system] Read output of an ls(1) command from Fortran
SYNOPSIS
subroutine, public system_uname (WHICH, NAMEOUT)
NAME
system_uname(3f) - [M_system] call a C wrapper that calls uname(3c) to get current system information from Fortran
SYNOPSIS
subroutine, public system_gethostname (NAME, IERR)
NAME
system_gethostname(3f) - [M_system] get name of current host
SYNOPSIS
character(len=:) function, allocatable, public system_getlogin ()
NAME
system_getlogin(3f) - [M_system] get login name
character(len=:) function, allocatable, public system_perm (mode)
NAME
system_perm(3f) - [M_system] get file type and permission as a string
character(len=:) function, allocatable, public system_getgrgid (gid)
NAME
system_getgrgid(3f) - [M_system] get groupd name associated with a GID
SYNOPSIS
character(len=:) function, allocatable, public system_getpwuid (uid)
NAME
system_getpwuid(3f) - [M_system] get login name associated with a UID
SYNOPSIS
pure character(len=size(array)) function arr2str (array)
pure character(len=1, kind=c_char) function, dimension(len(string)+1) str2arr (string)
character(len=:) function, allocatable c2f_string (c_string_pointer)
subroutine, public system_stat (pathname, values, ierr)
NAME
SYSTEM_STAT - [M_system] Get file status information
subroutine, public system_stat_print (filename, lun)
NAME
system_stat_print(3f) - [M_system] print the principal info obtained for a pathname from system_stat(3f)
SYNOPSIS
Variables
integer, parameter, public mode_t =kind(c_int)
character(len= *), parameter ident_srand ="@(#)M_system::system_srand(3f): call srand(3c)"
NAME
system_srand(3f) - [M_system] set seed for pseudo-random number generator system_rand(3f)
character(len= *), parameter ident_kill ="@(#)M_system::system_kill(3f): call kill(3c) to send a signal to a process"
NAME
system_kill(3f) - [M_system] send a signal to a process or a group of processes
character(len= *), parameter ident_errno ="@(#)M_system::system_errno(3f): return errno(3c)"
NAME
system_errno(3f) - [M_system] C error return value
SYNOPSIS
character(len= *), parameter ident_euid ="@(#)M_system::system_geteuid(3f): call geteuid(3c)"
NAME
system_geteuid(3f) - [M_system] get effective UID of current process from Fortran by calling geteuid(3c)
SYNOPSIS
character(len= *), parameter ident_uid ="@(#)M_system::system_getuid(3f): call getuid(3c)"
NAME
system_getuid(3f) - [M_system] get real UID of current process from Fortran by calling getuid(3c)
SYNOPSIS
character(len= *), parameter ident_egid ="@(#)M_system::system_getegid(3f): call getegid(3c)"
NAME
system_getegid(3f) - [M_system] get the effective group ID (GID) of current process from Fortran by calling getegid(3c)
SYNOPSIS
character(len= *), parameter ident_gid ="@(#)M_system::system_getgid(3f): call getgid(3c)"
NAME
system_getgid(3f) - [M_system] get the real group ID (GID) of current process from Fortran by calling getgid(3c)
SYNOPSIS
character(len= *), parameter ident_getsid ="@(#)M_system::system_getsid(3f): call getsid(3c) to get session leader for given pid"
NAME
system_getsid(3f) - [M_system] get the process group ID of a session leader
SYNOPSIS
character(len= *), parameter ident_pid ="@(#)M_system::system_getpid(3f): call getpid(3c)"
NAME
system_getpid(3f) - [M_system] get PID (process ID) of current process from Fortran by calling getpid(3c)
SYNOPSIS
character(len= *), parameter ident_ppid ="@(#)M_system::system_getppid(3f): call getppid(3c)"
NAME
system_getppid(3f) - [M_system] get parent process ID (PPID) of current process from Fortran by calling getppid(3c)
SYNOPSIS
character(len= *), parameter ident_umask ="@(#)M_system::system_umask(3f): call umask(3c)"
NAME
system_umask(3fp) - [M_system] set and get the file mode creation mask
SYNOPSIS
character(len= *), parameter ident_rand ="@(#)M_system::system_rand(3f): call rand(3c)"
NAME
system_rand(3f) - [M_system] call pseudo-random number generator rand(3c)
SYNOPSIS
integer(kind=c_long), dimension(c, name="f_ok") bind
NAME
system_initenv(3f) - [M_system] initialize environment table pointer and size so table can be read by readenv(3f)
SYNOPSIS
integer(kind=c_long) longest_env_variable
character(len= *), parameter ident_initenv ="@(#)M_system::system_initenv(3f): initialize environment table for reading"
integer(kind=c_int), public r_grp
integer(kind=c_int), public r_oth
integer(kind=c_int), public r_usr
integer(kind=c_int), public r_wxg
integer(kind=c_int), public r_wxo
integer(kind=c_int), public r_wxu
integer(kind=c_int), public w_grp
integer(kind=c_int), public w_oth
integer(kind=c_int), public w_usr
integer(kind=c_int), public x_grp
integer(kind=c_int), public x_oth
integer(kind=c_int), public x_usr
integer(kind=c_int), public deffilemode
integer(kind=c_int), public accessperms
integer(kind=c_int) host_name_max
integer(kind=c_int), public r_ok
integer(kind=c_int), public w_ok
integer(kind=c_int), public x_ok
integer(kind=c_int), public f_ok
Detailed Description
NAME
M_system(3fm) - [M_system] Fortran interface to C system interface
SYNOPSIS
Public objects:
use m_system, only : set_environment_variable, system_unsetenv, & system_putenv
use m_system, only : system_intenv, system_readenv, system_clearenv
use M_system, only : system_getcwd, system_link, & system_mkfifo, system_remove, system_rename, & system_umask, system_unlink, fileglob, & system_rmdir, system_chdir, system_mkdir, & system_stat, system_isdir, system_islnk, system_isreg, & system_isblk, system_ischr, system_isfifo, & system_access, & system_access, & system_issock, system_perm, system_stat_print
!!use M_system, only : system_getc, system_putc use M_system, only : system_errno, system_perror
use M_system, only : system_getegid, system_geteuid, system_getgid, & system_gethostname, system_getpid, system_getppid, system_getsid, & system_getuid, system_uname
use M_system, only : system_kill
use M_system, only : system_rand, system_srand
use M_system, only : system_cpu_time
DESCRIPTION
M_system(3fm) is a collection of Fortran procedures that call C or a C wrapper using the ISO_C_BINDING interface to access system calls. System calls are a special set of functions used by programs to communicate directly with an operating system.
Generally, system calls are slower than normal function calls because when you make a call control is relinquished to the operating system to perform the system call. In addition, depending on the nature of the system call, your program may be blocked by the OS until the system call has finished, thus making the execution time of your program even longer.
One rule-of-thumb that should always be followed when calling a system call – Always check the return value.
ENVIRONMENT ACCESS
o system_putenv(3f): call putenv(3c) o system_unsetenv(3f): call unsetenv(3c) to remove variable from environment o set_environment_variable(3f): set environment variable by calling setenv(3c)
o system_initenv(3f): initialize environment table for reading o system_readenv(3f): read next entry from environment table o system_clearenv(3f): emulate clearenv(3c) to clear environment
FILE SYSTEM
o system_chdir(3f): call chdir(3c) to change current directory of a process o system_getcwd(3f): call getcwd(3c) to get pathname of current working directory
o system_stat(3f): determine system information of file by name o system_stat_print(3f): determine system information of file by name o system_perm(3f): create string representing file permission and type o system_access(3f): determine filename access or existence o system_isdir(3f): determine if filename is a directory o system_islnk(3f): determine if filename is a link o system_isreg(3f): determine if filename is a regular file o system_isblk(3f): determine if filename is a block device o system_ischr(3f): determine if filename is a character device o system_isfifo(3f): determine if filename is a fifo - named pipe o system_issock(3f): determine if filename is a socket
o system_chmod(3f): call chmod(3c) to set file permission mode o system_chown(3f): call chown(3c) to set file owner o system_getumask(3f): call umask(3c) to get process permission mask o system_setumask(3f): call umask(3c) to set process permission mask
o system_mkdir(3f): call mkdir(3c) to create empty directory o system_mkfifo(3f): call mkfifo(3c) to create a special FIFO file o system_link(3f): call link(3c) to create a filename link
o system_rename(3f): call rename(3c) to change filename
o system_remove(3f): call remove(3c) to remove file o system_rmdir(3f): call rmdir(3c) to remove empty directory o system_unlink(3f): call unlink(3c) to remove a link to a file
o fileglob(3f): Returns list of files using a file globbing pattern
STREAM I/O
o system_getc(3f): get a character from stdin o system_putc(3f): put a character on stdout
RANDOM NUMBERS
o system_srand(3f): call srand(3c) o system_rand(3f): call rand(3c)
C ERROR INFORMATION
o system_errno(3f): return errno(3c) o system_perror(3f): call perror(3c) to display last C error message
QUERIES
o system_geteuid(3f): call geteuid(3c) o system_getuid(3f): call getuid(3c) o system_getegid(3f): call getegid(3c) o system_getgid(3f): call getgid(3c) o system_getpid(3f): call getpid(3c) o system_getppid(3f): call getppid(3c) o system_gethostname(3f): get name of current host o system_uname(3f): call my_uname(3c) which calls uname(3c) o system_getlogin(3f): get login name o system_getpwuid(3f): get login name associated with given UID o system_getgrgid(3f): get group name associated with given GID o system_cpu_time(3f) : get processor time in seconds using times(3c)
FUTURE DIRECTIONS
A good idea of what system routines are commonly required is to refer to the POSIX binding standards. (Note: IEEE 1003.9-1992 was withdrawn 6 February 2003.) The IEEE standard covering Fortran 77 POSIX bindings is available online, though currently (unfortunately) only from locations with appropriate subscriptions to the IEEE server (e.g., many university networks). For those who do have such access, the link is: POSIX Fortran 77 Language Interfaces (IEEE Std 1003.9-1992) (pdf)
SEE ALSO
Some vendors provide their own way to access POSIX functions and make those available as modules; for instance ...
o the IFPORT module of Intel o or the f90_* modules of NAG. o There also some compiler-independent efforts to make them accessible, e.g.
o Posix90 (doc), o flib.a platform/files and directories, o fortranposix.
Function/Subroutine Documentation
arr2str()
pure character(len=size(array)) function m_system::arr2str (character(len=1), dimension(:), intent(in) array) private
c2f_string()
character(len=:) function, allocatable m_system::c2f_string (type(c_ptr), intent(in) c_string_pointer) private
fileglob()
subroutine, public m_system::fileglob (character(len=*), intent(in) glob, character(len=*), dimension(:), pointer list)
NAME
fileglob(3f) - [M_system] Read output of an ls(1) command from Fortran
SYNOPSIS
subroutine fileglob(glob, list)
character(len=*),intent(in) :: glob character(len=*),pointer :: list(:)
DESCRIPTION
Non-portable procedure uses the shell and the ls(1) command to expand a filename and returns a pointer to a list of expanded filenames.
OPTIONS
glob Pattern for the filenames (like: *.txt) list Allocated list of filenames (returned), the caller must deallocate it.
EXAMPLE
Read output of an ls(1) command from Fortran
program test_fileglob ! simple unit test call testit('*.*') call testit('/tmp/__notthere.txt') end program test_fileglob
subroutine testit(string) use M_system, only : fileglob character(len=255),pointer :: list(:) character(len=*) :: string call fileglob(string, list) write(*,*)'Files:',size(list) write(*,'(a)')(trim(list(i)),i=1,size(list)) deallocate(list) end subroutine testit
References file(), m_io::notopen(), and m_io::uniq().
set_environment_variable()
subroutine, public m_system::set_environment_variable (character(len=*) NAME, character(len=*) VALUE, integer, intent(out), optional STATUS)
NAME
set_environment_variable(3f) - [M_system] call setenv(3c) to set environment variable
SYNOPSIS
subroutine set_environment_variable(NAME, VALUE, STATUS)
character(len=*) :: NAME character(len=*) :: VALUE integer, optional, intent(out) :: STATUS
DESCRIPTION
The set_environment_variable() procedure adds or changes the value of environment variables.
NAME If name does not already exist in the environment, then string is added to the environment. If name does exist, then the value of name in the environment is changed to value. VALUE Value to assign to environment variable NAME STATUS returns zero on success, or nonzero if an error occurs. A non-zero error usually indicates sufficient memory does not exist to store the variable.
EXAMPLE
Sample setting an environment variable from Fortran:
program demo_set_environment_variable use M_system, only: set_environment_variable use iso_c_binding implicit none integer :: ierr
write(*,'(a)')'no environment variables containing "GRU":' call execute_command_line('env|grep GRU')
call set_environment_variable('GRU','this is the value',ierr) write(*,'(a,i0)')'now "GRU" should be defined, status=',ierr call execute_command_line('env|grep GRU')
call set_environment_variable('GRU2','this is the second value',ierr) write(*,'(a,i0)')'now "GRU" and "GRU2" should be defined, status =',ierr call execute_command_line('env|grep GRU')
end program demo_set_environment_variable
Results:
no environment variables containing "GRU": now "GRU" should be defined, status=0 GRU=this is the value now "GRU" and "GRU2" should be defined, status =0 GRU2=this is the second value GRU=this is the value
References str2arr().
str2arr()
pure character(len=1,kind=c_char) function, dimension(len(string)+1) m_system::str2arr (character(len=*), intent(in) string) private
system_access()
logical function, public m_system::system_access (character(len=*), intent(in) pathname, integer, intent(in) amode)
NAME
system_access(3f) - [M_system] checks accessibility or existence of a pathname
SYNOPSIS
logical function system_access(pathname,amode)
character(len=*),intent(in) :: pathname integer,intent(in) :: amode
DESCRIPTION
The system_access(3f) function checks pathname existence and access
permissions.  The function checks the pathname for accessibility
according to the bit pattern contained in amode, using the real user
ID in place of the effective user ID and the real group ID in place
of the effective group ID.
The value of amode is either the bitwise-inclusive OR of the access
permissions to be checked (R_OK, W_OK, X_OK) or the existence test (F_OK).
OPTIONS
pathname a character string representing a directory pathname. Trailing spaces are ignored. amode bitwise-inclusive OR of the values R_OK, W_OK, X_OK, or F_OK.
RETURN VALUE
If not true an error occurred or the requested access is not granted
EXAMPLE
check if filename is a directory
end program demo_system_access Sample program:
program demo_system_access Use M_system, only : system_access, F_OK, R_OK, W_OK, X_OK implicit none integer :: i character(len=80),parameter :: names(*)=[ & '/usr/bin/bash ', & '/tmp/NOTTHERE ', & '/usr/local ', & '. ', & 'PROBABLY_NOT '] do i=1,size(names) write(*,*)' does ',trim(names(i)),' exist? ', system_access(names(i),F_OK) write(*,*)' is ',trim(names(i)),' readable? ', system_access(names(i),R_OK) write(*,*)' is ',trim(names(i)),' writeable? ', system_access(names(i),W_OK) write(*,*)' is ',trim(names(i)),' executable? ', system_access(names(i),X_OK) enddo end program demo_system_access
References false(), str2arr(), and true().
system_chdir()
subroutine, public m_system::system_chdir (character(len=*) path, integer, intent(out), optional err)
NAME
system_chdir(3f) - [M_system] call chdir(3c) from Fortran to change working directory
SYNOPSIS
subroutine system_chdir(path, err)
character(len=*) :: path integer, optional, intent(out) :: err
DESCRIPTION
system_chdir(3f) changes the current working directory of the calling
process to the directory specified in path. The current working
directory is the starting point for interpreting relative pathnames
(those not starting with '/').
RETURN VALUE
On success, zero is returned. On error, -1 is returned, and errno is
set appropriately.
Depending on the file system, other errors can be returned. The more
general errors for chdir() are listed below, by their C definitions:
Errors
EACCES        Search permission is denied for one of the components of path.
              (See also path_resolution(7).)
EFAULT        path points outside your accessible address space.
EIO           An I/O error occurred.
ELOOP         Too many symbolic links were encountered in resolving path.
ENAMETOOLONG  path is too long.
ENOENT        The file does not exist.
ENOMEM        Insufficient kernel memory was available.
ENOTDIR       A component of path is not a directory.
SEE ALSO
chroot(2), getcwd(3), path_resolution(7)
EXAMPLE
Change working directory from Fortran
  program demo_system_chdir
  use M_system, only : system_chdir
  implicit none
  integer :: ierr
  call execute_command_line('pwd')
  call system_chdir('/tmp',ierr)
  call execute_command_line('pwd')
  write(*,*)'*CHDIR TEST* IERR=',ierr
  end program demo_system_chdir
RESULTS:
Sample run output:
/home/urbanjs/V600 /tmp CHDIR TEST IERR= 0
References str2arr().
system_chmod()
integer function, public m_system::system_chmod (character(len=*), intent(in) filename, integer, intent(in), value mode)
NAME
system_chmod(3f) - [M_system] call chmod(3c) to change permission mode of a file relative to directory file descriptor
SYNOPSIS
function system_chmod(filename,mode) result(ierr)
character(len=*),intent(in) :: filename integer,value,intent(in) :: mode integer :: ierr
DESCRIPTION
The chmod() function shall change UID, _ISGID, S_ISVTX, and the file permission bits of the file named by the pathname pointed to by the path argument to the corresponding bits in the mode argument. The application shall ensure that the effective user ID of the process matches the owner of the file or the process has appropriate privileges in order to do this.
S_ISUID, S_ISGID, S_ISVTX, and the file permission bits are described in <sys/stat.h>.
If the calling process does not have appropriate privileges, and if the group ID of the file does not match the effective group ID or one of the supplementary group IDs and if the file is a regular file, bit S_ISGID (set-group-ID on execution) in the file's mode shall be cleared upon successful return from chmod().
Additional implementation-defined restrictions may cause the S_ISUID and S_ISGID bits in mode to be ignored.
Upon successful completion, system_chmod() marks for update the last file status change timestamp of the file.
Values for flag are constructed by a bitwise-inclusive OR of flags from the following list, defined in <fcntl.h>:
AT_SYMLINK_NOFOLLOW If path names a symbolic link, then the mode of the symbolic link is changed.
RETURN VALUE
Upon successful completion, system_chmod(3f) returns 0. Otherwise, it returns -1 and sets errno to indicate the error. If -1 is returned, no change to the file mode occurs.
EXAMPLES
Sample program:
program demo_system_chmod use M_system, only : system_chmod use M_system, only : R_GRP,R_OTH,R_USR,R_WXG,R_WXO use M_system, only : R_WXU,W_GRP,W_OTH,W_USR,X_GRP,X_OTH,X_USR use M_system, only : DEFFILEMODE, ACCESSPERMS implicit none integer :: ierr integer :: status !Setting Read Permissions for User, Group, and Others ! The following example sets read permissions for the owner, group, and others. open(file='_test1',unit=10) write(10,*)'TEST FILE 1' close(unit=10) ierr=system_chmod('_test1', IANY(R_USR,R_GRP,R_OTH))
!Setting Read, Write, and Execute Permissions for the Owner Only ! The following example sets read, write, and execute permissions for the owner, and no permissions for group and others. open(file='_test2',unit=10) write(10,*)'TEST FILE 2' close(unit=10) ierr=system_chmod('_test2', R_WXU)
!Setting Different Permissions for Owner, Group, and Other ! The following example sets owner permissions for CHANGEFILE to read, write, and execute, group permissions to read and ! execute, and other permissions to read. open(file='_test3',unit=10) write(10,*)'TEST FILE 3' close(unit=10) ierr=system_chmod('_test3', IANY([R_WXU,R_GRP,X_GRP,R_OTH]));
!Setting and Checking File Permissions ! The following example sets the file permission bits for a file named /home/cnd/mod1, then calls the stat() function to ! verify the permissions.
ierr=system_chmod("home/cnd/mod1", IANY([R_WXU,R_WXG,R_OTH,W_OTH])) status = system_stat("home/cnd/mod1", buffer)
! In order to ensure that the S_ISUID and S_ISGID bits are set, an application requiring this should use stat() after a ! successful chmod() to verify this.
! Any files currently open could possibly become invalid if the mode ! of the file is changed to a value which would deny access to ! that process.
end program demo_system_chmod
References str2arr().
system_chown()
logical function, public m_system::system_chown (character(len=*), intent(in) dirname, integer, intent(in) owner, integer, intent(in) group)
NAME
system_chown(3f) - [M_system] change file owner and group
SYNOPSIS
logical function system_chown(path,owner,group)
character(len=*),intent(in) :: path integer,intent(in) :: owner integer,intent(in) :: group
DESCRIPTION
The chown(3f) function changes owner and group of a file
The path argument points to a pathname naming a file. The user ID and group ID of the named file shall be set to the numeric values contained in owner and group, respectively.
Only processes with an effective user ID equal to the user ID of the file or with appropriate privileges may change the ownership of a file.
OPTIONS
path a character string representing a file pathname. Trailing spaces are ignored. owner UID of owner that ownership is to be changed to group GID of group that ownership is to be changed to
RETURN VALUE
The system_chown() function should return zero (0) if successful. Otherwise, these functions shall return 1 and set errno to indicate the error. If 1 is returned, no changes are made in the user ID and group ID of the file.
EXAMPLE
    Sample program:
       program demo_system_chown
       Use M_sytem, only : system_chown
       implicit none
       integer                     :: i
       character(len=80),parameter :: names(*)=[ 'myfile1','/usr/local']
       do i=1,size(names)
          ierr=chown(names(i))
          write(*,*)' for ',trim(names(i)),' ownership is ', chown(names(i))
       enddo
       end program demo_system_chown
    Results:
References false(), str2arr(), and true().
system_clearenv()
subroutine, public m_system::system_clearenv (integer, intent(out), optional ierr)
NAME
system_clearenv(3f) - [M_system] clear environment by calling clearenv(3c)
SYNOPSIS
subroutine system_clearenv(ierr)
 integer,intent(out),optional :: ierr
DESCRIPTION
The clearenv() procedure clears the environment of all name-value pairs. Typically used in security-conscious applications or ones where configuration control requires ensuring specific variables are set.
RETURN VALUES
ierr returns zero on success, and a nonzero value on failure. Optional. If not present and an error occurs the program stops.
EXAMPLE
Sample program:
program demo_system_clearenv use M_system, only : system_clearenv implicit none ! environment before clearing call execute_command_line('env|wc') ! environment after clearing (not necessarily blank!!) call system_clearenv() call execute_command_line('env') end program demo_system_clearenv
Typical output:
89 153 7427 PWD=/home/urbanjs/V600 SHLVL=1
References system_readenv(), and system_unsetenv().
system_closedir()
subroutine, public m_system::system_closedir (type(c_ptr), value dir, integer, intent(out), optional ierr)
NAME
system_closedir(3f) - [M_system] close a directory stream by calling closedir(3c)
SYNOPSIS
subroutine system_closedir(dir,ierr)
type(c_ptr) :: dir integer,intent(out) :: ierr
DESCRIPTION
The SYSTEM_CLOSEDIR(3f) function closes the directory stream referred to by the argument DIR. Upon return, the value of DIR may no longer point to an accessible object.
OPTIONS
dir directory stream pointer opened by SYSTEM_OPENDIR(3f). ierr Upon successful completion, SYSTEM_CLOSEDIR(3f) returns 0; otherwise, an error has occurred.
ERRORS
system_closedir(3f) may fail if:
EBADF The dirp argument does not refer to an open directory stream. EINTR The closedir() function was interrupted by a signal.
EXAMPLE
Sample program
program demo_system_closedir use M_system, only : system_opendir,system_readdir use M_system, only : system_closedir, system_rewinddir use iso_c_binding, only : c_ptr implicit none type(c_ptr) :: dir character(len=:),allocatable :: filename integer :: ierr !— open directory stream to read from call system_opendir('.',dir,ierr) !— read directory stream do call system_readdir(dir,filename,ierr) if(filename.eq.' ')exit write(*,*)filename enddo call system_rewinddir(dir) !— close directory stream call system_closedir(dir,ierr) end program demo_system_closedir
system_cpu_time()
subroutine, public m_system::system_cpu_time (real, intent(out) total, real, intent(out) user, real, intent(out) system)
NAME
system_cpu_time(3f) - [M_system] get processor time by calling times(3c)
SYNOPSIS
    subroutine system_cpu_time(c_user, c_system, c_total)
     real,intent(out) :: c_total
     real,intent(out) :: c_user
     real,intent(out) :: c_system
DESCRIPTION
OUTPUT
c_total total processor time (c_user + c_system) c_user processor user time c_system processor system time
ERRORS
No errors are defined.
EXAMPLES
Sample program:
   program demo_system_cpu_time
   use M_system, only : system_cpu_time
   use ISO_C_BINDING, only : c_float
   implicit none
   real    :: user_start, system_start, total_start
   real    :: user_finish, system_finish, total_finish
   integer :: i
   real    :: value
      call system_cpu_time(total_start,user_start,system_start)
      value=0.0
      do i=1,1000000
         value=sqrt(real(i)+value)
         write(10,*)value
      enddo
      flush(10)
      write(*,*)'average sqrt value=',value/10000.0
      call system_cpu_time(totl_finish,user_finish,system_finish)
      write(*,*)'USER ......',user_finish-user_start
      write(*,*)'SYSTEM ....',system_finish-system_start
      write(*,*)'TOTAL .....',total_finish-total_start
   end program demo_system_cpu_time
Typical Results:
system_getcwd()
subroutine, public m_system::system_getcwd (character(len=:), intent(out), allocatable output, integer, intent(out) ierr)
NAME
system_getcwd(3f) - [M_system] call getcwd(3c) to get the pathname of the current working directory
SYNOPSIS
subroutine system_getcwd(output,ierr)
character(len=:),allocatable,intent(out) :: output integer,intent(out) :: ierr
DESCRIPTION
system_getcwd(3f) calls the C routine getcwd(3c) to obtain the absolute pathname of the current working directory.
RETURN VALUE
FILENAME The absolute pathname of the current working directory The pathname shall contain no components that are dot or dot-dot, or are symbolic links. IERR is not zero if an error occurs.
EXAMPLE
Sample program:
program demo_system_getcwd use M_system, only : system_getcwd implicit none character(len=:),allocatable :: dirname integer :: ierr call system_getcwd(dirname,ierr) if(ierr.eq.0)then write(*,*)'CURRENT DIRECTORY ',trim(dirname) else write(*,*)'ERROR OBTAINING CURRENT DIRECTORY NAME' endif end program demo_system_getcwd
References arr2str().
system_getgrgid()
character(len=:) function, allocatable, public m_system::system_getgrgid (class(*), intent(in) gid)
NAME
system_getgrgid(3f) - [M_system] get groupd name associated with a GID
SYNOPSIS
function system_getgrgid(gid) result (gname)
class(*),intent(in) :: gid ! any INTEGER type character(len=:),allocatable :: gname
DESCRIPTION
The system_getlogin() function returns a string containing the group
name associated with the given GID. If no match is found
it returns a null string and sets errno to indicate the error.
OPTION
gid GID to try to look up associated group for. Can be of any INTEGER type.
RETURN VALUE
gname returns the group name. Blank if an error occurs
EXAMPLE
Sample program:
program demo_system_getgrgid use M_system, only : system_getgrgid use M_system, only: system_getgid implicit none character(len=:),allocatable :: name name=system_getgrgid(system_getgid()) write(*,'("group[",a,"] for ",i0)')name,system_getgid() end program demo_system_getgrgid
Results:
group[default] for 197121
References m_anyscalar::anyinteger_to_128bit(), and arr2str().
system_gethostname()
subroutine, public m_system::system_gethostname (character(len=:), intent(out), allocatable NAME, integer, intent(out) IERR)
NAME
system_gethostname(3f) - [M_system] get name of current host
SYNOPSIS
subroutine system_gethostname(string,ierr)
character(len=:),allocatable,intent(out) :: NAME integer,intent(out) :: IERR
DESCRIPTION
The system_gethostname(3f) procedure returns the standard host name for the current machine.
OPTIONS
string returns the hostname. Must be an allocatable CHARACTER variable. ierr Upon successful completion, 0 shall be returned; otherwise, -1 shall be returned.
EXAMPLE
Sample program:
program demo_system_gethostname
use M_system, only : system_gethostname implicit none character(len=:),allocatable :: name integer :: ierr
call system_gethostname(name,ierr) if(ierr.eq.0)then write(*,'("hostname[",a,"]")')name else write(*,'(a)')'ERROR: could not get hostname' endif
end program demo_system_gethostname
References arr2str(), and host_name_max.
system_getlogin()
character(len=:) function, allocatable, public m_system::system_getlogin ()
NAME
system_getlogin(3f) - [M_system] get login name
SYNOPSIS
function system_getlogin() result (fname)
character(len=:),allocatable :: FNAME
DESCRIPTION
The system_getlogin() function returns a string containing the user
name associated by the login activity with the controlling terminal
of the current process.  Otherwise, it returns a null string and sets
errno to indicate the error.
Three names associated with the current process can be determined:
   o system_getpwuid(system_getuid()) returns the name associated with the real user ID of the process.
   o system_getpwuid(system_geteuid()) returns the  name  associated with  the  effective user ID of the process
   o system_getlogin() returns the name associated with the current login activity
RETURN VALUE
fname returns the login name.
EXAMPLE
Sample program:
program demo_system_getlogin use M_system, only : system_getlogin implicit none character(len=:),allocatable :: name name=system_getlogin() write(*,'("login[",a,"]")')name end program demo_system_getlogin
Results:
login[JSU]
References c2f_string().
system_getpwuid()
character(len=:) function, allocatable, public m_system::system_getpwuid (class(*), intent(in) uid)
NAME
system_getpwuid(3f) - [M_system] get login name associated with a UID
SYNOPSIS
function system_getpwuid(uid) result (uname)
class(*),intent(in) :: id ! any INTEGER type character(len=:),allocatable :: uname
DESCRIPTION
The system_getlogin() function returns a string containing the user
name associated with the given UID. If no match is found
it returns a null string and sets errno to indicate the error.
OPTION
uid UID to try to look up associated username for. Can be of any INTEGER type.
RETURN VALUE
uname returns the login name.
EXAMPLE
Sample program:
program demo_system_getpwuid use M_system, only : system_pwuid use M_system, only: system_getuid implicit none character(len=:),allocatable :: name name=system_getpwuid(system_getuid)) write(*,'("login[",a,"] for ",i0)')name,uid end program demo_system_getpwuid
References m_anyscalar::anyinteger_to_128bit(), and arr2str().
system_getumask()
integer function, public m_system::system_getumask ()
NAME
system_getumask(3f) - [M_system] get current umask
SYNOPSIS
integer function system_getumask() result (umask_value)
DESCRIPTION
The return value from getumask(3f) is the value of the file creation mask, obtained by using umask(3c).
EXAMPLE
Sample program
program demo_getumask use M_system, only : system_getumask, system_setumask integer :: newmask write(*,101)(system_getumask(),i=1,4) 101 format(1x,i0,1x,"O'",o4.4,"'",1x,'Z"',z0,"'",1x,"B'",b12.12,"'") end program demo_getumask
Expected output
18 O'022' Z"12' B'000010010"
system_isblk()
logical function, public m_system::system_isblk (character(len=*), intent(in) pathname)
NAME
system_isblk(3f) - [M_system] checks if argument is a block device
SYNOPSIS
logical function system_isblk()
DESCRIPTION
The isblk(3f) function checks if path is a path to a block device.
OPTIONS
path a character string representing a block device pathname. Trailing spaces are ignored.
RETURN VALUE
The system_isblk() function should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
system_isreg(3f), system_stat(3f), system_isdir(3f), system_perm(3f)
EXAMPLE
check if filename is a directory
end program demo_system_isblk Sample program:
program demo_system_isblk Use M_sytem, only : system_isblk implicit none integer :: i character(len=80),parameter :: names(*)=[ & '/tmp ', & '/tmp/NOTTHERE ', & '/usr/local ', & '. ', & 'block_device.tst', & 'PROBABLY_NOT '] do i=1,size(names) write(*,*)' is ',trim(names(i)),' a block device? ', isblk(names(i)) enddo end program demo_system_isblk
Results:
References false(), str2arr(), and true().
system_ischr()
logical function, public m_system::system_ischr (character(len=*), intent(in) pathname)
NAME
system_ischr(3f) - [M_system] checks if argument is a character device
SYNOPSIS
logical function system_ischr()
DESCRIPTION
The ischr(3f) function checks if path is a path to a character device.
OPTIONS
path a character string representing a character device pathname. Trailing spaces are ignored.
RETURN VALUE
The system_ischr() function should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
system_isreg(3f), system_stat(3f), system_isdir(3f), system_perm(3f)
EXAMPLE
check if filename is a directory
end program demo_system_ischr Sample program:
program demo_system_ischr Use M_sytem, only : system_ischr implicit none integer :: i character(len=80),parameter :: names(*)=[ & '/tmp ', & '/tmp/NOTTHERE ', & '/usr/local ', & '. ', & 'char_dev.test ', & 'PROBABLY_NOT '] do i=1,size(names) write(*,*)' is ',trim(names(i)),' a character device? ', ischr(names(i)) enddo end program demo_system_ischr
Results:
References false(), str2arr(), and true().
system_isdir()
logical function, public m_system::system_isdir (character(len=*), intent(in) dirname)
NAME
system_isdir(3f) - [M_system] checks if argument is a directory path
SYNOPSIS
logical function system_isdir()
DESCRIPTION
The isdir(3f) function checks if path is a path to a directory.
OPTIONS
path a character string representing a directory pathname. Trailing spaces are ignored.
RETURN VALUE
The system_isdir() function should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
system_islnk(3f), system_stat(3f), isreg(3f), system_perm(3f)
EXAMPLE
check if filename is a directory
end program demo_system_isdir Sample program:
program demo_system_isdir Use M_sytem, only : system_isdir implicit none integer :: i character(len=80),parameter :: names(*)=[ & '/tmp ', & '/tmp/NOTTHERE ', & '/usr/local ', & '. ', & 'PROBABLY_NOT '] do i=1,size(names) write(*,*)' is ',trim(names(i)),' a directory? ', isdir(names(i)) enddo end program demo_system_isdir
Results:
is /tmp a directory? T is /tmp/NOTTHERE a directory? F is /usr/local a directory? T is . a directory? T is PROBABLY_NOT a directory? F
References false(), str2arr(), and true().
system_isfifo()
logical function, public m_system::system_isfifo (character(len=*), intent(in) pathname)
NAME
system_isfifo(3f) - [M_system] checks if argument is a fifo - named pipe
SYNOPSIS
logical function system_isfifo()
DESCRIPTION
The isfifo(3f) function checks if path is a path to a fifo - named pipe.
OPTIONS
path a character string representing a fifo - named pipe pathname. Trailing spaces are ignored.
RETURN VALUE
The system_isfifo() function should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
system_isreg(3f), system_stat(3f), system_isdir(3f), system_perm(3f)
EXAMPLE
check if filename is a directory
end program demo_system_isfifo Sample program:
program demo_system_isfifo Use M_sytem, only : system_isfifo implicit none integer :: i character(len=80),parameter :: names(*)=[ & '/tmp ', & '/tmp/NOTTHERE ', & '/usr/local ', & '. ', & 'fifo.test '] 'PROBABLY_NOT '] do i=1,size(names) write(*,*)' is ',trim(names(i)),' a fifo(named pipe)? ', isfifo(names(i)) enddo end program demo_system_isfifo
Results:
References false(), str2arr(), and true().
system_islnk()
logical function, public m_system::system_islnk (character(len=*), intent(in) pathname)
NAME
system_islnk(3f) - [M_system] checks if argument is a link
SYNOPSIS
logical function system_islnk()
DESCRIPTION
The islnk(3f) function checks if path is a path to a link.
OPTIONS
path a character string representing a link pathname. Trailing spaces are ignored.
RETURN VALUE
The system_islnk() function should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
system_isreg(3f), system_stat(3f), system_isdir(3f), system_perm(3f)
EXAMPLE
    Sample program:
       program demo_system_islnk
       Use M_sytem, only : system_islnk
       implicit none
       integer                     :: i
       character(len=80),parameter :: names(*)=[ &
       '/tmp            ', &
       '/tmp/NOTTHERE   ', &
       '/usr/local      ', &
       '.               ', &
       'link.test       ']
       'PROBABLY_NOT    ']
       do i=1,size(names)
          write(*,*)' is ',trim(names(i)),' a link? ', islnk(names(i))
       enddo
       end program demo_system_islnk
    Results:
References false(), str2arr(), and true().
system_isreg()
logical function, public m_system::system_isreg (character(len=*), intent(in) pathname)
NAME
system_isreg(3f) - [M_system] checks if argument is a regular file
SYNOPSIS
logical function system_isreg()
DESCRIPTION
The isreg(3f) function checks if path is a regular file
OPTIONS
path a character string representing a pathname. Trailing spaces are ignored.
RETURN VALUE
The system_isreg() function should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
system_islnk(3f), system_stat(3f), system_isdir(3f), system_perm(3f)
EXAMPLE
check if filename is a regular file
end program demo_system_isreg Sample program:
program demo_system_isreg Use M_sytem, only : system_isreg implicit none integer :: i character(len=80),parameter :: names(*)=[ & '/tmp ', & 'test.txt ', & '. '] do i=1,size(names) write(*,*)' is ',trim(names(i)),' a regular file? ', isreg(names(i)) enddo end program demo_system_isreg
Results:
References false(), str2arr(), and true().
system_issock()
logical function, public m_system::system_issock (character(len=*), intent(in) pathname)
NAME
system_issock(3f) - [M_system] checks if argument is a socket
SYNOPSIS
logical function system_issock()
DESCRIPTION
The issock(3f) function checks if path is a path to a socket
OPTIONS
path a character string representing a socket pathname. Trailing spaces are ignored.
RETURN VALUE
The system_issock() function should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
system_isreg(3f), system_stat(3f), system_isdir(3f), system_perm(3f)
EXAMPLE
check if filename is a directory
end program demo_system_issock Sample program:
program demo_system_issock Use M_sytem, only : system_issock implicit none integer :: i character(len=80),parameter :: names(*)=[ & '/tmp ', & '/tmp/NOTTHERE ', & '/usr/local ', & '. ', & 'sock.test '] 'PROBABLY_NOT '] do i=1,size(names) write(*,*)' is ',trim(names(i)),' a socket? ', issock(names(i)) enddo end program demo_system_issock
Results:
References false(), str2arr(), and true().
system_link()
integer function, public m_system::system_link (character(len=*), intent(in) oldname, character(len=*), intent(in) newname)
NAME
system_link(3f) - [M_system] link one file to another file relative to two directory file descriptors
SYNOPSIS
integer function link(oldpath,newpath);
 character(len=*),intent(in) :: oldpath
 character(len=*),intent(in) :: newpath
DESCRIPTION
The link() function shall create a new link (directory entry) for the existing file, path1.
The path1 argument points to a pathname naming an existing file. The path2 argument points to a pathname naming the new directory entry to be created. The link() function shall atomically create a new link for the existing file and the link count of the file shall be incremented by one.
If path1 names a directory, link() shall fail unless the process has appropriate privileges and the implementation supports using link() on directories.
If path1 names a symbolic link, it is implementation-defined whether link() follows the symbolic link, or creates a new link to the symbolic link itself.
Upon successful completion, link() shall mark for update the last file status change timestamp of the file. Also, the last data modification and last file status change timestamps of the directory that contains the new entry shall be marked for update.
If link() fails, no link shall be created and the link count of the file shall remain unchanged.
The implementation may require that the calling process has permission to access the existing file.
The linkat() function shall be equivalent to the link() function except that symbolic links shall be handled as specified by the value of flag (see below) and except in the case where either path1 or path2 or both are relative paths. In this case a relative path path1 is interpreted relative to the directory associated with the file descriptor fd1 instead of the current working directory and similarly for path2 and the file descriptor fd2. If the file descriptor was opened without O_SEARCH, the function shall check whether directory searches are permitted using the current permissions of the directory underlying the file descriptor. If the file descriptor was opened with O_SEARCH, the function shall not perform the check.
Values for flag are constructed by a bitwise-inclusive OR of flags from the following list, defined in <fcntl.h>:
AT_SYMLINK_FOLLOW If path1 names a symbolic link, a new link for the target of the symbolic link is created.
If linkat() is passed the special value AT_FDCWD in the fd1 or fd2 parameter, the current working directory shall be used for the respective path argument. If both fd1 and fd2 have value AT_FDCWD, the behavior shall be identical to a call to link(), except that symbolic links shall be handled as specified by the value of flag.
Some implementations do allow links between file systems.
If path1 refers to a symbolic link, application developers should use linkat() with appropriate flags to select whether or not the symbolic link should be resolved.
If the AT_SYMLINK_FOLLOW flag is clear in the flag argument and the path1 argument names a symbolic link, a new link is created for the symbolic link path1 and not its target.
RETURN VALUE
Upon successful completion, these functions shall return 0. Otherwise, these functions shall return -1 and set errno to indicate the error.
EXAMPLES
Creating a Link to a File
program demo_system_link use M_system, only : system_link, system_perror ierr = system_link('myfile1','myfile2') if(ierr.ne.0)then call system_perror('demo_system_link') endif end program demo_system_link
References str2arr().
system_mkdir()
integer function, public m_system::system_mkdir (character(len=*), intent(in) dirname, integer, intent(in) mode)
NAME
system_mkdir(3f) - [M_system] call mkdir(3c) to create a new directory
SYNOPSIS
DESCRIPTION
Predefined variables are typically used to set permission modes.
You can bytewise-OR together these variables to to create the most common
permissions mode:
 User:    R_USR  (read),  W_USR  (write),  X_USR(execute)
 Group:   R_GRP  (read),  W_GRP  (write),  X_GRP(execute)
 Others:  R_OTH  (read),  W_OTH  (write),  X_OTH(execute)
Additionally, some shortcuts are provided (basically a bitwise-OR combination of the above):
  Read + Write + Execute: R_WXU (User), R_WXG (Group), R_WXO (Others)
  DEFFILEMODE: Equivalent of 0666 =rw-rw-rw-
  ACCESSPERMS: Equivalent of 0777 = rwxrwxrwx
Therefore, to give only the user rwx (read+write+execute) rights whereas
group members and others may not do anything, you can use any of the
following mkdir() calls equivalently:
  ierr= mkdir("mydir", IANY(R_USR, W_USR, X_USR));
  ierr= mkdir("mydir", R_WXU);
In order to give anyone any rights (mode 0777 = rwxrwxrwx), you can
use any of the following calls equivalently:
  ierr= mkdir("mydir",IANY(R_USR,W_USR,X_USR,R_GRP,W_GRP,X_GRP,R_OTH,W_OTH,X_OTH));
  ierr= mkdir("mydir",IANY(R_WXU,R_WXG,R_WXO));
  ierr= mkdir("mydir",ACCESSPERMS);
EXAMPLE
Sample program:
program demo_system_mkdir use M_system, only : system_perror use M_system, only : system_mkdir use M_system, only : R_GRP,R_OTH,R_USR,R_WXG,R_WXO use M_system, only : R_WXU,W_GRP,W_OTH,W_USR,X_GRP,X_OTH,X_USR use M_system, only : DEFFILEMODE, ACCESSPERMS implicit none integer :: ierr ierr=system_mkdir('_scratch',IANY(R_USR,W_USER,X_USR)) end program demo_system_mkdir
References str2arr().
system_mkfifo()
integer function, public m_system::system_mkfifo (character(len=*), intent(in) dirname, integer, intent(in) mode)
NAME
system_mkfifo(3f) - [M_system] make a FIFO special file relative to directory file descriptor
SYNOPSIS
DESCRIPTION
The mkfifo() function creates a new FIFO special file named by the pathname pointed to by path.
The file permission bits of the new FIFO are initialized from mode.
The file permission bits of the mode argument are modified by the process' file creation mask.
When bits in mode other than the file permission bits are set, the effect is implementation-defined.
If path names a symbolic link, mkfifo() shall fail and set errno to [EEXIST].
The FIFO's user ID will be set to the process' effective user ID.
The FIFO's group ID shall be set to the group ID of the parent directory or to the effective group ID of the process.
Implementations shall provide a way to initialize the FIFO's group ID to the group ID of the parent directory.
Implementations may, but need not, provide an implementation-defined way to initialize the FIFO's group ID to the effective group ID of the calling process.
Upon successful completion, mkfifo() shall mark for update the last data access, last data modification, and last file status change timestamps of the file.
Also, the last data modification and last file status change timestamps of the directory that contains the new entry shall be marked for update.
Predefined variables are typically used to set permission modes.
You can bytewise-OR together these variables to to create the most common permissions mode:
User: R_USR (read), W_USR (write), X_USR(execute) Group: R_GRP (read), W_GRP (write), X_GRP(execute) Others: R_OTH (read), W_OTH (write), X_OTH(execute)
Additionally, some shortcuts are provided (basically a bitwise-OR combination of the above):
Read + Write + Execute: R_WXU (User), R_WXG (Group), R_WXO (Others) DEFFILEMODE: Equivalent of 0666 =rw-rw-rw- ACCESSPERMS: Equivalent of 0777 = rwxrwxrwx
Therefore, to give only the user rwx (read+write+execute) rights whereas group members and others may not do anything, you can use any of the following mkfifo() calls equivalently:
ierr= mkfifo("myfile", IANY(R_USR, W_USR, X_USR)); ierr= mkfifo("myfile", R_WXU);
In order to give anyone any rights (mode 0777 = rwxrwxrwx), you can use any of the following calls equivalently:
ierr= mkfifo("myfile",IANY(R_USR,W_USR,X_USR,R_GRP,W_GRP,X_GRP,R_OTH,W_OTH,X_OTH)); ierr= mkfifo("myfile",IANY(R_WXU,R_WXG,R_WXO)); ierr= mkfifo("myfile",ACCESSPERMS);
RETURN VALUE
Upon successful completion, these functions shall return 0. Otherwise, these functions return -1 and set errno to indicate the error. If -1 is returned, no FIFO is created.
EXAMPLES
The following example shows how to create a FIFO file named /home/cnd/mod_done, with read/write permissions for owner, and with read permissions for group and others.
program demo_system_mkfifo use M_system, only : system_mkfifo, system_perror use M_system, only : R_GRP,R_OTH,R_USR,R_WXG,R_WXO use M_system, only : R_WXU,W_GRP,W_OTH,W_USR,X_GRP,X_OTH,X_USR use M_system, only : DEFFILEMODE, ACCESSPERMS implicit none integer :: status status = system_mkfifo("/home/cnd/mod_done", IANY([W_USR, R_USR, R_GRP, R_OTH])) if(status.ne.0)then call system_perror('mkfifo error:') endif end program demo_system_mkfifo
EXAMPLE
integer :: ierr
ierr=system_mkfifo('_scratch',IANY(R_USR,W_USER,X_USR))
end program demo_system_mkfifo
References str2arr().
system_opendir()
subroutine, public m_system::system_opendir (character(len=*), intent(in) dirname, type(c_ptr) dir, integer, intent(out) ierr)
NAME
system_opendir(3f) - [M_system] open directory stream by calling opendir(3c)
SYNOPSIS
subroutine system_opendir(dirname,dir,ierr)
character(len=*), intent(in) :: dirname type(c_ptr) :: dir integer,intent(out) :: ierr
DESCRIPTION
The system_opendir(3f) procedure opens a directory stream corresponding to the directory named by the dirname argument. The directory stream is positioned at the first entry.
RETURN VALUE
Upon successful completion, a pointer to a C dir type is returned. Otherwise, these functions shall return a null pointer and set IERR to indicate the error.
ERRORS
    An error corresponds to a condition described in opendir(3c):
    EACCES    Search permission is denied for the component of the
              path prefix of dirname or read permission is denied
              for dirname.
    ELOOP     A loop exists in symbolic links encountered during
              resolution of the dirname argument.
    ENAMETOOLONG  The length of a component of a pathname is longer than {NAME_MAX}.
    ENOENT        A component of dirname does not name an existing directory or dirname is an empty string.
    ENOTDIR       A component of dirname names an existing file that is neither a directory nor a symbolic link to a directory.
    ELOOP         More than {SYMLOOP_MAX} symbolic links were encountered during resolution of the dirname argument.
    EMFILE        All file descriptors available to the process are currently open.
    ENAMETOOLONG  The length of a pathname exceeds {PATH_MAX},
                  or pathname resolution of a symbolic link produced an intermediate
                  result with a length that exceeds {PATH_MAX}.
    ENFILE        Too many files are currently open in the system.
APPLICATION USAGE
The opendir() function should be used in conjunction with readdir(), closedir(), and rewinddir() to examine the contents of the directory (see the EXAMPLES section in readdir()). This method is recommended for portability.
OPTIONS
dirname name of directory to open a directory stream for
RETURNS
dir pointer to directory stream. If an error occurred, it will not be associated. ierr 0 indicates no error occurred
EXAMPLE
Sample program:
program demo_system_opendir use M_system, only : system_opendir,system_readdir use M_system, only : system_closedir use iso_c_binding implicit none type(c_ptr) :: dir character(len=:),allocatable :: filename integer :: ierr !— open directory stream to read from call system_opendir('.',dir,ierr) !— read directory stream do call system_readdir(dir,filename,ierr) if(filename.eq.' ')exit write(*,*)filename enddo !— close directory stream call system_closedir(dir,ierr) end program demo_system_opendir
References str2arr().
system_perm()
character(len=:) function, allocatable, public m_system::system_perm (class(*), intent(in) mode)
NAME
system_perm(3f) - [M_system] get file type and permission as a string
SYNOPSIS
function system_perm(mode) result (perms)
integer(kind=8),intent(in) :: MODE character(len=:),allocatable :: PERMS
DESCRIPTION
The system_perm(3f) function returns a string containing the type
and permission of a file implied by the value of the mode value.
RETURN VALUE
PERMS returns the permission string in a format similar to that used by Unix commands such as ls(1).
EXAMPLE
Sample program:
program demo_system_perm use M_system, only : system_perm, system_stat implicit none character(len=4096) :: string integer(kind=8) :: values(13) integer :: ierr character(len=:),allocatable :: perms values=0 call get_command_argument(1, string) ! get pathname from command line call system_stat(string,values,ier) ! get pathname information if(ierr.eq.0)then perms=system_perm(values(3)) ! convert permit mode to a string ! print permits as a string, decimal value, and octal value write(*,'("for ",a," permits[",a,"]",1x,i0,1x,o0)') & trim(string),perms,values(3),values(3) endif end program demo_system_perm
Results:
demo_system_perm /tmp
for /tmp permits[drwxrwxrwx –S] 17407 41777
References m_anyscalar::anyinteger_to_128bit(), and c2f_string().
system_perror()
subroutine, public m_system::system_perror (character(len=*), intent(in) prefix)
NAME
perror(3f) - [M_system] print error message for last C error on stderr
SYNOPSIS
subroutine system_perror(prefix)
character(len=*),intent(in) :: prefix
DESCRIPTION
Use system_perror(3f) to print an error message on stderr corresponding to the current value of the C global variable errno. Unless you use NULL as the argument prefix, the error message will begin with the prefix string, followed by a colon and a space (:). The remainder of the error message produced is one of the strings described for strerror(3c).
EXAMPLE
Sample program:
program demo_system_perror use M_system, only : system_perror,system_rmdir ! generate an error with a routine that supports errno and perror(3c) ierr=system_rmdir('/NOT/THERE/OR/ANYWHERE') call system_perror('demo_system_perror') end program demo_system_perror
Expected results:
demo_system_perror: No such file or directory
References str2arr(), and unit().
system_putenv()
subroutine, public m_system::system_putenv (character(len=*), intent(in) string, integer, intent(out), optional err)
NAME
system_putenv(3f) - [M_system] set environment variable from Fortran by calling putenv(3c)
SYNOPSIS
subroutine system_putenv(string, err)
 character(len=*),intent(in)    :: string
 integer, optional, intent(out) :: err
DESCRIPTION
The system_putenv() function adds or changes the value of environment variables.
OPTIONS
string string of format "NAME=value". If name does not already exist in the environment, then string is added to the environment. If name does exist, then the value of name in the environment is changed to value. The string passed to putenv(3c) becomes part of the environment, so this routine creates a string each time it is called that increases the amount of memory the program uses. err The system_putenv() function returns zero on success, or nonzero if an error occurs. A non-zero error usually indicates sufficient memory does not exist to store the variable.
EXAMPLE
Sample setting an environment variable from Fortran:
program demo_system_putenv use M_system, only: system_putenv use iso_c_binding implicit none integer :: ierr
write(*,'(a)')'no environment variables containing "GRU":' call execute_command_line('env|grep GRU')
call system_putenv('GRU=this is the value',ierr) write(*,'(a,i0)')'now "GRU" should be defined: ',ierr call execute_command_line('env|grep GRU')
call system_putenv('GRU2=this is the second value',ierr) write(*,'(a,i0)')'now "GRU" and "GRU2" should be defined: ',ierr call execute_command_line('env|grep GRU')
call system_putenv('GRU2',ierr) call system_putenv('GRU',ierr) write(*,'(a,i0)')'should be gone, varies with different putenv(3c): ',ierr call execute_command_line('env|grep GRU') write(*,'(a)')'system_unsetenv(3f) is a better way to remove variables'
end program demo_system_putenv
Results:
no environment variables containing "GRU": now "GRU" should be defined: 0 GRU=this is the value now "GRU" and "GRU2" should be defined: 0 GRU2=this is the second value GRU=this is the value should be gone, varies with different putenv(3c): 0 system_unsetenv(3f) is a better way to remove variables
system_readdir()
subroutine, public m_system::system_readdir (type(c_ptr), value dir, character(len=:), intent(out), allocatable filename, integer, intent(out) ierr)
NAME
system_readdir(3f) - [M_system] read a directory using readdir(3c)
SYNOPSIS
subroutine system_readdir(dir,filename,ierr)
type(c_ptr),value :: dir character(len=:),intent(out),allocatable :: filename integer,intent(out) :: ierr
DESCRIPTION
system_readdir(3f) returns the name of the directory entry at the current position in the directory stream specified by the argument DIR, and positions the directory stream at the next entry. It returns a null name upon reaching the end of the directory stream.
The readdir() function does not return directory entries containing empty names. If entries for dot or dot-dot exist, one entry is returned for dot and one entry is returned for dot-dot.
The entry is marked for update of the last data access timestamp each time it is read.
If IERR is set to non-zero on return, an error occurred.
least {NAME_MAX}+1 elements.
reaching the end of the directory stream, the name is a blank name.
EXAMPLE
Sample program:
program demo_system_readdir use M_system, only : system_opendir,system_readdir use M_system, only : system_rewinddir,system_closedir use iso_c_binding implicit none
type(c_ptr) :: dir character(len=:),allocatable :: filename integer :: i, ierr !— open directory stream to read from call system_opendir('.',dir,ierr) !— read directory stream twice do i=1,2 write(*,'(a,i0)')'PASS ',i do call system_readdir(dir,filename,ierr) if(filename.eq.' ')exit write(*,*)filename enddo call system_rewinddir(dir) enddo !— close directory stream call system_closedir(dir,ierr)
end program demo_system_readdir
References arr2str().
system_readenv()
character(len=:) function, allocatable, public m_system::system_readenv ()
NAME
system_readenv(3f) - [M_system] step thru and read environment table
SYNOPSIS
function system_readenv() result(string)
character(len=:),allocatable :: string
DESCRIPTION
A simple interface allows reading the environment variable table of the process. Call system_initenv(3f) to initialize reading the environment table, then call system_readenv(3f) can be called until a blank line is returned. If more than one thread reads the environment or the environment is changed while being read the results are undefined.
OPTIONS
string the string returned from the environment of the form "NAME=VALUE"
EXAMPLE
Sample program:
program demo_system_readenv use M_system, only : system_initenv, system_readenv character(len=:),allocatable :: string call system_initenv() do string=system_readenv() if(string.eq.'')then exit else write(*,'(a)')string endif enddo end program demo_system_readenv
Sample results:
USERDOMAIN_ROAMINGPROFILE=buzz HOMEPATH= APPDATA=C: MANPATH=/home/urbanjs/V600/LIBRARY/libGPF/download/tmp/man:/home/urbanjs/V600/doc/man::: DISPLAYNUM=0 ProgramW6432=C: Files HOSTNAME=buzz XKEYSYMDB=/usr/share/X11/XKeysymDB PUBLISH_CMD= OnlineServices=Online Services : : :
References arr2str(), and longest_env_variable.
system_remove()
integer(c_int) function, public m_system::system_remove (character(*), intent(in) path)
NAME
system_remove(3f) - [M_system] call remove(3c) to remove file
SYNOPSIS
function system_remove(path) result(err)
character(*),intent(in) :: path integer(c_int) :: err
DESCRIPTION
Fortran supports scratch files via the OPEN(3c) command; but does not otherwise allow for removing files. The system_remove(3f) command allows for removing files by name that the user has the authority to remove by calling the C remove(3c) function.
EXAMPLE
Sample program:
program demo_system_remove use M_system, only : system_remove character(len=*),parameter :: FILE='MyJunkFile.txt' write(*,*)'BEFORE CREATED '//FILE call execute_command_line('ls -l '//FILE) write(*,*)
! note intentionally causes error if file exists open(unit=10,file=FILE,status='NEW') write(*,*)'AFTER OPENED '//FILE call execute_command_line('ls -l '//FILE) write(*,*)
write(10,'(a)') 'This is a file I want to delete' close(unit=10) write(*,*)'AFTER CLOSED ' call execute_command_line('ls -l '//FILE) write(*,*)
ierr=system_remove(FILE) write(*,*)'AFTER REMOVED',IERR call execute_command_line('ls -l '//FILE) write(*,*)
end program demo_system_remove
Expected Results:
> BEFORE CREATED MyJunkFile.txt > ls: cannot access 'MyJunkFile.txt': No such file or directory > > AFTER OPENED MyJunkFile.txt > -rw-r–r– 1 JSU None 0 Nov 19 19:32 MyJunkFile.txt > > AFTER CLOSED > -rw-r–r– 1 JSU None 32 Nov 19 19:32 MyJunkFile.txt > > AFTER REMOVED 0 > ls: cannot access 'MyJunkFile.txt': No such file or directory
References str2arr().
system_rename()
integer function, public m_system::system_rename (character(*), intent(in) input, character(*), intent(in) output)
NAME
system_rename(3f) - [M_system] call rename(3c) to rename a system file
SYNOPSIS
function system_rename(input,output) result(ierr)
character(*),intent(in) :: input,output integer :: ierr
DESCRIPTION
Rename a file by calling rename(3c). It is not recommended that the rename occur while either filename is being used on a file currently OPEN(3f) by the program.
OPTIONS
INPUT system filename of an existing file to rename OUTPUT system filename to be created or overwritten by INPUT file
RETURNS
IERR zero (0) if no error occurs. If not zero a call to system_errno(3f) or system_perror(3f) is supported to diagnose error
EXAMPLE
Sample program:
  program demo_system_rename
  use M_system, only : system_rename
  use M_system, only : system_remove
  use M_system, only : system_perror
  implicit none
  character(len=256) :: string
  integer            :: ios, ierr
  ! try to remove junk files just in case
  ierr=system_remove('_scratch_file_')
  write(*,'(a,i0)') 'should not be zero ',ierr
  call system_perror('*demo_system_rename*')
  ierr=system_remove('_renamed_scratch_file_')
  write(*,'(a,i0)') 'should not be zero ',ierr
  call system_perror('*demo_system_rename*')
  ! create scratch file to rename
  open(unit=10,file='_scratch_file_',status='new')
  write(10,'(a)') 'Test by renaming "_scratch_file_" to "_renamed_scratch_file_"'
  write(10,'(a)') 'IF YOU SEE THIS ON OUTPUT THE RENAME WORKED'
  close(10)
  ! rename scratch file
  ierr=system_rename('_scratch_file_','_renamed_scratch_file_')
  if(ierr.ne.0)then
     write(*,*)'ERROR RENAMING FILE ',ierr
  endif
  ! read renamed file
  open(unit=11,file='_renamed_scratch_file_',status='old')
  INFINITE: do
     read(11,'(a)',iostat=ios)string
     if(ios.ne.0)exit INFINITE
     write(*,'(a)')trim(string)
  enddo INFINITE
  close(unit=11)
  ! clean up
  ierr=system_remove('_scratch_file_')
  write(*,'(a,i0)') 'should not be zero ',ierr
  ierr=system_remove('_renamed_scratch_file_')
  write(*,'(a,i0)') 'should be zero ',ierr
  end program demo_system_rename
Expected output:
> should not be zero -1 > demo_system_rename: No such file or directory > should not be zero -1 > demo_system_rename: No such file or directory > Test by renaming "_scratch_file_" to "_renamed_scratch_file_" > IF YOU SEE THIS ON OUTPUT THE RENAME WORKED > should not be zero -1 > should be zero 0
References str2arr().
system_rewinddir()
subroutine, public m_system::system_rewinddir (type(c_ptr), value dir)
NAME
system_rewinddir(3f) - [M_system] call rewinddir(3c) to rewind directory stream
SYNOPSIS
subroutine system_rewinddir(dir)
type(c_ptr),value :: dir
DESCRIPTION
Return to pointer to the beginning of the list for a currently open directory list.
OPTIONS
DIR A C_pointer assumed to have been allocated by a call to SYSTEM_OPENDIR(3f).
EXAMPLE
Sample program:
program demo_system_rewinddir use M_system, only : system_opendir,system_readdir use M_system, only : system_rewinddir,system_closedir use iso_c_binding implicit none
type(c_ptr) :: dir character(len=:),allocatable :: filename integer :: i, ierr !>>> open directory stream to read from call system_opendir('.',dir,ierr) !>>> read directory stream twice do i=1,2 write(*,'(a,i0)')'PASS ',i do call system_readdir(dir,filename,ierr) if(filename.eq.' ')exit write(*,*)filename enddo !>>> rewind directory stream call system_rewinddir(dir) enddo !>>> close directory stream call system_closedir(dir,ierr)
end program demo_system_rewinddir
system_rmdir()
integer(c_int) function, public m_system::system_rmdir (character(*), intent(in) dirname)
NAME
system_rmdir(3f) - [M_system] call rmdir(3c) to remove empty directories
SYNOPSIS
function system_rmdir(dirname) result(err)
character(*),intent(in) :: dirname integer(c_int) :: err
DESCRIPTION
DIRECTORY The name of a directory to remove if it is empty err zero (0) if no error occurred
EXAMPLE
Sample program:
program demo_system_rmdir use M_system, only : system_perror use M_system, only : system_rmdir, system_mkdir implicit none integer :: ierr write(*,*)'BEFORE TRY TO CREATE _scratch/' call execute_command_line('ls -ld _scratch')
write(*,*)'TRY TO CREATE _scratch/' ierr=system_mkdir('_scratch',0+8*0+7) write(*,*)'IERR=',ierr call execute_command_line('ls -ld _scratch')
write(*,*)'TRY TO REMOVE _scratch/' ierr=system_rmdir('_scratch') write(*,*)'IERR=',ierr call execute_command_line('ls -ld _scratch')
write(*,*)'TRY TO REMOVE _scratch when it should be gone/' ierr=system_rmdir('_scratch') call system_perror('test of system_rmdir') write(*,*)'IERR=',ierr call execute_command_line('ls -ld _scratch')
end program demo_system_rmdir
Expected output:
References str2arr().
system_setumask()
integer function, public m_system::system_setumask (integer, intent(in) umask_value)
NAME
system_setumask(3f) - [M_system] set the file mode creation umask
SYNOPSIS
integer function system_setumask(new_umask) result (old_umask)
integer,intent(in) :: new_umask integer(kind=c_int) :: umask_c
DESCRIPTION
The umask() function sets the file mode creation mask of the process to cmask and return the previous value of the mask. Only the file permission bits of cmask (see <sys/stat.h>) are used; the meaning of the other bits is implementation-defined.
The file mode creation mask of the process is used to turn off permission bits in the mode argument supplied during calls to the following functions:
open(), openat(), creat(), mkdir(), mkdirat(), mkfifo(), and mkfifoat()
mknod(), mknodat()
mq_open()
sem_open()
Bit positions that are set in cmask are cleared in the mode of the created file.
RETURN VALUE
The file permission bits in the value returned by umask() shall be the previous value of the file mode creation mask. The state of any other bits in that value is unspecified, except that a subsequent call to umask() with the returned value as cmask shall leave the state of the mask the same as its state before the first call, including any unspecified use of those bits.
ERRORS
No errors are defined.
EXAMPLE
Sample program
program demo_setumask use M_system, only : system_getumask, system_setumask integer :: newmask write(*,101)(system_getumask(),i=1,4) 101 format(1x,i0,1x,"O'",o4.4,"'",1x,'Z"',z0,"'",1x,"B'",b12.12,"'") newmask=63 old_umask=system_setumask(newmask) write(*,*)'NEW' write(*,101)(system_getumask(),i=1,4) end program demo_setumask
Expected output
18 O'022' Z"12' B'000010010" NEW 63 O'077' Z"3F' B'000111111"
system_stat()
subroutine, public m_system::system_stat (character(len=*), intent(in) pathname, integer(kind=8), dimension(13), intent(out) values, integer, intent(out), optional ierr)
NAME
SYSTEM_STAT - [M_system] Get file status information
SYNTAX
CALL SYSTEM_STAT(NAME, VALUES [, STATUS],[DEBUG])
character(len=*),intent(in) :: NAME integer(kind=8),intent(out) :: values(13) integer,optional,intent(out) :: status integer,intent(in) :: debug
DESCRIPTION
This function returns information about a file. No permissions are
required on the file itself, but execute (search) permission is required
on all of the directories in path that lead to the file.  The elements
that are obtained and stored in the array VALUES:
   VALUES(1) Device ID
   VALUES(2) Inode number
   VALUES(3) File mode
   VALUES(4) Number of links
   VALUES(5) Owner's uid
   VALUES(6) Owner's gid
   VALUES(7) ID of device containing directory entry for file (0 if not available)
   VALUES(8) File size (bytes)
   VALUES(9) Last access time as a Unix Epoch time rounded to seconds
   VALUES(10) Last modification time as a Unix Epoch time rounded to seconds
   VALUES(11) Last file status change time as a Unix Epoch time rounded to seconds
   VALUES(12) Preferred I/O block size (-1 if not available)
   VALUES(13) Number of blocks allocated (-1 if not available)
Not all these elements are relevant on all systems. If an element is
not relevant, it is returned as 0.
OPTIONS
NAME    The type shall be CHARACTER, of the default kind and a valid
        path within the file system.
VALUES  The type shall be INTEGER(8), DIMENSION(13).
STATUS  (Optional) status flag of type INTEGER(4). Returns 0 on success
        and a system specific error code otherwise.
DEBUG   (Optional) print values being returned from C routine being
        called if value of 0 is used
EXAMPLE
program demo_system_stat
use M_system, only : system_stat, system_getpwuid, system_getgrgid use M_time, only : fmtdate, u2d implicit none
integer(kind=8) :: buff(13) integer(kind=4) :: status character(len=*),parameter :: fmt_date='year-month-day hour:minute:second'
integer(kind=8) :: & Device_ID, Inode_number, File_mode, Number_of_links, Owner_uid, & Owner_gid, Directory_device, File_size, Last_access, Last_modification, & Last_status_change, Preferred_block_size, Number_of_blocks_allocated equivalence & (buff(1) , Device_ID) , & (buff(2) , Inode_number) , & (buff(3) , File_mode) , & (buff(4) , Number_of_links) , & (buff(5) , Owner_uid) , & (buff(6) , Owner_gid) , & (buff(7) , Directory_device) , & (buff(8) , File_size) , & (buff(9) , Last_access) , & (buff(10) , Last_modification) , & (buff(11) , Last_status_change) , & (buff(12) , Preferred_block_size) , & (buff(13) , Number_of_blocks_allocated)
CALL SYSTEM_STAT("/etc/hosts", buff, status)
if (status == 0) then write (*, FMT="('Device ID(hex/decimal):', T30, Z0,'h/',I0,'d')") buff(1),buff(1) write (*, FMT="('Inode number:', T30, I0)") buff(2) write (*, FMT="('File mode (octal):', T30, O19)") buff(3) write (*, FMT="('Number of links:', T30, I0)") buff(4) write (*, FMT="('Owner''s uid/username:', T30, I0,1x, A)") buff(5), system_getpwuid(buff(5)) write (*, FMT="('Owner''s gid/group:', T30, I0),1x, A") buff(6), system_getgrgid(buff(6)) write (*, FMT="('Device where located:', T30, I0)") buff(7) write (*, FMT="('File size(bytes):', T30, I0)") buff(8) write (*, FMT="('Last access time:', T30, I0,1x, A)") buff(9), fmtdate(u2d(int(buff(9))),fmt_date) write (*, FMT="('Last modification time', T30, I0,1x, A)") buff(10),fmtdate(u2d(int(buff(10))),fmt_date) write (*, FMT="('Last status change time:', T30, I0,1x, A)") buff(11),fmtdate(u2d(int(buff(11))),fmt_date) write (*, FMT="('Preferred block size(bytes):', T30, I0)") buff(12) write (*, FMT="('No. of blocks allocated:', T30, I0)") buff(13) endif
end program demo_system_stat 1 Results:
References str2arr().
system_stat_print()
subroutine, public m_system::system_stat_print (character(len=*), intent(in) filename, integer, intent(in), optional lun)
NAME
system_stat_print(3f) - [M_system] print the principal info obtained for a pathname from system_stat(3f)
SYNOPSIS
subroutine system_stat_print(filename)
character(len=*),intent(in) :: filename integer,intent(in),optional :: lun
DESCRIPTION
Call the system_stat(3f) routine and print the results
OPTIONS
filename pathname to print information for lun unit number to write to. Optional
EXAMPLE
Sample program
program demo_system_stat_print use M_system, only : system_stat_print call system_stat_print(pathname) end program demo_system_stat_print
References fmtdate, system_getgrgid(), system_getpwuid(), system_perm(), system_stat(), and u2d.
system_uname()
subroutine, public m_system::system_uname (character(kind=c_char), intent(in) WHICH, character(len=*), intent(out) NAMEOUT)
NAME
system_uname(3f) - [M_system] call a C wrapper that calls uname(3c) to get current system information from Fortran
SYNOPSIS
subroutine system_uname(WHICH,NAMEOUT)
character(KIND=C_CHAR),intent(in) :: WHICH character(len=*),intent(out) :: NAMEOUT
DESCRIPTION
Given a letter, return a corresponding description of the current operating system. The NAMEOUT variable is assumed sufficiently large enough to hold the value.
s return the kernel name r return the kernel release v return the kernel version n return the network node hostname m return the machine hardware name T test mode – print all information, in the following order - srvnm
EXAMPLE
Call uname(3c) from Fortran
program demo_system_uname use M_system, only: system_uname implicit none integer,parameter :: is=100 integer :: i character(len=*),parameter :: letters='srvnmxT' character(len=is) :: string=' '
do i=1,len(letters) write(*,'(80("="))') call system_uname(letters(i:i),string) write(*,*)'=====> TESTING system_uname('//letters(i:i)//')—>'//trim(string) enddo
end program demo_system_uname
system_unlink()
integer function, public m_system::system_unlink (character(len=*), intent(in) fname)
NAME
system_unlink(3f) - [M_system] remove a directory entry relative to directory file descriptor
SYNOPSIS
integer function unlink(path);
 character(len=*) :: path
DESCRIPTION
The unlink() function shall remove a link to a file. If path names a symbolic link, unlink() shall remove the symbolic link named by path and shall not affect any file or directory named by the contents of the symbolic link. Otherwise, unlink() shall remove the link named by the pathname pointed to by path and shall decrement the link count of the file referenced by the link.
When the file's link count becomes 0 and no process has the file open, the space occupied by the file shall be freed and the file shall no longer be accessible. If one or more processes have the file open when the last link is removed, the link shall be removed before unlink() returns, but the removal of the file contents shall be postponed until all references to the file are closed.
The path argument shall not name a directory unless the process has appropriate privileges and the implementation supports using unlink() on directories.
Upon successful completion, unlink() shall mark for update the last data modification and last file status change timestamps of the parent directory. Also, if the file's link count is not 0, the last file status change timestamp of the file shall be marked for update.
Values for flag are constructed by a bitwise-inclusive OR of flags from the following list, defined in <fcntl.h>:
AT_REMOVEDIR
Remove the directory entry specified by fd and path as a directory, not a normal file.
RETURN VALUE
Upon successful completion, these functions shall return 0. Otherwise,
these functions shall return -1 and set  errno  to indicate the error. If
-1 is returned, the named file shall not be changed.
EXAMPLES
Removing a link to a file
program demo_system_unlink use M_system, only : system_unlink, system_perroZ ierr = system_unlink('myfile1') if(ierr.ne.0)then call system_perror('demo_system_unlink') endif end program demo_system_unlink
References str2arr().
system_unsetenv()
subroutine, public m_system::system_unsetenv (character(len=*), intent(in) name, integer, intent(out), optional ierr)
NAME
system_unsetenv(3f) - [M_system] change or add an environment variable by calling unsetenv(3c)
SYNOPSIS
subroutine system_unsetenv(name,ierr)
character(len=*),intent(in) :: name integer,intent(out),optional :: ierr
DESCRIPTION
The system_unsetenv(3f) function deletes the variable name from the
environment.
OPTIONS
name name of variable to delete. If name does not exist in the environment, then the function succeeds, and the environment is unchanged.
ierr The system_unsetenv(3f) function returns zero on success, or -1 on error. name is NULL, points to a string of length 0, or contains an '=' character. Insufficient memory to add a new variable to the environment.
EXAMPLE
Sample program:
program demo_system_unsetenv use M_system, only : system_unsetenv, system_putenv implicit none call system_putenv('GRU=this is the value') write(*,'(a)')'The variable GRU should be set' call execute_command_line('env|grep GRU') call system_unsetenv('GRU') write(*,'(a)')'The variable GRU should not be set' call execute_command_line('env|grep GRU') end program demo_system_unsetenv
References str2arr().
Variable Documentation
accessperms
integer(kind=c_int), public m_system::accessperms
bind
integer(kind=c_int), dimension(c,name="f_ok") m_system::bind private
NAME
system_initenv(3f) - [M_system] initialize environment table pointer and size so table can be read by readenv(3f)
SYNOPSIS
subroutine system_initenv()
DESCRIPTION
A simple interface allows reading the environment variable table of the process. Call system_initenv(3f) to initialize reading the environment table, then call system_readenv(3f) until a blank line is returned. If more than one thread reads the environment or the environment is changed while being read the results are undefined.
EXAMPLE
Sample program:
program demo_system_initenv use M_system, only : system_initenv, system_readenv character(len=:),allocatable :: string call system_initenv() do string=system_readenv() if(string.eq.'')then exit else write(*,'(a)')string endif enddo end program demo_system_initenv
Sample results:
USERDOMAIN_ROAMINGPROFILE=buzz HOMEPATH= APPDATA=C: MANPATH=/home/urbanjs/V600/LIBRARY/libGPF/download/tmp/man:/home/urbanjs/V600/doc/man::: DISPLAYNUM=0 ProgramW6432=C: Files HOSTNAME=buzz XKEYSYMDB=/usr/share/X11/XKeysymDB PUBLISH_CMD= OnlineServices=Online Services : : :
deffilemode
integer(kind=c_int), public m_system::deffilemode
f_ok
integer(kind=c_int), public m_system::f_ok
host_name_max
integer(kind=c_int) m_system::host_name_max private
ident_egid
character(len=*), parameter m_system::ident_egid ="@(#)M_system::system_getegid(3f): call getegid(3c)" private
NAME
system_getegid(3f) - [M_system] get the effective group ID (GID) of current process from Fortran by calling getegid(3c)
SYNOPSIS
integer(kind=c_int) function system_getegid()
DESCRIPTION
The getegid() function returns the effective group ID of the calling process.
RETURN VALUE
The getegid() should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
getegid(), system_geteuid(), getuid(), setegid(), seteuid(), setgid(), setregid(), setreuid(), setuid()
EXAMPLE
Get group ID from Fortran
program demo_system_getegid use M_system, only: system_getegid implicit none write(*,*)'GID=',system_getegid() end program demo_system_getegid
ident_errno
character(len=*), parameter m_system::ident_errno ="@(#)M_system::system_errno(3f): return errno(3c)" private
NAME
system_errno(3f) - [M_system] C error return value
SYNOPSIS
integer(kind=c_int) function system_errno()
DESCRIPTION
Many C routines return an error code which can be queried by errno. The M_system(3fm) is primarily composed of Fortran routines that call C routines. In the cases where an error code is returned vi system_errno(3f) these routines will indicate it.
EXAMPLE
Sample program:
program demo_system_errno use M_system, only: system_errno, system_unlink, system_perror implicit none integer :: stat stat=system_unlink('not there/OR/anywhere') if(stat.ne.0)then write(*,*)'err=',system_errno() call system_perror('demo_system_errno') endif end program demo_system_errno
Typical Results:
err= 2 demo_system_errno: No such file or directory
ident_euid
character(len=*), parameter m_system::ident_euid ="@(#)M_system::system_geteuid(3f): call geteuid(3c)" private
NAME
system_geteuid(3f) - [M_system] get effective UID of current process from Fortran by calling geteuid(3c)
SYNOPSIS
integer(kind=c_int) function system_geteuid()
DESCRIPTION
The system_geteuid(3f) function shall return the effective user ID of the calling process. The geteuid() function shall always be successful and no return value is reserved to indicate the error.
EXAMPLE
Get group ID from Fortran:
program demo_system_geteuid use M_system, only: system_geteuid implicit none write(*,*)'EFFECTIVE UID=',system_geteuid() end program demo_system_geteuid
ident_getsid
character(len=*), parameter m_system::ident_getsid ="@(#)M_system::system_getsid(3f): call getsid(3c) to get session leader for given pid" private
NAME
system_getsid(3f) - [M_system] get the process group ID of a session leader
SYNOPSIS
integer(kind=c_int) function system_getsid(pid) integer(kind=c_int) :: pid
DESCRIPTION
The system_getsid() function obtains the process group ID of the process that is the session leader of the process specified by pid. If pid is 0, it specifies the calling process.
RETURN VALUE
Upon successful completion, system_getsid() shall return the process group ID of the session leader of the specified process. Otherwise, it shall return -1 and set errno to indicate the error.
EXAMPLE
Get SID from Fortran
program demo_system_getsid use M_system, only : system_getsid use ISO_C_BINDING, only : c_int implicit none write(*,*)'SID=',system_getsid(0_c_int) end program demo_system_getsid
ident_gid
character(len=*), parameter m_system::ident_gid ="@(#)M_system::system_getgid(3f): call getgid(3c)" private
NAME
system_getgid(3f) - [M_system] get the real group ID (GID) of current process from Fortran by calling getgid(3c)
SYNOPSIS
integer(kind=c_int) function system_getgid()
DESCRIPTION
The getgid() function returns the real group ID of the calling process.
RETURN VALUE
The getgid() should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
getegid(), system_geteuid(), getuid(), setegid(), seteuid(), setgid(), setregid(), setreuid(), setuid()
EXAMPLE
Get group ID from Fortran
program demo_system_getgid use M_system, only: system_getgid implicit none write(*,*)'GID=',system_getgid() end program demo_system_getgid
ident_initenv
character(len=*), parameter m_system::ident_initenv ="@(#)M_system::system_initenv(3f): initialize environment table for reading" private
ident_kill
character(len=*), parameter m_system::ident_kill ="@(#)M_system::system_kill(3f): call kill(3c) to send a signal to a process" private
NAME
system_kill(3f) - [M_system] send a signal to a process or a group of processes
SYNOPSIS
integer(kind=c_int) function system_kill(pid,sig)
   integer,intent(in) :: pid
   integer,intent(in) :: sig
DESCRIPTION
The kill() function shall send a signal to a process or a group of
processes specified by pid. The signal to be sent is specified by sig
and is either one from the list given in <signal.h> or 0. If sig is 0
(the null signal), error checking is performed but no signal is actually
sent. The null signal can be used to check the validity of pid.
For a process to have permission to send a signal to a process designated
by pid, unless the sending process has appropriate privileges, the real
or effective user ID of the sending process shall match the real or
saved set-user-ID of the receiving process.
If pid is greater than 0, sig shall be sent to the process whose process
ID is equal to pid.
If pid is 0, sig shall be sent to all processes (excluding an unspecified
set of system processes) whose process group ID is equal to the process
group ID of the sender, and for which the process has permission to send
a signal.
If pid is -1, sig shall be sent to all processes (excluding an unspecified
set of system processes) for which the process has permission to send
that signal.
If pid is negative, but not -1, sig shall be sent to all processes
(excluding an unspecified set of system processes) whose process group
ID is equal to the absolute value of pid, and for which the process has
permission to send a signal.
If the value of pid causes sig to be generated for the sending process,
and if sig is not blocked for the calling thread and if no other thread
has sig unblocked or is waiting in a sigwait() function for sig, either
sig or at least one pending unblocked signal shall be delivered to the
sending thread before kill() returns.
The user ID tests described above shall not be applied when sending
SIGCONT to a process that is a member of the same session as the sending
process.
An implementation that provides extended security controls may impose
further implementation-defined restrictions on the sending of signals,
including the null signal. In particular, the system may deny the
existence of some or all of the processes specified by pid.
The kill() function is successful if the process has permission to send
sig to any of the processes specified by pid. If kill() fails, no signal
shall be sent.
RETURN VALUE
Upon successful completion, 0 shall be returned. Otherwise, -1 shall be
returned and errno set to indicate the error.
ERRORS
The kill() function shall fail if:
EINVAL The value of the sig argument is an invalid or unsupported signal number. EPERM The process does not have permission to send the signal to any receiving process. ESRCH No process or process group can be found corresponding to that specified by pid. The following sections are informative.
EXAMPLE
Sample program:
program demo_system_kill use M_system, only : system_kill use M_system, only : system_perror implicit none integer :: i,pid,ios,ierr,signal=9 character(len=80) :: argument
do i=1,command_argument_count() ! get arguments from command line call get_command_argument(i, argument) ! convert arguments to integers assuming they are PID numbers read(argument,'(i80)',iostat=ios) pid if(ios.ne.0)then write(*,*)'bad PID=',trim(argument) else write(*,*)'kill SIGNAL=',signal,' PID=',pid ! send signal SIGNAL to pid PID ierr=system_kill(pid,signal) ! write message if an error was detected if(ierr.ne.0)then call system_perror('demo_system_kill') endif endif enddo end program demo_system_kill
SEE ALSO
getpid(), raise(), setsid(), sigaction(), sigqueue(),
ident_pid
character(len=*), parameter m_system::ident_pid ="@(#)M_system::system_getpid(3f): call getpid(3c)" private
NAME
system_getpid(3f) - [M_system] get PID (process ID) of current process from Fortran by calling getpid(3c)
SYNOPSIS
integer function system_getpid()
DESCRIPTION
The system_getpid() function returns the process ID of the calling process.
RETURN VALUE
The value returned is the integer process ID. The system_getpid() function shall always be successful and no return value is reserved to indicate an error.
EXAMPLE
Get process PID from Fortran
program demo_system_getpid use M_system, only: system_getpid implicit none write(*,*)'PID=',system_getpid() end program demo_system_getpid
ident_ppid
character(len=*), parameter m_system::ident_ppid ="@(#)M_system::system_getppid(3f): call getppid(3c)" private
NAME
system_getppid(3f) - [M_system] get parent process ID (PPID) of current process from Fortran by calling getppid(3c)
SYNOPSIS
integer(kind=c_int) function system_getppid()
DESCRIPTION
The system_getppid() function returns the parent process ID of the calling process.
RETURN VALUE
The system_getppid() function should always be successful and no return value is reserved to indicate an error.
ERRORS
No errors are defined.
SEE ALSO
exec, fork(), getpgid(), getpgrp(), getpid(), kill(), setpgid(), setsid()
EXAMPLE
Get parent process PID (PPID) from Fortran
program demo_system_getppid use M_system, only: system_getppid implicit none
write(*,*)'PPID=',system_getppid()
end program demo_system_getppid
ident_rand
character(len=*), parameter m_system::ident_rand ="@(#)M_system::system_rand(3f): call rand(3c)" private
NAME
system_rand(3f) - [M_system] call pseudo-random number generator rand(3c)
SYNOPSIS
integer(kind=c_int) :: function system_rand()
DESCRIPTION
Use rand(3c) to generate pseudo-random numbers.
EXAMPLE
Sample program:
   program demo_system_srand
   use M_system, only : system_srand, system_rand
   implicit none
   integer :: i
   call system_srand(1001)
   do i=1,10
      write(*,*)system_rand()
   enddo
   write(*,*)
   end program demo_system_srand
expected results:
1512084687 1329390995 1874040748 60731048 239808950 2017891911 22055588 1105177318 347750200 1729645355
1512084687 1329390995 1874040748 60731048 239808950 2017891911 22055588 1105177318 347750200 1729645355
ident_srand
character(len=*), parameter m_system::ident_srand ="@(#)M_system::system_srand(3f): call srand(3c)" private
NAME
system_srand(3f) - [M_system] set seed for pseudo-random number generator system_rand(3f)
SYNOPSIS
subroutine system_srand()
DESCRIPTION
system_srand(3f) calls the C routine srand(3c) The srand(3c)/system_srand(3f) function uses its argument as the seed for a new sequence of pseudo-random integers to be returned by system_rand(3f)/rand(3c). These sequences are repeatable by calling system_srand(3f) with the same seed value. If no seed value is provided, the system_rand(3f) function is automatically seeded with a value of 1.
EXAMPLE
Sample program:
   program demo_system_srand
   use M_system, only : system_srand, system_rand
   implicit none
   integer :: i,j
   do j=1,2
      call system_srand(1001)
      do i=1,10
         write(*,*)system_rand()
      enddo
      write(*,*)
   enddo
   end program demo_system_srand
expected results:
1512084687 1329390995 1874040748 60731048 239808950 2017891911 22055588 1105177318 347750200 1729645355
1512084687 1329390995 1874040748 60731048 239808950 2017891911 22055588 1105177318 347750200 1729645355
SEE ALSO
drand48(3c), random(3c)
ident_uid
character(len=*), parameter m_system::ident_uid ="@(#)M_system::system_getuid(3f): call getuid(3c)" private
NAME
system_getuid(3f) - [M_system] get real UID of current process from Fortran by calling getuid(3c)
SYNOPSIS
integer(kind=c_int) function system_getuid()
DESCRIPTION
The system_getuid(3f) function shall return the real user ID of the calling process. The getuid() function shall always be successful and no return value is reserved to indicate the error.
EXAMPLE
Get group ID from Fortran:
program demo_system_getuid use M_system, only: system_getuid implicit none write(*,*)'UID=',system_getuid() end program demo_system_getuid
Results:
UID= 197609
ident_umask
character(len=*), parameter m_system::ident_umask ="@(#)M_system::system_umask(3f): call umask(3c)" private
NAME
system_umask(3fp) - [M_system] set and get the file mode creation mask
SYNOPSIS
integer(kind=c_int) function system_umask(umask_value)
DESCRIPTION
The umask() function shall set the file mode creation mask of the process to cmask and return the previous value of the mask. Only the file permission bits of cmask (see <sys/stat.h>) are used; the meaning of the other bits is implementation-defined.
The file mode creation mask of the process is used to turn off permission bits in the mode argument supplied during calls to the following functions:
open(), openat(), creat(), mkdir(), mkdirat(), mkfifo(), and mkfifoat()
mknod(), mknodat()
mq_open()
sem_open()
Bit positions that are set in cmask are cleared in the mode of the created file.
RETURN VALUE
The file permission bits in the value returned by umask() shall be the previous value of the file mode creation mask. The state of any other bits in that value is unspecified, except that a subsequent call to umask() with the returned value as cmask shall leave the state of the mask the same as its state before the first call, including any unspecified use of those bits.
EXAMPLE
Sample program:
program demo_system_umask use M_system, only: system_getumask, system_setumask implicit none integer value value=system_getumask(002) write(*,*)'VALUE=',value value=system_setumask(value) write(*,*)'VALUE=',value end program demo_system_umask
longest_env_variable
integer(kind=c_long) m_system::longest_env_variable private
mode_t
integer, parameter, public m_system::mode_t =kind(c_int)
r_grp
integer(kind=c_int), public m_system::r_grp
r_ok
integer(kind=c_int), public m_system::r_ok
r_oth
integer(kind=c_int), public m_system::r_oth
r_usr
integer(kind=c_int), public m_system::r_usr
r_wxg
integer(kind=c_int), public m_system::r_wxg
r_wxo
integer(kind=c_int), public m_system::r_wxo
r_wxu
integer(kind=c_int), public m_system::r_wxu
w_grp
integer(kind=c_int), public m_system::w_grp
w_ok
integer(kind=c_int), public m_system::w_ok
w_oth
integer(kind=c_int), public m_system::w_oth
w_usr
integer(kind=c_int), public m_system::w_usr
x_grp
integer(kind=c_int), public m_system::x_grp
x_ok
integer(kind=c_int), public m_system::x_ok
x_oth
integer(kind=c_int), public m_system::x_oth
x_usr
integer(kind=c_int), public m_system::x_usr