GeneralPurposeFortran: m_fpp Module Reference
m_fpp Module Reference
<html> <head> <title> ufpp </title> <link rel="stylesheet" type="text/css" href="StyleSheets/man.css" title="Local"> <meta name="description" content="Fortran module containing library of date and time procedures"> <meta name="keywords" content="date_and_time,date,time,gregorian,julian,epoch time,day of week, ordinal day"> <meta name="keywords" content="week of year"> <meta name="keywords" content="Fortran,module,library,repository,collection"> <script src="../../../javascript/toggleHidden.js" type="text/javascript"></script> </head> <body>
Data Types
type file_stack
Functions/Subroutines
subroutine cond ()
subroutine exe ()
subroutine ident (opts)
subroutine output_case (opts)
subroutine define (opts, ireset)
character(len=17) function getdatetimestr ()
subroutine printenv (opts)
subroutine name (line)
subroutine getval (line, ipos1, ipos2, value)
subroutine undef (opts)
subroutine if (opts, noelse, eb)
subroutine def (verb, opts, noelse, eb)
subroutine ifdef (line, ipos1)
subroutine else (verb, opts, noelse, eb)
subroutine endif (noelse, eb)
subroutine parens (line)
subroutine math (line, ipos1, ipos2)
subroutine domath (line, ipos2)
subroutine doop (line, ipos1, ipos2)
logical function trufal (line, ipos1, ipos2)
subroutine logic (line, ipos1, ipos2)
subroutine eval (line)
integer function get_integer_from_string (line, ipos1, ipos2)
subroutine rewrit (line, temp, j, j1, l, l1)
subroutine document (opts)
subroutine stop (opts)
subroutine print_comment_block ()
subroutine format_g_man ()
subroutine stops (iexit)
subroutine debug (msg)
subroutine write_arguments ()
subroutine include (line, iunit)
subroutine findit (line)
subroutine opens ()
subroutine includes ()
subroutine defines ()
subroutine stop_ufpp (message)
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
ufpp(1) - [DEVELOPER] pre-process FORTRAN source files
subroutine write_out (line)
subroutine www (line)
Variables
integer, parameter num =2048
integer, parameter, public g_line_length =4096
integer, parameter, public g_var_len =31
integer, public g_numdef =0
character(len=g_line_length), public g_source
character(len=g_line_length), public g_outline
character(len=g_var_len), dimension(num), public g_defval
character(len=g_var_len), dimension(num), public g_defvar
type(file_stack), dimension(50) g_file_dictionary
type(streampointer) g_fp
character(len=:), allocatable g_scratch_filename
integer, public g_iocount =0
integer, public g_io_total_lines =0
integer, public g_iwidth
logical, public g_noenv =.false.
integer, public g_iout
integer, save, public g_iout_init
integer, public g_ihelp =OUTPUT_UNIT
character(len=10), public g_outtype ='asis'
integer, public g_inc_count =0
character(len=g_line_length), dimension(50), public g_inc_files
character(len=:), allocatable, save g_man
logical, save g_man_collect =.false.
logical, save g_man_print =.false.
character(len=:), allocatable g_man_file
character(len=10) g_man_file_position ='ASIS '
integer, public g_nestl =0
integer, parameter, public g_nestl_max =20
logical, save, public g_html_switch =.false.
logical, save, public g_write_what =.false.
logical, save, public g_system_on =.false.
logical, dimension(0:g_nestl_max), save, public g_condop
logical, public g_dc
logical, public g_write =.true.
logical, public g_llwrite =.true.
integer, public g_comment_count =0
character(len=10), public g_comment_style =' '
Detailed Description
<html> <head> <title> ufpp </title> <link rel="stylesheet" type="text/css" href="StyleSheets/man.css" title="Local"> <meta name="description" content="Fortran module containing library of date and time procedures"> <meta name="keywords" content="date_and_time,date,time,gregorian,julian,epoch time,day of week, ordinal day"> <meta name="keywords" content="week of year"> <meta name="keywords" content="Fortran,module,library,repository,collection"> <script src="../../../javascript/toggleHidden.js" type="text/javascript"></script> </head> <body>
NAME
ufpp(1) - [DEVELOPER] a Fortran source code pre-processor
SYNOPSIS
    ufpp  [[-D] define_list]
          [-I include_directories]
          [-i input_file(s)]
          [-o output_file]
          [-html]
          [-system]
          [-verbose]
          [-prefix character_ADE]
          [-keeptabs]
          [-noenv]
          [-width n]
          [-d ignore|remove|blank]
          [-cstyle default|doxygen]
          [-version]
          [-help [-html]]
DESCRIPTION
The ufpp(1) command is a basic file pre-processor in the style of fpp(1) and cpp(1) that allows simple embedded directives to be used to conditionally select source code lines.
Additional features allow ufpp(1) to easily support single files that contain documentation, source code, and unit testing materials and commands.
A detailed description of command options can be generated by using the "-help" switch , which was used to generate ufpp.1.html.
ufpp(1) is relatively language-agnostic, but is particularly designed with Fortran in mind. It is in fact written in Fortran. You will therefore find ufpp(1) particularly useful if you desire a Fortran-based pre-processor that is simple enough that you can easily customize it.
More specifically source file lines can be selected conditionally using basic directives ($IF, $ELSE, $ELSEIF, $ENDIF, $DEFINE, $UNDEFINE, ...) The syntax for numeric expressions in the directives is very similar to FORTRAN 77 INTEGER and LOGICAL expressions.
Additionally ufpp(1) supports
generating multiple files from a single input file
embedded system commands
incorporation of input into simple HTML documents
conversion of flat text to a help/version routine or Fortran comments.
Output is filtered to generate files that are "Fortran-friendly". By default:
tab characters are expanded.
DOS line terminators are removed in GNU/Linux and Unix environments.
For fixed-format files
Common Fortran source-code extensions such as "dee'd" conditional lines are conditionally expanded in a compiler-independent fashion ("dee'd" lines are ones where a 'D' in column 1 designates lines that are only compiled to create a debug version, often found in fixed-format Fortran).
optionally data past column 72 can be ignored as comments or "idents"
EXAMPLES
a basic input file ...
Assuming you are familiar with the basic behavior of preprocessors such as cpp(1), fpp(1), coco(1), or more powerful macro processors such as m4(1) let us start with a basic input file example:
  $! Compile this program and one of the following versions of subroutine SUB1 depending on the value of A
  $! NOTE: This Fortran source file contains ufpp(1) directives beginning with a dollar("$") character.
  $!------------------
  $! set default values for variables tested
  $IF .NOT.DEFINED(A)
  $  DEFINE A=1
  $ENDIF
  $!------------------
     program conditional_compile
        call sub1
     end program conditional_compile
  $IF A .EQ. 1        ! If A=1 output this version of subroutine sub1
     subroutine sub1
        print*, "This is the first SUB1"
     end subroutine sub1
  $ELSEIF A .EQ. 2    ! If A=2 output this version of subroutine sub1
     subroutine sub1
        print*, "This is the second SUB1"
     end subroutine sub1
  $ELSE               ! If A was not 1 or 2 output this version of subroutine sub1
     subroutine sub1
        print*, "This is the third SUB1"
     end subroutine sub1
  $ENDIF
Assuming this example is in the file "basic.ff" the output of the command
    ufpp a=2 -i basic.ff -o basic.f90
would be
    program conditional_compile
       call sub1
    end program conditional_compile
    subroutine sub1
       print*, "This is the second SUB1"
    end subroutine sub1
The next example shows how regions of flat text can be processed by ufpp(1): o The $FILTER HELP directive can be used to produce a routine to display help text and the help text can also be written to a file to produce further document formats. o The $FILTER VERSION directive can be used a to produce a routine that displays a version in a way that is compatible with the metadata display program what(1). o The $FILTER NULL directive can be used for text that is otherwise ignored. o The $FILTER NULL directive can be used for text that is otherwise ignored. Note that text can optionally be written to an alternate file using $OUTPUT directives. o The $FILTER SHELL directive can be used for text that is the output of a shell. This can be very system-dependent but allows code to be built dynamically.
<xmp> $FILTER NULL -file notes.txt !@@@@@@@@@@@@@@@@@@@@@@@@@ This section uses $FILTER NULL to let a block of text be included in the source that is essentially ignored. The difference between this and a $IFDEF .FALSE. ... $ENDIF or $OUTPUT /dev/null .. $OUTPUT END section is that the -file switch lets this section get written to a file optionally when the $UFPP_DOCUMENT_DIR variable is set. This text could be markdown text, HTML, RTF, LaTex or some other format to be post-processed independently.
The following $FILTER HELP section directives is converted into the HELP_USAGE() subroutine by ufpp. Optionally if the environment variable $UFPP_DOCUMENT_DIR is set the text is additionally written as-is into
$UFPP_DOCUMENT_DIR/doc/cf.1.man
because the optional "-file cf.1.man" switch was specified.
This additional file would then typically be run thru txt2man(1) to create a man(1) page. $FILTER END !@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ $IFDEF F90 $FILTER HELP -file cf.1.man NAME cf - Convert between Fahrenheit and Celsius temperature values
SYNOPSIS cf [-C val1 val2 val3 ...] [-F val1 val2 val3 ...][–help][–version]
DESCRIPTION -C [ val(1) val(2) val(3) ... ] Display the given Celsius values as both Celsius and Fahrenheit values -F [ val(1) val(2) val(3) ... ] Display the given Fahrenheit values as both Celsius and Fahrenheit values
If no values are given a small table of common temperatures is displayed
–help display this help and exit
–version output version information and exit
At the physically impossible-to-reach temperature of zero Kelvin, or minus 459.67 degrees Fahrenheit (minus 273.15 Celsius), atoms would stop moving. As such, nothing can be colder than absolute zero on the Kelvin scale.
$FILTER END $!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ $! this text is converted into the help_version subroutine by ufpp ... $! in a format that works with what(1), do not use ",>,\ characters in the labels $FILTER VERSION PRODUCT: CLI library utilities and examples PROGRAM: cf(1f) DESCRIPTION: convert multiple values between Celsius and Fahrenheit VERSION: 1.0, 2016-04-09 AUTHOR: John S. Urban REPORTING BUGS: http://www.urbanjost.altervista.org/ HOME PAGE: http://www.urbanjost.altervista.org/index.html LICENSE: Public Domain. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law. $FILTER END $!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ $! use output of a bash(1) shell here document to build some comments $FILTER SHELL cat <<EOF !! date ....... !! userid ..... !! hostname ... EOF $FILTER END $!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ $FILTER COMMENT This block of text becomes Fortran comment lines by having exclamations placed in front of each line, but is otherwise left as-is.
The next section is just as-is Fortran $FILTER END $!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ program cf use M_kracken, only: kracken, rgets, lget implicit none $IDENT cf(1f): convert multiple values between Celsius and Fahrenheit real,allocatable :: val(:) integer :: i, isum=0 call kracken('cf','-F -C -help .F. -version .F.') ! define and crack command line arguments call help_usage(lget('cf_help')) ! display help information and stop if true call help_version(lget('cf_version')) ! display version information and stop if true isum=0 ! running tally of values found on -C and -F options val=rgets('cf_C') ! get any values specified on -C option
if(size(val).gt.0)then ! have something to print in C ==> F table isum=isum+size(val) write(*,'(a,t14,a)')'Celsius','Fahrenheit' write(*,'(f8.2,"C",t14,f8.2,"F")')& & (val(i),(val(i)+40.0)*9.0/5.0 - 40.0,i=1,size(val)) ! print the requested values endif
val=rgets('cf_F') ! check for values on -F
if(size(val).gt.0)then isum=isum+size(val) write(*,'(a,t14,a)') 'Fahrenheit', 'Celsius' write(*,'(f8.2,"F",t14,f8.2,"C")')(val(i),(val(i)+40.0)*5.0/9.0 - 40.0,i=1,size(val)) endif
if(isum.eq.0)then ! if no values given on -C and -F switches show default table val=[ & &-459.67, & & -20.0, -15.0, -10.0, -5.0, 0.0, & & 5.0, 10.0, 15.0, 20.0, 25.0, & & 30.0, 32.0, 35.0, 40.0, 45.0, & & 50.0, 55.0, 60.0, 65.0, 70.0, & & 75.0, 80.0, 85.0, 90.0, 95.0, & & 98.6, 100.0, 105.0, 110.0, 115.0 ] write(*,'(a,t14,a)') 'Fahrenheit', 'Celsius' write(*,'(f8.2,"F",t14,f8.2,"C")')(val(i),(val(i)+40.0)*5.0/9.0 - 40.0,i=1,size(val)) endif
end program cf and the output file $ENDIF $!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ $IFDEF UFPP_TEST Normally you would not just put text here, but $SYSTEM and $OUTPUT sections to unit test your commands. Then you would call ufpp UFPP_TEST -system ... to run your tests, and ufpp F90 ... to generate the expanded source code when compiling
$ENDIF $!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ </xmp>
The output from "ufpp F90 -i FILE -system" is:
<xmp> subroutine help_usage(l_help) implicit none character(len=*),parameter :: ident="@(#)help_usage(3f): prints help information" logical,intent(in) :: l_help character(len=:),allocatable :: help_text(:) integer :: i logical :: stopit=.false. stopit=.false. if(l_help)then help_text=[ CHARACTER(LEN=128) :: & 'NAME ',& ' cf - Convert between Fahrenheit and Celsius temperature values ',& ' ',& 'SYNOPSIS ',& ' cf [-C val1 val2 val3 ...] [-F val1 val2 val3 ...][–help][–version] ',& ' ',& 'DESCRIPTION ',& ' -C [ val(1) val(2) val(3) ... ] ',& ' Display the given Celsius values as both Celsius and Fahrenheit values ',& ' -F [ val(1) val(2) val(3) ... ] ',& ' Display the given Fahrenheit values as both Celsius and Fahrenheit values ',& ' ',& ' If no values are given a small table of common temperatures is displayed ',& ' ',& ' –help display this help and exit ',& ' ',& ' –version ',& ' output version information and exit ',& ' ',& ' At the physically impossible-to-reach temperature of zero Kelvin, or ',& ' minus 459.67 degrees Fahrenheit (minus 273.15 Celsius), atoms would ',& ' stop moving. As such, nothing can be colder than absolute zero on the ',& ' Kelvin scale. ',& ' ',& ''] WRITE(*,'(a)')(trim(help_text(i)),i=1,size(help_text)) stop ! if -help was specified, stop endif end subroutine help_usage !--------------------------------------------------------------------------------------------------------------------------------— subroutine help_version(l_version) implicit none character(len=*),parameter :: ident="@(#)help_version(3f): prints version information" logical,intent(in) :: l_version character(len=:),allocatable :: help_text(:) integer :: i logical :: stopit=.false. stopit=.false. if(l_version)then help_text=[ CHARACTER(LEN=128) :: & '@(#)PRODUCT: CLI library utilities and examples>',& '@(#)PROGRAM: cf(1f)>',& '@(#)DESCRIPTION: convert multiple values between Celsius and Fahrenheit>',& '@(#)VERSION: 1.0, 2016-04-09>',& '@(#)AUTHOR: John S. Urban>',& '@(#)REPORTING BUGS: http://www.urbanjost.altervista.org/>',& '@(#)HOME PAGE: http://www.urbanjost.altervista.org/index.html>',& '@(#)LICENSE: Public Domain. This is free software: you are free>',& '@(#) to change and redistribute it. There is NO WARRANTY,>',& '@(#) to the extent permitted by law.>',& '@(#)COMPILED: Mon, Dec 18th, 2017 2:55:24 AM>',& ''] WRITE(*,'(a)')(trim(help_text(i)(5:len_trim(help_text(i))-1)),i=1,size(help_text)) stop ! if -version was specified, stop endif end subroutine help_version !--------------------------------------------------------------------------------------------------------------------------------— !! date ....... Mon, Dec 18, 2017 2:55:25 AM !! userid ..... JSU !! hostname ... buzz ! This block of text becomes Fortran comment lines by having exclamations ! placed in front of each line, but is otherwise left as-is. ! ! The next section is just as-is Fortran !=================================================================================================================================== program cf use M_kracken, only: kracken, rgets, lget implicit none character(len=*),parameter::ident="@(#)cf(1f): convert multiple values between Celsius and Fahrenheit" real,allocatable :: val(:) integer :: i, isum=0 call kracken('cf','-F -C -help .F. -version .F.') ! define and crack command line arguments call help_usage(lget('cf_help')) ! display help information and stop if true call help_version(lget('cf_version')) ! display version information and stop if true isum=0 ! running tally of values found on -C and -F options val=rgets('cf_C') ! get any values specified on -C option
if(size(val).gt.0)then ! have something to print in C ==> F table isum=isum+size(val) write(*,'(a,t14,a)')'Celsius','Fahrenheit' write(*,'(f8.2,"C",t14,f8.2,"F")')& & (val(i),(val(i)+40.0)*9.0/5.0 - 40.0,i=1,size(val)) ! print the requested values endif
val=rgets('cf_F') ! check for values on -F
if(size(val).gt.0)then isum=isum+size(val) write(*,'(a,t14,a)') 'Fahrenheit', 'Celsius' write(*,'(f8.2,"F",t14,f8.2,"C")')(val(i),(val(i)+40.0)*5.0/9.0 - 40.0,i=1,size(val)) endif
if(isum.eq.0)then ! if no values given on -C and -F switches show default table val=[ & &-459.67, & & -20.0, -15.0, -10.0, -5.0, 0.0, & & 5.0, 10.0, 15.0, 20.0, 25.0, & & 30.0, 32.0, 35.0, 40.0, 45.0, & & 50.0, 55.0, 60.0, 65.0, 70.0, & & 75.0, 80.0, 85.0, 90.0, 95.0, & & 98.6, 100.0, 105.0, 110.0, 115.0 ] write(*,'(a,t14,a)') 'Fahrenheit', 'Celsius' write(*,'(f8.2,"F",t14,f8.2,"C")')(val(i),(val(i)+40.0)*5.0/9.0 - 40.0,i=1,size(val)) endif
end program cf </xmp>
This small example shows an easy way to maintain help and version options easily for programs. Note that the M_kracken module was used to provide the example with command line argument parsing; but that is not required.
A more complicated example follows where code is contained in an HTML document. When the ufpp(1) switch "-html" is used or the input filename ends in ".html" , all lines outside of the lines delimited with the XMP directive are ignored, allowing documentation and code to be contained in one file that can be viewed via a browser.
     <html>
     <head>
        <title> Simple HTML template for use with ufpp(1) </title>
        <link rel="stylesheet" href="http://www.w3.org/StyleSheets/Core/OldStyle&quot; type="text/css" />
        <!-- Chocolate Midnight Modernist Oldstyle Steely Swiss Traditional Ultramarine -->
     </head>
     <body>
     <h1> This is an HTML document that can be used as input to ufpp(1)</h1>
     <p>
         If you are comfortable writing simple HTML documents, a simple
         feature of ufpp(1) allows you to easily maintain documentation,
         source, and links to external files all together. If you run the
         ufpp(1) Fortran Preprocessor on this file with the command
         <pre>
         ufpp -html -i THISFILE.html -o THISFILE.f90
         </pre>
         the Fortran source is extracted using very simple rules: If lines
         begin with &lt;xmp&gt; start writing out the lines; quit if
         &lt;/xmp&gt; is encountered.
     </p>
     <h2> TEST PROGRAM </h2>
     <!-- =============================================================== -->
     <xmp>
     $if .not.defined(WHICH_VERSION)
     $define WHICH_VERSION=1 ! Will only compile the first version of subroutine ONE
     $endif
           program testit
              write(*,*)'hello world'
              call one()
              call two()
           end program testit
     </xmp>
     <!-- =============================================================== -->
     <h2> ROUTINE ONE </h2>
     <p>
          There are three versions of subroutine ONE(). If WHICH_VERSION
          is not defined, the "third" version is written to output.
          If WHICH_VERSION = 1, version "first" is used.
          If WHICH_VERSION =2 , version "second" is used.
     </p>
     <xmp>
     $IF WHICH_VERSION .EQ. 1
          subroutine one()
             write(*,*)'called one, first version'
          end subroutine one
     $ELSEIF WHICH_VERSION .eq. 2
          subroutine one()
             write(*,*)'called one, second version'
          end subroutine one
     $ELSE
          subroutine one()
             write(*,*)'called one, third version'
          end subroutine one
     $ENDIF
     </xmp>
     <!-- =============================================================== -->
     <h2> ROUTINE TWO</h2>
     <xmp>
           subroutine two()
              write(*,*)'called two'
           end subroutine two
     </xmp>
     <!-- =============================================================== -->
     </body>
History:
This customized pre-processor is derived from the public-domain Lahey pre-processor. Parsing of expressions remains significantly unchanged from the Lahey version; but the rest is essentially a re-write. ufpp(1) compiles with all the Fortran 90+ compilers I have needed it for; including the freely available gfortran(1) compiler (version 4.5.3+).
Notes on Fortran source code pre-processing with ufpp(1)
In practice Fortran codes rarely need traditional pre-processing. In the past the most common reason for passing Fortran files through a pre-processor was when the code was calling C code or other languages where there was no standard calling interface defined. The ISO_C_BINDING standard now defines a C-Fortran interface; so there is now generally less need to pre-process Fortran source. The second-most common need for pre-processing was to easily use different Fortran extensions in different environments. Since the most common extensions are now standardized (accessing command line arguments, getting date/time information, passing a system command to the operating system, ...) the need for traditional pre-processing has diminished even more. On the other hand dealing with differences between compilers that only partially implement newer Fortran versions has brought back a new need for pre-processing; but that is hopefully a temporary issue.
That being said, pre-processing is occasionally still required. I strongly recommend that you isolate such code by putting the code sections that require pre-processing into small procedures that perform just the non-standard operations, and keep this in the smallest number of files possible.
If I try to avoid the need for traditional pre-processing of Fortran source code whenever possible why not just use cpp(1) instead of making ufpp(1)? Even if traditional pre-processing is not required I find the ufpp(1) filtering capabilities useful as a way to keep related text files (documentation, test files, test programs, test scripts, ...) together in an easily maintained form.
Notes on alternatives to ufpp(1)
If you just want traditional pre-processing capabilities and use a major Linux or Unix distribution you may find existing tools already meet your needs.
Some Fortran compilers provide their own "Fortran-safe" pre-processors. The compiler documentation often describes their features; which are usually a subset of the Unix utility cpp(1). They often intentionally do not provide macro expansion or C-style comments (block or in-line); but otherwise look very much like cpp(1). They are often called "fpp" if they can be called as a stand-alone utility. Sun has an open-source version on netlib of their flavor of fpp(1).
The cpp(1) program is designed for C/C++ and is not totally "Fortran- safe". It is, however, a de-facto standard for code pre-processing. Different versions often have switches to reduce the chances of generating unexpected Fortran code. The most common version of cpp(1) works with most Fortran using the following form:
    cpp -P -C -traditional MYFILE.F90
The Fortran 95 standard provided an optional standard pre-processor definition. Currently, it seems to rarely be provided with compilers. Dan Nagle has an open-source version with macro expansion called "coco".
The Lahey Fortran site has a pre-processor code in a public-domain repository at http://www.lahey.com/code.htm. It is written in Fortran 77. This is what ufpp(1) was originally derived from. Typically you need to create a small wrapper script to call it from make(1)/cmake(1)/...
Other pre-processors that are Fortran-friendly or relatively language-agnostic are
"f90ppr" by Michel Olganon
"fpx3" (Joerg Behren version is popular)
"mp4" (commonly available on Unix/GNU platforms. It is a powerful general macro pre-processor.)
"tradcpp" ("traditional" cpp from GNU; which has less problems with Fortran than modern C-standard cpp(1) versions)
"filepp" at http://www.cabaret.demon.co.uk/filepp
"forpedo"
Using alternate Fortran sources and/or INCLUDE files
Simply put, instead of pre-processors you can conditionally compile different files.
If you have a directory for each programming environment with identically named procedures in them that are specific to a system you can often avoid pre-processing altogether. Isolate the system-dependent code into small procedures to minimize duplicate code. Usually, the files are of the same name but in different directories, one per platform. You can often additionally reduce the amount of duplicate code by judicious use of Fortran INCLUDE files. The most common problem with this method is making sure you keep any changes to the procedure parameters consistent across all the versions of the same routine.
"INCLUDE" method
A variation on the previous approach is to have different directories with the same filenames in them that are INCLUDE files. You compile for different environments with the -I switch commonly available on Fortran compilers. So if you had directories CRAY and HP that both had the same files in them you could build different versions by entering "f90 -ICRAY ..." or "f90 -IHP ...".
Using dead code
If the system-dependent code is all "standard" code that will compile on all platforms some people recommend placing all the code in a procedure and setting a variable with an INCLUDE to select the proper code (assuming the selection does not cause major performance overhead).
This will make some branches into "dead code"; which many compilers will remove while optimizing the code.
      subroutine system_dependent()
      character(len=10) :: system
      include "system.h"
      if(system.eq.'hp')then
        write(*,*)'do hp stuff'
      elseif(system.eq.'cray')then
        write(*,*)'do cray stuff'
      else
        write(*,*)'error: unknown system'
      endif
      end subroutine system_dependent
Assuming you have multiple "system.h" files that include a line like
      system='hp'
or
      system='cray'
You can build different versions using the -I parameter once again to point to the different INCLUDE files.
I personally do not use this "dead code" method, but have seen it used to good effect.
Run-time selection
Of course when all the code can be compiled on all platforms you can write the code without any preprocessing or use of alternate INCLUDE files and provide input at run-time to select the correct branch as well. The difference is that the compiler cannot optimize out the unused branches in that case.
Procedure pointers
When all the code is standard a good method can be to use pointers to procedures, as is often used to select between different graphics drivers or various mathematical "solvers".
<footer> <script language="JavaScript" type="text/javascript" src="../../../javascript/doc.js"> </script> <script language="JavaScript"> footer("2015-09-13"); </script> </footer>
</body> </html>
Function/Subroutine Documentation
cond()
subroutine m_fpp::cond ()
References m_debug::debug, def(), define(), document(), else(), endif(), exe(), g_iocount, g_source, g_write, help_usage(), if(), include(), m_strings::nospace(), output_case(), printenv(), m_debug::stderr(), stop(), stop_ufpp(), true(), undef(), and m_strings::upper().
debug()
subroutine m_fpp::debug (character(len=*), intent(in) msg)
References g_defval, g_defvar, g_file_dictionary, g_inc_count, g_inc_files, g_io_total_lines, g_iocount, g_iout, g_llwrite, g_nestl, g_numdef, g_write, getdatetimestr(), and write_arguments().
def()
subroutine m_fpp::def (character(len=*), intent(in) verb, character(len=*), intent(in) opts, integer, intent(out) noelse, logical eb)
References false(), g_condop, g_dc, g_defvar, g_nestl, g_nestl_max, g_noenv, g_numdef, g_source, g_write, stop_ufpp(), and true().
define()
subroutine m_fpp::define (character(len=*), intent(in) opts, integer, intent(in) ireset)
References doop(), g_defval, g_defvar, g_numdef, g_var_len, getval(), logic(), math(), parens(), and stop_ufpp().
defines()
subroutine m_fpp::defines ()
References cond(), and g_source.
document()
subroutine m_fpp::document (character(len=*), intent(in) opts)
References m_kracken::dissect(), false(), g_comment_count, g_comment_style, g_fp, g_iout, g_man, g_man_collect, g_man_file, g_man_file_position, g_man_print, g_outtype, g_scratch_filename, g_source, g_system_on, m_kracken::lget(), m_time::now(), print_comment_block(), m_kracken::sget(), m_io::slurp(), stop_ufpp(), m_system::system_remove(), true(), m_io::uniq(), unit(), and m_strings::upper().
domath()
subroutine m_fpp::domath (character(len=*) line, integer ipos2)
References g_line_length, g_source, get_integer_from_string(), m_strings::nospace(), stop_ufpp(), and m_strings::substitute().
doop()
subroutine m_fpp::doop (character(len=g_line_length) line, integer ipos1, integer ipos2)
References false(), g_dc, getval(), m_strings::nospace(), rewrit(), and true().
else()
subroutine m_fpp::else (character(len=*) verb, character(len=*) opts, integer noelse, logical eb)
References false(), g_condop, g_nestl, g_source, g_write, if(), stop_ufpp(), and true().
endif()
subroutine m_fpp::endif (integer, intent(out) noelse, logical, intent(out) eb)
References else(), false(), g_condop, g_nestl, g_source, g_write, stop_ufpp(), and true().
eval()
subroutine m_fpp::eval (character(len=g_line_length) line)
References doop(), g_dc, g_source, logic(), math(), parens(), and stop_ufpp().
exe()
subroutine m_fpp::exe ()
References define(), g_source, g_system_on, g_write_what, m_strings::nospace(), m_debug::stderr(), and stop_ufpp().
findit()
subroutine m_fpp::findit (character(len=g_line_length) line)
References file(), g_inc_count, g_inc_files, and stop_ufpp().
format_g_man()
subroutine m_fpp::format_g_man ()
References g_comment_style, g_iout, g_man, m_strings::isalpha(), m_strings::lower(), m_strings::split(), m_debug::stderr(), stop_ufpp(), m_strings::substitute(), and m_strings::upper().
get_integer_from_string()
integer function m_fpp::get_integer_from_string (character(len=*), intent(in) line, integer, intent(in) ipos1, integer, intent(in) ipos2)
References g_defval, g_defvar, g_numdef, g_source, and stop_ufpp().
getdatetimestr()
character(len=17) function m_fpp::getdatetimestr ()
getval()
subroutine m_fpp::getval (character(len=g_line_length), intent(in) line, integer, intent(in) ipos1, integer, intent(in) ipos2, character(len=g_var_len), intent(out) value)
References g_defval, g_defvar, g_numdef, g_source, g_var_len, and stop_ufpp().
help_usage()
subroutine m_fpp::help_usage (logical, intent(in) l_help)
References false(), and stop().
help_version()
subroutine m_fpp::help_version (logical, intent(in) l_version)
NAME
ufpp(1) - [DEVELOPER] pre-process FORTRAN source files
SYNOPSIS
ufpp  [[-D] define_list]
      [-I include_directories]
      [-i input_file(s)]
      [-o output_file]
      [-html]
      [-system]
      [-verbose]
      [-prefix character_ADE]
      [-keeptabs]
      [-noenv]
      [-width n]
      [-d ignore|remove|blank]
      [-cstyle default|doxygen]
      [-version]
      [-help [-html]]
OPTIONS
define_list, -D define_list An optional space-delimited list of expressions used to define variables before file processing commences. -i input_files The default input file is stdin. Filenames are space-delimited. In a list, @ represents stdin. -o output_file The default output file is stdout. -I include_directories The directories to search for files specified on $INCLUDE directives. -prefix ADE|letter The default directive prefix character is "$". Alternatives may be specified by providing an ASCII Decimal Equivalent (Common values are 37=% 42=* 35=# 36=$ 64=@). If the value is not numeric it is assumed to be a literal character. -html Assumes the input file is HTML that follows the following rules:
Input lines are not output until a simple < X'//'MP> directive is found.
Output stops when a simple < /X'//'MP> directive is encountered. This allows code to be maintained as part of an HTML document.
-help [-html] Display documentation and exit. If "-html" is present, write documentation as basic HTML, instead of as a text file. -verbose All commands on a $SYSTEM directive are echoed to stderr with a + prefix. Text following the string "@(#)" is printed to stderr similar to the Unix command what(1) but is otherwise treated as other text input.
-noenv The $IFDEF and $IFNDEF directives test for an internal ufpp(1) variable and then an environment variable by default. This option turns off testing for environment variables. -system Allow system commands on $SYSTEM directives to be executed. -keeptabs By default tab characters are expanded assuming a stop has been set every eight columns; and trailing carriage-return characters are removed. Use this flag to prevent this processing from occurring. -cstyle try to style comments generated in $FILTER blocks for other utilities such as doxygen. Default is to prefix lines with '!!'. Allowed keywords are currently "default", "doxygen". -d ignore|remove|blank Enable special treatment for lines beginning with "d" or "D" The letter will be left as-is (the default); removed; or replaced with a blank character. This non-standard syntax has been used to support the optional compilation of "debug" code by many Fortran compilers when compiling fixed-format Fortran source. -version Display version and exit -width n Maximum line length of the output file. Default is 1024. Typically used to trim fixed-format FORTRAN code that contains comments or "ident" labels past column 72 when compiling fixed-format Fortran code.
DEFINITION
By default the stand-alone pre-processor ufpp(1) will interpret lines with
"$" in column one, and will output no such lines. Other input is
conditionally written to the output file based on the directives encountered
in the input.
The syntax for the control lines is as follows:
  $DEFINE   variable_name[=expression]                 [! comment ]
  $ERROR    message_to_stderr                          [! comment ]
  $IF       {constant LOGICAL expression}              [! comment ]
   or
  $IFDEF    {variable_name}                            [! comment ]
   or
  $IFNDEF   {variable_name}                            [! comment ]
            { sequence of source statements}
  [$ELSEIF  {constant LOGICAL expression}              [! comment ]
            { sequence of source statements}]
  [$ELSE                                               [! comment ]
            { sequence of source statements}]
  $ENDIF                                               [! comment ]
  $IDENT    metadata                                   [! comment ]
  $@(#)     metadata                                   [! comment ]
  $INCLUDE  filename                                   [! comment ]
  $OUTPUT   filename  [-append]                        [! comment ]
  $FILTER   [comment|write|help|version|shell [-cmd NAME]]
            [-append] [-file NAME]                     [! comment ]
  $DOCUMENT is a synonym for $FILTER
  $PRINTENV predefined_name|environment_variable_name  [! comment ]
  $SHOW                                                [! comment ]
  $STOP {stop_value}                                   [! comment ]
  $SYSTEM system_command                               [! comment ]
  $UNDEFINE variable_name                              [! comment ]
  $WARNING  message_to_stderr                          [! comment ]
  $MESSAGE  message_to_stderr                          [! comment ]
Compiler directives are specified by a "$" in column one, followed by a
keyword.
An exclamation character on a valid directive begins an in-line comment
that is terminated by an end-of-line.
Any LOGICAL expression composed of integer constants, parameters
and operators, is valid. Operators are
  .NOT.  .AND.  .OR.  .EQV.  .NEQV.  .EQ.  .NE.  .GE.
  .GT.   .LE.   .LT.  +      -       *     /     (
  )      **
DIRECTIVES
$DEFINE variable_name [=expression]
A $DEFINE may appear anywhere in a source file. If the value is ".TRUE."
or ".FALSE." then the parameter is of type LOGICAL, otherwise the
parameter is of type INTEGER and the value must be an INTEGER. If no
value is supplied, the parameter is of type INTEGER and is given the
value 1.
Constant parameters are defined from the point they are encountered in a
$DEFINE directive until program termination unless explicitly
undefined with a $UNDEFINE directive.
Example:
 $define A=1
 $define B=1
 $define C=2
 $if ( A + B ) / C .eq. 1
    (a+b)/c is one
 $endif
$ERROR message
Write message to stderr and display program condition and exit program.
$IF/$ELSEIF/$ELSE/$ENDIF directives
Each of the control lines delineates a block of FORTRAN source. If the
expression following the $IF is ".TRUE.", then the lines of FORTRAN
source following are output. If it is ".FALSE.", and an $ELSEIF
follows, the expression is evaluated and treated the same as the $IF. If
the $IF and all $ELSEIF expressions are ".FALSE.", then the lines of
source following the $ELSE are output. A matching $ENDIF ends the
conditional block.
$IFDEF/$IFNDEF directives
$IFDEF and $IFNDEF are special forms of the $IF directive that simply test
if a variable name is defined or not. Essentially, these are equivalent:
  $IFDEF varname  ==> $IF DEFINED(varname)
  $IFNDEF varname ==> $IF .NOT. DEFINED(varname)
except that environment variables are tested as well if the -noenv option
is not specified.
$IDENT metadata [-language fortran|c|shell]
Writes a line using SCCS-metadata format of the following forms:
  language:
  fortran   character(len=*),parameter::ident="@(#)metadata"
  c         #ident "@(#)metadata"
  shell     #@(#) metadata
This string is generally included for use with the what(1) command.
The default language is fortran. Depending on your compiler, the
optimization level used when compiling, these strings may or may not
remain in the object files and executables created.
Do not use the characters double-quote, greater-than, backslash (">\)
in the metadata; do not use strings starting with " -" either.
$INCLUDE filename
Nested read of specified input file. Fifty (50) nesting levels are allowed.
$OUTPUT filename [-append]
Specify the output file to write to. Overrides the initial output file
specified with command line options. If no output filename is given
revert back to initial output file. @ is a synonym for stdout.
   -append [.true.|.false]
Named files open at the beginning by default. Use the -append switch to
append to the end of an existing file instead of overwriting it.
$PRINTENV name
If the name of an uppercase environment variable is given the value
of the variable will be placed in the output file. If the value is a
null string or if the variable is undefined output will be stopped.
This allows the system shell to generate code lines. This is usually
used to pass in information about the compiler environment. For
example:
  # If the following command were executed in the bash(1) shell...
   export STAMP="      write(*,*)''COMPILED ON:`uname -s`;AT `date`''"
the environment variable STAMP would be set to something like
  write(*,*)''COMPILED ON:Eureka;AT Wed, Jun 12, 2013  8:12:06 PM''
A version number would be another possibility
  export VERSION="      program_version=2.2"
Special predefined variable names are:
  Variable Name      Output
  UFPP_DATE  ......  UFPP_DATE="12:58 14Jun2013"
  Where code is assumed to have defined UFPP_DATE as CHARACTER(LEN=15)
  UFPP_FILE  ......  UFPP_FILE="current filename"
  Where code is assumed to have defined UFPP_FILE as CHARACTER(LEN=1024)
  UFPP_LINE  ......  UFPP_LINE=    nnnnnn
  Where code is assumed to have defined UFPP_LINE as INTEGER
This example shows one way how an environment variable can be turned
into a write statement
  $document write
  $ifdef HOME
  $printenv HOME
  $else
     HOME not defined
  $endif
  $document end
Sample output
  write(io,'(a)')'/home/urbanjs/V600'
$FILTER [comment|write|help|version|shell[ -cmd COMMAND]] [-file NAME][! comment]
   COMMENT:  write text prefixed by two exclamations and a space
   WRITE:    write text as Fortran WRITE(3f) statements
   HELP:     write text as a subroutine called HELP_USAGE
   VERSION:  write text as a subroutine called HELP_VERSION
             prefixing lines with @(#) for use with the what(1) command.
   NULL:     Do not write to output file
   SHELL:    run text in block as a shell and replace with the stdout
             generated by the shell. The shell may be specified by the -cmd
             option. The default shell is bash(1).
   END:      End block of documentation
Causes documentation to be altered in output so it is easily maintained as
plain text. This is useful for keeping help text or man pages as part of a
source file.
It is assumed the output will not generate lines over 132 columns. FORTRAN is
currently the only language supported. A blank value also returns to normal
output processing. The Fortran generated is free-format Fortran 2003.
So the text can easily be processed by other utilities such as markdown(1)
or txt2man(1) to produce man(1) pages and HTML documents the file can be
written as-is to $UFPP_DOCUMENT_DIR/doc/NAME with the -file parameter. If the
environment variable $UFPP_DOCUMENT_DIR is not set the option is ignored.
$SHOW
Shows current state of ufpp(1); including variable names and values; and
the name of the current input files. All output is preceded by an
exclamation character.
Example:
 ufpp A=10 B C D -o paper
 $define z=22
 $show
 $stop
 !======================================================================
 ! *ufpp* CURRENT STATE
 ! *ufpp*    TOTAL LINES READ ............          2
 ! *ufpp*    CONDITIONAL_NESTING_LEVEL....   0
 ! *ufpp*    DATE......................... 11:18 21Jun2013
 ! *ufpp*    ARGUMENTS ................... A=10 B C D -o paper
 ! *ufpp* VARIABLES:
 ! *ufpp*    ! A                               !          10
 ! *ufpp*    ! B                               !           1
 ! *ufpp*    ! C                               !           1
 ! *ufpp*    ! D                               !           1
 ! *ufpp*    ! Z                               !          22
 ! *ufpp* OPEN FILES:
 ! *ufpp*    ! ---- ! UNIT ! LINE NUMBER ! FILENAME
 ! *ufpp*    !    1 !    5 !           2 !
 !======================================================================
$STOP stop-value
Stops input file processing. An optional integer value of 1 to 20 will be
returned as a status value to the system where supported. A value of zero
is returned if no value is specified.
$SYSTEM system_command
If system command processing is enabled using the -system switch system
commands can be executed to create files to be read or to execute test
programs, for example. $SYSTEM directives are ignored by default; as you
clearly need to ensure the input file is trusted before allowing commands
to be executed.
Examples:
 $! build variable definitions using GNU/Linux commands
 $SYSTEM echo system=`hostname` > compiled.h
 $SYSTEM echo compile_time="`date`" >> compiled.h
 $INCLUDE compiled.h
 $! obtain up-to-date copy of source file from HTTP server:
 $SYSTEM wget http://repository.net/src/func.F90 -O -|
 cpp -P -C -traditional >_tmp.f90
 $INCLUDE _tmp.f90
 $SYSTEM  rm _tmp.f90
$UNDEFINE variable_name
A symbol defined with $DEFINE can be removed with the $UNDEFINE
directive.
DEFINED(variable_name)
A special function called DEFINED() may appear only in a $IF or $ELSEIF.
If "variable_name" has been defined at that point in the source code,
then the function value is ".TRUE.", otherwise it is ".FALSE.". A name is
defined only if it has appeared in the source previously in a $DEFINE
directive or been declared on the command line.
The names used in compiler directives are district from names in the
FORTRAN source, which means that "a" in a $DEFINE and "a" in a FORTRAN
source statement are totally unrelated.
The DEFINED() parameter is NOT valid in a $DEFINE directive.
Example:
 >        Program test
 > $IF .NOT. DEFINED (inc)
 >        INCLUDE ''comm.inc''
 > $ELSE
 >        INCLUDE ''comm2.inc''
 > $ENDIF
 >        END
The file, "comm.inc" will be INCLUDEd in the source if the parameter,
"inc", has not been previously defined, while INCLUDE "comm2.inc" will
be included in the source if "inc" has been previously defined. This is
useful for setting up a default inclusion.
$WARNING message
Write message to stderr of form "WARNING message"
$MESSAGE message
Write message to stderr of form "message"
LIMITATIONS
$IF constructs can be nested up to 20 levels deep. Note that using
more than two levels typically makes input files less readable.
$FILTER END is required after a $FILTER or -file FILENAME is not written
and output of a shell is not read.
Nesting of $FILTER sections not allowed.
Messages for $MESSAGE, $WARNING, $ERROR cannot contain an exclamation
Input files
o lines are limited to 1024 columns. Text past column 1024 is ignored. o files currently opened cannot be opened again. o a maximum of 50 files can be nested by $INCLUDE o filenames cannot contain spaces on the command line.
Variable names
o cannot be redefined unless first undefined. o are limited to 31 characters. o must start with a letter (A-Z). o are composed of the letters A-Z, digits 0-9 and _ and $. o 2048 variable names may be defined at a time.
Major cpp(1) features not present in ufpp(1):
There are no predefined preprocessor symbols. Use a directive input file instead. The predefined variables such as UFPP_DATE can be used as a substitute in some cases.
This program does not provide string (macro) substitution in output lines. See cpp(1) and m4(1) and related utilities if macro expansion is required.
While cpp(1) is the de-facto standard for preprocessing Fortran code, Part 3 of the Fortran 95 standard (ISO/IEC 1539-3:1998) defines Conditional Compilation, but it is (currently) not widely supported (See coco(1)).
ENVIRONMENT
The environment variable $DEFAULT_ufpp can change command defaults.
The values for -i, -I, and defined variables from $DEFAULT_ufpp will be
prepended to the list defined on the command line. Other switches will be
replaced by values on the command line. For example:
   env DEFAULT_ufpp="CRAY 64BIT -html -d -I CRAY_DIR" ufpp A=10 -i f90.html
would run the same as the command
   ufpp CRAY 64BIT A=10 -html -d -I CRAY_DIR -i f90.html
Overriding command defaults can be very useful when builds are done using
make(1) files and/or scripts; as platform-specific and debug options can
be evoked without changing the build-related files.
EXAMPLES
Define variables on command line:
Typically, variables are defined on the command line when ufpp(1) is invoked
or are grouped together into small files that are included with a $INCLUDE
or as input files.
  ufpp HP size=64 -i hp_directives.dirs @ test.F90 -o test_out.f90
defines variables HP and SIZE as if the expressions had been on a $DEFINE
and reads file "hp_directives.dirs" and then stdin and then test.F90.
Output is directed to test_out.f90
Basic conditionals:
>$! set value of variable "a" if it is not specified on the ufpp(1) command. >$IF .NOT.DEFINED(A) >$DEFINE a=1 ! define only the first version of SUB1(3f) >$ENDIF >program conditional_compile > use M_kracken, only : kracken, lget > ! use M_kracken module to crack command line arguments > call kracken("cmd","-help .false. -version .false.") > ! call routine generated by $FILTER HELP > call help_usage(lget("cmd_help")) > ! call routine generated by $FILTER VERSION > call help_version(lget("cmd_version")) > call sub1() >end program conditional_compile >! select a version of SUB1 depending on the value of ufpp(1) variable "a" >$IF a .EQ. 1 >subroutine sub1 > print*, "This is the first SUB1" >end subroutine sub1 >$ELSEIF a .eq. 2 >subroutine sub1 > print*, "This is the second SUB1" >end subroutine sub1 >$ELSE >subroutine sub1 > print*, "This is the third SUB1" >end subroutine sub1 >$ENDIF >$! generate help_usage() procedure (and file to run thru txt2man(1) or other >$! filters to make man(1) page if $UFPP_DOCUMENT_DIR is set). >$FILTER HELP -file conditional_compile.man >NAME > conditional_compile - basic example for ufpp(1) pre-processor. >SYNOPSIS > conditional_example [–help] [–version] >DESCRIPTION > This is a basic example program showing how documentation can be used > to generate program help text >OPTIONS > –help > display this help and exit > –version > output version information and exit >$FILTER END >$! generate help_version() procedure >$FILTER VERSION >DESCRIPTION: example program showing conditional compilation with ufpp(1) >PROGRAM: conditional_compile >VERSION: 1.0, 20160703 >AUTHOR: John S. Urban >$FILTER END
References false(), and stop().
ident()
subroutine m_fpp::ident (character(len=*) opts)
References m_kracken::dissect(), g_iout, g_source, m_kracken::sget(), and stop_ufpp().
if()
subroutine m_fpp::if (character(len=*) opts, integer, intent(out) noelse, logical eb)
References eval(), false(), g_condop, g_dc, g_defval, g_defvar, g_nestl, g_nestl_max, g_numdef, g_source, g_var_len, g_write, ifdef(), m_strings::nospace(), parens(), stop_ufpp(), and true().
ifdef()
subroutine m_fpp::ifdef (character(len=g_line_length) line, integer ipos1)
References false(), g_dc, g_defvar, g_numdef, g_source, g_var_len, stop_ufpp(), and true().
include()
subroutine m_fpp::include (character(len=g_line_length), intent(in) line, integer, intent(in) iunit)
References debug(), file(), findit(), g_file_dictionary, g_iocount, g_source, stderr(), stop_ufpp(), and unit().
includes()
subroutine m_fpp::includes ()
References g_inc_count, and g_inc_files.
logic()
subroutine m_fpp::logic (character(len=*) line, integer, intent(in) ipos1, integer, intent(in) ipos2)
References false(), g_dc, in, loop, rewrit(), stop_ufpp(), and trufal().
math()
subroutine m_fpp::math (character(len=g_line_length) line, integer ipos1, integer ipos2)
References domath(), and m_strings::nospace().
name()
subroutine m_fpp::name (character(len=*) line)
References g_source, g_var_len, and stop_ufpp().
opens()
subroutine m_fpp::opens ()
References g_inc_count, g_inc_files, g_line_length, g_source, and include().
output_case()
subroutine m_fpp::output_case (character(len=*) opts)
References m_kracken::dissect(), else(), file(), g_iout, g_iout_init, g_write_what, m_kracken::lget(), m_kracken::sget(), stop_ufpp(), then(), and unit().
parens()
subroutine m_fpp::parens (character(len=g_line_length) line)
References doop(), g_source, logic(), math(), m_strings::nospace(), and stop_ufpp().
print_comment_block()
subroutine m_fpp::print_comment_block ()
References file(), format_g_man(), g_man, g_man_file, g_man_file_position, g_man_print, m_debug::stderr(), stop_ufpp(), m_system::system_stat(), and unit().
printenv()
subroutine m_fpp::printenv (character(len=*) opts)
References g_file_dictionary, g_iocount, g_outline, g_source, getdatetimestr(), stop_ufpp(), and write_out().
rewrit()
subroutine m_fpp::rewrit (character(len=g_line_length) line, character(len=*) temp, integer j, integer j1, integer l, integer l1)
stop()
subroutine m_fpp::stop (character(len=*) opts)
References m_debug::fstop(), g_source, get_integer_from_string(), and stop_ufpp().
stop_ufpp()
subroutine m_fpp::stop_ufpp (character(len=*), intent(in) message)
References debug(), g_source, stderr(), and stop().
stops()
subroutine m_fpp::stops (integer, intent(in) iexit)
References stop().
trufal()
logical function m_fpp::trufal (character(len=g_line_length), intent(in) line, integer, intent(in) ipos1, integer, intent(in) ipos2)
References false(), g_defval, g_defvar, g_numdef, g_source, stop_ufpp(), and true().
undef()
subroutine m_fpp::undef (character(len=*) opts)
References g_defval, g_defvar, g_numdef, g_source, and stop_ufpp().
write_arguments()
subroutine m_fpp::write_arguments ()
References g_iout, and write_out().
write_out()
subroutine m_fpp::write_out (character(len=*), intent(in) line)
References false(), g_html_switch, g_llwrite, g_write_what, true(), and www().
www()
subroutine m_fpp::www (character(len=*), intent(in) line)
References g_comment_count, g_fp, g_iout, g_iwidth, g_man, g_man_collect, g_outtype, g_source, and stop_ufpp().
Variable Documentation
g_comment_count
integer, public m_fpp::g_comment_count =0
g_comment_style
character(len=10), public m_fpp::g_comment_style =' '
g_condop
logical, dimension(0:g_nestl_max), save, public m_fpp::g_condop
g_dc
logical, public m_fpp::g_dc
g_defval
character(len=g_var_len), dimension(num), public m_fpp::g_defval
g_defvar
character(len=g_var_len), dimension(num), public m_fpp::g_defvar
g_file_dictionary
type(file_stack), dimension(50) m_fpp::g_file_dictionary
g_fp
type(streampointer) m_fpp::g_fp
g_html_switch
logical, save, public m_fpp::g_html_switch =.false.
g_ihelp
integer, public m_fpp::g_ihelp =OUTPUT_UNIT
g_inc_count
integer, public m_fpp::g_inc_count =0
g_inc_files
character(len=g_line_length), dimension(50), public m_fpp::g_inc_files
g_io_total_lines
integer, public m_fpp::g_io_total_lines =0
g_iocount
integer, public m_fpp::g_iocount =0
g_iout
integer, public m_fpp::g_iout
g_iout_init
integer, save, public m_fpp::g_iout_init
g_iwidth
integer, public m_fpp::g_iwidth
g_line_length
integer, parameter, public m_fpp::g_line_length =4096
g_llwrite
logical, public m_fpp::g_llwrite =.true.
g_man
character(len=:), allocatable, save m_fpp::g_man
g_man_collect
logical, save m_fpp::g_man_collect =.false.
g_man_file
character(len=:), allocatable m_fpp::g_man_file
g_man_file_position
character(len=10) m_fpp::g_man_file_position ='ASIS '
g_man_print
logical, save m_fpp::g_man_print =.false.
g_nestl
integer, public m_fpp::g_nestl =0
g_nestl_max
integer, parameter, public m_fpp::g_nestl_max =20
g_noenv
logical, public m_fpp::g_noenv =.false.
g_numdef
integer, public m_fpp::g_numdef =0
g_outline
character(len=g_line_length), public m_fpp::g_outline
g_outtype
character(len=10), public m_fpp::g_outtype ='asis'
g_scratch_filename
character(len=:), allocatable m_fpp::g_scratch_filename
g_source
character(len=g_line_length), public m_fpp::g_source
g_system_on
logical, save, public m_fpp::g_system_on =.false.
g_var_len
integer, parameter, public m_fpp::g_var_len =31
g_write
logical, public m_fpp::g_write =.true.
g_write_what
logical, save, public m_fpp::g_write_what =.false.
num
integer, parameter m_fpp::num =2048