GeneralPurposeFortran: m_journal Module Reference
m_journal Module Reference
Data Types
interface journal
NAME
journal(3f) - [M_journal] provides public message routine, no paging or graphic mode change"
SYNOPSIS
Functions/Subroutines
subroutine write_msg (where, msg)
subroutine set_stdout (iounit)
subroutine change_model (value, mode)
subroutine wm (message)
subroutine wm_r (where, message, value)
subroutine wm_l (where, message, truefalse)
subroutine wm_d (where, message, dvalue)
subroutine wm_i (where, message, ival)
Variables
character(len= *), parameter ident ="@(#)M_journal::journal(3fg): provides public message routine, no paging or graphic mode change"
integer, save, private stdout =OUTPUT_UNIT
logical, save debug =.false.
integer, save last_int =0
Function/Subroutine Documentation
change_model()
subroutine m_journal::change_model (logical, intent(in) value, character(len=*), intent(in) mode) private
References debug, and write_msg().
set_stdout()
subroutine m_journal::set_stdout (integer, intent(in) iounit) private
References stdout.
wm()
subroutine m_journal::wm (character(len=*), intent(in) message) private
References write_msg().
wm_d()
subroutine m_journal::wm_d (character(len=*), intent(in) where, character(len=*), intent(in) message, doubleprecision, intent(in) dvalue) private
References write_msg().
wm_i()
subroutine m_journal::wm_i (character(len=*), intent(in) where, character(len=*), intent(in) message, integer, intent(in) ival) private
References last_int, and write_msg().
wm_l()
subroutine m_journal::wm_l (character(len=*), intent(in) where, character(len=*), intent(in) message, logical, intent(in) truefalse) private
References write_msg().
wm_r()
subroutine m_journal::wm_r (character(len=*), intent(in) where, character(len=*), intent(in) message, real, intent(in) value) private
References write_msg().
write_msg()
subroutine m_journal::write_msg (character(len=*), intent(in) where, character(len=*), intent(in) msg) private
References debug, false(), file(), form, last_int, now_ex(), stdout, true(), and unit().
Variable Documentation
debug
logical, save m_journal::debug =.false. private
ident
character(len=*), parameter m_journal::ident ="@(#)M_journal::journal(3fg): provides public message routine, no paging or graphic mode change" private
last_int
integer, save m_journal::last_int =0 private
stdout
integer, save, private m_journal::stdout =OUTPUT_UNIT private