GeneralPurposeFortran: m_math Module Reference
m_math Module Reference
Data Types
interface invert_2x2
NAME
invert_2x2(3f) - [M_math] directly invert 2x2 matrix
interface invert_3x3
NAME
interface invert_4x4
NAME
invert_4x4(3f) - [M_math] directly invert 4x4 matrix
Functions/Subroutines
subroutine, public julfit (x, y, ixn, itype, a, b, r2)
NAME
julfit(3f) - [M_math:fit] linear least squares curve fits , destroys input arrays
subroutine, public julfit1 (x, y, ixn, a, b, r2)
NAME
julfit1(3f) - [M_math:fit] internal routine for linear least square fit(y=a*x+b), changes the y array
SYNOPSIS
subroutine, public lowess (x, y, n, f, nsteps, delta, ys, rw, res)
NAME
lowess(3f) - [M_math:fit] procedures for locally weighted regression
subroutine lowest (x, y, n, xs, ys, nleft, nright, w, userw, rw, ok)
subroutine, public splift (X, Y, YP, YPP, N, ierr, a1, b1, an, bn)
NAME
splift(3f) - [M_math:fit] fits a spline to the n data points given in x and y and also returns first and second derivatives
SYNOPSIS
subroutine, public splint (x, y, ypp, n, xi, yi, ypi, yppi, ni, kerr)
NAME
splint(3f) - [M_math:fit] interpolates and twice differentiates a cubic spline
SYNOPSIS
subroutine, public linearint (X, Y, N, XI, YI, NI, KERR)
NAME
linearint(3f) - [M_math:fit] interpolates a curve defined by X(i),Y(i) using linear interpolation at given XI(j) values
SYNOPSIS
subroutine, public citer (A, R, H, S, C, DADH)
NAME
citer(3f) - [M_math:geometry] determine various geometric properties of circle segment given radius and area of the segment.
SYNOPSIS
subroutine, public envelope (x, y, n, vertex, nvert)
NAME
envelope(3f) - [M_math:geometry] Find vertices (in clockwise order) of a polygon enclosing the points (x(i), y(i), i=1, ..., n.
SYNOPSIS
logical function, public inpolygon (XIN, YIN, XCONV, YCONV, NCONV)
NAME
inpolygon(3f) - [M_math:geometry] determine whether or not an integer point is in an integer polygon
subroutine, public locpt (x0, y0, x, y, n, l, m)
NAME
locpt - [M_math:geometry] find if a point is inside a polygonal path
SYNOPSIS
subroutine, public poly_intercept (a, b, x, y, n, u, v, m, num, ierr)
NAME
poly_intercept(3f) - [M_math:geometry] intersection of a straight line and polygonal path
SYNOPSIS
real function, public polyarea (x, y)
NAME
polyarea(3f) - [M_math:geometry] compute the area bounded by a closed polygonal curve
subroutine, public extremum (array, small, big)
NAME
extremum(3f) - [M_math:statistics] Finds the minimum and maximum value in a REAL array.
SYNOPSIS
subroutine, public bds (X, N, STAT)
NAME
bds(3f) - [M_math:statistics] Basic Statistical Measures
SYNOPSIS
subroutine, public skekur1 (Y, NHI, YSKEW, YKURT, IOPT)
NAME
skekur1(3f) - [M_math:statistics] variant on calculating skewness and kurtosis of an array
subroutine, public skekurx (Y, N, YSKEW, YKURT)
NAME
skekurx(3f) - [M_math:statistics] Compute unbiased estimator of the population SKEWNESS and KURTOSIS
SYNOPSIS
real function, public stddev (vector, n, avg)
NAME
stddev(3f) - [M_math:statistics] given a real vector and the vector average calculate the standard deviation
SYNTAX
function stddev(vector,n,avg)
logical function, public almost (x, y, digits, verbose)
NAME
almost(3f) - [M_math] return true or false if two numbers agree up to specified number of digits
SYNOPSIS
subroutine, public accdig (X, Y, digi0, ACURCY, IND)
NAME
accdig(3f) - [M_math] compare two real numbers only up to a specified number of digits
subroutine, public dp_accdig (X, Y, digi0, ACURCY, IND)
NAME
dp_addig(3f) - [M_math] compare two DOUBLEPRECISION numbers only up to a specified number of digits
elemental pure logical function, public in_margin (expected_value, measured_value, allowed_margin)
NAME
in_margin(3f) - [M_math] check if two reals are approximately equal using a relative margin
real(kind=dp) function, public round (val, idigits0)
subroutine, public scale1 (xmin0, xmax0, n0, xminp, xmaxp, dist)
NAME
scale1(3f) - [M_math] find new range xminp xmaxp divisible into approximately n linear intervals of size dist
subroutine, public scale3 (xmin0, xmax0, n0, xminp, xmaxp, dist)
NAME
scale3(3f) - [M_math] find nice log range
subroutine, public quadratic (a, b, c, z1, z2, discriminant)
NAME
quadratic(3f) - [M_math] calculate the roots of a quadratic formula even if they are complex
pure real(kind=wp) function, dimension(2, 2) double_invert_2x2 (A)
pure real(kind=wp) function, dimension(3, 3) double_invert_3x3 (A)
pure real(kind=wp) function, dimension(4, 4) double_invert_4x4 (A)
pure integer(kind=wp) function, dimension(2, 2) integer_invert_2x2 (A)
pure integer(kind=wp) function, dimension(3, 3) integer_invert_3x3 (A)
pure integer(kind=wp) function, dimension(4, 4) integer_invert_4x4 (A)
pure real(kind=wp) function, dimension(2, 2) real_invert_2x2 (A)
pure real(kind=wp) function, dimension(3, 3) real_invert_3x3 (A)
pure real(kind=wp) function, dimension(4, 4) real_invert_4x4 (A)
pure complex(kind=wp) function, dimension(2, 2) complex_invert_2x2 (A)
pure complex(kind=wp) function, dimension(3, 3) complex_invert_3x3 (A)
pure complex(kind=wp) function, dimension(4, 4) complex_invert_4x4 (A)
Function/Subroutine Documentation
accdig()
subroutine, public m_math::accdig (real, intent(in) X, real, intent(in) Y, real, intent(in) digi0, real, intent(out) ACURCY, integer, intent(out) IND)
NAME
accdig(3f) - [M_math] compare two real numbers only up to a specified number of digits
SYNOPSIS
   subroutine accdig(x,y,rdgits,acurcy,ind)
    real,intent(in)     :: X
    real,intent(in)     :: Y
    real,intent(in)     :: DIGI0
    real,intent(out)    :: acurcy
    integer,intent(out) :: ind
DESCRIPTION
This procedure is used to check how closely two numbers agree.
   call accdig(X,Y,DIGI0,ACURCY,IND)
the values X and Y are the numbers to compare, and DIGI0 is the
threshold number of digits to consider significant in returning IND.
If X and Y are considered equal within DIGI0 relative tolerance,
    IND    = 0, if tolerance is     satisfied.
           = 1, if tolerance is not satisfied.
The result ACURCY gives a measure of the number of leading digits in X
which are the same as the number of leading digits in Y.
        ACURCY=-log10((X-Y)/Y)   if X != Y and Y != 0
        ACURCY=-log10(X-Y)       if X != Y and Y = 0
        ACURCY=8                 if X=Y
        ACURCY is never less than -8 or greater than 8
TOLERANCE ...
     X and Y are considered equal within DIGI0 relative tolerance,
     if ACURCY is greater than DIGI0.
For example, Take some numbers and compare then  to 1.2345678 ...
   ================================================
   A number     |    ACURCY       |   ACURCY
                |    1.2345678=Y  |   1.2345678=X
   ================================================
    1.234680    |    3.7900571    |   3.7901275
    1.2345378   |    4.6144510    |   4.6144404
    2.2234568   |    0.096367393  |   0.35188114
    1.2345678   |    8.0000000    |   8.0000000
    1.2345679   |    7.0732967    |   7.0731968
   -1.2345678   |   -0.30103000   |  -0.30103000
   76.234567    |   -1.7835463    |   0.0070906729
    2.4691356   |    0.0          |   0.3010300
    0.0         |    0.0          |  -0.91514942.
Due to the typical limits of the log function, the number of
significant digits in the result is best considered to be three.
Notice that 1.2345678=Y produces different values than 1.2345678=X
A negative result indicates the two values being compared either do
not agree in the first digit or they differ with respect to sign. An
example of two numbers which do not agree in their leading digit (and
actually differ in order of magnitude) is given above by X=76.234567
and Y=1.2345678; the accuracy reported is -1.7835463. An example of
two numbers which do not agree in sign in X=-1.2345678 and Y=1.2345678;
here the accuracy reported is -0.30103000.
EXAMPLE
Example program:
program demo_accdig ! fortran 90 example use M_math, only : accdig integer digi real vals(9) data vals/ & &1.234680, 1.2345378, 2.2234568, 1.2345678, & &1.2345679, -1.2345678, 76.234567, 2.4691356, & &0.0/ write(*,*)'=========================' do i10=0,16 a=1.0 b=a+1.0/(10**i10) call accdig(a,b,8.0,acurcy,ind) write(*,*)i10,a,b,acurcy,ind enddo write(*,*)'=========================' digi=16 do i20=0,digi a=1.0 b=a+1.0/(10**i20) call accdig(a,b,real(digi),acurcy,ind) write(*,*)i20,a,b,acurcy,ind enddo write(*,*)'=========================' do i30=1,9 call accdig(1.2345678,vals(i30),8.0,acurcy1,ind1) call accdig(vals(i30),1.2345678,8.0,acurcy2,ind2) write(*,*)i30,vals(i30),acurcy1,acurcy2,ind1,ind2 enddo end program demo_accdig
NOTES
REFERENCES
based on ...
NBS OMNITAB 1980 VERSION 6.01 1/ 1/81. accdig V 7.00 2/14/90. ** David Hogben, Statistical Engineering Division, Center for Computing and Applied Mathematics, A337 Administration Building, National Institute of Standards and Technology, Gaithersburg, MD 20899 TELEPHONE 301-975-2845 ORIGINAL VERSION - October, 1969. CURRENT VERSION - February, 1990. JSU VERSION - February, 1991.
DEPENDENCIES
o M_journal(),log10(), abs(1)
FILES
o libGPF.a
LEGAL RESTRICTIONS
none
QA
o Authors: David Hogben, John S. Urban
almost()
logical function, public m_math::almost (real, intent(in) x, real, intent(in) y, real, intent(in) digits, logical, intent(in), optional verbose)
NAME
almost(3f) - [M_math] return true or false if two numbers agree up to specified number of digits
SYNOPSIS
function almost(x,y,digits) real,intent(in) :: x,y real,intent(in) :: rdigits
DESCRIPTION
Returns true or false depending on whether the two numbers given agree to within the specified number of digits as calculated by ACCDIG(3f).
EXAMPLE
References accdig(), false(), and true().
bds()
subroutine, public m_math::bds (real, dimension(n), intent(in) X, integer, intent(in) N, real, dimension(13), intent(out) STAT)
NAME
bds(3f) - [M_math:statistics] Basic Statistical Measures
SYNOPSIS
subroutine bds(x,n,stat)
integer,intent(in) :: n real,intent(in) :: x(n) real,intent(out) :: STAT(13)
DESCRIPTION
 Given a vector of real values calculate common basic statistical measures for
 the array.
OPTIONS
x REAL input vector of values to determine statistical properties for n size of input vector
RETURNS
stat array of statistical measurements calculated
1.  mean
2.  second moment about the mean
3.  third moment about the mean
4.  fourth moment about the mean
5.  variance
6.  standard deviation
7.  skewness
8.  kurtosis
9.  sum
largest value
smallest value
location of largest value
location of smallest value
DEFINITIONS
MEAN
   A type of average, calculated by dividing the sum of
   a set of values by the number of values.
      mean = Sum(Xi)/N
MEDIAN
   A type of average, found by arranging the values in
   order and then selecting the one in the middle. If the
   total number of values in the sample is even, then the
   median is the mean of the two middle numbers.
MODE
   The most frequent value in a group of values.
VARIANCE
   The average of the square of the distance of each
   data point from the mean
      variance = Sum((Xi-mean)^2))/N
   for a population, or more commonly, for a sample the
   unbiased value is
      variance = Sum((Xi-mean)^2))/(N-1)
STANDARD DEVIATION
   The standard deviation is the square root of the
   variance.
      sd = sqrt(variance)
   It is the most commonly used measure of spread.
SKEWNESS
   Skewness is a measure of symmetry, or more
   precisely, the lack of symmetry. A distribution, or
   data set, is symmetric if it looks the same to the left
   and right of the center point.
      skewness = Sum{(X(i)-mean)^3} /((N-1)*SD^3)
   Where SD is the standard deviation, and N is the number of
   samples. Some sources will use N instead of N-1 or they might
   present the formula in a slightly different mathematically
   equivalent format.
      The skewness of symmetric data is zero
KURTOSIS
   Kurtosis is a measure of whether the data are peaked
   or flat relative to a normal distribution. That is,
   data sets with high kurtosis tend to have a distinct
   peak near the mean, decline rather rapidly, and have
   heavy tails. Data sets with low kurtosis tend to have a
   flat top near the mean rather than a sharp peak. A
   uniform distribution would be the extreme case.
      kurtosis = ( SUM{(X(i)-mean)^4} ) / ((N-1)*SD^4) -3
   The standard normal distribution has a kurtosis of
   zero. Positive kurtosis indicates a "peaked"
   distribution and negative kurtosis indicates a "flat"
   distribution.
 Although often called kurtosis, historically the above expression is
 for "excess kurtosis" because three is subtracted from the value.
 The purpose of this is to give the normal distribution a kurtosis
 of 0. In recent times, the term "excess kurtosis" is often simply
 called "kurtosis", so consider that whether to subtract 3 or not
 is merely a convention, not a right or wrong answer. When using a
 particular program, you just need to be aware of which convention
 Again, another freqent difference is whether they use N in
 the denominator or the bias corrected N-1.
 The formulas for skewness and kurtosis are treated in
    Sokal, R. R., &amp; Rohlf, F. J. (1995).
    Biometry: The principles and practice of statistics in biological
    research. (3rd ed.) New York: W. H. Freeman, pp. 114-115.
 Similar formulas are given in
    Zar, J. H., Biostatistical analysis (3rd ed)., Prentice
    Hall, 1996.
 which refers to "machine formulas" and cites
    Bennett and Franklin, Statistical analysis in chemistry and
    the chemical industry. NY: Wiley, 1954, at p. 81.
EXAMPLES
citer()
subroutine, public m_math::citer (double precision A, double precision R, double precision H, double precision S, double precision C, double precision DADH)
NAME
citer(3f) - [M_math:geometry] determine various geometric properties of circle segment given radius and area of the segment.
SYNOPSIS
Usage:
SUBROUTINE CITER(A,R,H,S,C,DADH) DOUBLEPRECISION,INTENT(IN) :: A,R DOUBLEPRECISION,INTENT(OUT) :: H,S,C,DADH
DESCRIPTION
This subroutine determines various geometric properties of a segment of a circle given the radius of the circle and area of the segment.
The figure below defines the geometry under consideration. This figure was taken directly from page 12 of the CRC Standard Mathematical Tables, 21st Edition, Published by the Chemical Rubber Company, Cleveland, OH. This page of the CRC Standard Mathematical Tables covers Mensuration Formulae for Circles.
In the figure below, the arc labeled "S" is the portion of the circle defined by angle "THETA". "C" is a secant, "H" is the height of the segment between "S" and "C", and "D" is the shortest distance from the center of the circle to the secant "C".
Specifically, this subroutine determines H, S, C, and the derivative of the segment area with respect to H given the radius of the circle, "R", and the area of the segment between "S" and "C".
Diagram:
> _________________ S > /|\ __—*****—__ > | _– –_ > H * * > ___|/___ *_______________________* > /|\ \ C / > | \ / > | \ / > | \ / > | \ / > | \ / > D \ / R > | \ THETA / > | \ / > | \ / > | \ / > ___|/_______________ * >
complex_invert_2x2()
pure complex(kind=wp) function, dimension(2,2) m_math::complex_invert_2x2 (complex(kind=wp), dimension(2,2), intent(in) A) private
complex_invert_3x3()
pure complex(kind=wp) function, dimension(3,3) m_math::complex_invert_3x3 (complex(kind=wp), dimension(3,3), intent(in) A) private
complex_invert_4x4()
pure complex(kind=wp) function, dimension(4,4) m_math::complex_invert_4x4 (complex(kind=wp), dimension(4,4), intent(in) A) private
double_invert_2x2()
pure real(kind=wp) function, dimension(2,2) m_math::double_invert_2x2 (real(kind=wp), dimension(2,2), intent(in) A) private
double_invert_3x3()
pure real(kind=wp) function, dimension(3,3) m_math::double_invert_3x3 (real(kind=wp), dimension(3,3), intent(in) A) private
double_invert_4x4()
pure real(kind=wp) function, dimension(4,4) m_math::double_invert_4x4 (real(kind=wp), dimension(4,4), intent(in) A) private
dp_accdig()
subroutine, public m_math::dp_accdig (doubleprecision, intent(in) X, doubleprecision, intent(in) Y, doubleprecision, intent(in) digi0, doubleprecision, intent(out) ACURCY, integer, intent(out) IND)
NAME
dp_addig(3f) - [M_math] compare two DOUBLEPRECISION numbers only up to a specified number of digits
SYNOPSIS
   subroutine dp_addig(x,y,rdgits,acurcy,ind)
    doubleprecision,intent(in)     :: X
    doubleprecision,intent(in)     :: Y
    doubleprecision,intent(in)     :: DIGI0
    doubleprecision,intent(out)    :: acurcy
    integer,intent(out) :: ind
DESCRIPTION
This procedure is used to check how closely two numbers agree.
   call dp_addig(X,Y,DIGI0,ACURCY,IND)
the values X and Y are the numbers to compare, and DIGI0 is the
threshold number of digits to consider significant in returning IND.
If X and Y are considered equal within DIGI0 relative tolerance,
    IND    = 0, if tolerance is     satisfied.
           = 1, if tolerance is not satisfied.
The result ACURCY gives a measure of the number of leading digits in X
which are the same as the number of leading digits in Y.
        ACURCY=-log10((X-Y)/Y)   if X != Y and Y != 0
        ACURCY=-log10(X-Y)       if X != Y and Y = 0
        ACURCY=8                 if X=Y
        ACURCY is never less than -8 or greater than 8
TOLERANCE ...
     X and Y are considered equal within DIGI0 relative tolerance,
     if ACURCY is greater than DIGI0.
For example, Take some numbers and compare then  to 1.2345678 ...
   ================================================
   A number     |    ACURCY       |   ACURCY
                |    1.2345678=Y  |   1.2345678=X
   ================================================
    1.234680    |    3.7900571    |   3.7901275
    1.2345378   |    4.6144510    |   4.6144404
    2.2234568   |    0.096367393  |   0.35188114
    1.2345678   |    8.0000000    |   8.0000000
    1.2345679   |    7.0732967    |   7.0731968
   -1.2345678   |   -0.30103000   |  -0.30103000
   76.234567    |   -1.7835463    |   0.0070906729
    2.4691356   |    0.0          |   0.3010300
    0.0         |    0.0          |  -0.91514942.
Due to the typical limits of the log function, the number of
significant digits in the result is best considered to be three.
Notice that 1.2345678=Y produces different values than 1.2345678=X
A negative result indicates the two values being compared either do
not agree in the first digit or they differ with respect to sign. An
example of two numbers which do not agree in their leading digit (and
actually differ in order of magnitude) is given above by X=76.234567
and Y=1.2345678; the accuracy reported is -1.7835463. An example of
two numbers which do not agree in sign in X=-1.2345678 and Y=1.2345678;
here the accuracy reported is -0.30103000.
EXAMPLE
Example program:
program demo_dp_addig ! fortran 90 example use M_math, only : dp_addig integer digi real vals(9) data vals/ & &1.234680, 1.2345378, 2.2234568, 1.2345678, & &1.2345679, -1.2345678, 76.234567, 2.4691356, & &0.0/ write(*,*)'=========================' do i10=0,16 a=1.0 b=a+1.0/(10**i10) call dp_addig(a,b,8.0,acurcy,ind) write(*,*)i10,a,b,acurcy,ind enddo write(*,*)'=========================' digi=16 do i20=0,digi a=1.0 b=a+1.0/(10**i20) call dp_addig(a,b,dble(digi),acurcy,ind) write(*,*)i20,a,b,acurcy,ind enddo write(*,*)'=========================' do i30=1,9 call dp_addig(1.2345678,vals(i30),8.0,acurcy1,ind1) call dp_addig(vals(i30),1.2345678,8.0,acurcy2,ind2) write(*,*)i30,vals(i30),acurcy1,acurcy2,ind1,ind2 enddo end program demo_dp_addig
NOTES
REFERENCES
based on ...
NBS OMNITAB 1980 VERSION 6.01 1/ 1/81. dp_addig V 7.00 2/14/90. ** David Hogben, Statistical Engineering Division, Center for Computing and Applied Mathematics, A337 Administration Building, National Institute of Standards and Technology, Gaithersburg, MD 20899 TELEPHONE 301-975-2845 ORIGINAL VERSION - October, 1969. CURRENT VERSION - February, 1990. JSU VERSION - February, 1991.
DEPENDENCIES
o M_journal(),log10(), abs(1)
FILES
o libGPF.a
LEGAL RESTRICTIONS
none
QA
o Authors: David Hogben, John S. Urban
envelope()
subroutine, public m_math::envelope (real, dimension(n), intent(in) x, real, dimension(n), intent(in) y, integer, intent(in) n, integer, dimension(n) vertex, integer nvert)
NAME
envelope(3f) - [M_math:geometry] Find vertices (in clockwise order) of a polygon enclosing the points (x(i), y(i), i=1, ..., n.
SYNOPSIS
subroutine envelope(x, y, n, vertex, nvert)
integer,intent(in) :: n real,intent(in) :: x(n), y(n) integer :: vertex(n), nvert
DESCRIPTION
Given the points composing a polygon find the points required to draw an envelope of the polygon
OPTIONS
x,y the vectors describing the polygon n the number of elements in the input vectors
RETURNS
vertex the number of the vertices needed to generate the envelope nvert number of vertices returned
EXAMPLE
Programmer: Alan Miller VERSION: Latest revision - 12 September 1987 VERSION: Fortran 90 version - 8 August 1996
References temp().
extremum()
subroutine, public m_math::extremum (real, dimension(:), intent(in) array, real, intent(out), optional small, real, intent(out), optional big)
NAME
extremum(3f) - [M_math:statistics] Finds the minimum and maximum value in a REAL array.
SYNOPSIS
subroutine extremum(array,small,big)
real,intent(in) :: array(:) real,intent(out) :: small real,intent(out) :: big
DESCRIPTION
Finds the minimum and maximum value in a REAL array.
OPTIONS
array The array to find the extremes of
RETURNS
small least value found big largest value found
EXAMPLE
Sample program:
program testit use M_math, only : extremum real,allocatable :: arr(:) arr=[-10.0,8.8,-5.0,0.0,5.0,10.0,-0.3] call extremum(arr,small,big) write(*,*)'SMALL=',small write(*,*)'BIG=',big end program testit
SEE ALSO
minval(3f), maxval(3f)
in_margin()
elemental pure logical function, public m_math::in_margin (class(*), intent(in) expected_value, class(*), intent(in) measured_value, class(*), intent(in) allowed_margin)
NAME
in_margin(3f) - [M_math] check if two reals are approximately equal using a relative margin
SYNOPSIS
 elemental pure function in_margin( expected_value, measured_value, allowed_margin )
  real, intent(in)    :: expected_value
  real, intent(in)    :: measured_value
  real, intent(in)    :: allowed_margin
  class(*),intent(in) :: invalue
DESCRIPTION
Compare two values to see if they are relatively equal using the specified allowed margin. That is, see if VALUE_MEASURED is in the range VALUE_EXPECTED +- ALLOWED_ERROR where the allowed error varies with the magnitude of the values, such that the allowed error is margin * average magnitude of measured and expected).
So the allowed error is smaller when the magnitudes are smaller.
OPTIONS
expected_value First value measured_value Second value allowed_margin Allowed relative margin
EXAMPLE
Sample program:
program demo_in_margin use :: M_math, only : in_margin implicit none end program demo_in_margin
References m_anyscalar::anyscalar_to_double(), false(), and true().
inpolygon()
logical function, public m_math::inpolygon (integer, intent(in) XIN, integer, intent(in) YIN, integer, dimension(nconv) XCONV, integer, dimension(nconv) YCONV, integer, intent(in) NCONV)
NAME
inpolygon(3f) - [M_math:geometry] determine whether or not an integer point is in an integer polygon
SYNOPSIS
 logical function inpolygon(xin, yin, xconv, yconv, nconv)
  integer,intent(in)  xin, yin
  integer,intent(in)  nconv
  integer,intent(in)  xconv(nconv), yconv(nconv)
DESCRIPTION
Given a closed polygon find if a point lies inside the polygon.
OPTIONS
xin the X coordinate of the point to be checked yin the Y coordinate of the point to be checked xconv contains the X coords of the polygon yconv contains the Y coords of the polygon nconv the number of points in the polygon
RESULT
INPOLYGON returns .true if the point lies inside the polygon, otherwise it returns .false.
References false(), and true().
integer_invert_2x2()
pure integer(kind=wp) function, dimension(2,2) m_math::integer_invert_2x2 (integer(kind=wp), dimension(2,2), intent(in) A) private
integer_invert_3x3()
pure integer(kind=wp) function, dimension(3,3) m_math::integer_invert_3x3 (integer(kind=wp), dimension(3,3), intent(in) A) private
integer_invert_4x4()
pure integer(kind=wp) function, dimension(4,4) m_math::integer_invert_4x4 (integer(kind=wp), dimension(4,4), intent(in) A) private
julfit()
subroutine, public m_math::julfit (real, dimension(ixn) x, real, dimension(ixn) y, integer, intent(in) ixn, integer, intent(in) itype, real, intent(out) a, real, intent(out) b, real, intent(out) r2)
NAME
julfit(3f) - [M_math:fit] linear least squares curve fits , destroys input arrays
SYNPOSIS
subroutine julfit(x,y,ixn,itype,a,b,r2)
integer,intent(in) :: ixn real :: x(ixn),y(ixn) integer,intent(in) :: itype real,intent(out) :: a,b,r2
DESCRIPTION
DESCRIPTION
use method of least squares to find a fit to the data. the expression being fitted is of one of several forms that have in common the fact that the expression will plot as a straight line if the proper axis type is selected.
type x-axis y-axis significance of a and b
1 linear linear y=a*x+b # linear function 2 linear log y=a*b**x # exponential function 3 log linear y=a*log10(x)+b # logarithmic function 4 log log y=a*x**b # power functions: hyperbolic if b <0; parabolic if b > 0. 5 linear log y=a*e**(-b*x) # a common variant of the exponential form.
OPTIONS
x = array of x values, input y = array of y values, input that are changed to hold the output ixn = number of points in arrays x and y to use itype = expression being solved (1) Y=a*X+b (2) Y=a*b**X (3) Y=a*log10(X)+b (4) Y=a*X**b (5) Y=a*e*(-b**X)
NOTE: odd use of arrays specifically optimized for calling from USH
RETURNS
a = slope of linearized line b = y intercept of linearized line r2 = correlation coefficient (1=perfect) In general, if the correlation coefficient is <0.5 the correlation is regarded as insignificant. If it is >0.8 the derived linear fit is considered highly significant. PRODUCT: CLI library utilities and examples PROGRAM: julfit(3f) DESCRIPTION: linear least squares curve fits , destroys input arrays AUTHOR: John S. Urban HOME PAGE: http://www.urbanjost.altervista.org/index.html
References julfit1().
julfit1()
subroutine, public m_math::julfit1 (real, dimension(*), intent(in) x, real, dimension(*) y, integer, intent(in) ixn, real, intent(out) a, real, intent(out) b, real, intent(out) r2)
NAME
julfit1(3f) - [M_math:fit] internal routine for linear least square fit(y=a*x+b), changes the y array
SYNOPSIS
subroutine julfit1(x,y,ixn,a,b,r2)
real,intent(in) :: x(*) real :: y(*) integer,intent(in) :: ixn real,intent(out) :: a real,intent(out) :: b real,intent(out) :: r2
DESCRIPTION
While the method of least squares often gives optimal estimates parameters for linear processes,
it is very sensitive to the presence of unusual data points in the data used to fit a model, as the square of the
distance from the resulting fit is used in the calculation.
That is, a few outliers can sometimes seriously skew the results of a least squares analysis;
this makes model validation, especially with respect to outliers, critical to obtaining sound answers.
OPTIONS
X input X values Y input Y values IXN size of X and Y vectors A multiplier B y-intercept R2
EXAMPLE
sample program
program demo_julfit1 implicit none intrinsic random_number integer :: points real :: slope, intercept write(*,*)'For y=m*x+b enter M and B and number of points N:' read(*,*)slope,intercept,points call testit() contains
subroutine testit() real :: x(points), y(points) real :: slope_out, intercept_out, r2 integer :: i, ii real :: rndnum do i=1,points x(i)=i*0.10 ! assigned pseudorandom numbers from the uniform distribution in the interval 0 x < 1. call random_number(rndnum) y(i)=slope*(x(i)+4.0*(rndnum-0.5))+intercept enddo !write(*,*)(ii,x(ii),y(ii),new_line('A'),ii=1,points) call julfit1(x,y,points,slope_out,intercept_out,r2) write(*,*)'SLOPE AND INTERCEPT IN ',slope,intercept write(*,*)'SLOPE AND INTERCEPT OUT ',slope_out,intercept_out,r2 end subroutine testit
end program demo_julfit1
Results
$ xxx For y=m*x+b enter M and B and number of points N: 10 20 1000000 SLOPE AND INTERCEPT IN 10.0000000 20.0000000 SLOPE AND INTERCEPT OUT 10.0000000 19.9998207 1.00000000
$ xxx For y=m*x+b enter M and B and number of points N: 10 20 100 SLOPE AND INTERCEPT IN 10.0000000 20.0000000 SLOPE AND INTERCEPT OUT 9.62195778 23.3507996 0.850686848 PRODUCT: CLI library utilities and examples PROGRAM: julfit1(3f) DESCRIPTION: internal routine for linear least square fit(y=a*x+b), changes the y array
VERSION: 1.0, 1980
AUTHOR: John S. Urban REPORTING BUGS: http://www.urbanjost.altervista.org/ HOME PAGE: http://www.urbanjost.altervista.org/index.html COPYRIGHT: Copyright (C) 1980 John S. Urban LICENSE: Public Domain. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
linearint()
subroutine, public m_math::linearint (real, dimension(n), intent(in) X, real, dimension(n), intent(in) Y, integer, intent(in) N, real, dimension(ni), intent(in) XI, real, dimension(ni), intent(out) YI, integer, intent(in) NI, integer, intent(out) KERR)
NAME
linearint(3f) - [M_math:fit] interpolates a curve defined by X(i),Y(i) using linear interpolation at given XI(j) values
SYNOPSIS
SUBROUTINE linearint(X,Y,N,XI,YI,NI,KERR)
INTEGER,intent(in) :: N, NI REAL,intent(in) :: X(N),Y(N),XI(NI) REAL,intent(out) :: YI(NI) INTEGER,intent(out) :: KERR
DESCRIPTION
OPTIONS
X array of data abscissas Y array of data ordinates N number of data points (the dimension of X,Y) XI array of abscissas (in arbitrary order) at which the curve is to be interpolated. YI array of interpolated ordinates (OUTPUT) NI dimension of XI, YI (if NI=1, XI, YI may be simple variables.) KERR error status parameter NORMAL CODES: =0 means the curve was evaluated at each abscissa in XI using only interpolation. =1 means the curve was evaluated at each abscissa in XI, but at least one extrapolation was performed. ABNORMAL CODES: =2 means the requested number of interpolations, NI, was not positive.
RETURNS
EXAMPLE
PRODUCT: CLI library utilities and examples PROGRAM: linearint(1) DESCRIPTION: interpolates a curve <X(i),Y(i)> using linear interpolation at given XI(j) values
VERSION: 1.0, 20031123
AUTHOR: John S. Urban (hacked from splint) HOME PAGE: http://www.urbanjost.altervista.org/index.html
locpt()
subroutine, public m_math::locpt (real, intent(in) x0, real, intent(in) y0, real, dimension(:), intent(in) x, real, dimension(:), intent(in) y, integer, intent(in) n, integer, intent(out) l, integer, intent(out) m)
NAME
locpt - [M_math:geometry] find if a point is inside a polygonal path
SYNOPSIS
Usage:
subroutine locpt (x0,y0,x,y,n,l,m) real, intent(in) :: x0, y0, x(:), y(:) integer, intent(in) :: n integer, intent(out) :: l, m
DESCRIPTION
Given a polygonal line connecting the vertices (X(I),Y(I)) (I = 1,...,N) taken in this order. it is assumed that the polygonal path is a loop, where (X(N),Y(N)) = (X(1),Y(1)) or there is an arc from (X(N),Y(N)) to (X(1),Y(1)). N.B. The polygon may cross itself any number of times.
(X0,Y0) is an arbitrary point and l and m are variables. On output, L and M are assigned the following values ...
L = -1 If (X0,Y0) is outside the polygonal path L = 0 If (X0,Y0) lies on the polygonal path L = 1 If (X0,Y0) is inside the polygonal path
M = 0 if (X0,Y0) is on or outside the path. If (X0,Y0) is inside the path then M is the winding number of the path around the point (X0,Y0).
o Fortran 66 version by A.H. Morris o Converted to ELF90 compatibility by Alan Miller, 15 February 1997 saved from url=(0050)http://users.bigpond.net.au/amiller/NSWC/locpt.f90
lowess()
subroutine, public m_math::lowess (real, dimension(n) x, real, dimension(n) y, integer n, real f, integer nsteps, real delta, real, dimension(n) ys, real, dimension(n) rw, real, dimension(n) res)
NAME
lowess(3f) - [M_math:fit] procedures for locally weighted regression
SYNOPSIS
Calling Sequence:
 subroutine lowess(x, y, n, f, nsteps, delta, ys, rw, res)
 real,intent(in)    :: x(n)
 real,intent(in)    :: y(n)
 integer,intent(in) :: n
 real,intent(in)    :: f
 integer,intent(in) :: nsteps
 real,intent(in)    :: delta
 real,intent(out)   :: ys(n)
 real,intent(out)   :: rw(n)
 real,intent(out)   :: rw(res)
PURPOSE
Lowess is a data analysis technique for producing a "smooth" set of
values from a time series which has been contaminated with noise,
or from a scatter plot with a "noisy" relationship between the two
variables. In a time series context, the technique is an improvement
over least squares smoothing when the data is not equally spaced
(as least squares smoothing assumes).
DESCRIPTION
LOWESS stands for "locally weighted regression". LOWESS computes the
smooth of a scatterplot of Y against X using robust locally weighted
regression. Fitted values, YS, are computed at each of the values of
the horizontal axis in X.
For lowess smoothing, the analyst can vary the size of the smoothing
window.  This size is given as the fraction (0 to 1) of the data that
the window should cover. The default window size is .2 (which states
that the smoothing window has a total width of 20% of the horizontal
axis variable). The LOWESS fraction (F) controls the smoothness of the
curve. For example, if it is 1.0, then the LOWESS curve is a single
straight line. In general, the smaller the fraction, the more that
LOWESS curve follows individual data points. To obtain a smoother
LOWESS curve, increase the value of the LOWESS FRACTION.
This package consists of two FORTRAN procedures for smoothing
scatterplots by robust locally weighted regression, or lowess. The
principal routine is LOWESS which computes the smoothed values using
the method described in "The Elements of Graphing Data", by William S.
Cleveland (Wadsworth, 555 Morego Street, Monterey, California 93940).
LOWESS calls a support routine, LOWEST, the code for which is
included. LOWESS also calls a routine SORT, which the user must provide.
To reduce the computations, LOWESS requires that the arrays X and Y,
which are the horizontal and vertical coordinates, respectively, of the
scatterplot, be such that X is sorted from smallest to largest. The
user must therefore use another sort routine which will sort X and Y
according to X.
To summarize the scatterplot, YS, the fitted values, should be plotted
against X. No graphics routines are available in the package and must
be supplied by the user.
The FORTRAN code for the routines LOWESS and LOWEST has been generated
from higher level RATFOR programs (B. W. Kernighan, ``RATFOR: A
Preprocessor for a Rational Fortran,'' Software Practice and Experience,
Vol. 5 (1975).
OPTIONS
ARGUMENT DESCRIPTION
      X =       Input; abscissas of the points on the
                scatterplot; the values in X must be ordered
                from smallest to largest.
      Y =       Input; ordinates of the points on the
                scatterplot.
      N =       Input; dimension of X,Y,YS,RW, and RES.
      F =       Input; specifies the amount of smoothing; F is
                the fraction of points used to compute each
                fitted value; as F increases the smoothed values
                become smoother; choosing F in the range .2 to
                .8 usually results in a good fit; if you have no
                idea which value to use, try F = .5.
      NSTEPS =  Input; the number of iterations in the robust
                fit; if NSTEPS = 0, the nonrobust fit is
                returned; setting NSTEPS equal to 2 should serve
                most purposes.
      DELTA =   input; nonnegative parameter which may be used
                to save computations; if N is less than 100, set
                DELTA equal to 0.0; if N is greater than 100 you
                should find out how DELTA works by reading the
                additional instructions section.
      YS =      Output; fitted values; YS(I) is the fitted value
                at X(I); to summarize the scatterplot, YS(I)
                should be plotted against X(I).
      RW =      Output; robustness weights; RW(I) is the weight
                given to the point (X(I),Y(I)); if NSTEPS = 0,
                RW is not used.
      RES =     Output; residuals; RES(I) = Y(I)-YS(I).
ADDITIONAL INSTRUCTIONS
    DELTA can be used to save computations.
    Very roughly the algorithm is this:
    on the initial fit and on each of the NSTEPS iterations locally weighted regression fitted values are computed
    at points in X which are spaced, roughly, DELTA apart;
    then the fitted values at the remaining points are computed using linear interpolation.
    The first locally weighted regression (LWR) computation is carried out at X(1) and the last is carried out at X(N).
    Suppose the LWR computation is carried out at X(I).
    If X(I+1) is greater than or equal to X(I)+DELTA, the next LWR computation is carried out at X(I+1).
    If X(I+1) is less than X(I)+DELTA, the next LWR computation is carried out at the largest X(J) which is greater than
    or equal to X(I) but is not greater than X(I)+DELTA.
    Then the fitted values for X(K) between X(I) and X(J), if there are any, are computed by linear interpolation
    of the fitted values at X(I) and X(J).
    If N is less than 100 then DELTA can be set to 0.0 since the computation time will not be too great.
    For larger N it is typically not necessary to carry out the LWR computation for all points,
    so that much computation time can be saved by taking DELTA to be greater than 0.0.
    If DELTA = Range (X)/k then,
    if the values in X were uniformly scattered over the range,
    the full LWR computation would be carried out at approximately k points.
    Taking k to be 50 often works well.
METHOD
    The fitted values are computed by using the nearest neighbor
    routine and robust locally weighted regression of degree 1
    with the tricube weight function. A few additional features
    have been added. Suppose r is FN truncated to an integer.
    Let h be the distance to the r-th nearest neighbor
    from X(I). All points within h of X(I) are used. Thus if
    the r-th nearest neighbor is exactly the same distance as
    other points, more than r points can possibly be used for
    the smooth at X(I). There are two cases where robust
    locally weighted regression of degree 0 is actually used at
    X(I). One case occurs when h is 0.0. The second case
    occurs when the weighted standard error of the X(I) with
    respect to the weights w(j) is less than .001 times the
    range of the X(I), where w(j) is the weight assigned to the
    j-th point of X (the tricube weight times the robustness
    weight) divided by the sum of all of the weights. Finally,
    if the w(j) are all zero for the smooth at X(I), the fitted
    value is taken to be Y(I).
DEPENDENCIES
  o LOWEST
  o SORT
LOWEST
Calling sequence
     CALL LOWEST(X,Y,N,XS,YS,NLEFT,NRIGHT,W,USERW,RW,OK)
PURPOSE
    LOWEST is a support routine for LOWESS and ordinarily will
    not be called by the user. The fitted value, YS, is
    computed at the value, XS, of the horizontal axis.
    Robustness weights, RW, can be employed in computing the
    fit.
OPTIONS
     Argument description
      X =       Input; abscissas of the points on the
                scatterplot; the values in X must be ordered
                from smallest to largest.
      Y =       Input; ordinates of the points on the
                scatterplot.
      N =       Input; dimension of X,Y,W, and RW.
      XS =      Input; value of the horizontal axis at which the
                smooth is computed.
      YS =      Output; fitted value at XS.
      NLEFT =   Input; index of the first point which should be
                considered in computing the fitted value.
      NRIGHT =  Input; index of the last point which should be
                considered in computing the fitted value.
      W =       Output; W(I) is the weight for Y(I) used in the
                expression for YS, which is the sum from
                I = NLEFT to NRIGHT of W(I)*Y(I); W(I) is
                defined only at locations NLEFT to NRIGHT.
      USERW =   Input; logical variable; if USERW is .TRUE., a
                robust fit is carried out using the weights in
                RW; if USERW is .FALSE., the values in RW are
                not used.
      RW =      Input; robustness weights.
      OK =      Output; logical variable; if the weights for the
                smooth are all 0.0, the fitted value, YS, is not
                computed and OK is set equal to .FALSE.; if the
                fitted value is computed OK is set equal to
METHOD
     The smooth at XS is computed using (robust) locally weighted
     regression of degree 1. The tricube weight function is used
     with h equal to the maximum of XS-X(NLEFT) and X(NRIGHT)-XS.
     Two cases where the program reverts to locally weighted
     regression of degree 0 are described in the documentation
     for LOWESS.
DEPENDENCIES
o lowest o sort_shell ! user-supplied SORT
EXAMPLES
Example program:
program T_lowess
!  test driver for lowess
!  for expected output, see introduction
real x(20), y(20), ys(20), rw(20), res(20)
data x /1,2,3,4,5,10*6,8,10,12,14,50/
data y /18,2,15,6,10,4,16,11,7,3,14,17,20,12,9,13,1,8,5,19/
call lowess(x,y,20,.25,0,0.,ys,rw,res)
write(*,*) ys
call lowess(x,y,20,.25,0,3.,ys,rw,res)
write(*,*) ys
call lowess(x,y,20,.25,2,0.,ys,rw,res)
write(*,*) ys
end
The following are data and output from LOWESS that can
be used to check your implementation of the routines. The
notation (10)v means 10 values of v.
 X values:
   1  2  3  4  5  (10)6  8  10  12  14  50
 Y values:
    18  2  15  6  10  4  16  11  7  3  14  17  20  12  9  13  1  8  5  19
 YS values with F = .25, NSTEPS = 0, DELTA = 0.0
  13.659  11.145  8.701  9.722  10.000  (10)11.300  13.000  6.440  5.596
    5.456  18.998
 YS values with F = .25, NSTEPS = 0 ,  DELTA = 3.0
   13.659  12.347  11.034  9.722  10.511  (10)11.300  13.000  6.440  5.596
     5.456  18.998
 YS values with F = .25, NSTEPS = 2, DELTA = 0.0
   14.811  12.115  8.984  9.676  10.000  (10)11.346  13.000  6.734  5.744
   5.415  18.998
REFERENCE
This routine is functionally based on the "netlib" routine lowess from netlib/go/lowess.f .
"Graphical Methods for Data Analysis", Chambers, Cleveland, Kleiner, and Tukey. Wadsworth, 1983.
APPLICATIONS
 Time Series Analysis
SEE ALSO
A multivariate version is available by "send dloess from a"
from the NETLIB server.
AUTHOR
Bill Cleveland
 research!alice!wsc Mon Dec 30 16:55 EST 1985
 W. S. Cleveland
 ATT Bell Laboratories
 Murray Hill NJ 07974
AUTHOR: Bill Cleveland
References lowest().
lowest()
subroutine m_math::lowest (real, dimension(n) x, real, dimension(n) y, integer n, real xs, real ys, integer nleft, integer nright, real, dimension(n) w, logical userw, real, dimension(n) rw, logical ok)
References false(), and true().
poly_intercept()
subroutine, public m_math::poly_intercept (real, dimension(2), intent(in) a, real, dimension(2), intent(in) b, real, dimension(:), intent(in) x, real, dimension(:), intent(in) y, integer, intent(in) n, real, dimension(:), intent(out) u, real, dimension(:), intent(out) v, integer, intent(in) m, integer, intent(out) num, integer, intent(out) ierr)
NAME
poly_intercept(3f) - [M_math:geometry] intersection of a straight line and polygonal path
SYNOPSIS
SUBROUTINE Poly_Intercept(a,b,x,y,n,u,v,m,num,ierr)
REAL, INTENT(IN) :: a(2) REAL, INTENT(IN) :: b(2) REAL, INTENT(IN) :: x(:) REAL, INTENT(IN) :: y(:) INTEGER, INTENT(IN) :: n
REAL, INTENT(OUT) :: u(:) REAL, INTENT(OUT) :: v(:)
INTEGER, INTENT(IN) :: m
INTEGER, INTENT(OUT) :: num INTEGER, INTENT(OUT) :: ierr
DESCRIPTION
Calculates the points <U(1:num),V(1:num)> at which a line <A,B> crosses a polygon <X(1:n),Y(1:n)>, provided that number of points found (NUM) is less than or equal to the storage given the output vector <U,V>.
Based upon routine PFIND from the NSWC Mathematics Library.
OPTIONS
a,b points (a(1),a(2)) and (b(1),b(2)) defining a line x,y the set of points (x(i),y(i)), i=1,2,3,....n define a polygon n the size of the x(:) and y(:) arrays
RETURNS
u,v the arrays U and V contain the number of points at which the line m the size of the U and V arrays num number of intersection points found at which the line crosses the polygon in order (provided that m < size(u)) ierr N where N is ... o 0 no error detected o 1 if a = b o 2 U and V require more storage, i.e. num > m. o -i if the ith segment of the polygon is coincident with part of the line.
EXAMPLE
PEDIGREE
o Based upon routine PFIND from the NSWC Mathematics Library. o Code converted using TO_F90 by Alan Miller, Date: 2000-07-04 Time: 12:24:01 o Update Sun, Mar 5, 2017 8:04:46 AM PROCEDURE: poly_intercept(3f) DESCRIPTION: intesections of a straight line and polygonal path AUTHOR: Code converted using TO_F90 by Alan Miller VERSION: Date: 2000-07-04 Time: 12:24:01
polyarea()
real function, public m_math::polyarea (real, dimension(:), intent(in) x, real, dimension(:), intent(in) y)
NAME
polyarea(3f) - [M_math:geometry] compute the area bounded by a closed polygonal curve
SYNOPSIS
FUNCTION polyarea(x, y) RESULT(fn_val)
   REAL, INTENT(IN)     :: x(:)
   REAL, INTENT(IN)     :: y(:)
   REAL                 :: fn_val
DESCRIPTION
Given a sequence of points (X(I),Y(I)), polyarea(3f) computes the area bounded by the closed polygonal curve which passes through the points in the order that they are indexed. The final point of the curve is assumed to be the first point given. Therefore, it need not be listed at the end of X and Y. The curve is not required to be simple (e.g. It may cross over itself).
OPTIONS
RETURNS
EXAMPLE
Sample program:
! (0,10) ########### (10,10) ! ## # ! # # # ! # # # ! # # # ! # # ! # # # ! # # # ! # # # ! ## # ! (0,0)########### (10,0)
program demo_polyarea use M_math, only : polyarea implicit none ! A B C D E F real,allocatable :: x(:) real,allocatable :: y(:)
x=[ 0.0, 10.0, 0.0, 0.0, 10.0, 0.0] y=[10.0, 10.0, 0.0, 10.0, 0.0, 0.0] write(*,*)'polyarea=',polyarea(x,y)
x=[ 0.0, 0.0, 10.0, 10.0, 0.0 ] y=[ 0.0, 10.0, 10.0, 0.0, 0.0 ] write(*,*)'polyarea=',polyarea(x,y)
x=[ 0.0, 10.0, 10.0, 0.0, 0.0 ] y=[10.0, 10.0, 0.0, 0.0, 10.0 ] write(*,*)'polyarea=',polyarea(x,y)
end program demo_polyarea PROCEDURE: polyarea(3f) DESCRIPTION: compute the area bounded by a closed polygonal curve AUTHOR: Code converted using TO_F90 by Alan Miller VERSION: 2000-07-04 Time: 12:24:06
quadratic()
subroutine, public m_math::quadratic (real, intent(in) a, real, intent(in) b, real, intent(in) c, complex, intent(out) z1, complex, intent(out) z2, real, intent(out) discriminant)
NAME
quadratic(3f) - [M_math] calculate the roots of a quadratic formula even if they are complex
SYNOPSIS
subroutine quadratic(a,b,c,z1,z2,discriminant)
real,intent(in) :: a, b, c complex,intent(out) :: z1, z2 real,intent(out) :: discriminant
DESCRIPTION
Given the equation
a*x**2+b*x+c=0
Use the quadratic formula to determine the root values and the discriminant of the equation.
OPTIONS
a,b,c coefficients
RETURNS
z1,z2 roots
EXAMPLE
Sample program:
program demo_quadratic use M_math, only : quadratic implicit none ! Calculate and print the roots of a quadratic formula ! even if they are complex real :: a, b, c ! coefficients complex :: z1, z2 ! roots real :: discriminant
a = 4.0 b = 8.0 c = 21.0 call quadratic(a,b,c,z1,z2,discriminant) ! Calculate the roots
if (abs(discriminant) < 0) then write(*,*) "the roots are real and equal:" else if (discriminant > 0) then write(*,*) "the roots are real:" else write(*,*) "the roots are complex:" end if ! Print the roots print *, "The roots are:" print *, "z1 =", z1 print *, "z2 =", z2
end program demo_quadratic
real_invert_2x2()
pure real(kind=wp) function, dimension(2,2) m_math::real_invert_2x2 (real(kind=wp), dimension(2,2), intent(in) A) private
real_invert_3x3()
pure real(kind=wp) function, dimension(3,3) m_math::real_invert_3x3 (real(kind=wp), dimension(3,3), intent(in) A) private
real_invert_4x4()
pure real(kind=wp) function, dimension(4,4) m_math::real_invert_4x4 (real(kind=wp), dimension(4,4), intent(in) A) private
round()
real(kind=dp) function, public m_math::round (real(kind=dp), intent(in) val, integer, intent(in) idigits0)
scale1()
subroutine, public m_math::scale1 (real, intent(in) xmin0, real, intent(in) xmax0, integer, intent(in) n0, real, intent(out) xminp, real, intent(out) xmaxp, real, intent(out) dist)
NAME
scale1(3f) - [M_math] find new range xminp xmaxp divisible into approximately n linear intervals of size dist
SYNOPSIS
subroutine scale1(xmin, xmax, n, xminp, xmaxp, dist)
real,intent(in) :: xmin, xmax integer,intent(in) :: n real,intent(out) :: xminp, xmaxp, dist
DESCRIPTION
Find new range divisible into approximately n linear intervals using
"CACM Algorithm 463 scale1".  Typically used to find nice ranges for
axis scales.
EXAMPLE
References m1.
scale3()
subroutine, public m_math::scale3 (real, intent(in) xmin0, real, intent(in) xmax0, integer, intent(in) n0, real, intent(out) xminp, real, intent(out) xmaxp, real, intent(out) dist)
NAME
scale3(3f) - [M_math] find nice log range
SYNOPSIS
subroutine scale3(xmin, xmax, n, xminp, xmaxp, dist)
real,intent(in) :: xmin, xmax integer,intent(in) :: n real,intent(out) :: xminp, xmaxp, dist
DESCRIPTION
Find nice logarithmic range using "CACM Algorithm 463 scale3".
Typically used to find nice ranges for axis scales.  Given XMIN, XMAX
and N, where N is greater than 1, find new log range.  Finds a new
range XMINP and XMAXP divisible into exactly N LOGARITHMIC intervals,
where the ratio of adjacent uniformly spaced scale values
is DIST.
EXAMPLE
References m1, and m2.
skekur1()
subroutine, public m_math::skekur1 (real, dimension(*), intent(in) Y, integer, intent(in) NHI, real, intent(out) YSKEW, real, intent(out) YKURT, integer, intent(in) IOPT)
NAME
skekur1(3f) - [M_math:statistics] variant on calculating skewness and kurtosis of an array
SYNOPSIS
SUBROUTINE SKEKUR1(Y,NHI,YSKEW,YKURT,IOPT)
 real,intent(in)    ::  y(*)
 integer,intent(in) :: nhi
 real,intent(out)   :: yskew
 real,intent(out)   :: ykurt
 integer,intent(in) :: iopt
DESCRIPTION
FOR: Computing SKEWNESS and KURTOSIS for entries 1 through NHI in vector Y. The values may be centered about either the MEAN (IOPT <> 0) or about ZERO (IOPT = 0). The traditional divisor of N (NOT N-1) is used when the MEAN is estimated.
SUBPROGRAMS CALLED: -NONE-
CURRENT VERSION COMPLETED FEBRUARY 28, 1986
OPTIONS
RETURNS
EXAMPLES
AUTHOR
Written by Charles P. Reeve
skekurx()
subroutine, public m_math::skekurx (real, dimension(*), intent(in) Y, integer, intent(in) N, real, intent(out) YSKEW, real, intent(out) YKURT)
NAME
skekurx(3f) - [M_math:statistics] Compute unbiased estimator of the population SKEWNESS and KURTOSIS
SYNOPSIS
SUBROUTINE SKEKURX(Y,N,YSKEW,YKURT)
integer,intent(in) :: n real,intent(in) :: y(*) real,intent(out) :: yskew real,intent(out) :: ykurt
DESCRIPTION
This routine calculates the unbiased estimator of the population kurtosis and skewness from a subset of samples
   kurt = {n*(n+1)/((n-1)*(n-2)*(n-3))*SUM[((x(i)-xbar)/stddev)**4]} -
             3*(n-1)**2/((n-2)*(n-3))
   skew =  ( n / ((n-1)*(n-2)) *SUM{((X(i) - xbar)/stddev)**3}
where xbar and stddev are the sample mean and standard deviation
Note that this is apparently The skewness and kurtosis calculated by the
MicroSoft Excel product.  I checked the Excel help and Excel uses the
above formulas.  No references are given in the Excel documentation. Note
that this converges on the standard expression for excess kurtosis and
skewness as N becomes large.
OPTIONS
RETURNS
EXAMPLES
AUTHOR
John S. Urban
splift()
subroutine, public m_math::splift (real, dimension(n), intent(in) X, real, dimension(n), intent(in) Y, real, dimension(n), intent(out) YP, real, dimension(n), intent(out) YPP, integer, intent(in) N, integer, intent(out) ierr, real, intent(in) a1, real, intent(in) b1, real, intent(in) an, real, intent(in) bn)
NAME
splift(3f) - [M_math:fit] fits a spline to the n data points given in x and y and also returns first and second derivatives
SYNOPSIS
subroutine splift(x,y,yp,ypp,n,ierr,a1,b1,an,bn)
real,intent(in) :: x(n),y(n) real,intent(out) :: yp(n),ypp(n) integer,intent(in) :: n integer,intent(out) :: ierr real,intent(in) :: a1 real,intent(in) :: b1 real,intent(in) :: an real,intent(in) :: bn
DESCRIPTION
SPLIFT(3f) fits a spline to the N data points given in X and Y and returns the first and second derivatives in YP and YPP. The resulting spline, defined by the arrays X, Y, and YPP, may then be interpolated (if desired) using SPLINT(3f).
For a smoothing spline fit see SUBROUTINE SMOOTH.
OPTIONS
   X            array of abscissas (in increasing order)
   Y            array of ordinates
   N            number of data points (the dimension of X,Y,YP and YPP)
   A1,B1,AN,BN  end condition specifications
                 The end conditions of the spline are
                      YPP(1) = A1*YPP(2) + B1
                 and
                      YPP(N) = AN*YPP(N-1) + BN,
                 where
                      ABS(A1).LT.1.0 and ABS(AN).LT.1.0.
         The smoothest (i.e., least integral of square of
         second derivative) spline is obtained by A1=B1=AN=BN=0.
         If extrapolation outside the range from X(1) to X(N)
         is to be done (By SPLINT(3f), say), better results may
         be obtained by using A1=AN=0.5, B1=BN=0.
RETURNS
   YP     Resulting derivative
   YPP    Resulting second derivative
   IERR   Error status.
          NORMAL CODES
            =0  means the requested spline was computed.
          ABNORMAL CODES
            =1  means N was too small (.LT.4).
            =2  means the abscissas were not strictly increasing.
EXAMPLE
PEDIGREE
Original written by:
  Rondall E. Jones
  Sandia Mathematical Program Library
  Applied Mathematics Division 2642
  Sandia Laboratories
  P. O. Box 5800
  Albuquerque, New Mexico  87115
  Control Data 6600 Version 5.1, 10 December 1973
  WARD implementation   S. J. Orbon        4/1/1974
  F90+ Implementation   J. S. Urban
PRODUCT: CLI library utilities and examples PROGRAM: splift(3f) DESCRIPTION: fits a spline to the n data points given in x and y
VERSION: 5.0: 20170129
AUTHOR: John S. Urban REPORTING BUGS: http://www.urbanjost.altervista.org/
splint()
subroutine, public m_math::splint (real, dimension(n), intent(in) x, real, dimension(n), intent(in) y, real, dimension(n), intent(in) ypp, integer, intent(in) n, real, dimension(ni), intent(in) xi, real, dimension(ni), intent(out) yi, real, dimension(ni), intent(out) ypi, real, dimension(ni), intent(out) yppi, integer, intent(in) ni, integer, intent(out) kerr)
NAME
splint(3f) - [M_math:fit] interpolates and twice differentiates a cubic spline
SYNOPSIS
subroutine splint (x,y,ypp,n,xi,yi,ypi,yppi,ni,kerr)
integer,intent(in) :: n, ni real,intent(in) :: x(n),y(n),ypp(n),xi(ni) real,intent(out) :: yi(ni),ypi(ni),yppi(ni)
DESCRIPTION
SPLINT(3f) interpolates and twice differentiates a cubic spline defined by X, Y, and YPP at the abscissas in XI. The spline may have been determined by SPLIFT(3f) or SMOOTH(3f) or any other spline fitting routine which provides second derivatives.
OPTIONS
X array of data abscissas Y array of data ordinates YPP array of spline second derivatives N number of data points (the dimension of X,Y, and YPP) XI array of abscissas (in arbitrary order) at which the spline is to be interpolated. NI dimension of XI, YI, YPI, and YPPI. (if NI=1, XI, YI, YPI and YPPI may be simple variables.)
RETURNS
YI array of interpolated ordinates (OUTPUT) YPI array of interpolated derivatives (OUTPUT) YPPI array of interpolated second derivatives (OUTPUT) KERR error status parameter (OUTPUT) NORMAL CODES =0 means the spline was evaluated at each abscissa in XI using only interpolation. =1 means the spline was evaluated at each abscissa in XI, but at least one extrapolation was performed. ABNORMAL CODE =2 means the requested number of interpolations, NI, was not positive.
EXAMPLE
PEDIGREE
Original written by:
  Rondall E. Jones
  Sandia Mathematical Program Library
  Applied Mathematics Division 2642
  Sandia Laboratories
  P. O. Box 5800
  Albuquerque, New Mexico  87115
Control Data 6600 Version 5.1, 10 December 1973
PRODUCT: CLI library utilities and examples PROGRAM: splint(3f) DESCRIPTION: interpolates and twice differentiates a cubic spline
VERSION: 5.0: 20170129
AUTHOR: John S. Urban REPORTING BUGS: http://www.urbanjost.altervista.org/
stddev()
real function, public m_math::stddev (real, dimension(n), intent(in) vector, integer, intent(in) n, real, intent(in) avg)
NAME
stddev(3f) - [M_math:statistics] given a real vector and the vector average calculate the standard deviation
SYNTAX
function stddev(vector,n,avg)
integer,intent(in) :: n real,intent(in) :: vector(n) real,intent(in) :: avg real :: stddev
DESCRIPTION
Clearly the average gives one number around which the n observations tend to cluster. And the standard deviation gives a measure of how the n observations vary or spread about this average. The square of the standard deviation is called the variance. If we consider a unit mass at each point x(i) , then the variance is equivalent to a moment of inertia about an axis through x(avg). It is readily seen that for a fixed value of x(avg), greater spreads from the average will produce larger values of the standard deviation s. The average and the standard deviation can be used jointly to summarize where the observations are concentrated. Tchebysheff's theorem states :
A fraction of at least 1 - (1/k**2) of the observations lie within k standard deviations of the average. The theorem guarantees lower bounds on the percentage of observations within k standard deviations of the average.
OPTIONS
n the size of the input vector vector(n) the input vector avg the average of the input vector
RETURNS
stddev the standard deviation of the vector
EXAMPLE
AUTHOR
1994 John S. Urban
REFERENCE
From Mark's Handbook, page 17-19, 8th edition