GeneralPurposeFortran: m_getopt Module Reference
m_getopt Module Reference
NAME
M_getopt(3fm) - [ARGUMENTS:M_getopt] parse command line arguments. similar to those in standard C library.
Data Types
type option_s
Functions/Subroutines
character function substr (str, i, j)
character function getopt (optstring, longopts)
character function process_long (longopts, arg)
character function process_short (optstring, arg)
Variables
character(len=80) optarg
character optopt
integer optind =1
logical opterr =.true.
integer, private grpind =2
Detailed Description
NAME
M_getopt(3fm) - [ARGUMENTS:M_getopt] parse command line arguments. similar to those in standard C library.
SYNOPSIS
use getopt_m, only : getopt use getopt_m, only : option_s use getopt_m, only : optarg,optopt,optind
DESCRIPTION
ch = getopt(optstring, [longopts])
Returns next option character from command line arguments. o If an option is not recognized, it returns '?'. o If no options are left, it returns a null character, char(0).
OPTIONS
optstring contains characters that are recognized as options. If a character is followed by a colon, then it takes a required argument. For example, "x" recognizes "-x", while "x:" recognizes "-x arg" or "-xarg". opterr Errors are printed by default. Set opterr=.false. to suppress them.
RETURNS
optopt is set to the option character, even if it isn't recognized. optarg is set to the option's argument. optind has the index of the next argument to process. Initially optind=1.
Grouped options are allowed, so "-abc" is the same as "-a -b -c".
If longopts is present, it is an array of type(option_s), where each entry describes one long option.
type option_s character(len=4096) :: name logical :: has_arg character :: val end type
The name field is the option name, without the leading – double dash. Set the has_arg field to true if it requires an argument, false if not. The val field is returned. Typically this is set to the corresponding short option, so short and long options can be processed together. (But there is no requirement that every long option has a short option, or vice-versa.)
Differences from C version:
when options are finished, C version returns -1 instead of char(0), and thus stupidly requires an int instead of a char.
does not support optreset
does not support "--" as last argument
if no argument, optarg is blank, not NULL
argc and argv are implicit
Differences for long options:
optional argument to getopt(), rather than separate function getopt_long()
has_arg is logical, and does not support optional_argument
does not support flag field (and thus always returns val)
does not support longindex
does not support "--opt=value" syntax, only "--opt value"
knows the length of longopts, so does not need an empty last record
EXAMPLE
Sample program:
program demo_getopts use getopt_m, only : getopt,option_s,optarg,optopt implicit none
character(len=*),parameter :: OPTIONS='ab:c' type(option_s):: opts(2) opts(1) = option_s("alpha", .false., 'a') opts(2) = option_s("beta", .true., 'b') do PARSE: select case(getopt(OPTIONS, opts)) case(char(0)) exit PARSE case('a') print *, 'option alpha/a', optarg case('b') print *, 'option beta/b=', optarg case('?') print *, 'unknown option ', optopt,' not in ',OPTIONS stop case default print *, 'unhandled option c ', optopt, ' (an intentional bug)' end select PARSE end do end program demo_getopts
COPYRIGHT
Copyright 2008 by Mark Gates
This program is free software; you can redistribute or modify it under the terms of the GNU general public license (GPL), version 2 or later.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of merchantability or fitness for a particular purpose.
If you wish to incorporate this into non-GPL software, please contact me regarding licensing terms.
Slightly modified from original -JSU
Function/Subroutine Documentation
getopt()
character function m_getopt::getopt (character(len=*), intent(in) optstring, type(option_s), dimension(:), intent(in), optional longopts)
References optarg, optind, process_long(), and process_short().
process_long()
character function m_getopt::process_long (type(option_s), dimension(:), intent(in) longopts, character(len=*), intent(in) arg)
References optarg, opterr, optind, optopt, stderr(), and true().
process_short()
character function m_getopt::process_short (character(len=*), intent(in) optstring, character(len=*), intent(in) arg)
References grpind, optarg, opterr, optind, optopt, stderr(), and substr().
substr()
character function m_getopt::substr (character(len=*), intent(in) str, integer, intent(in) i, integer, intent(in) j)
Variable Documentation
grpind
integer, private m_getopt::grpind =2 private
optarg
character(len=80) m_getopt::optarg
opterr
logical m_getopt::opterr =.true.
optind
integer m_getopt::optind =1
optopt
character m_getopt::optopt