GeneralPurposeFortran: m_calculator_plus Module Reference
m_calculator_plus Module Reference
Functions/Subroutines
integer function, public inum0 (inline, ierr)
NAME
inum0(3f) - [M_calculator_plus] return integer value from calculator expression
SYNOPSIS
real function, public rnum0 (inline, ierr)
NAME
rnum0(3f) - [M_calculator_plus] returns real number from string expression using JUCALC(3f)
SYNOPSIS
doubleprecision function, public dnum0 (inline, ierr)
NAME
dnum0(3f) - [M_calculator_plus] return double precision value from string expression using JUCALC
SYNOPSIS
character(len=:) function, allocatable, public snum0 (inline0, ierr)
NAME
snum0(3f) - [M_calculator_plus] resolve a calculator expression into a string(return blank on errors)
recursive subroutine, public jucalcx (inlin0, outval, outlin0, ierr, ilen)
NAME
jucalcx(3f) - [M_calculator_plus] return value from a string expression processing messages to simplify call to JUCALC(3f)
SYNOPSIS
subroutine, public strgarr (line, ivals, vals, ifound, delims0, ierr)
NAME
strgarr(3f) - [M_calculator_plus] read a string into an array using jucalc(3f) calculator
SYNOPSIS
subroutine, public strgar2 (line, iread, numbrs, inums, delims0, ierr)
NAME
strgar2(3f) - [M_calculator_plus] read a string into a real array USING CALCULATOR, allowing quoted strings in arguments,
Function/Subroutine Documentation
dnum0()
doubleprecision function, public m_calculator_plus::dnum0 (character(len=*), intent(in) inline, integer, intent(out), optional ierr)
NAME
dnum0(3f) - [M_calculator_plus] return double precision value from string expression using JUCALC
SYNOPSIS
doubleprecision function dnum0(inline,ierr)
character(len=*),intent(in) :: inline integer,optional,intent(out) :: ierr
DESCRIPTION
DNUM0() is used to return a DOUBLEPRECISION value from a CHARACTER string representing a numeric expression. o If an error occurs in evaluating the expression INUM() returns zero(0). o DNUM0() ultimately uses the calculator routine jucalc.f .
inline INLINE is a CHARACTER variable up to (iclen_calc=255) characters long that is similar to a FORTRAN 77 numeric expression. ierr error code. If zero, no error occurred
DEPENDENCIES
o jucalcx o User-supplied routines: All programs that call the calculator routine must supply their own JUOWN1 and C procedures. See the example program for samples. o juown1 o c
EXAMPLES
Sample Program
program demo_dnum0 doubleprecision x,y,z ! NOTE: user must supply the JUOWN1 and C procedures. X=DNUM0('20/3.4') Y=DNUM0('CI = 10 * sin(3.1416/4)') Z=DNUM0('CI') write(*,*)x,y,z end program demo_dnum0
SEE ALSO
   o The syntax of an expression is as described in the main documentation of the Calculator Library.
   o See JUCALCX(), JUCALC(), STRGAR2(), RNUM0(), SNUM0().
REFERENCES
o NONE. AUTHOR + John S. Urban
VERSION 1.0, 19971123
References jucalcx().
inum0()
integer function, public m_calculator_plus::inum0 (character(len=*), intent(in) inline, integer, intent(out), optional ierr)
NAME
inum0(3f) - [M_calculator_plus] return integer value from calculator expression
SYNOPSIS
integer function inum0(inline,ierr)
character(len=*),intent(in) :: inline integer,optional,intent(out) :: ierr
SYNOPSIS
INUM0() evaluates a CHARACTER argument as a FORTRAN-like
calculator expression and returns an integer.
 o INUM0() uses the calculator routine jucalc(3f)
 o Remember that the calculator treats all values as DOUBLEPRECISION.
Values returned are assumed to be very close to being whole integer
values.  A small value (0.01) is added to the result before it is
returned to reduce roundoff error problems. This could introduce
errors if INUM0 is misused and is not being used to calculate
essentially integer results.
DESCRIPTION
inline  INLINE is a CHARACTER variable up to 255 characters long that is
        similar to a FORTRAN 77 numeric expression. Keep it less than 80
        characters when possible.
ierr    zero (0) if no error occurs
DEPENDENCIES
o jucalcx o User-supplied routines:
All programs that call the calculator routine must supply their own JUOWN1 and C procedures. See the ../html/Example.html">example program for samples. o juown1 o c
EXAMPLES
Sample program:
   program demo_inum0
   ! NOTE: user must supply the JUOWN1 and C procedures.
   i=inum0('20/3.4')
   j=inum0('CI = 13 * 3.1')
   k=inum0('CI')
   write(*,*)'Answers are ',I,J,K
   end program demo_inum0
SEE ALSO
The syntax of an expression is as described in the main document of the Calculator Library. See JUCALC(), RNUM0(), DNUM0(), SNUM0(), STRGARR(), STRGAR2(), JUCALCX()
REFERENCES
NONE.
AUTHOR: John S. Urban
VERSION: 19971123
References jucalcx().
jucalcx()
recursive subroutine, public m_calculator_plus::jucalcx (character(len=*), intent(in) inlin0, doubleprecision outval, character(len=*) outlin0, integer, intent(out) ierr, integer, intent(out) ilen)
NAME
jucalcx(3f) - [M_calculator_plus] return value from a string expression processing messages to simplify call to JUCALC(3f)
SYNOPSIS
subroutine jucalcx(inlin0,outval,outlin0,ierr,ilen)
character(len=*), intent=(in) :: inlin0 doubleprecision, intent=(out) :: outval character(len=*), intent=(out) :: outlin0 integer, intent=(out) :: ierr integer, intent=(out) :: ilen
DESCRIPTION
JUCALCX() takes a string containing a FORTRAN-like expression and evaluates it and returns a numeric or string value as appropriate. The main purpose of JUCALCX() is to assume the burden of displaying the calculator messages for codes that make multiple calls to JUCALC(). JUCALC () does not display error messages directly. o JUCALCX() calls the calculator routine jucalc.f to evaluate the expressions. o Messages beginning with a # are considered comments and are not passed on to the calculator.
inlin0 INLIN0 is a string containing a numeric expression. The expression can be up to (iclen_calc=512) characters long. The syntax of an expression is as described in the main document of the Calc library. For example:
'A=sin(3.1416/5)' '# this is a comment' '$STR("The value is ",40/3)'
outval OUTVAL is a numeric value calculated from the expression in INLIN0 (when IERR returns 0). When a string value is returned (IERR=2) then OUTVAL is the length of the output string. outlin0 OUTLIN0 contains a string representation of the number returned in OUTVAL up to 20 characters long when INLIN0 is a numeric expression. It contains a string up to (iclen_calc=512) characters long when INLIN0 is a string expression. ierr IERR returns
    o -1 if an error occurred
    o 0 if a numeric value is returned (value is in OUTVAL, string
      representation of the value is in OUTLIN2).
    o 1 if no value was returned but a message was displayed (If a 'dump'
      or 'funcs' command was passed to the calculator).
    o 2 if the expression evaluated to a string value instead of a
      numeric value (value is in OUTLIN0).
ilen ILEN returns the length of the input string minus trailing blanks.
DEPENDENCIES
o jucalc o pdec o User-supplied routines:
All programs that call the calculator routine must supply their own JUOWN1 and C procedures. See the example program for samples. o juown1 o c
EXAMPLES
Sample program:
 program TEST_JUCALCX
 !     NOTE: user must supply the JUOWN1 and C procedures.
 use m_calculator, only: iclen_calc
 character(len=iclen_calc) ::  outlin0
 doubleprecision :: outval
 call jucalcx('A=3.4**5    ',outval,outlin0,ierr,ilen)
 write(*,*)'value of expression is ',outval
 write(*,*)'string representation of value is ',outlin0
 write(*,*)'error flag value is ',ierr
 write(*,*)'length of expression is ',ilen
 end program TEST_JUCALCX
SEE ALSO
See also: STRGAR(),RNUM0(),JUCALC(),INUM0(),SNUM0()
REFERENCES
NONE. AUTHOR John S. Urban
VERSION V1.0, 19971123
References m_calculator::jucalc().
rnum0()
real function, public m_calculator_plus::rnum0 (character(len=*), intent(in) inline, integer, intent(out), optional ierr)
NAME
rnum0(3f) - [M_calculator_plus] returns real number from string expression using JUCALC(3f)
SYNOPSIS
real function rnum0(inline) character(len=*), intent=(in) :: inline integer,intent(out),optional :: ierr
DESCRIPTION
RNUM0() is used to return a REAL value from a CHARACTER string representing a numeric expression. It uses the M_calculator(3fp) module.
inline INLINE is a CHARACTER variable up to (iclen_calc=512) characters long that is similar to a FORTRAN 77 numeric expression. ierr error code. If zero, no error occurred
DEPENDENCIES
o jucalcx o User-supplied routines: All programs that call the calculator routine must supply their own JUOWN1 and C procedures. See the example program for samples. o juown1 o c
EXAMPLES
Sample program
program demo_rnum0 ! NOTE: user must supply the JUOWN1 and C procedures. x=rnum0('20/3.4') y=rnum0('CI = 10 * sin(3.1416/4)') z=rnum0('CI') write(*,*)x,y,z end program demo_rnum0
SEE ALSO
   o The syntax of an expression is as described in the main documentation
     of the Calculator Library.
   o See JUCALCX(3f), JUCALC(3f), STRGAR2(3f), INUM0(3f), DNUM0(3f), SNUM0(3f).
REFERENCES
o NONE. AUTHOR John S. Urban
VERSION 1.0,19971123
References jucalcx().
snum0()
character(len=:) function, allocatable, public m_calculator_plus::snum0 (character(len=*), intent(in) inline0, integer, intent(out), optional ierr)
NAME
snum0(3f) - [M_calculator_plus] resolve a calculator expression into a string(return blank on errors)
SYNOPSIS
function snum0(inline0,ierr)
character(len=:),allocatable :: snum0(inline0) character(len=*),intent(in) :: inline0 ! input string integer,optional,intent(out) :: ierr
DESCRIPTION
SNUM0() is used to return a string value up to (iclen_calc=512) characters long from a string expression. SNUM0() uses the calculator routine jucalc.f .
inline0 INLINE0 is a CHARACTER variable up to (iclen_calc=512) characters long that is similar to a FORTRAN 77 expression. ierr error code. If zero, no error occurred
EXAMPLES
Sample program:
! NOTE: user must supply the JUOWN1 and C procedures. program DEMO_SNUM0 use m_calculator_plus, only: iclen_calc, rnum0, snum0 CHARACTER(len=80) :: IC,JC,KC
RDUM=RNUM0('A=83/2') ! set a variable in the calculator KC=SNUM0('$MYTITLE="This is my title variable"')
IC=SNUM0('$STR("VALUE IS [",A,"]")') JC=SNUM0('$MYTITLE')
WRITE(*,*)'IC=',TRIM(IC) WRITE(*,*)'JC=',TRIM(JC) WRITE(*,*)'KC=',TRIM(KC)
end program DEMO_SNUM0 $endif
The output should look like
IC=VALUE IS [41.5] JC=This is my title variable KC=This is my title variable
DEPENDENCIES
o jucalcx o User-supplied routines: All programs that call the calculator routine must supply their own JUOWN1 and C procedures. See the example program for samples. o juown1 o c
SEE ALSO
o The syntax of an expression is described in the main document of the Calculator Library. o See JUCALC(), RNUM0(), SNUM0(), STRGAR2(), JUCALCX().
REFERENCES
o NONE. AUTHOR John S. Urban
VERSION 1.0, 19971123
References m_calculator::iclen_calc, and jucalcx().
strgar2()
subroutine, public m_calculator_plus::strgar2 (character(len=*), intent(in) line, integer, intent(in) iread, real, dimension(iread), intent(out) numbrs, integer, intent(out) inums, character(len=*), intent(in) delims0, integer, intent(out) ierr)
NAME
strgar2(3f) - [M_calculator_plus] read a string into a real array USING CALCULATOR, allowing quoted strings in arguments,
SYNOPSIS
subroutine strgar2(line,ivals,vals,ifound,delims,ierr)
character(len=*), intent=(in) :: line integer, intent=(in) :: ivals real, intent=(out) :: vals(ivals) integer, intent=(out) :: ifound character(len=*), intent=(in) :: delims integer, intent=(out) :: ierr
DESCRIPTION
STRGAR2() returns an array of real values from a string containing numeric and string expressions. o STRGAR2() parses the string at the specified delimiters and calls the calculator routine jucalc.f to evaluate the expressions. o It counts the number of values found. o Once the maximum allowable number of values have been found STRGAR2() returns, ignoring the rest of the line. o If an error occurs the error flag returns the column number where the expression that failed begins. o If the string is '*', the value -99999.0 is returned.
line LINE is a string of numeric expressions. Each expression can be up to (iclen_calc=512) characters long. The syntax of an expression is as described in the main document of the Calculator Library. (Assuming the delimiters include a space character) an example would be:
 'A=10 100 300E2/42.6  sin(3.1416/5)'
 ivals        IVALS is the maximum number of values to return.
 vals(ivals)  VALS is an array filled with the numeric values calculated from the
              expressions in LINE.
 ifound       IFOUND is the number of values successfully returned in VALS
 delims       DELIMS is a character(s) to use as an expression delimiter. It is
              commonly set to a space (' '). If more than one character is specified,
              the space must not be last.
 ierr         IERR returns 0 if no error occurred. If an error did occur, it returns
              the column number the expression started at that could not be
              evaluated.
DEPENDENCIES
o jucalcx o User-supplied routines: All programs that call the calculator routine must supply their own JUOWN1 and C procedures. See the example program for samples. o juown1 o c
EXAMPLES
Sample program:
program T_STRGAR2 use M_calculator_plus, only : strgar2 integer :: ios integer :: i integer :: ifound integer :: ierr real :: vals(1000) character(len=4096) :: line ! NOTE: user must supply the JUOWN1 and C procedures.
write(*,'(80("-"))') call strgar2('10;2/3;sin(4.314)',4,vals,ifound,' ;',ierr) write(*,*)'should find three values in 10;2/3;sin(4.314)' write(*,*)'ifound=',ifound write(*,*)'values are',(vals(i),i=1,ifound)
write(*,'(80("-"))') write(*,*)'should find three values in 10;2/3;sin(4.314)' write(*,*)'ifound=',ifound call strgar2('10;2/3;sin(4.314) ',3,vals,ifound,' ;',ierr) write(*,*)'ifound=',ifound write(*,*)'values are',(vals(i),i=1,ifound)
write(*,'(80("-"))') write(*,*)'should stop at two values in 10;2/3;sin(4.314)' call strgar2('10;2/3;sin(4.314)',2,vals,ifound,' ;',ierr) write(*,*)'ifound=',ifound write(*,*)'values are',(vals(i),i=1,ifound)
write(*,'(80("-"))') write(*,*)'should stop at one values in 10;2/3;sin(4.314)' call strgar2('10;2/3;sin(4.314)',1,vals,ifound,' ;',ierr) write(*,*)'ifound=',ifound write(*,*)'values are',(vals(i),i=1,ifound)
write(*,'(80("-"))') write(*,*)'should find three values in 10;2/3;sin(4.314) ; ; ; ;; ' call strgar2('10;2/3;sin(4.314) ; ; ; ;; ',1000,vals,ifound,' ;',ierr) write(*,*)'ifound=',ifound write(*,*)'values are',(vals(i),i=1,ifound)
write(*,'(80("-"))') write(*,*)'should find an error in values in 10;20/3O;sin(4.314) ; ; ; ;; ' call strgar2('10;20/3O;sin(4.314) ; ; ; ;; ',1000,vals,ifound,' ;',ierr) write(*,*)'ifound=',ifound,' error=',ierr write(*,*)'values are',(vals(i),i=1,ifound)
write(*,'(80("-"))') write(*,*)'Enter strings delimited by spaces or semicolons' do read(*,'(a)',iostat=ios)line if(ios.ne.0)then stop endif call strgar2(line,1000,vals,ifound,' ;',ierr) write(*,*)'ifound=',ifound write(*,*)'values are',(vals(i),i=1,ifound) enddo end program T_STRGAR2
SEE ALSO
 To parse a list of numbers instead of expressions see STRGAR().
 If there is only one expression see RNUM0(), JUCALCX(), JUCALC().
REFERENCES
NONE. AUTHOR John S. Urban
VERSION 1.0 19971123
References false(), m_calculator::iclen_calc, jucalcx(), and true().
strgarr()
subroutine, public m_calculator_plus::strgarr (character(len=*), intent(in) line, integer, intent(in) ivals, real, dimension(ivals) vals, integer, intent(out) ifound, character(len=*), intent(in) delims0, integer, intent(out) ierr)
NAME
strgarr(3f) - [M_calculator_plus] read a string into an array using jucalc(3f) calculator
SYNOPSIS
subroutine strgarr(line,ivals,vals,ifound,delims,ierr)
character(len=*), intent=(in) :: line integer, intent=(in) :: ivals real, intent=(out) :: vals(ivals) integer, intent=(out) :: ifound character(len=*), intent=(in) :: delims integer, intent=(out) :: ierr
DESCRIPTION
strgarr() returns an array of real values from a string containing numeric expressions. Use strgar2() if you are going to permit string expressions with " delimiters.
o strgarr() parses the string at the specified delimiters and calls the calculator routine JUCALCX(3f) to evaluate the expressions. o It counts the number of values found. o Once the maximum allowable number of values have been found strgarr() returns, ignoring the rest of the line. o If an error occurs the error flag returns the column number where the expression that failed begins.
line LINE is a string of numeric expressions. Each expression can be up to (iclen_calc=255) characters long. The syntax of an expression is as described in the main document of the Calculator Library. Assuming the delimiters include a space character an example would be:
'A=10 100 300E2/42.6 sin(3.1416/5)'
Only numeric expressions are expected; so no use of the delimiter characters is allowed except as a delimiter, even in quoted strings. ivals IVALS is the maximum number of values to return. vals(ivals) VALS is an array filled with the numeric values calculated from the expressions in LINE. ifound IFOUND is the number of values successfully returned in VALS delims DELIMS is a character to use as an expression delimiter. It is commonly set to a space and semi-colon(' ;'). ierr IERR returns 0 if no error occurred. If an error did occur, it returns the column number the expression started at that could not be evaluated.
DEPENDENCIES
o jucalcx o User-supplied routines: All programs that call the calculator routine must supply their own JUOWN1 and C procedures. See the example program for samples. o juown1 o c
EXAMPLES
Sample program:
   program T_strgarr
   use M_kracken, only: sget, kracken, lget
   use M_calculator_plus, only : strgarr
   real vals(41)
   character(len=80) :: line=' '
   character(len=10) :: delims=' ;'
   !  define command arguments, default values and crack command line
   call kracken('cmd','-d " ;" -test .false. -help .false. -begin -end')
   !----------------------------------------------------------
   write(*,*)'SGET',trim(sget('cmd_test'))
   write(*,*)'LGET',lget('cmd_test')
   if(lget('cmd_test'))then   ! cursory test
      call strgarr("10;2/3;sin(4.314)",41,vals,ifound,' ;',ierr)
      write(*,*)'values are',(vals(i),i=1,ifound)
      sumtarget= 9.74497986
      tol=       0.00000001
      sumup=sum(vals(:ifound))
      ipass=0
      if(ifound.ne.3) ipass=ipass+1
      if(ierr.ne.0)   ipass=ipass+2
      if( sumup >= (sumtarget-tol) .and. sumup <= (sumtarget+tol) ) then
      else
         ipass=ipass+4
      endif
      if(ipass.eq.0)then
         write(*,*)'sum is ',sumup
         write(*,*)'number of values is',ifound
         write(*,*)'error flag is',ierr
         write(*,*)'STRGARR*: PASSED'
         stop(0)
      else
         write(*,*)'IFOUND:',ifound
         write(*,*)'IERR  :',ierr
         write(*,*)'SUM   :',sumup
         write(*,*)'STRGARR*: FAILED',ipass
         stop(-1)
      endif
   endif
   !----------------------------------------------------------
   delims=sget('cmd_d')
   write(*,*)'DELIMS=[',trim(delims),']'
   !----------------------------------------------------------
   line=sget('cmd_begin')
   write(*,*)'BEGIN:',trim(line)
   if(line.ne.' ')then
      call strgarr(line,41,vals,ifound,delims,ierr)
   endif
   !----------------------------------------------------------
   line=sget('cmd_oo')
   write(*,*)'LINE:',trim(line)
   if(line.ne.' ')then
      call strgarr(line,41,vals,ifound,delims,ierr)
      write(*,*)(VALS(I),I=1,IFOUND)
   else
      INFINITE: do
         read(*,'(a)',iostat=ios)line
         if(ios.ne.0)then
            exit INFINITE
         endif
         call strgarr(line,41,vals,ifound,delims,ierr)
         write(*,*)IERR,IFOUND,':',(VALS(I),I=1,IFOUND)
      enddo INFINITE
   endif
   !----------------------------------------------------------
   line=sget('cmd_end')
   write(*,*)'END',trim(line)
   if(line.ne.' ')then
      call strgarr(line,41,vals,ifound,delims,ierr)
      write(*,*)'END:',(VALS(I),I=1,IFOUND)
   endif
   !----------------------------------------------------------
   end
   ! NOTE: user must supply the JUOWN1 and C procedures.
SEE ALSO
To parse a list of numbers instead of expressions see STRGAR(). If there is only one expression see RNUM0(), JUCALCX(), JUCALC().
REFERENCES
none. AUTHOR John S. Urban
VERSION 1.0, 19971123
References jucalcx().