GeneralPurposeFortran: m_time_oop Module Reference
m_time_oop Module Reference
Data Types
interface date_time
Functions/Subroutines
type(date_time) function construct_from_dat (dat)
type(date_time) function construct_from_jed (jed)
type(date_time) function construct_from_uet (uet)
integer function, dimension(8), private dt2d (self)
real(kind=realtime) function, private epoch (self)
character(len=:) function, allocatable, private format (self, fmt)
real(kind=realtime) function, private julian (self)
integer function, private ordinal (self)
integer function, private weekday (self)
type(date_time) function, private delta (self, year, month, day, tz, hour, minute, second, millisecond, week, duration)
subroutine, private init_dt (self, year, month, day, tz, hour, minute, second, millisecond, type, dat)
type(date_time) function plus_seconds (self, seconds)
type(date_time) function minus_seconds (self, seconds)
real(kind=realtime) function minus_date_time (self, other)
logical function eq (self, other)
logical function lt (self, other)
logical function gt (self, other)
logical function le (self, other)
logical function ge (self, other)
logical function ne (self, other)
Function/Subroutine Documentation
construct_from_dat()
type(date_time) function m_time_oop::construct_from_dat (integer, dimension(:), intent(in) dat) private
References u2d.
construct_from_jed()
type(date_time) function m_time_oop::construct_from_jed (real(kind=realtime), intent(in) jed) private
References construct_from_dat(), and m_time::j2d().
construct_from_uet()
type(date_time) function m_time_oop::construct_from_uet (integer, intent(in) uet) private
References construct_from_dat(), and u2d.
delta()
type(date_time) function, private m_time_oop::delta (class(date_time), intent(in) self, integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional tz, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, integer, intent(in), optional week, character(len=*), intent(in), optional duration) private
References construct_from_dat(), d2u, dt2d(), then(), and u2d.
dt2d()
integer function, dimension(8), private m_time_oop::dt2d (class(date_time), intent(in) self) private
epoch()
real(kind=realtime) function, private m_time_oop::epoch (class(date_time), intent(in) self) private
References d2u, and dt2d().
eq()
logical function m_time_oop::eq (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u, and dt2d().
format()
character(len=:) function, allocatable, private m_time_oop::format (class(date_time), intent(in) self, character(len=*), intent(in), optional fmt) private
References dt2d(), fmtdate, and m_strings::upper().
ge()
logical function m_time_oop::ge (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u, and dt2d().
gt()
logical function m_time_oop::gt (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u, dt2d(), and gt.
init_dt()
subroutine, private m_time_oop::init_dt (class(date_time) self, integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional tz, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, character(len=*), intent(in), optional type, integer, dimension(8), intent(in), optional dat) private
References construct_from_dat(), d2u, dt2d(), and u2d.
julian()
real(kind=realtime) function, private m_time_oop::julian (class(date_time), intent(in) self) private
References d2j, and dt2d().
le()
logical function m_time_oop::le (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u, and dt2d().
lt()
logical function m_time_oop::lt (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u, dt2d(), and lt.
minus_date_time()
real(kind=realtime) function m_time_oop::minus_date_time (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u, and dt2d().
minus_seconds()
type(date_time) function m_time_oop::minus_seconds (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds) private
References construct_from_dat(), d2u, dt2d(), and u2d.
ne()
logical function m_time_oop::ne (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u, and dt2d().
ordinal()
integer function, private m_time_oop::ordinal (class(date_time), intent(in) self) private
References dt2d().
plus_seconds()
type(date_time) function m_time_oop::plus_seconds (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds) private
References construct_from_dat(), d2u, dt2d(), and u2d.
weekday()
integer function, private m_time_oop::weekday (class(date_time), intent(in) self) private
References dt2d().