GeneralPurposeFortran: m_kracken Module Reference
m_kracken Module Reference
Functions/Subroutines
subroutine, public retrev (name, val, len, ier)
NAME
RETREV(3f) - [ARGUMENTS:M_kracken] get keyword value as a string from a command's argument list processed by kracken(3f)
real(kind=dp) function, public dget (keyword)
NAME
dget - [ARGUMENTS:M_kracken] given keyword fetch doubleprecision value from command argument
SYNOPSIS
real function, public rget (keyword)
NAME
rget - [ARGUMENTS:M_kracken] given keyword fetch real value from command argument
SYNOPSIS
integer function, public iget (keyword)
NAME
iget - [ARGUMENTS:M_kracken] given keyword fetch integer value from command argument
logical function, public lget (keyword)
NAME
lget - [ARGUMENTS:M_kracken] given keyword fetch logical value from command arguments
SYNOPSIS
character(len=:) function, allocatable, public sget (name, ilen)
NAME
sget - [ARGUMENTS:M_kracken] given keyword fetch string value and length from command arguments
SYNOPSIS
real(kind=dp) function, dimension(:), allocatable, public dgets (keyword)
NAME
dgets - [ARGUMENTS:M_kracken] given keyword fetch doubleprecision array from command arguments
SYNOPSIS
integer function, dimension(:), allocatable, public igets (keyword)
NAME
igets - [ARGUMENTS:M_kracken] given keyword fetch integer array from command arguments
SYNOPSIS
real function, dimension(:), allocatable, public rgets (keyword)
NAME
rgets - [ARGUMENTS:M_kracken] given keyword fetch real array from command arguments
SYNOPSIS
logical function, dimension(:), allocatable, public lgets (keyword)
NAME
lget - [ARGUMENTS:M_kracken] given keyword fetch logical array from command argument
SYNOPSIS
character(len=ipvalue) function, dimension(:), allocatable, public sgets (name, delim)
NAME
sgets - [ARGUMENTS:M_kracken] given keyword fetch string value parsed on whitespace into an array
SYNOPSIS
subroutine, public kracken (verb, string, error_return)
NAME
kracken(3f) - [ARGUMENTS:M_kracken] crack command line options on Fortran programs, using "-KEYWORD VALUE" syntax
SYNOPSIS
subroutine, public setprompts (verb, init)
NAME
setprompts(3f) - [ARGUMENTS:M_kracken] set explicit prompts for keywords in interactive mode
SYNOPSIS
subroutine, public dissect (verb, init, pars, error_return)
NAME
dissect(3f) - [ARGUMENTS:M_kracken] convenient call to parse() – define defaults, then process
subroutine, public parse (verb, string, allow, error_return)
NAME
parse(3f) - [ARGUMENTS:M_kracken] parse user command and store tokens into Language Dictionary
subroutine, public store (name1, value1, allow1, ier)
NAME
store(3fp) - [ARGUMENTS:M_kracken] add or replace dict. name's value (if allow='add' add name if necessary)
SYNOPSIS
subroutine, private bounce (varnam, index, dictionary, ier, mssge)
NAME
bounce(3fp) - [ARGUMENTS:M_kracken] find index in Language Dictionary where VARNAM can be found
SYNOPSIS
subroutine, private add_string (newnam, nchars, index, ier)
NAME
add_string(3fp) - [ARGUMENTS:M_kracken] Add new string name to Language Library dictionary
integer function, private subscript (chars0)
NAME
subscript(3fp) - [ARGUMENTS:M_kracken] return the subscript value of a string when given it's name
SYNOPSIS
subroutine, private get_command_arguments (string, istatus)
NAME
get_command_arguments(3fp) - [ARGUMENTS:M_kracken] return all command arguments as an allocated string
subroutine, private menu (verb)
NAME
menu(3fp) - [ARGUMENTS:M_kracken] prompt for values using a menu interface
SYNOPSIS
subroutine, public show (VERB_NAME0, VERBS_ONLY, IWIDE0)
NAME
show(3f) - [ARGUMENTS:M_kracken] dump dictionary entries
Variables
character(len= *), parameter ident ="@(#)M_kracken(3fm):parse command line options of Fortran programs using Unix-like syntax"
integer, parameter, public ipic =4000
logical, public stop_command =.false.
integer, parameter, public ipvalue =4096
integer, parameter, public ipcmd =32768
integer, parameter, public ipverb =20
integer, parameter dp = kind(0.d0)
integer, parameter k_int = SELECTED_INT_KIND(9)
integer, parameter k_dbl = SELECTED_REAL_KIND(15, 300)
character(len=ipvalue), dimension(ipic) dict_vals =" "
character(len=ipverb), dimension(ipic) dict_verbs =" "
integer(kind=k_int), dimension(ipic) dict_lens =0
integer(kind=k_int), dimension(ipic) dict_calls =0
character(len=1), save, public kracken_comment ='#'
character(len=ipcmd), public leftover =' '
integer, save, public current_command_length =0
Function/Subroutine Documentation
add_string()
subroutine, private m_kracken::add_string (character(len=*), intent(in) newnam, integer, intent(in) nchars, integer, intent(in) index, integer, intent(out) ier) private
NAME
add_string(3fp) - [ARGUMENTS:M_kracken] Add new string name to Language Library dictionary
SYNOPSIS
subroutine add_string(newnam,nchars,index,ier)
character(len=*),intent(in) :: newnam integer,intent(in) :: nchars integer,intent(in) :: index integer,intent(out) :: ier
DESCRIPTION
OPTIONS
NEWNAM new variable name to add to dictionary NCHARS number of characters in NEWNAM
RETURNS
EXAMPLE
References dict_calls, dict_lens, dict_vals, dict_verbs, and ipic.
bounce()
subroutine, private m_kracken::bounce (character(len=*), intent(in) varnam, integer, intent(out) index, character(len=*), dimension(:), intent(in) dictionary, integer, intent(out) ier, character(len=*), intent(out) mssge) private
NAME
bounce(3fp) - [ARGUMENTS:M_kracken] find index in Language Dictionary where VARNAM can be found
SYNOPSIS
subroutine bounce(varnam,index,dictionary,ier,mssge)
character(len=*),intent(in) :: varnam integer,intent(out) :: index character(len=*),dimension(:),intent(in) :: dictionary integer,intent(out) :: ier character(len=*),intent(out) :: mssge
DESCRIPTION
OPTIONS
VARNAM variable name to look up in dictionary DICTIONARY sorted dictionary array to find varnam in
RETURNS
INDEX location where variable is or should be IER error code MSSGE message to describe error code
EXAMPLE
References m_debug::debug, and ipic.
dget()
real(kind=dp) function, public m_kracken::dget (character(len=*), intent(in) keyword)
NAME
dget - [ARGUMENTS:M_kracken] given keyword fetch doubleprecision value from command argument
SYNOPSIS
function dget(keyword) result(value)
character(len=*),intent(in) :: keyword doubleprecision :: value
DESCRIPTION
The dget(3f) function returns a scalar doubleprecision value from a command line argument using the M_kracken(3fm) module.
OPTIONS
KEYWORD the dictionary keyword (in form VERB_KEYWORD) to retrieve. The VERB name comes from the first argument of the KRACKEN(3f) call. The KEYWORD is a keyword from the KRACKEN(3f) call that should be interpreted as a doubleprecision value.
RETURNS
VALUE doubleprecision value returned by function
EXAMPLE
Sample program
program demo_dget use M_kracken, only: kracken, dget implicit none doubleprecision :: val ! define command arguments and parse user command call kracken('demo','-val 3.1416') val=dget('demo_val') ! get any values specified on -val option write(*,*)val ! print the value end program demo_dget
Example program runs:
$ demo_dget 3.14159989
$ demo_dget -val 10 10.0000000
$ demo_dget -val 3.000 3.00000000
References sget().
dgets()
real(kind=dp) function, dimension(:), allocatable, public m_kracken::dgets (character(len=*), intent(in) keyword)
NAME
dgets - [ARGUMENTS:M_kracken] given keyword fetch doubleprecision array from command arguments
SYNOPSIS
function dgets(keyword) result(darray)
character(len=*),intent(in) :: keyword doubleprecision,allocatable :: DARRAY
DESCRIPTION
The dgets(3f) function returns a dynamically allocated array of doubleprecision values from a string that is the value for a command line option. It is part of the M_kracken(3fp) module.
Values that cannot be read as a numeric value are returned as a zero (0).
OPTIONS
keyword dictionary name to retrieve, of form VERB_NAME where VERB is taken from the first parameter of the call to KRACKEN(3f) or DISSECT(3f).
RETURNS
darray double precision numeric array returned by function
EXAMPLE
Sample program
program demo_dnums use M_kracken, only: kracken, dgets implicit none doubleprecision,allocatable :: vals(:) integer :: i ! define command arguments and parse user command call kracken('demo','-nums 1 2 3 1000 100,000 11.11111 77.77777 -77.7777') vals=dgets('demo_nums') ! get any values specified for -nums write(*,'(*(g0:,","))')(vals(i),i=1,size(vals)) ! print the values end program demo_dnums
Example program runs:
$ demo_dnums 1.0000000000000000,2.0000000000000000,3.0000000000000000, 1000.0000000000000,100000.00000000000,11.111110000000000, 77.777770000000004,-77.777699999999996
$ demo_dnums -nums 89,123,456.789 10.9999999 89123456.789000005,10.999999900000001
References sget(), and m_strings::split().
dissect()
subroutine, public m_kracken::dissect (character(len=*), intent(in) verb, character(len=*), intent(in) init, character(len=*), intent(in) pars, integer, intent(out), optional error_return)
NAME
dissect(3f) - [ARGUMENTS:M_kracken] convenient call to parse() – define defaults, then process
SYNOPSIS
subroutine dissect(verb,init,pars,error_return)
character(len=*),intent(in) :: verb character(len=*),intent(in) :: init character(len=*),intent(in) :: pars integer,intent(out),optional :: error_return
DESCRIPTION
OPTIONS
VERB the name of the command to be reset/defined INIT used to define command options; usually hard-set in the program. PARS defines the command options to be set, usually from user input
RETURNS
ERROR_RETURN error code. If zero no error occurred.
EXAMPLE
References m_debug::debug, lget(), menu(), parse(), and store().
get_command_arguments()
subroutine, private m_kracken::get_command_arguments (character(len=:), intent(out), allocatable string, integer, intent(out) istatus) private
NAME
get_command_arguments(3fp) - [ARGUMENTS:M_kracken] return all command arguments as an allocated string
SYNOPSIS
subroutine get_command_arguments(string,istatus)
character(len=:),allocatable,intent(out) :: string integer,intent(out) :: istatus
DESCRIPTION
RETURNS
STRING composed of all command arguments concatenated into a string ISTATUS status (non-zero means error)
EXAMPLE
Sample usage if procedure is made public for debugging:
program testit use M_journal, only : journal implicit none integer :: ier character(len=:),allocatable :: cmd call get_command_arguments(cmd,ier) write(*,*)'CMD=',trim(cmd) write(*,*)'LEN(CMD)=',len(cmd) write(*,*)'IER=',ier end program testit
References length().
iget()
integer function, public m_kracken::iget (character(len=*), intent(in) keyword)
NAME
iget - [ARGUMENTS:M_kracken] given keyword fetch integer value from command argument
SYNOPSIS
function iget(keyword) result(value)
 character(len=*),intent(in)  :: keyword
 integer              :: value
DESCRIPTION
The iget(3f) function returns a scalar integer value from a command line argument using the M_kracken(3fm) module.
OPTIONS
KEYWORD the dictionary keyword (in form VERB_KEYWORD) to retrieve. The VERB name comes from the first argument of the KRACKEN(3f) call. The KEYWORD is a keyword from the KRACKEN(3f) call that should be interpreted as a integer value.
RETURNS
VALUE integer value returned by function
EXAMPLE
Sample program
program demo_iget use M_kracken, only: kracken, iget implicit none integer :: val ! define command arguments and parse user command call kracken('demo','-val 31416') val=iget('demo_val') ! get any values specified on -val option write(*,*)val ! print the value end program demo_iget
Example program runs:
$ demo_iget 31416
$ demo_iget -val 10 10
$ demo_iget -val 3.000 3
References dget().
igets()
integer function, dimension(:), allocatable, public m_kracken::igets (character(len=*), intent(in) keyword)
NAME
igets - [ARGUMENTS:M_kracken] given keyword fetch integer array from command arguments
SYNOPSIS
function igets(keyword) result(iarray)
character(len=*),intent(in) :: keyword integer,allocatable :: iarray(:)
DESCRIPTION
The igets(3f) function returns a dynamically allocated array of integers from a string that is the value for a command line option. It is part of the M_kracken(3fp) module.
Values that cannot be read as an integer value are returned as a zero (0).
OPTIONS
KEYWORD the dictionary keyword (in form VERB_KEYWORD) to retrieve. The VERB name comes from the first argument of the KRACKEN(3f) call. The KEYWORD is a keyword from the KRACKEN(3f) call that should be interpreted as a list of INTEGER values. Decimal values are allowed but truncated. Note that comma characters are ignored.
RETURNS
IARRAY INTEGER array returned by function
EXAMPLE
Sample program
program demo_inums use M_kracken, only: kracken, igets implicit none integer,allocatable :: vals(:) integer :: i ! define command arguments and parse user command call kracken('demo','-nums 1 2 3 100 1000 10000 100,000 11.11111 77.77777 -77.7777') ! get any values specified for -nums vals=igets('demo_nums') if(size(vals).gt.0)then ! print the requested values write(*,'(*(i0:,","))')(vals(i),i=1,size(vals)) endif end program demo_inums
Example program runs:
$ demo_inums 1,2,3,100,1000,10000,100000,11,77,-77 $ demo_inums -val 89,123,456 10.9999999 89123456,10
References dgets().
kracken()
subroutine, public m_kracken::kracken (character(len=*), intent(in) verb, character(len=*), intent(in) string, integer, intent(out), optional error_return)
NAME
kracken(3f) - [ARGUMENTS:M_kracken] crack command line options on Fortran programs, using "-KEYWORD VALUE" syntax
SYNOPSIS
subroutine kracken(verb, string[,ierror])
character(len=*), intent(in) :: verb character(len=*), intent(in) :: string integer, intent(out), optional :: ierror
DESCRIPTION
 This is the main public procedure in the M_kracken(3f) module.
 It is used to define the command line options, their default
 values, and to crack the command line options using a syntax
 that looks very much like an execution of the program.
OPTIONS
VERB arbitrary command name, usually 'cmd' or the name of the program calling the routine. This defines the variable prefix name used by the other functions to retrieve command option values.
STRING prototype command to define keywords and defaults. This string is simply a list of all keywords and their default values exactly as you would type them on the command line, with default values explicitly set.
IERROR If an error occurs such as an unknown keyword the calling program will be stopped unless the optional parameter IERROR is present. If present, it is up to the calling program to decide what to do if a non-zero value is returned.
EXAMPLE
Sample program:
program krackenbasic
use M_kracken
! define command arguments, default values and crack command line
call kracken('cmd',              &
   &   '-int 20                  &
   &   -real 10e3                &
   &   -file input               &
   &   -dble 4.11223344556677d0  &
   &   -help    .false.          &
   &   -version .false.         '&
   &   )
! that's it. You defined your command arguments and their default
! values and parsed the user-supplied command line arguments.
! Now you can just retrieve the values as strings using
! names of the form VERB_SWITCHNAME anywhere in your program.
! Note that the special name "VERB_oo"  is for the string
! before any switch.
   if(lget('cmd_help'))then ! was -help specified?
      write(*,*)'The help text'
      stop
   endif
   if(lget('cmd_version'))then ! was -version specified?
      write(*,*)'version 1.0 20161030'
      stop
   endif
   ! convert all the remaining options to scalar values
   ! and call a procedure with the values
   call mymain(                  &
   & sget('cmd_file'),           &
   & rget('cmd_real'),           &
   & dget('cmd_dble'),           &
   & iget('cmd_int')             &
   & )
end program krackenbasic
subroutine mymain(filename,value1,value2,ivalue3)
! this routine is using conventional values and does
! not use M_kracken(3fm) module at all
implicit none
character(len=*),intent(in) :: filename
real,intent(in)             :: value1
doubleprecision,intent(in)  :: value2
integer,intent(in)          :: ivalue3
   ! just to show the command arguments have
   ! been processed echo the values
   print *, 'filename=',trim(filename)
   print *, 'values=',value1,value2,ivalue3
end subroutine mymain
expected output from : "./cmd"
   filename=input
   values= 10000.0000  4.1122334455667700  20
expected output from : "./cmd -file myfile -int 1234"
   filename=myfile
   values= 10000.0000  4.1122334455667700  1234
References m_debug::debug, dissect(), and get_command_arguments().
lget()
logical function, public m_kracken::lget (character(len=*), intent(in) keyword)
NAME
lget - [ARGUMENTS:M_kracken] given keyword fetch logical value from command arguments
SYNOPSIS
function lget(keyword) result(lval)
character(len=*),intent(in) :: keyword logical :: lval
DESCRIPTION
The lget(3f) function returns a scalar logical value from a command line argument using the M_kracken(3fm) module.
OPTIONS
keyword the dictionary keyword (in form VERB_KEYWORD) to retrieve. The VERB name comes from the first argument of the KRACKEN(3f) call. The KEYWORD is a keyword from the second argument to the KRACKEN(3f) call.
RETURNS
lval logical value returned by function. The input value should be from the case-insensitive list of the words "true, false, t, f, yes, no, y, n, .false., .true., .f., .t".
EXAMPLE
Sample program:
program demo_lget use M_kracken, only: kracken, lget implicit none logical :: val ! define command arguments and parse user command call kracken('demo','-truth .F.') ! get any values specified on command line for -truth val=lget('demo_truth') write(*,'("The truth is ",l1)')val end program demo_lget
Example program runs:
$ demo_lget # uses the default The truth is F $ demo_lget -truth # A BLANK VALUE IS TRUE The truth is T $ demo_lget -truth yes # Y, yes, T, true, .T., .true. are all true The truth is T $ demo_lget -truth F # N, no, F, false, .F., .FALSE. are all false The truth is F
References false(), sget(), true(), and m_strings::upper().
lgets()
logical function, dimension(:), allocatable, public m_kracken::lgets (character(len=*), intent(in) keyword)
NAME
lget - [ARGUMENTS:M_kracken] given keyword fetch logical array from command argument
SYNOPSIS
function lgets(keyword) result(lvals)
character(len=*),intent(in) :: keyword logical,allocatable :: lvals(:)
DESCRIPTION
The lgets(3f) function returns a dynamically allocated array of logical values from a string that is the value for a command line option. It is part of the M_kracken(3fp) module.
Values that cannot be read as a logical value are returned as a ".FALSE.".
OPTIONS
keyword the dictionary keyword (in form VERB_KEYWORD) to retrieve. The VERB name comes from the first argument of the KRACKEN(3f) call. The KEYWORD is a keyword from the second argument to the KRACKEN(3f) call.
RETURNS
lvals logical array returned by function. The input value should be from the case-insensitive list of the words "true, false, t, f, yes, no, y, n, .false., .true., .f., .t".
EXAMPLE
Sample program:
program demo_lgets use M_kracken, only: kracken, lgets implicit none logical,allocatable :: vals(:) ! define command arguments and parse user command call kracken('demo','-truths .F. .T. .F. .F. .T. .T.') ! get any values specified on command line for -truth vals=lgets('demo_truths') write(*,*)vals end program demo_lgets
Example program runs:
$ demo_lgets F T F F T T
$ demo_lgets -truths false F .f. no true .true. t T Yes No F F F F T T T T T T F
References false(), sget(), m_strings::split(), true(), and m_strings::upper().
menu()
subroutine, private m_kracken::menu (character(len=*), intent(in) verb) private
NAME
menu(3fp) - [ARGUMENTS:M_kracken] prompt for values using a menu interface
SYNOPSIS
subroutine menu(verb)
character(len=*),intent(in) :: verb
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References bounce(), m_debug::debug, dict_lens, dict_vals, dict_verbs, false(), ipic, parse(), m_strings::s2v(), stop_command, store(), and true().
parse()
subroutine, public m_kracken::parse (character(len=*), intent(in) verb, character(len=*), intent(in) string, character(len=*), intent(in) allow, integer, intent(out), optional error_return)
NAME
parse(3f) - [ARGUMENTS:M_kracken] parse user command and store tokens into Language Dictionary
SYNOPSIS
subroutine parse(verb,string,allow,error_return)
character(len=*),intent(in) :: verb character(len=*),intent(in) :: string character(len=*),intent(in) :: allow integer,optional,intent(out) :: error_return
DESCRIPTION
given a string of form
value -var value -var value
define variables of form
verb_var(i) = value
–var will become verb__var
o values may be in double quotes if they contain alphameric characters o a # signifies the rest of the line is a comment o adjacent double quotes put one double quote into value o processing ends when an unquoted semi-colon or end of string is encountered o the variable name for the first value is verb_init (often verb_oo) o leading and trailing blanks are removed from values o call it once to give defaults o call it again and vars without values are set to null strings
OPTIONS
VERB          command name to process
STRING        string is character input string with first verb removed (options + other commands)
ALLOW         keyword indicating whether commands may be added or only replaced
ERROR_RETURN  error code. If zero, no error occurred
RETURNS
EXAMPLE
References current_command_length, m_debug::debug, dict_calls, kracken_comment, leftover, lget(), menu(), store(), and subscript().
retrev()
subroutine, public m_kracken::retrev (character(len=*), intent(in) name, character(len=*), intent(out) val, integer, intent(out) len, integer, intent(out) ier)
NAME
RETREV(3f) - [ARGUMENTS:M_kracken] get keyword value as a string from a command's argument list processed by kracken(3f)
SYNOPSIS
SUBROUTINE retrev(name, string, len, ier)
CHARACTER(len=*),intent(in) :: name CHARACTER(len=*),intent(out) :: string INTEGER,intent(out) :: len INTEGER,intent(out) :: ier
DESCRIPTION
When a command has had it's command argument list parsed using the kracken(3f) routine the value associated with any keyword can be retrieved as a string.
OPTIONS
 NAME    parameter name of form VERB_KEYWORD
 STRING  returned parameter value
 LEN     length of returned STRING
 IER     error flag. Any non-zero value means an error occurred
EXAMPLE
Sample program:
program demo_retrev use M_kracken, only : kracken, retrev use M_kracken, only : IPvalue ! length of keyword value implicit none character(len=IPvalue) :: val integer :: len, ier
call kracken('demo', ' -value my default string') call retrev('demo_value',val,len,ier) write(*,'(a)')'VALUE IS '//trim(val)
end program demo_retrev
Example execution and output:
$ ./demo_retrev VALUE IS my default string
$ ./demo_retrev -value use this value instead VALUE IS use this value instead
References dict_lens, dict_vals, and subscript().
rget()
real function, public m_kracken::rget (character(len=*), intent(in) keyword)
NAME
rget - [ARGUMENTS:M_kracken] given keyword fetch real value from command argument
SYNOPSIS
function rget(keyword) result(value)
character(len=*),intent(in) :: keyword real :: value
DESCRIPTION
The rget(3f) function returns a scalar real value from a command line argument using the M_kracken(3fm) module.
OPTIONS
KEYWORD the dictionary keyword (in form VERB_KEYWORD) to retrieve. The VERB name comes from the first argument of the KRACKEN(3f) call. The KEYWORD is a keyword from the KRACKEN(3f) call that should be interpreted as a REAL value.
RETURNS
VALUE real value returned by function
EXAMPLE
Sample program
program demo_rget use M_kracken, only: kracken, rget implicit none real :: val ! define command arguments and parse user command call kracken('demo','-val 3.1416') val=rget('demo_val') ! get any values specified on -val option write(*,*)val ! print the value end program demo_rget
Example program runs:
$ demo_rget 3.14159989
$ demo_rget -val 10 10.0000000
$ demo_rget -val 3.000 3.00000000
rgets()
real function, dimension(:), allocatable, public m_kracken::rgets (character(len=*), intent(in) keyword)
NAME
rgets - [ARGUMENTS:M_kracken] given keyword fetch real array from command arguments
SYNOPSIS
function rgets(keyword) result(rarray)
character(len=*),intent(in) :: keyword real,allocatable :: rarray(:)
DESCRIPTION
The rgets(3f) function returns a dynamically allocated array of real values from a string that is the value for a command line option. It is part of the M_kracken(3fp) module.
Values that cannot be read as a numeric value are returned as a zero (0).
OPTIONS
KEYWORD the dictionary keyword (in form VERB_KEYWORD) to retrieve. The VERB name comes from the first argument of the KRACKEN(3f) call. The KEYWORD is a keyword from the KRACKEN(3f) call that should be interpreted as a list of REAL values.
RETURNS
RARRAY real array returned by function
EXAMPLE
Sample program converts between Celcius and Fahrenheit
program demo_rgets use M_kracken, only: kracken, rgets implicit none real,allocatable :: val(:) integer :: i ! define command arguments and parse user command call kracken('fc','-F -C')
! get any values specified on -C option val=rgets('fc_C') ! test if have something to print in C ==> F table if(size(val).gt.0)then ! print the requested values write(*,'(a,t14,a)')'celsius','fahrenheit' write(*,'(f5.1,t14,f5.1)')(val(i),(val(i)+40.0)*9.0/5.0 - 40.0,i=1,size(val)) endif
val=rgets('fc_F') ! check for values on -F if(size(val).gt.0)then write(*,'(a,t14,a)') 'fahrenheit', 'celsius' write(*,'(f5.1,t14,f5.1)')(val(i),(val(i)+40.0)*5.0/9.0 - 40.0,i=1,size(val)) endif end program demo_rgets
Example program runs:
% demo_rgets -C -273.15 0 100 -40 37 celsius fahrenheit -273.15 -459.67 0.0 32.0 100.0 212.0 -40.0 -40.0 37.0 98.6
% demo_rgets -F -459.67 32 212 -40 98.6 fahrenheit celsius -459.67 -273.15 32.00 0.00 212.00 100.00 -40.00 -40.00 98.60 37.00
setprompts()
subroutine, public m_kracken::setprompts (character(len=*), intent(in) verb, character(len=*), intent(in) init)
NAME
setprompts(3f) - [ARGUMENTS:M_kracken] set explicit prompts for keywords in interactive mode
SYNOPSIS
subroutine setprompts(verb,init)
character(len=*),intent(in):: verb character(len=*),intent(in):: init
DESCRIPTION
Optionally set prompts for interactive prompting mode.
The syntax of the call is the same as for KRACKEN(3f)/DISSECT(3f) except that prompt
strings are given instead of default values. It is called after a call to KRACKEN(3f)
or DISSECT(3f).
OPTIONS
verb name to define prompts for string to define prompts instead of values
RETURNS
EXAMPLE
References parse().
sget()
character(len=:) function, allocatable, public m_kracken::sget (character(len=*), intent(in) name, integer, intent(out), optional ilen)
NAME
sget - [ARGUMENTS:M_kracken] given keyword fetch string value and length from command arguments
SYNOPSIS
function sget(name,ilen) result(string)
character(len=*),intent(in) :: name ! name to look up in dictionary integer,intent(out),optional :: ilen ! length of returned output string character(len=:),allocatable :: string ! returned value
DESCRIPTION
The sget(3f) function returns a scalar character value from a command line argument using the M_kracken(3fm) module.
OPTIONS
name the dictionary keyword (in form VERB_KEYWORD) to retrieve. The VERB name comes from the first argument of the KRACKEN(3f) call. The KEYWORD is a keyword from the second argument to the KRACKEN(3f) call. This routine trusts that the desired name exists. A blank is returned if the name is not in the dictionary
RETURNS
string returned string ilen optional length of returned output string
EXAMPLE
Sample program:
program demo_sget use M_kracken, only: kracken, sget, IPvalue implicit none character(len=IPvalue) :: string, a, b ! define command arguments and parse user command call kracken('demo','-string This is the default -a A default -b B default') ! get any values specified on command line for -truth string=sget('demo_string') a=sget('demo_a') b=sget('demo_b') write(*,'("string is ",a')trim(string) write(*,'("a is ",a')trim(a) write(*,'("b is ",a')trim(b) end program demo_sget
Example program runs:
$demo_sget string is This is the default a is A default b is B default
$ demo_sget -a A value for A -string new value for string -b BBBBBBB string is new value for string a is A value for A b is BBBBBBB
References dict_lens, dict_vals, and subscript().
sgets()
character(len=ipvalue) function, dimension(:), allocatable, public m_kracken::sgets (character(len=*), intent(in) name, character(len=*), intent(in), optional delim)
NAME
sgets - [ARGUMENTS:M_kracken] given keyword fetch string value parsed on whitespace into an array
SYNOPSIS
function sgets(name,delim) result(strings)
character(len=*),intent(in) :: name character(len=*),intent(in),optional :: delim character(len=IPvalue),allocatable :: strings(:)
DESCRIPTION
The sgets(3f) function returns a dynamically allocated array of character values from a string that is the value for a command line option. It is part of the M_kracken(3fp) module.
OPTIONS
name the dictionary keyword (in form VERB_KEYWORD) to retrieve. The VERB name comes from the first argument of the KRACKEN(3f) or DISSECT(3f) call. The KEYWORD is a keyword from the second argument to the KRACKEN(3f) or DISSECT(3f) call. This routine trusts that the desired name exists. A blank is returned if the name is not in the dictionary. delim characters to split the string at into elements
RETURNS
strings returned string array
EXAMPLE
Sample program:
program demo_sgets use M_kracken, only : kracken, sgets, IPvalue character(len=IPvalue),allocatable :: strings(:) call kracken('cmd',' -string This is a sentence ') strings= sgets("cmd_string") ! get -strings words print *, "string=",('['//trim(strings(i))//']',i=1,size(strings)) end program demo_sgets
Example program execution: $ xxx string=[This][is][a][sentence]
$ xxx -string parse this into words string=[parse][this][into][words]
References dict_vals, m_strings::split(), and subscript().
show()
subroutine, public m_kracken::show (character(len=*), intent(in) VERB_NAME0, logical, intent(in) VERBS_ONLY, integer, intent(in) IWIDE0)
NAME
show(3f) - [ARGUMENTS:M_kracken] dump dictionary entries
SYNOPSIS
subroutine show(VERB_NAME0,VERBS_ONLY,IWIDE0)
character(len=*),intent(in) :: VERB_NAME0 logical,intent(in) :: VERBS_ONLY integer,intent(in) :: iwide0
DESCRIPTION
Write information about a command from the command dictionary or list all the command verbs in the dictionary
OPTIONS
VERB_NAME0 verb prefix to display. Default is all VERBS_ONLY flag to show verbs only IWIDE0 if .ge. zero, how many columns wide to show just verbs
EXAMPLE
References dict_lens, dict_vals, dict_verbs, ipic, and ipverb.
store()
subroutine, public m_kracken::store (character(len=*), intent(in) name1, character(len=*), intent(in) value1, character(len=*), intent(in) allow1, integer, intent(out) ier)
NAME
store(3fp) - [ARGUMENTS:M_kracken] add or replace dict. name's value (if allow='add' add name if necessary)
SYNOPSIS
subroutine store(name1,value1,allow1,ier)
character(len=*),intent(in) :: name1 character(len=*),intent(in) :: value1 character(len=*),intent(in) :: allow1 integer,intent(out) :: ier
DESCRIPTION
OPTIONS
NAME1 name in dictionary of form VERB_KEYWORD VALUE1 value to be associated to NAME1 ALLOW1 flag to allow new VERB_KEYWORD name being added
RETURNS
IER flag if error occurs in adding or setting value
EXAMPLE
References add_string(), bounce(), m_debug::debug, dict_calls, dict_lens, dict_vals, dict_verbs, ipic, and ipverb.
subscript()
integer function, private m_kracken::subscript (character(len=*), intent(in) chars0) private
NAME
subscript(3fp) - [ARGUMENTS:M_kracken] return the subscript value of a string when given it's name
SYNOPSIS
function subscript(chars0)
character(len=*),intent(in) :: chars0
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References bounce(), and dict_verbs.
Variable Documentation
current_command_length
integer, save, public m_kracken::current_command_length =0
dict_calls
integer(kind=k_int), dimension(ipic) m_kracken::dict_calls =0 private
dict_lens
integer(kind=k_int), dimension(ipic) m_kracken::dict_lens =0 private
dict_vals
character(len=ipvalue), dimension(ipic) m_kracken::dict_vals =" " private
dict_verbs
character(len=ipverb), dimension(ipic) m_kracken::dict_verbs =" " private
dp
integer, parameter m_kracken::dp = kind(0.d0) private
ident
character(len=*), parameter m_kracken::ident ="@(#)M_kracken(3fm):parse command line options of Fortran programs using Unix-like syntax"
ipcmd
integer, parameter, public m_kracken::ipcmd =32768
ipic
integer, parameter, public m_kracken::ipic =4000
ipvalue
integer, parameter, public m_kracken::ipvalue =4096
ipverb
integer, parameter, public m_kracken::ipverb =20
k_dbl
integer, parameter m_kracken::k_dbl = SELECTED_REAL_KIND(15, 300) private
k_int
integer, parameter m_kracken::k_int = SELECTED_INT_KIND(9) private
kracken_comment
character(len=1), save, public m_kracken::kracken_comment ='#'
leftover
character(len=ipcmd), public m_kracken::leftover =' '
stop_command
logical, public m_kracken::stop_command =.false.