GeneralPurposeFortran: m_display Module Reference
m_display Module Reference
Data Types
interface disp
NAME
disp(3f) - [M_display] pretty-print a matrix
interface disp_set
interface tostring
Functions/Subroutines
subroutine, public disp_set (advance, digmax, matsep, orient, sep, style, unit, zeroas)
NAME
disp_set(3f) - [M_display] set default options for disp(3f)
subroutine, public disp_set_factory ()
NAME
tostring_disp_factory(3f) - [M_display] set DISP(3f) output back to original defaults
subroutine avoid_compiler_warnings
subroutine, public tostring_set (sep, rfmt, ifmt, trimb, trimz)
NAME
tostring_set(3f) - [M_display] set modes for TOSTRING(3f)
subroutine, public tostring_set_factory ()
NAME
tostring_set_factory(3f) - [M_display] set TOSTRING(3f) output back to original defaults
subroutine disp_set_ds (settings)
type(disp_settings) function, public disp_get ()
NAME
subroutine disp_scalar_int (x, fmt, advance, sep, trim, unit, zeroas)
subroutine disp_title_scalar_int (title, x, fmt, advance, sep, style, trim, unit, zeroas)
subroutine disp_vector_int (x, fmt, advance, lbound, sep, style, trim, unit, orient, zeroas)
subroutine disp_title_vector_int (title, x, fmt, advance, lbound, sep, style, trim, unit, orient, zeroas)
subroutine disp_matrix_int (x, fmt, advance, lbound, sep, style, trim, unit, zeroas)
subroutine disp_title_matrix_int (title, x, fmt, advance, lbound, sep, style, trim, unit, zeroas)
subroutine disp_dint (title, x, SE)
subroutine tobox_dint (title, x, SE, wid, nbl)
subroutine find_editdesc_dint (x, SE, wid, nbl)
subroutine getwid_dint (xmaxv, xminv, xzero, xallz, SE, wid, nbl)
character(len_f_dint([x], tosset % ifmt)) function tostring_s_dint (x)
NAME
tostring(3f) - [M_display] change numbers to a string
character(len_f_dint([x], fmt)) function tostring_sf_dint (x, fmt)
character(len_f_dint(x, tosset % ifmt)) function tostring_dint (x)
character(len_f_dint(x, fmt)) function tostring_f_dint (x, fmt)
pure integer function len_f_dint (x, fmt)
pure integer function widthmax_dint (x, fmt)
subroutine disp_s_sngl (x, fmt, advance, digmax, sep, trim, unit, zeroas)
subroutine disp_v_sngl (x, fmt, advance, digmax, lbound, sep, style, trim, unit, orient, zeroas)
subroutine disp_m_sngl (x, fmt, advance, lbound, sep, style, trim, unit, digmax, zeroas)
subroutine disp_ts_sngl (title, x, fmt, advance, digmax, sep, style, trim, unit, zeroas)
subroutine disp_tv_sngl (title, x, fmt, advance, digmax, lbound, sep, style, trim, unit, orient, zeroas)
subroutine disp_tm_sngl (title, x, fmt, advance, digmax, lbound, sep, style, trim, unit, zeroas)
subroutine disp_sngl (title, x, SE)
subroutine tobox_sngl (title, x, SE, wid, nbl)
pure integer function maxw_sngl (x, d)
subroutine find_editdesc_sngl (x, SE, wid, nbl)
subroutine getwid_sngl (xmaxv, xminv, xzero, xallz, xnonn, xalln, SE, wid, nbl)
character(len_f_sngl([x], tosset % rfmt)) function tostring_s_sngl (x)
character(len_f_sngl([x], fmt)) function tostring_sf_sngl (x, fmt)
character(len_f_sngl(x, tosset % rfmt)) function tostring_sngl (x)
character(len_f_sngl(x, fmt)) function tostring_f_sngl (x, fmt)
pure integer function len_f_sngl (x, fmt)
pure integer function widthmax_sngl (x, fmt)
subroutine disp_s_cplx (x, fmt, fmt_imag, advance, digmax, sep, trim, unit)
subroutine disp_v_cplx (x, fmt, fmt_imag, advance, digmax, lbound, sep, style, trim, unit, orient)
subroutine disp_m_cplx (x, fmt, fmt_imag, advance, digmax, lbound, sep, style, trim, unit)
subroutine disp_ts_cplx (title, x, fmt, fmt_imag, advance, digmax, sep, style, trim, unit)
subroutine disp_tv_cplx (title, x, fmt, fmt_imag, advance, digmax, lbound, sep, style, trim, unit, orient)
subroutine disp_tm_cplx (title, x, fmt, fmt_imag, advance, digmax, lbound, sep, style, trim, unit)
subroutine disp_cplx (title, x, SE, SEim, n)
subroutine tobox_cplx (title, x, SE, SEim, widre, widim, nblre, nblim, m, n)
character(len_s_cplx(x, tosset % rfmt)) function tostring_s_cplx (x)
character(len_s_cplx(x, fmt)) function tostring_sf_cplx (x, fmt)
character(len_f_cplx(x, tosset % rfmt)) function tostring_cplx (x)
character(len_f_cplx(x, fmt)) function tostring_f_cplx (x, fmt)
pure integer function len_s_cplx (x, fmt)
pure integer function len_f_cplx (x, fmt)
subroutine disp_s_dble (x, fmt, advance, digmax, sep, trim, unit, zeroas)
subroutine disp_v_dble (x, fmt, advance, digmax, lbound, sep, style, trim, unit, orient, zeroas)
subroutine disp_m_dble (x, fmt, advance, lbound, sep, style, trim, unit, digmax, zeroas)
subroutine disp_ts_dble (title, x, fmt, advance, digmax, sep, style, trim, unit, zeroas)
subroutine disp_tv_dble (title, x, fmt, advance, digmax, lbound, sep, style, trim, unit, orient, zeroas)
subroutine disp_tm_dble (title, x, fmt, advance, digmax, lbound, sep, style, trim, unit, zeroas)
subroutine disp_dble (title, x, SE)
subroutine tobox_dble (title, x, SE, wid, nbl)
pure integer function maxw_dble (x, d)
subroutine find_editdesc_dble (x, SE, wid, nbl)
subroutine getwid_dble (xmaxv, xminv, xzero, xallz, xnonn, xalln, SE, wid, nbl)
character(len_f_dble([x], tosset % rfmt)) function tostring_s_dble (x)
character(len_f_dble([x], fmt)) function tostring_sf_dble (x, fmt)
character(len_f_dble(x, tosset % rfmt)) function tostring_dble (x)
character(len_f_dble(x, fmt)) function tostring_f_dble (x, fmt)
pure integer function len_f_dble (x, fmt)
pure integer function widthmax_dble (x, fmt)
subroutine disp_s_cpld (x, fmt, fmt_imag, advance, digmax, sep, trim, unit)
subroutine disp_v_cpld (x, fmt, fmt_imag, advance, digmax, lbound, sep, style, trim, unit, orient)
subroutine disp_m_cpld (x, fmt, fmt_imag, advance, digmax, lbound, sep, style, trim, unit)
subroutine disp_ts_cpld (title, x, fmt, fmt_imag, advance, digmax, sep, style, trim, unit)
subroutine disp_tv_cpld (title, x, fmt, fmt_imag, advance, digmax, lbound, sep, style, trim, unit, orient)
subroutine disp_tm_cpld (title, x, fmt, fmt_imag, advance, digmax, lbound, sep, style, trim, unit)
subroutine disp_cpld (title, x, SE, SEim, n)
subroutine tobox_cpld (title, x, SE, SEim, widre, widim, nblre, nblim, m, n)
character(len_s_cpld(x, tosset % rfmt)) function tostring_s_cpld (x)
character(len_s_cpld(x, fmt)) function tostring_sf_cpld (x, fmt)
character(len_f_cpld(x, tosset % rfmt)) function tostring_cpld (x)
character(len_f_cpld(x, fmt)) function tostring_f_cpld (x, fmt)
pure integer function len_s_cpld (x, fmt)
pure integer function len_f_cpld (x, fmt)
subroutine disp_s_dlog (x, fmt, advance, sep, trim, unit)
subroutine disp_v_dlog (x, fmt, advance, lbound, sep, style, trim, unit, orient)
subroutine disp_m_dlog (x, fmt, advance, lbound, sep, style, trim, unit)
subroutine disp_ts_dlog (title, x, fmt, advance, sep, style, trim, unit)
subroutine disp_tv_dlog (title, x, fmt, advance, lbound, sep, style, trim, unit, orient)
subroutine disp_tm_dlog (title, x, fmt, advance, lbound, sep, style, trim, unit)
subroutine disp_dlog (title, x, SE)
subroutine tobox_dlog (title, x, SE, wid, nbl)
character(1) function tostring_s_dlog (x)
character(len_f_dlog([x], fmt)) function tostring_sf_dlog (x, fmt)
character(1+(size(x) - 1) *(1+tosset % seplen)) function tostring_dlog (x)
character(len_f_dlog(x, fmt)) function tostring_f_dlog (x, fmt)
pure integer function len_f_dlog (x, fmt)
pure integer function widthmax_dlog (fmt)
subroutine disp_v_dchr (x, fmt, advance, lbound, sep, style, trim, unit, orient)
subroutine disp_m_dchr (x, fmt, advance, lbound, sep, style, trim, unit)
subroutine disp_ts_dchr (title, x, fmt, advance, sep, style, trim, unit)
subroutine disp_nonopt_dchr (title, x, fmt, advance, sep, style, trim, unit)
subroutine disp_tv_dchr (title, x, fmt, advance, lbound, sep, style, trim, unit, orient)
subroutine disp_tm_dchr (title, x, fmt, advance, lbound, sep, style, trim, unit)
subroutine disp_dchr (title, x, SE)
Variables
integer, parameter, public asterisk_unit = -3
integer, parameter, public putstr_unit = -2
integer, parameter, public null_unit = -1
integer, parameter dint = kind(0)
integer, parameter sngl = kind(0.0)
integer, parameter dble = kind(0d0)
integer, parameter dlog = kind(.false.)
Function/Subroutine Documentation
avoid_compiler_warnings()
subroutine m_display::avoid_compiler_warnings () private
disp_cpld()
subroutine m_display::disp_cpld (character(*), intent(in) title, complex(dble), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, type(settings), intent(inout) SEim, integer, intent(in) n) private
References find_editdesc_dble(), and tobox_cpld().
disp_cplx()
subroutine m_display::disp_cplx (character(*), intent(in) title, complex(sngl), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, type(settings), intent(inout) SEim, integer, intent(in) n) private
References find_editdesc_sngl(), and tobox_cplx().
disp_dble()
subroutine m_display::disp_dble (character(*), intent(in) title, real(dble), dimension(:,:), intent(in) x, type(settings), intent(inout) SE) private
References find_editdesc_dble(), and tobox_dble().
disp_dchr()
subroutine m_display::disp_dchr (character(*), intent(in) title, character(*), dimension(:,:), intent(in) x, type(settings), intent(inout) SE) private
References m_display_util::copyseptobox(), m_display_util::copytobox(), m_display_util::finishbox(), m_display_util::preparebox(), and true().
disp_dint()
subroutine m_display::disp_dint (character(*), intent(in) title, integer(dint), dimension(:,:), intent(in) x, type(settings), intent(inout) SE) private
References find_editdesc_dint(), and tobox_dint().
disp_dlog()
subroutine m_display::disp_dlog (character(*), intent(in) title, logical(dlog), dimension(:,:), intent(in) x, type(settings), intent(inout) SE) private
References tobox_dlog().
disp_get()
type(disp_settings) function, public m_display::disp_get ()
NAME
disp_get(3f) - [M_display] return default settings in a structure of DISP(3f) settings
DESCRIPTION
The argumentless function DISP_GET returns the current default settings in a structure of type DISP_SETTINGS. If a subroutine changes the default settings with DISP_SET it is possible to save the settings that are in effect when the routine is entered, and restore these settings before returning from the routine.
EXAMPLE
An example is:
program demo_disp_get real :: xx(2,3), yy(2,3) xx(1,:)=[ 1.0, 6.0, 5.0 ] xx(2,:)=[ 2.4, 4.0, 6.0 ] yy(1,:)=[ 0.0, 3.5, 2.0 ] yy(2,:)=[ 7.0, 4.0, 8.22 ] call disp_xy(xx,yy) contains
subroutine disp_xy(x,y) use M_display real x(:,:), y(:,:) type(disp_settings) ds ds = disp_get() call disp_set(digmax=4, sep=',') call disp('x=',x) write(*,*) call disp('y=',y) call disp_set(ds) end subroutine disp_xy
end program demo_disp_get
Expected:
x=1.000,6.000,5.000 2.400,4.000,6.000
y=0.000,3.500,2.000 7.000,4.000,8.220
AUTHOR
Based on dispmodule(3f), "A Fortran 95 module for pretty-printing matrices". Version number 1.02 6-Sept-2008, Kristjan Jonasson, Dept. of Computer Science, University of Iceland (jonas.nosp@m.son@.nosp@m.hi.is).
References m_display_util::defset.
disp_m_cpld()
subroutine m_display::disp_m_cpld (complex(dble), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_tm_cpld().
disp_m_cplx()
subroutine m_display::disp_m_cplx (complex(sngl), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_tm_cplx().
disp_m_dble()
subroutine m_display::disp_m_dble (real(dble), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, integer, intent(in), optional digmax, character(*), intent(in), optional zeroas) private
References disp_tm_dble().
disp_m_dchr()
subroutine m_display::disp_m_dchr (character(*), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_tm_dchr().
disp_m_dlog()
subroutine m_display::disp_m_dlog (logical(dlog), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_tm_dlog().
disp_m_sngl()
subroutine m_display::disp_m_sngl (real(sngl), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, integer, intent(in), optional digmax, character(*), intent(in), optional zeroas) private
References disp_tm_sngl().
disp_matrix_int()
subroutine m_display::disp_matrix_int (integer(dint), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_title_matrix_int().
disp_nonopt_dchr()
subroutine m_display::disp_nonopt_dchr (character(*), intent(in) title, character(*), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_tm_dchr().
disp_s_cpld()
subroutine m_display::disp_s_cpld (complex(dble), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, character(*), intent(in), optional sep, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_ts_cpld().
disp_s_cplx()
subroutine m_display::disp_s_cplx (complex(sngl), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, character(*), intent(in), optional sep, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_ts_cplx().
disp_s_dble()
subroutine m_display::disp_s_dble (real(dble), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, character(*), intent(in), optional sep, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_ts_dble().
disp_s_dlog()
subroutine m_display::disp_s_dlog (logical(dlog), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, character(*), intent(in), optional sep, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_ts_dlog().
disp_s_sngl()
subroutine m_display::disp_s_sngl (real(sngl), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, character(*), intent(in), optional sep, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_ts_sngl().
disp_scalar_int()
subroutine m_display::disp_scalar_int (integer(dint), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, character(*), intent(in), optional sep, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_title_scalar_int().
disp_set()
subroutine, public m_display::disp_set (character(*), intent(in), optional advance, integer, intent(in), optional digmax, character(*), intent(in), optional matsep, character(*), intent(in), optional orient, character(*), intent(in), optional sep, character(*), intent(in), optional style, integer, intent(in), optional unit, character(*), intent(in), optional zeroas)
NAME
disp_set(3f) - [M_display] set default options for disp(3f)
DESCRIPTION
The subroutine DISP_SET may be used to change default values of all the arguments of DISP except TITLE, X, FMT and LBOUND. In addition the default separator between items that are displayed side-by-side (using ADVANCE='no') may be changed with the MATSEP argument.
THE DERIVED TYPE DISP_SETTINGS
M_display contains the following definition of the data type DISP_SETTINGS.
  TYPE DISP_SETTINGS
    character(3)  :: advance   = 'YES'
    character(9)  :: matsep    = '   '
    character(3)  :: orient    = 'COL'
    character(9)  :: sep       = '  '
    character(19) :: style     = 'LEFT'
    character(4)  :: trim      = 'AUTO'
    character(9)  :: zeroas    = ''
    integer       :: digmax    = 6
    integer       :: matseplen = 3
    integer       :: seplen    = 2
    integer       :: unit      = -3
    integer       :: zaslen    = 0
  END TYPE DISP_SETTINGS
Structures of type DISP_SETTINGS may be used to save and later restore format control settings of DISP. As shown, new variables of this type will automatically have default values for all components.
CALLING SYNTAX FOR DISP_SET
There are two ways to call DISP_SET:
  CALL DISP_SET(SETTINGS)
  CALL DISP_SET(ADVANCE, DIGMAX, MATSEP, ORIENT, SEP, STYLE, UNIT, ZEROAS)
Both calls change the default format control used in subsequent calls to DISP. In the first call, SETTINGS is of type DISP_SETTINGS and the default values for all arguments is changed. In the second call all the arguments are optional. If an argument is absent the corresponding default setting is not changed. An example call is
  CALL DISP_SET(STYLE = 'PAD', SEP = ' ').
The effect is that titles will be written padded above matrices, and matrix column will be separated by one blank. The type and purpose of all the arguments except MATSEP has been described in section 3.2.
MATSEP = ms Specifies a character string of length <= 9 that is written out between items (matrices) when they are displayed side-by-side. An example is:
 CALL DISP(X, ADVANCE='NO')
 CALL DISP(Y, ADVANCE='NO')
 CALL DISP_SET(MATSEP=' | ')
 CALL DISP(Z, ADVANCE='YES')
The output from these calls might be:
 12.2 |  1.3 | 1
  9.6 | 13.0 | 3
 -2.0 |  4.0 | 4
Note that MATSEP affects the separation of all items that have been placed in the output queue of the unit being displayed on.
AUTHOR
Based on dispmodule(3f), "A Fortran 95 module for pretty-printing matrices". Version number 1.02 6-Sept-2008, Kristjan Jonasson, Dept. of Computer Science, University of Iceland (jonas.nosp@m.son@.nosp@m.hi.is).
References m_display_util::check_settings(), m_display_util::defset, and m_display_util::upper().
disp_set_ds()
subroutine m_display::disp_set_ds (type(disp_settings), intent(in) settings) private
References m_display_util::check_settings(), and m_display_util::defset.
disp_set_factory()
subroutine, public m_display::disp_set_factory ()
NAME
tostring_disp_factory(3f) - [M_display] set DISP(3f) output back to original defaults
DESCRIPTION
The subroutine TOSTRING_DISP_FACTORY (which has no arguments) may be called to restore all settings of DISP(3f) to the original default values.
AUTHOR
Based on dispmodule(3f), "A Fortran 95 module for pretty-printing matrices". Version number 1.02 6-Sept-2008, Kristjan Jonasson, Dept. of Computer Science, University of Iceland (jonas.nosp@m.son@.nosp@m.hi.is).
References m_display_util::defset, and m_display_util::factory_settings.
disp_sngl()
subroutine m_display::disp_sngl (character(*), intent(in) title, real(sngl), dimension(:,:), intent(in) x, type(settings), intent(inout) SE) private
References find_editdesc_sngl(), and tobox_sngl().
disp_title_matrix_int()
subroutine m_display::disp_title_matrix_int (character(*), intent(in) title, integer(dint), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_dint(), and m_display_util::get_se().
disp_title_scalar_int()
subroutine m_display::disp_title_scalar_int (character(*), intent(in) title, integer(dint), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_title_matrix_int().
disp_title_vector_int()
subroutine m_display::disp_title_vector_int (character(*), intent(in) title, integer(dint), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient, character(*), intent(in), optional zeroas) private
References disp_dint(), and m_display_util::get_se().
disp_tm_cpld()
subroutine m_display::disp_tm_cpld (character(*), intent(in) title, complex(dble), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_cpld(), m_display_util::disp_errmsg(), and m_display_util::get_se().
disp_tm_cplx()
subroutine m_display::disp_tm_cplx (character(*), intent(in) title, complex(sngl), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_cplx(), m_display_util::disp_errmsg(), and m_display_util::get_se().
disp_tm_dble()
subroutine m_display::disp_tm_dble (character(*), intent(in) title, real(dble), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_dble(), and m_display_util::get_se().
disp_tm_dchr()
subroutine m_display::disp_tm_dchr (character(*), intent(in) title, character(*), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_dchr(), and m_display_util::get_se().
disp_tm_dlog()
subroutine m_display::disp_tm_dlog (character(*), intent(in) title, logical(dlog), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_dlog(), and m_display_util::get_se().
disp_tm_sngl()
subroutine m_display::disp_tm_sngl (character(*), intent(in) title, real(sngl), dimension(:,:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_sngl(), and m_display_util::get_se().
disp_ts_cpld()
subroutine m_display::disp_ts_cpld (character(*), intent(in) title, complex(dble), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_tm_cpld().
disp_ts_cplx()
subroutine m_display::disp_ts_cplx (character(*), intent(in) title, complex(sngl), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_tm_cplx().
disp_ts_dble()
subroutine m_display::disp_ts_dble (character(*), intent(in) title, real(dble), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_tm_dble().
disp_ts_dchr()
subroutine m_display::disp_ts_dchr (character(*), intent(in), optional title, character(*), intent(in), optional x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_nonopt_dchr(), and disp_tm_dchr().
disp_ts_dlog()
subroutine m_display::disp_ts_dlog (character(*), intent(in) title, logical(dlog), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit) private
References disp_tm_dlog().
disp_ts_sngl()
subroutine m_display::disp_ts_sngl (character(*), intent(in) title, real(sngl), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional zeroas) private
References disp_tm_sngl().
disp_tv_cpld()
subroutine m_display::disp_tv_cpld (character(*), intent(in) title, complex(dble), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient) private
References disp_cpld(), m_display_util::disp_errmsg(), and m_display_util::get_se().
disp_tv_cplx()
subroutine m_display::disp_tv_cplx (character(*), intent(in) title, complex(sngl), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient) private
References disp_cplx(), m_display_util::disp_errmsg(), and m_display_util::get_se().
disp_tv_dble()
subroutine m_display::disp_tv_dble (character(*), intent(in) title, real(dble), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient, character(*), intent(in), optional zeroas) private
References disp_dble(), and m_display_util::get_se().
disp_tv_dchr()
subroutine m_display::disp_tv_dchr (character(*), intent(in) title, character(*), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient) private
References disp_dchr(), and m_display_util::get_se().
disp_tv_dlog()
subroutine m_display::disp_tv_dlog (character(*), intent(in) title, logical(dlog), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient) private
References disp_dlog(), and m_display_util::get_se().
disp_tv_sngl()
subroutine m_display::disp_tv_sngl (character(*), intent(in) title, real(sngl), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient, character(*), intent(in), optional zeroas) private
References disp_sngl(), and m_display_util::get_se().
disp_v_cpld()
subroutine m_display::disp_v_cpld (complex(dble), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient) private
References disp_tv_cpld().
disp_v_cplx()
subroutine m_display::disp_v_cplx (complex(sngl), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional fmt_imag, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient) private
References disp_tv_cplx().
disp_v_dble()
subroutine m_display::disp_v_dble (real(dble), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient, character(*), intent(in), optional zeroas) private
References disp_tv_dble().
disp_v_dchr()
subroutine m_display::disp_v_dchr (character(*), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient) private
References disp_tv_dchr().
disp_v_dlog()
subroutine m_display::disp_v_dlog (logical(dlog), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient) private
References disp_tv_dlog().
disp_v_sngl()
subroutine m_display::disp_v_sngl (real(sngl), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, intent(in), optional digmax, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient, character(*), intent(in), optional zeroas) private
References disp_tv_sngl().
disp_vector_int()
subroutine m_display::disp_vector_int (integer(dint), dimension(:), intent(in) x, character(*), intent(in), optional fmt, character(*), intent(in), optional advance, integer, dimension(:), intent(in), optional lbound, character(*), intent(in), optional sep, character(*), intent(in), optional style, character(*), intent(in), optional trim, integer, intent(in), optional unit, character(*), intent(in), optional orient, character(*), intent(in), optional zeroas) private
References disp_title_vector_int().
find_editdesc_dble()
subroutine m_display::find_editdesc_dble (real(dble), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, integer, dimension(size(x,2)), intent(out) wid, integer, dimension(size(x,2)), intent(out) nbl) private
References m_display_util::find_editdesc_real(), getwid_dble(), maxw_dble(), and m_display_util::replace_w().
find_editdesc_dint()
subroutine m_display::find_editdesc_dint (integer(dint), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, integer, dimension(size(x,2)), intent(out) wid, integer, dimension(size(x,2)), intent(out) nbl) private
References getwid_dint(), and m_display_util::replace_w().
find_editdesc_sngl()
subroutine m_display::find_editdesc_sngl (real(sngl), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, integer, dimension(size(x,2)), intent(out) wid, integer, dimension(size(x,2)), intent(out) nbl) private
References m_display_util::find_editdesc_real(), getwid_sngl(), maxw_sngl(), and m_display_util::replace_w().
getwid_dble()
subroutine m_display::getwid_dble (real(dble), dimension(:), intent(in) xmaxv, real(dble), dimension(:), intent(in) xminv, logical, dimension(:), intent(in) xzero, logical, dimension(:), intent(in) xallz, logical, dimension(:), intent(in) xnonn, logical, dimension(:), intent(in) xalln, type(settings), intent(in) SE, integer, dimension(:), intent(out) wid, integer, dimension(:), intent(out) nbl) private
getwid_dint()
subroutine m_display::getwid_dint (integer(dint), dimension(:), intent(in) xmaxv, integer(dint), dimension(:), intent(in) xminv, logical, dimension(:), intent(in) xzero, logical, dimension(:), intent(in) xallz, type(settings), intent(in) SE, integer, dimension(:), intent(out) wid, integer, dimension(:), intent(out) nbl) private
getwid_sngl()
subroutine m_display::getwid_sngl (real(sngl), dimension(:), intent(in) xmaxv, real(sngl), dimension(:), intent(in) xminv, logical, dimension(:), intent(in) xzero, logical, dimension(:), intent(in) xallz, logical, dimension(:), intent(in) xnonn, logical, dimension(:), intent(in) xalln, type(settings), intent(in) SE, integer, dimension(:), intent(out) wid, integer, dimension(:), intent(out) nbl) private
len_f_cpld()
pure integer function m_display::len_f_cpld (complex(dble), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, len_f_dble(), m_display_util::readfmt(), and then().
len_f_cplx()
pure integer function m_display::len_f_cplx (complex(sngl), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, len_f_sngl(), m_display_util::readfmt(), and then().
len_f_dble()
pure integer function m_display::len_f_dble (real(dble), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, maxw_dble(), m_display_util::readfmt(), m_display_util::replace_w(), then(), m_display_util::tosset, and m_display_util::trim_real().
len_f_dint()
pure integer function m_display::len_f_dint (integer(dint), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, m_display_util::readfmt(), then(), and m_display_util::tosset.
len_f_dlog()
pure integer function m_display::len_f_dlog (logical(dlog), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, m_display_util::readfmt(), then(), and m_display_util::tosset.
len_f_sngl()
pure integer function m_display::len_f_sngl (real(sngl), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, maxw_sngl(), m_display_util::readfmt(), m_display_util::replace_w(), then(), m_display_util::tosset, and m_display_util::trim_real().
len_s_cpld()
pure integer function m_display::len_s_cpld (complex(dble), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, len_f_dble(), m_display_util::readfmt(), and then().
len_s_cplx()
pure integer function m_display::len_s_cplx (complex(sngl), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, len_f_sngl(), m_display_util::readfmt(), and then().
maxw_dble()
pure integer function m_display::maxw_dble (real(dble), dimension(:), intent(in) x, integer, intent(in) d) private
maxw_sngl()
pure integer function m_display::maxw_sngl (real(sngl), dimension(:), intent(in) x, integer, intent(in) d) private
tobox_cpld()
subroutine m_display::tobox_cpld (character(*), intent(in) title, complex(dble), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, type(settings), intent(inout) SEim, integer, dimension(:), intent(in) widre, integer, dimension(:), intent(in) widim, integer, dimension(:), intent(in) nblre, integer, dimension(:), intent(in) nblim, integer, intent(in) m, integer, intent(in) n) private
References m_display_util::copyseptobox(), m_display_util::copytobox(), m_display_util::finishbox(), m_display_util::preparebox(), and then().
tobox_cplx()
subroutine m_display::tobox_cplx (character(*), intent(in) title, complex(sngl), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, type(settings), intent(inout) SEim, integer, dimension(:), intent(in) widre, integer, dimension(:), intent(in) widim, integer, dimension(:), intent(in) nblre, integer, dimension(:), intent(in) nblim, integer, intent(in) m, integer, intent(in) n) private
References m_display_util::copyseptobox(), m_display_util::copytobox(), m_display_util::finishbox(), m_display_util::preparebox(), and then().
tobox_dble()
subroutine m_display::tobox_dble (character(*), intent(in) title, real(dble), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, integer, dimension(:), intent(inout) wid, integer, dimension(:), intent(inout) nbl) private
References m_display_util::copyseptobox(), m_display_util::copytobox(), m_display_util::finishbox(), m_display_util::preparebox(), and m_display_util::replace_zeronaninf().
tobox_dint()
subroutine m_display::tobox_dint (character(*), intent(in) title, integer(dint), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, integer, dimension(:), intent(inout) wid, integer, dimension(:), intent(inout) nbl) private
References m_display_util::copyseptobox(), m_display_util::copytobox(), m_display_util::finishbox(), m_display_util::preparebox(), and m_display_util::replace_zeronaninf().
tobox_dlog()
subroutine m_display::tobox_dlog (character(*), intent(in) title, logical(dlog), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, integer, dimension(:), intent(inout) wid, integer, dimension(:), intent(inout) nbl) private
References m_display_util::copyseptobox(), m_display_util::copytobox(), m_display_util::finishbox(), and m_display_util::preparebox().
tobox_sngl()
subroutine m_display::tobox_sngl (character(*), intent(in) title, real(sngl), dimension(:,:), intent(in) x, type(settings), intent(inout) SE, integer, dimension(:), intent(inout) wid, integer, dimension(:), intent(inout) nbl) private
References m_display_util::copyseptobox(), m_display_util::copytobox(), m_display_util::finishbox(), m_display_util::preparebox(), and m_display_util::replace_zeronaninf().
tostring_cpld()
character(len_f_cpld(x, tosset % rfmt)) function m_display::tostring_cpld (complex(dble), dimension(:), intent(in) x) private
References m_display_util::tosset, and tostring_f_cpld().
tostring_cplx()
character(len_f_cplx(x, tosset % rfmt)) function m_display::tostring_cplx (complex(sngl), dimension(:), intent(in) x) private
References m_display_util::tosset, and tostring_f_cplx().
tostring_dble()
character(len_f_dble(x, tosset % rfmt)) function m_display::tostring_dble (real(dble), dimension(:), intent(in) x) private
References m_display_util::tosset, and tostring_f_dble().
tostring_dint()
character(len_f_dint(x, tosset % ifmt)) function m_display::tostring_dint (integer(dint), dimension(:), intent(in) x) private
References m_display_util::tosset, and tostring_f_dint().
tostring_dlog()
character(1 + (size(x) - 1)*(1 + tosset % seplen)) function m_display::tostring_dlog (logical(dlog), dimension(:), intent(in) x) private
References tostring_f_dlog().
tostring_f_cpld()
character(len_f_cpld(x, fmt)) function m_display::tostring_f_cpld (complex(dble), dimension(:), intent(in) x, character(widthmax_dble(abs(x-real(x)), intent(in) fmt) private
References m_display_util::errormsg, maxw_dble(), m_display_util::readfmt(), m_display_util::replace_w(), then(), m_display_util::tostring_get_complex(), and m_display_util::trim_real().
tostring_f_cplx()
character(len_f_cplx(x, fmt)) function m_display::tostring_f_cplx (complex(sngl), dimension(:), intent(in) x, character(widthmax_sngl(abs(x-real(x)), intent(in) fmt) private
References m_display_util::errormsg, maxw_sngl(), m_display_util::readfmt(), m_display_util::replace_w(), then(), m_display_util::tostring_get_complex(), and m_display_util::trim_real().
tostring_f_dble()
character(len_f_dble(x, fmt)) function m_display::tostring_f_dble (real(dble), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, maxw_dble(), m_display_util::readfmt(), m_display_util::replace_w(), m_display_util::tostring_get(), and m_display_util::trim_real().
tostring_f_dint()
character(len_f_dint(x, fmt)) function m_display::tostring_f_dint (integer(dint), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, m_display_util::readfmt(), then(), m_display_util::tosset, and m_display_util::tostring_get().
tostring_f_dlog()
character(len_f_dlog(x, fmt)) function m_display::tostring_f_dlog (logical(dlog), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, m_display_util::readfmt(), then(), m_display_util::tosset, and m_display_util::tostring_get().
tostring_f_sngl()
character(len_f_sngl(x, fmt)) function m_display::tostring_f_sngl (real(sngl), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::errormsg, maxw_sngl(), m_display_util::readfmt(), m_display_util::replace_w(), m_display_util::tostring_get(), and m_display_util::trim_real().
tostring_s_cpld()
character(len_s_cpld(x, tosset % rfmt)) function m_display::tostring_s_cpld (complex(dble), intent(in) x) private
References m_display_util::tosset, and tostring_f_cpld().
tostring_s_cplx()
character(len_s_cplx(x, tosset % rfmt)) function m_display::tostring_s_cplx (complex(sngl), intent(in) x) private
References m_display_util::tosset, and tostring_f_cplx().
tostring_s_dble()
character(len_f_dble([x], tosset % rfmt)) function m_display::tostring_s_dble (real(dble), intent(in) x) private
References m_display_util::tosset, and tostring_f_dble().
tostring_s_dint()
character(len_f_dint([x], tosset % ifmt)) function m_display::tostring_s_dint (integer(dint), intent(in) x) private
NAME
tostring(3f) - [M_display] change numbers to a string
INTRODUCTION
Many programming languages have built-in functions that change numbers to strings. It is possible to achieve a similar effect in Fortran using internal files and list-directed output:
  character(100) s
  real :: x = 1.5
  write(s, *) 'The square of', x, 'is', x*x
  print *, trim(s)
but this is cumbersome, and also there is the disadvantage that the result is compiler-dependent. M_display has a function, TOSTRING, which overcomes this disadvantage and offers additional flexibility. With x = 1.5 the following statement will produce the same output as Matlab and Java give:
  CALL DISP('The square of '//TOSTRING(X)//' is '//TOSTRING(X*X))
TOSTRING accepts integer, logical or real scalars or vectors. The subroutine TOSTRING_SET may be used to change settings for TOSTRING.
THE FUNCTION TOSTRING
Apart from the item to be turned into a string, an edit descriptor to use can optionally be supplied as the second argument to TOSTRING. The two ways to invoke TOSTRING are:
  TOSTRING(X)
  TOSTRING(X, FMT)
These invocations return a character string representing the value of the argument X. When X is a vector individual elements are separated by a string, with the original (or factory) default value ", ". By (original) default G editing is used to convert real numbers, I editing integers, and blanks are trimmed from (each element of) X, both from the left and the right. In addition trailing zeroes are trimmed from the fractional part of real X-elements, as well as a trailing decimal point. The separating string, trimming behaviour, and default editing may be changed by calling TOSTRING_SET
X The item to be changed to a string. X may be a scalar or a vector (i.e. of rank 0 or 1) and of one of the following kinds:
default integer default real (i.e. real(1.0), single precision) double precision real (i.e. real(1d0)) default logical
FMT Character string with an edit descriptor used to format each element of X. The possible edit descriptors are given in section 3.1, except that A and Aw can of course not be used. When FMT is absent, a default edit descriptor is used. The default may be set by calling TOSTRING_SET but the original (or factory) defaults are I0 for integers, L1 for logicals and 1PG12.5 for reals.
AUTHOR
Based on dispmodule(3f), "A Fortran 95 module for pretty-printing matrices". Version number 1.02 6-Sept-2008, Kristjan Jonasson, Dept. of Computer Science, University of Iceland (jonas.nosp@m.son@.nosp@m.hi.is).
References m_display_util::tosset, and tostring_f_dint().
tostring_s_dlog()
character(1) function m_display::tostring_s_dlog (logical(dlog), intent(in) x) private
References tostring_f_dlog().
tostring_s_sngl()
character(len_f_sngl([x], tosset % rfmt)) function m_display::tostring_s_sngl (real(sngl), intent(in) x) private
References m_display_util::tosset, and tostring_f_sngl().
tostring_set()
subroutine, public m_display::tostring_set (character(*), intent(in), optional sep, character(*), intent(in), optional rfmt, character(*), intent(in), optional ifmt, character(*), intent(in), optional trimb, character(*), intent(in), optional trimz)
NAME
tostring_set(3f) - [M_display] set modes for TOSTRING(3f)
DESCRIPTION
The subroutine TOSTRING_SET has five arguments, all of which are optional. Argument association will normally be realized using argument keywords, e.g. CALL TOSTRING_SET(SEP='; '). The examples in section 5.4 clarify how to use this subroutine. The five arguments are:
SEP Character string used to separate elements of displayed vectors. Original default value is ', '.
RFMT Character string containing default edit descriptor to use to display real items. The original default value is '1PG12.5'
IFMT Character string containing default edit descriptor to use to display integer items. The original default value is 'I0'.
TRIMB Controls whether leading and trailing blanks are trimmed from individual displayed elements. Possible values are 'YES' (to trim blanks) and 'NO' (for no trimming). Default is 'YES'.
TRIMZ Controls whether trailing zeros are trimmed from the fractional part of displayed items. Possible values are 'NONE' (for no zero trimming), 'G' (to trim fractional trailing zeros only when G editing is used), and 'ALL' (to trim zeros with all types of editing). Trailing decimal points are also removed when zero-trimming is active. Default value is 'G'.
EXAMPLES
When the original (factory) defaults are in effect, the result of invoking TOSTRING will usually be as follows.
  Invocation                             Returned String
  ----------                             ---------------
  tostring(atan(1.0))                    '0.785398'
  tostring(exp([-3.,-1.,0.,1.]))         '4.97871E-02, 0.36788, 1, 2.7183'
  tostring(real([(i,i=1,5)])**8)         '1, 256, 6561, 65536, 3.90625E+05'
  tostring([1.23456,1.2300,1.23456e6])   '1.2346, 1.23, 1.23456E+06'
  tostring(real([(i,i=1,5)])**8,'f0.1')  '1.0, 256.0, 6561.0, 65536.0, 390625.0'
  tostring(real([(i,i=1,5)])**8,'f6.1')  '1.0, 256.0, 6561.0, ******, ******'
  tostring([1200000.,-1.2e-9])           '1.2E+06, -1.2E-09'
  !
  tostring(1.200d103)                    '1.2+103'
  tostring([1.1d0,2.2d10,3.3d20])        '1.1E+00, 2.2E+10, 3.3E+20'
  !
  tostring(-77)                          '-77'
  tostring([(i,i=-3,3)]**11)             '-177147, -2048, -1, 0, 1, 2048, 177147'
  tostring([(i,i=-3,3)]**11, 'i7')       '-177147, -2048, -1, 0, 1, 2048, 177147'
  tostring([(i,i=-3,3)]**11, 'i4')       '****, ****, -1, 0, 1, 2048, ****'
  !
  tostring((1,3)/(4,2))                  '0.5 + 0.5i'
  tostring(cmplx([-1,-2])**0.25)       '0.70711 + 0.70711i, 0.8409 + 0.8409i'
  !
  tostring([.true., .false., .false.])   'T, F, F'
  tostring(.true., 'L2')                 'T'
The returned strings may be slightly different from the ones shown, because some compilers (at least some versions of g95) will produce one more decimal place in a few cases, and because the Fortran standard allows G editing to give exponent fields in the form 0dd instead of Edd. The examples make use of brackets to construct vector constants (a Fortran 2003 feature). If the compiler being used does not support this, [ and ] must be used instead. Notice that trimming is on by default so there is not much purpose in specifying the format for integers and logicals. Notice also that (usually) 5 significant digits are displayed when the default G editing results in F edited output, but 6 digits for the numbers of small or large magnitude, displayed with E editing. This discrepancy is present in the Fortran standard; the presence of the scale factor 1P in the edit descriptor increases the number of displayed significant digits.
Examples of using TOSTRING_SET follow (again the returned string may be slightly different).
  Invocation                              Returned String
  ----------                              ---------------
  call tostring_set(sep=';')
  tostring([1,2,30])                      '1;2;30'
  !
  call tostring_set(trimb='NO')
  tostring(real([(i,i=1,5)])**8,'f6.1')   '   1.0; 256.0;6561.0;******;******'
  tostring([1,2,30],'i3')                 '  1;  2; 30'
  tostring([(i,i=-3,3)]**11, 'i4')        '****;****;  -1;   0;   1;2048;****'
  tostring([1,2,30],'i0')                 '1;2;30'
  tostring(.true.,'L3')                   '  T'
  !
  call tostring_set(trimz='NONE',sep=', ',trimb='YES')
  tostring(real([(i,i=1,4)])**8)          '1.0000, 256.00, 6561.0, 65536.'
  tostring([1.23456,1.2300,1.23456e6])    '1.2346, 1.2300, 1.23456E+06'
  tostring(1.200d103)                     '1.20000+103'
  !
  call tostring_set(trimz='ALL')
  tostring(real([(i,i=1,5)])**8,'f0.1')   '1, 256, 6561, 65536, 390625'
  !
  call tostring_set(rfmt='G12.4')
  tostring(real([(i,i=0,5)])**8)          '1, 256, 6561, 0.6554E+05, 0.3906E+06'
  tostring([1200000.,-1.2e-9])            '0.12E+07, -0.12E-08'
  !
  call tostring_set_factory()
AUTHOR
Based on dispmodule(3f), "A Fortran 95 module for pretty-printing matrices". Version number 1.02 6-Sept-2008, Kristjan Jonasson, Dept. of Computer Science, University of Iceland (jonas.nosp@m.son@.nosp@m.hi.is).
References m_display_util::tosset, m_display_util::tostring_check_settings(), and m_display_util::upper().
tostring_set_factory()
subroutine, public m_display::tostring_set_factory ()
NAME
tostring_set_factory(3f) - [M_display] set TOSTRING(3f) output back to original defaults
DESCRIPTION
The subroutine TOSTRING_SET_FACTORY (which has no arguments) may be called to restore all settings of TOSTRING(3f) to the original default values (the factory defaults): SEP=',', RFMT = '1PG12.5', IFMT= 'I0', TRIMB='YES' and TRIMZ='G'.
AUTHOR
Based on dispmodule(3f), "A Fortran 95 module for pretty-printing matrices". Version number 1.02 6-Sept-2008, Kristjan Jonasson, Dept. of Computer Science, University of Iceland (jonas.nosp@m.son@.nosp@m.hi.is).
References avoid_compiler_warnings(), false(), m_display_util::tosfac, and m_display_util::tosset.
tostring_sf_cpld()
character(len_s_cpld(x, fmt)) function m_display::tostring_sf_cpld (complex(dble), intent(in) x, character(*), intent(in) fmt) private
References tostring_f_cpld().
tostring_sf_cplx()
character(len_s_cplx(x, fmt)) function m_display::tostring_sf_cplx (complex(sngl), intent(in) x, character(*), intent(in) fmt) private
References tostring_f_cplx().
tostring_sf_dble()
character(len_f_dble([x], fmt)) function m_display::tostring_sf_dble (real(dble), intent(in) x, character(*), intent(in) fmt) private
References tostring_f_dble().
tostring_sf_dint()
character(len_f_dint([x], fmt)) function m_display::tostring_sf_dint (integer(dint), intent(in) x, character(*), intent(in) fmt) private
References tostring_f_dint().
tostring_sf_dlog()
character(len_f_dlog([x], fmt)) function m_display::tostring_sf_dlog (logical(dlog), intent(in) x, character(*), intent(in) fmt) private
References tostring_f_dlog().
tostring_sf_sngl()
character(len_f_sngl([x], fmt)) function m_display::tostring_sf_sngl (real(sngl), intent(in) x, character(*), intent(in) fmt) private
References tostring_f_sngl().
tostring_sngl()
character(len_f_sngl(x, tosset % rfmt)) function m_display::tostring_sngl (real(sngl), dimension(:), intent(in) x) private
References m_display_util::tosset, and tostring_f_sngl().
widthmax_dble()
pure integer function m_display::widthmax_dble (real(dble), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References maxw_dble(), and m_display_util::readfmt().
widthmax_dint()
pure integer function m_display::widthmax_dint (integer(dint), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References m_display_util::readfmt().
widthmax_dlog()
pure integer function m_display::widthmax_dlog (character(*), intent(in) fmt) private
References m_display_util::readfmt().
widthmax_sngl()
pure integer function m_display::widthmax_sngl (real(sngl), dimension(:), intent(in) x, character(*), intent(in) fmt) private
References maxw_sngl(), and m_display_util::readfmt().
Variable Documentation
asterisk_unit
integer, parameter, public m_display::asterisk_unit = -3
dble
integer, parameter m_display::dble = kind(0d0) private
dint
integer, parameter m_display::dint = kind(0) private
dlog
integer, parameter m_display::dlog = kind(.false.) private
null_unit
integer, parameter, public m_display::null_unit = -1
putstr_unit
integer, parameter, public m_display::putstr_unit = -2
sngl
integer, parameter m_display::sngl = kind(0.0) private