GeneralPurposeFortran: m_readgif Module Reference
m_readgif Module Reference
NAME
readgif(3f) - [M_readgif] read a GIF file
Data Types
type gif89_type
type gif_screen_type
Functions/Subroutines
subroutine, public readgif (filename, num_image, image, iostat, color_map, verbose)
integer function bcint2b (buf)
subroutine do_extension (filename, iostat, verbose)
subroutine get_code (result, code_size, flag, filename, iostat)
subroutine get_data_block (buf, filename, countx, iostat)
subroutine get_lun (lun)
subroutine io_error (message, iostat, filename)
subroutine lzw_read_byte (result, input_code_size, flag, filename, iostat)
subroutine open_gif (filename, iostat, verbose, color_map)
subroutine read_buf (buf, iostat)
subroutine read_colormap (colormap, iostat)
subroutine read_image (length, height, interlace, ignore, verbose, filename, iostat, image)
Variables
integer, parameter, private interlace = 6
integer, parameter, private max_lzw_bits = 12
integer, parameter, private use_local_colormap = 7
integer, parameter, public max_colormap_size = 256
integer, save, private lun
logical, private zero_data_block
type(gif_screen_type), public gif_screen
type(gif89_type), public gif89
Detailed Description
NAME
readgif(3f) - [M_readgif] read a GIF file
SYNOPSIS
subroutine readgif(filename, num_image, image, iostat, color_map, verbose)
character(len=*), intent(in) :: filename integer, intent(in) :: num_image integer, intent(out), allocatable :: image(:,:) integer, intent(out) :: iostat real , allocatable, intent(out) :: color_map(:,:) logical, intent(in), optional :: verbose
DESCRIPTION
read the num_image'th gif image from filename into arrays image and color_map
OPTIONS
filename input file num_image number of image required image Image data returned iostat I/O error number, =0 if ok color_map RGB for each level, range 0.0 to 1.0 verbose .true.for verbose output
EXAMPLE
Sample program:
   program demo_readgif
   use M_readgif, only : readgif
   use M_writegif, only : writegif
   implicit none
   character(len=*),parameter :: filename='boxes.gif'
   integer                    :: num_image=1
   integer,allocatable        :: image(:,:)
   integer                    :: iostat=0
   real,allocatable           :: color_map(:,:)
   integer,allocatable        :: color_map2(:,:)
   logical                    :: verbose=.true.
   integer                    :: i,ii,jj
   call readgif(filename,num_image,image,iostat,color_map,verbose)
   if(iostat.ne.0)then
      write(*,*)'*demo_readgif* could not read GIF file ',trim(filename)
      stop
   endif
   write(*,*)'SIZE OF IMAGE =',size(image)
   do i=1,rank(image)
      write(*,*)'RANK OF IMAGE=',i,size(image,dim=i)
   enddo
   write(*,*)'SIZE OF COLORMAP=',size(color_map)
   do i=1,rank(color_map)
      write(*,*)'RANK OF COLORMAP=',i,size(color_map,dim=i)
   enddo
   ! convert between colormap types
   ! writegif uses an integer colormap, values 0 to 255
   ! readgif  uses real values 0.0 to 1.0
   ii=size(color_map,dim=1)
   jj=size(color_map,dim=2)
   allocate(color_map2(ii,0:jj-1)
   color_map2=255*color_map
   ! change color and write standard gif file
   where (image.eq.1) image=4
   call writegif('boxes_new.gif',image,color_map2)
   end program demo_readgif
Function/Subroutine Documentation
bcint2b()
integer function m_readgif::bcint2b (character(len=*), intent(in) buf) private
do_extension()
subroutine m_readgif::do_extension (character(len=*), intent(in) filename, integer, intent(out) iostat, logical, intent(in) verbose) private
References bcint2b(), get_data_block(), gif89, io_error(), and read_buf().
get_code()
subroutine m_readgif::get_code (integer, intent(out) result, integer, intent(in) code_size, logical, intent(in) flag, character (len=*), intent(in) filename, integer, intent(out) iostat) private
References false(), get_data_block(), and true().
get_data_block()
subroutine m_readgif::get_data_block (character(len=*), intent(out) buf, character(len=*), intent(in) filename, integer, intent(out) countx, integer, intent(out) iostat) private
References io_error(), read_buf(), and zero_data_block.
get_lun()
subroutine m_readgif::get_lun (integer, intent(out) lun) private
References unit().
io_error()
subroutine m_readgif::io_error (character(len=*), intent(in) message, integer, intent(in) iostat, character(len=*), intent(in) filename) private
lzw_read_byte()
subroutine m_readgif::lzw_read_byte (integer, intent(out) result, integer, intent(in) input_code_size, logical, intent(in) flag, character(len=*), intent(in) filename, integer, intent(out) iostat) private
References code, false(), get_code(), get_data_block(), max_lzw_bits, true(), unit(), and zero_data_block.
open_gif()
subroutine m_readgif::open_gif (character(len=*), intent(in) filename, integer, intent(out) iostat, logical, intent(in) verbose, real, dimension(:,:), intent(out), allocatable color_map) private
References bcint2b(), file(), get_lun(), gif_screen, io_error(), lun, read_buf(), read_colormap(), unit(), and use_local_colormap.
read_buf()
subroutine m_readgif::read_buf (character(len=*), intent(out) buf, integer, intent(out) iostat) private
References lun, and unit().
read_colormap()
subroutine m_readgif::read_colormap (real, dimension(:,:), intent(out) colormap, integer, intent(out) iostat) private
References read_buf().
read_image()
subroutine m_readgif::read_image (integer, intent(in) length, integer, intent(in) height, logical, intent(in) interlace, logical, intent(in) ignore, logical, intent(in) verbose, character(len=*), intent(in) filename, integer, intent(out) iostat, integer, dimension(:,:), intent(out), allocatable image) private
References false(), io_error(), lzw_read_byte(), read_buf(), true(), and unit().
readgif()
subroutine, public m_readgif::readgif (character(len=*), intent(in) filename, integer, intent(in) num_image, integer, dimension(:,:), intent(out), allocatable image, integer, intent(out) iostat, real, dimension(:,:), intent(out), allocatable color_map, logical, intent(in), optional verbose)
References bcint2b(), do_extension(), false(), gif89, gif_screen, interlace, io_error(), lun, open_gif(), read_buf(), read_colormap(), read_image(), unit(), use_local_colormap, and zero_data_block.
Variable Documentation
gif89
type(gif89_type), public m_readgif::gif89
gif_screen
type(gif_screen_type), public m_readgif::gif_screen
interlace
integer, parameter, private m_readgif::interlace = 6 private
lun
integer, save, private m_readgif::lun private
max_colormap_size
integer, parameter, public m_readgif::max_colormap_size = 256
max_lzw_bits
integer, parameter, private m_readgif::max_lzw_bits = 12 private
use_local_colormap
integer, parameter, private m_readgif::use_local_colormap = 7 private
zero_data_block
logical, private m_readgif::zero_data_block private