GeneralPurposeFortran: m_pixel Module Reference
m_pixel Module Reference
NAME
M_pixel(3f) - [M_pixel] module for drawing into a pixel array with 2D vector operations
Functions/Subroutines
subroutine, public rect (x1, y1, x2, y2)
NAME
rect(3f) - [M_pixel] draw rectangle given two corners
subroutine, public line (x1, y1, x2, y2)
NAME
line(3f) - [M_pixel] draw line between two points
subroutine swapcoord (p1, p2)
subroutine draw_line_single (x1, y1, x2, y2)
NAME
draw_line_single(3fp) - [M_pixel] Bresenham's line algorithm
subroutine, public hershey (x, y, height, itext, theta, ntext)
NAME
hershey(3f) - [M_pixel] draw text string as Hershey software vector fonts
subroutine hstylus (xi, yi, ipen)
subroutine chrcod (text, ntext)
real function, public strlength (string)
NAME
strlength(3f) - [M_pixel] return length of string
subroutine, public justfy (s, height, text, ntext)
NAME
justfy(3f) - [M_pixel] return lengths used to justify a string when calling hershey
subroutine, public polyline (x, y)
NAME
polyline(3f) - [M_pixel] connect points with lines
subroutine, public clear (indx)
NAME
clear(3f) - [M_pixel] clear background to current color or specified color index
subroutine if_init ()
subroutine, public arc (x, y, radius, startang, endang)
NAME
arc(3f) - [M_pixel] draw an arc using current line width and color
subroutine, public circle (x, y, radius)
NAME
circle(3f) - [M_pixel] draw a circle using current line width and color
subroutine, public linewidth (iwidth)
NAME
linewidth(3f) - [M_pixel] set linewidth
subroutine, public color (icolor)
NAME
color(3f) - [M_pixel] set current color index
subroutine, public mapcolor (indx, red, green, blue)
NAME
mapcolor(3f) - [M_pixel] set a color index using RGB values
subroutine, public circleprecision (nsegs)
NAME
circleprecision(3f) - [M_pixel] set number of line segments used to approximate a circle
subroutine, public getviewport (left, right, bottom, top)
NAME
getviewport(3f) - [M_pixel] return viewport in screen pixel coordinates
subroutine, public viewport (left, right, bottom, top)
NAME
viewport(3f) - [M_pixel] Specify which part of the screen to draw in.
subroutine mapping ()
NAME
subroutine world2viewport (xw, yw, xv, yv)
subroutine viewport2world (xv, yv, xw, yw)
subroutine, public ortho2 (left, right, bottom, top)
NAME
ortho2(3f) - [M_pixel] define the area of the virtual world coordinates to map to the viewport
subroutine, public biggest_ortho2 (xsmall, xlarge, ysmall, ylarge)
NAME
biggest_ortho2(3f) - [M_pixel] define the area of the virtual world coordinates to map to the viewport
subroutine, public rmove2 (Xdelta, Ydelta)
NAME
rmove2(3f) - [M_pixel] relative move
subroutine, public move2 (x, y)
NAME
move2(3f) - [M_pixel] change current position
subroutine, public rdraw2 (xdelta, ydelta)
NAME
rdraw2(3f) - [M_pixel] draw from current position to given point
subroutine, public draw2 (x, y)
NAME
draw2(3f) - [M_pixel] draw from current position to given point
subroutine, public prefsize (x, y)
NAME
prefsize(3f) - [M_pixel] specify size of pixel array
SYNOPSIS
subroutine, public vexit ()
NAME
vexit(3f) - [M_pixel] exit pixel graphics mode
subroutine, public vinit (string)
NAME
vinit(3f) - [M_pixel] initialize pixel graphics module
subroutine, public makepoly ()
NAME
makepoly(3f) - [M_pixel] opens polygon constructed by a series of move-draws and closed by closepoly |
subroutine, public closepoly ()
NAME
closepoly(3f) - [M_pixel] Terminates a polygon opened by makepoly(3f)
subroutine, public print_ppm (filename)
NAME
print_ppm(3f) - [M_pixel] print pixel array as a ppm p3 file
subroutine, public print_ascii (filename)
NAME
print_ascii(3f) - [M_pixel] print small pixel array as ASCII text
subroutine, public textsize (width, height)
NAME
ppm - portable pixmap file format
subroutine, public ycentertext ()
NAME
ycentertext(3f) - [M_pixel] set text centering mode on for drawstr(3f) and drawc(3f) in Y direction
subroutine, public xcentertext ()
NAME
xcentertext(3f) - [M_pixel] set text centering mode on for drawstr(3f) and drawc(3f) in X direction
subroutine, public centertext (onoff)
NAME
centertext(3f) - [M_pixel] set text centering mode for drawstr(3f) and drawc(3f)
subroutine, public textang (ang)
NAME
textang(3f) - [M_pixel] set text angle
subroutine, public font (fontname)
NAME
font(3f) - [M_pixel] select font style by name
subroutine, public drawchar (ch)
NAME
drawchar(3f) - [M_pixel] Draw a character at the current position
subroutine, public drawstr (string)
NAME
drawstr(3f) - [M_pixel] Draw the text string at the current position
subroutine, public getgp2 (x, y)
NAME
getgp2(3f) - [M_pixel] Gets the current graphics position in world coords.
subroutine, public getdisplaysize (w, h)
NAME
getdisplaysize(3f) - [M_pixel] Returns the width and height of the device in pixels
subroutine, public point2 (x, y)
NAME
point2(3f) - [M_pixel] Draw a point at x, y
recursive subroutine, public state (string)
NAME
state(3f) - [M_pixel] print graphics state of M_pixel graphics module
subroutine, public poly2 (n, points)
NAME
poly2(3f) - [M_pixel] construct a polygon from an array of points
subroutine, public vflush ()
subroutine ppm_draw_fill_line (xstart, ystart, x, y)
subroutine ppm_draw_thick_line (inx1, iny1, inx2, iny2)
logical function ppm_yintercept (yscan, x1, y1, x2, y2, xintercept, yprev)
subroutine ppm_solid_fill (x, y, n)
subroutine ppm_endcap_circle (x, y)
Variables
real, parameter pi =3.14159265358979323844
real, parameter d2r =acos(-1.0)/180.0
logical, save p_vinit_called =.false.
real, save p_x =0.0
real, save p_y =0.0
integer, save p_width =1
integer, save p_color_index =1
integer, save p_nsegs =60
integer, save p_viewport_width =400
integer, save p_viewport_height =400
real, save p_text_height =10.0
real, save p_text_width =7.0
real, save p_text_angle =0.0
real, save p_text_cosine =1.0
real, save p_text_sine =0.0
logical, save p_x_centertext =.false.
logical, save p_y_centertext =.false.
character(len=20) p_font ='SIMPLEX'
integer, parameter p_maxverts =9999
logical, save p_inpolygon =.false.
integer, save p_polyvertex =1
real, dimension(2, p_maxverts), save p_polypoints
real, save p_viewport_left =0.0
real, save p_viewport_right =0.0
real, save p_viewport_bottom =0.0
real, save p_viewport_top =0.0
real, save p_window_left =0.0
real, save p_window_right =0.0
real, save p_window_bottom =0.0
real, save p_window_top =0.0
real, save p_a
real, save p_b
real, save p_c
real, save p_d
integer, dimension(:,:), allocatable, save, public p_pixel
integer, dimension(3, 0:255), save, public p_colormap
logical, save, public p_debug =.false.
integer p_ioff =0
integer p_just1
integer p_just2
integer p_nchr
integer, dimension(350) p_ichr
integer j
integer, dimension(4711), save symbcd
integer, dimension(432), save istart
integer, dimension(128), save ssymbc
integer, dimension(22), save isstar
real, dimension(432), save width
Detailed Description
NAME
M_pixel(3f) - [M_pixel] module for drawing into a pixel array with 2D vector operations
SYNOPSIS
Module procedures
use M_writegif, only : writegif
use :: M_pixel, only : drawchar, rect, rdraw2, strlength use :: M_pixel, only : color, mapcolor, clear, draw2 use :: M_pixel, only : circle, circleprecision, arc, getviewport use :: M_pixel, only : viewport, ortho2, rmove2 use :: M_pixel, only : line, linewidth, polyline, move2 use :: M_pixel, only : move2, draw2, prefsize, vinit use :: M_pixel, only : textang, textsize, drawstr, getgp2 use :: M_pixel, only : vflush, biggest_ortho2, point2, getdisplaysize use :: M_pixel, only : poly2, centertext, xcentertext, ycentertext use :: M_pixel, only : makepoly, closepoly, font
use :: M_pixel, only : state, hershey, justfy use :: M_pixel, only : print_ascii, print_ppm
! Differences between M_pixel and M_vogle and VOGLE-related procedures: ! hershey(3f) and justfy(3f) do not exist in VOGLE and might be replaced ! and the same font names are not available ! print_ascii(3f) and print_ppm(3f) do not exist in VOGLE ! state(3f) does not exist in VOGLE ! biggest_ortho2(3f) is like juaspct(3f) ! viewport is in terms of pixels, not range -1.0 to 1.0
Module variables
use M_pixel, only : P_pixel, P_ColorMap, P_debug
DESCRIPTION
M_pixel(3fm) is intended to produce simple pixel graphics composed of
line drawings and polygon fills in two dimensions. It handles circles,
curves, arcs, polygons, and software text. It is designed to provide a
programming interface very similar to a subset of the VOGLE graphics
library (M_pixel does not support objects, interactive graphics,
or 3D vectors).
It is primarily intended to provide a simple Fortran-based set of
routines that can generate simple graphics that can be written to a
GIF file using the writegif(3f) routine.
This is a prototype under construction starting 2017-06, but is already
useful. Improvements in line width, dashed lines, polygon fill and
higher level graphing routines are being worked on. If anyone is
interested in collaborating on the module, contact the author.
EXAMPLE
Sample program
program demo_M_pixel
use M_pixel use M_writegif, only : writegif use M_units, only : cosd, sind implicit none
integer :: i integer :: j integer :: icolor
! initialize image call prefsize(400,400) ! set size before starting call vinit() ! start graphics call clear(0) ! clear to color 0
! put some colored boxes into pixmap by address ! so show how the pixel map can be edited easily with ! other routines that can manipulate a pixel array. ! The P_pixel array was created when vinit(3f) was called icolor=1 do i=1,4 do j=1,4 P_pixel((i-1)*100+1+3:i*100-3,(j-1)*100+1+3:j*100-3)=icolor icolor=icolor+1 enddo enddo
! map area of virtual world to pixel array ! notice Y-axis for viewport is zero at TOP ! viewport(left, right, bottom, top) call viewport(0.0, 400.0, 400.0, 0.0) ! define the virtual world area we want to work in !ortho2(left, right, bottom, top) call ortho2(0.0, 400.0, 0.0, 400.0) ! the drawing routines use these world units
! draw polar grids call linewidth(100) call color(14) call target(200.0,200.0,200.0)
call linewidth(75) call color(0) call target(100.0,200.0,50.0)
! draw some lines call color(1) call linewidth(200) call line(1.0,1.0,400.0,400.0)
call color(4) call line(350.0,200.0,350.0,300.0)
! print some text call color(1) !call hershey(x,y,height,itext,theta,ntext) call linewidth(125) call hershey(40.0, 40.0,35.0,'Hello World',0.0,11) call color(7) call linewidth(25) call hershey(40.0, 80.0,35.0,'Hello World',0.0,11) call linewidth(100) call hershey(40.0,120.0,35.0,'Hello World',30.0,11)
call hershey(40.0,350.0,35.0,' World',0.0,20) call hershey(40.0,310.0,35.0,' World',0.0,19) call hershey(350.0,400.0,35.0,' World',90.0,19) call linewidth(50) call hershey(200.0,120.0,15.0,' World',20.0,20)
! change background color directly where (P_pixel.eq.0) P_pixel=9 ! write standard gif file call writegif('M_pixel.3.gif',P_pixel,P_ColorMap)
contains
subroutine target(xc,yc,rc) use M_units, only : cosd, sind real :: xc,yc,rc integer :: i real :: x,y do i=0,360,10 x=rc*cosd(i) y=rc*sind(i) call line(xc,yc,xc+x,yc+y) enddo do i=1,int(rc),10 call circle(xc,yc,real(i)) enddo end subroutine target end program demo_M_pixel
Function/Subroutine Documentation
arc()
subroutine, public m_pixel::arc (real, intent(in) x, real, intent(in) y, real, intent(in) radius, real, intent(in) startang, real, intent(in) endang)
NAME
arc(3f) - [M_pixel] draw an arc using current line width and color
SYNOPSIS
definition:
subroutine arc(x, y, radius, startang, endang) real,intent(in) :: x real,intent(in) :: y real,intent(in) :: radius real,intent(in) :: startang real,intent(in) :: endang
DESCRIPTION
Draw an arc. x, y, and radius are values in world units.
Angles are in degrees, positive measured counterclockwise from the
+X axis. The current position after the arc is drawn is at the end
of the arc.
OPTIONS
X,Y Coordinates for the center of the circle RADIUS Radius of the circle STARTANG Start angle ENDANG End angle
EXAMPLE
Sample program:
program demo_arc use M_pixel use M_writegif, only : writegif integer :: transparent=0 call prefsize(600,240) call vinit() call ortho2(0.0,60.0,0.0,24.0) call linewidth(400) call color(1) call arc(16.0,12.0,12.0,90.0,270.0) call color(2) call arc(44.0,12.0,12.0,-90.0,90.0) ! write gif with a transparent background call writegif('arc.3.gif',P_pixel,P_ColorMap,transparent) call vexit() end program demo_arc
References m_units::cosd(), draw2(), move2(), p_nsegs, and m_units::sind().
biggest_ortho2()
subroutine, public m_pixel::biggest_ortho2 (real, intent(in) xsmall, real, intent(in) xlarge, real, intent(in) ysmall, real, intent(in) ylarge)
NAME
biggest_ortho2(3f) - [M_pixel] define the area of the virtual world coordinates to map to the viewport
SYNOPSIS
definition:
subroutine biggest_ortho2(left, right, bottom, top) real,intent(in) :: left, right, bottom, top
DESCRIPTION
Defines the section of the virtual world coordinates to map to the viewport. Automatically use the largest viewport that provides one-to-one correspondence between the window and the viewport.
EXAMPLE
References getdisplaysize(), ortho2(), p_debug, and viewport().
centertext()
subroutine, public m_pixel::centertext (logical, intent(in) onoff)
NAME
centertext(3f) - [M_pixel] set text centering mode for drawstr(3f) and drawc(3f)
SYNOPSIS
definition:
subroutine centertext(onoff) logical,intent(in) :: onoff
DESCRIPTION
Set text centering mode on or off. Only approximate in vertical direction.
OPTIONS
ONOFF set centering mode on or off
EXAMPLE
Sample program:
program demo_centertext use :: M_pixel use :: M_units, only : cosd, sind use :: M_writegif, only : writegif !! set up drawing environment call prefsize(600,600) call vinit() call ortho2(-300.0,300.0,-300.0,300.0) call textsize(8.0,8.0) call linewidth(30) x1=-150 y1=-150 do j=1,4 select case(j) case(1); call xcentertext(); x1=-150; y1=-150; r=100 case(2); call ycentertext(); x1=+150; y1=-150; r= 30 case(3); call centertext(.true.); x1=-150; y1=+150; r=100 case(4); call centertext(.false.); x1=+150; y1=+150; r= 30 end select !! draw radial lines call color(1) do i=1,80 call move2(x1,y1) call draw2(x1+150.0*cosd(i*12), y1+150.0*sind(i*12)) enddo
!! draw rotated text call color(2) do i=1,30 ang=i*12.0 xx=x1+r*cosd(ang) yy=y1+r*sind(ang) call move2(xx,yy) call textang(ang) call color(7) call drawstr('This is angled text') call color(1) enddo enddo
call writegif('centertext.3.gif',P_pixel,P_colormap) call execute_command_line('display centertext.3.gif')
call vexit()
end program demo_centertext
References p_x_centertext, and p_y_centertext.
chrcod()
subroutine m_pixel::chrcod (character(len=*), intent(in) text, integer, intent(in) ntext) private
References j, p_ichr, p_ioff, and p_nchr.
circle()
subroutine, public m_pixel::circle (real, intent(in) x, real, intent(in) y, real, intent(in) radius)
NAME
circle(3f) - [M_pixel] draw a circle using current line width and color
SYNOPSIS
definition:
subroutine circle(x,y,radius) real,intent(in) :: x real,intent(in) :: y real,intent(in) :: radius
DESCRIPTION
Draw a circle using the current line width and color into the pixel array. Units are in world coordinates.
OPTIONS
X,Y Coordinates for the center of the circle RADIUS Radius of the circle
EXAMPLE
Sample program:
program demo_circle use M_pixel use M_writegif, only : writegif !! set up drawing surface call prefsize(400,400) call vinit() call ortho2(left=-100.0, right=100.0, bottom=-100.0, top=100.0) call color(3) call clear() call color(4) call linewidth(200) !! draw some circles call circle(0.0, 0.0, 90.0) call color(1) call circle(0.0, 0.0, 40.0) call color(2) call circle(-25.0, 25.0, 20.0) call circle(-25.0,-25.0, 20.0) call circle(25.0, 25.0, 20.0) call circle(25.0,-25.0, 20.0) !! render the pixel map call writegif('circle.3.gif',P_pixel,P_colormap) !! display the graphic assuming display(1) is available call execute_command_line('display circle.3.ppm') !! exit graphics mode call vexit() end program demo_circle
References m_units::cosd(), line(), p_nsegs, and m_units::sind().
circleprecision()
subroutine, public m_pixel::circleprecision (integer, intent(in) nsegs)
NAME
circleprecision(3f) - [M_pixel] set number of line segments used to approximate a circle
SYNOPSIS
definition:
subroutine circleprecision(nsegs) integer :: nsegs
DESCRIPTION
Set the number of line segments making up a circle. Default is currently
The number of segments in an arc or sector is calculated from the variable "nsegs" according to the span of the arc or sector.
OPTIONS
NSEGS number of line segments making up a circle
EXAMPLE
Sample program:
program demo_circleprecision use M_pixel use M_strings, only : v2s use M_writegif, only : writegif real :: b=0.5 real :: y1,y2,ym,x1,x2 real :: width=50.0/8.0,width2 integer,parameter :: ivals(*)=[3,5,7,10,20,30,60,100] integer :: i !! set up long bar as plotting area call prefsize(1000,200) call vinit() call ortho2(-25.0-b, 25.0+b, -5.0-b, 5.0+b) call textsize(2.5/2.0, 3.0/2.0) call font('DUPLEX') call centertext(.true.) call linewidth(30) call color(2) y1=-5 y2=5 ym=0 x1=-25+.05*width ! draw colored rectangle and a circle and label center of circle repeat width2=width*0.95 do i=1,size(ivals) x2=x1+width2 call move2((x1+x2)/2.0,ym) call circleprecision(ivals(i)) call drawstr((v2s(ivals(i)))) ! convert number to string and draw it call circle((x1+x2)/2.0, ym, (x2-x1)/2.10) x1=x1+width enddo ! write plot as GIF file call writegif('circleprecision.3.gif',P_pixel,P_colormap) call vexit() ! use system to display GIF file call execute_command_line('display circleprecision.3.gif') end program demo_circleprecision
References p_nsegs.
clear()
subroutine, public m_pixel::clear (integer, intent(in), optional indx)
NAME
clear(3f) - [M_pixel] clear background to current color or specified color index
SYNOPSIS
definition:
subroutine clear(indx) integer,intent(in),optional :: indx
DESCRIPTION
Clears the screen to the current color or to color specified
OPTIONS
INDX color index to set pixel array to. Optional
EXAMPLE
References if_init(), p_color_index, and p_pixel.
closepoly()
subroutine, public m_pixel::closepoly ()
NAME
closepoly(3f) - [M_pixel] Terminates a polygon opened by makepoly(3f)
SYNOPSIS
definition:
 subroutine closepoly()
DESCRIPTION
Terminates a polygon opened by MAKEPOLY(3f).
References false(), p_inpolygon, p_polypoints, p_polyvertex, and poly2().
color()
subroutine, public m_pixel::color (integer, intent(in) icolor)
NAME
color(3f) - [M_pixel] set current color index
SYNOPSIS
definition:
subroutine color(col) integer,intent(in) :: col
DESCRIPTION
Set the current color. The standard colors are as follows:
black = 0 red = 1 green = 2 yellow = 3 blue = 4 magenta = 5 cyan = 6 white = 7
OPTION
COL A color number from 0 to 255. To define additional colors see mapcolor(3f).
EXAMPLE
Sample program:
program demo_color use M_pixel use M_strings, only : v2s use M_writegif, only : writegif real :: b=0.5 real :: y1,y2,ym,x1,x2 real :: width=50.0/8.0,width2 integer :: i !! set up long bar as plotting area call prefsize(1000,200) call vinit() call ortho2(-25.0-b, 25.0+b, -5.0-b, 5.0+b) call textsize(3.5, 4.0) call font('DUPLEX') call centertext(.true.) call linewidth(90) y1=-5 y2=5 ym=0 x1=-25+.05*width ! draw colored rectangle and a circle and label center of circle ! and repeat from colors 0 to 7. width2=width*0.95 do i=0,7 call color(i) x2=x1+width2 call makepoly() call rect(x1,y1,x2,y2) call closepoly() call color(i+1) call move2((x1+x2)/2.0,ym) call drawstr((v2s(i))) ! convert number to string and draw it call circle((x1+x2)/2.0, ym, (x2-x1)/2.10) x1=x1+width enddo ! write plot as GIF file call writegif('color.3.gif',P_pixel,P_colormap) call vexit() ! use system to display GIF file call execute_command_line('display color.3.gif') end program demo_color
References p_color_index.
draw2()
subroutine, public m_pixel::draw2 (real, intent(in) x, real, intent(in) y)
NAME
draw2(3f) - [M_pixel] draw from current position to given point
SYNOPSIS
definition:
subroutine draw2(x, y) real,intent(in) :: x, y
DESCRIPTION
Draw from current position to specified point using current color and line width. Updates current position to new point. (x, y) is a point in world coordinates.
OPTIONS
X new X position Y new Y position
EXAMPLE
Sample program:
program demo_draw2 use M_pixel, only : prefsize, vinit, ortho2, clear use M_pixel, only : move2, draw2, vexit, color,linewidth use M_pixel, only : P_pixel, P_colormap use M_writegif, only : writegif use M_units, only : d2r, polar_to_cartesian ! ! The Archimedean spiral is the locus of points corresponding ! to the locations over time of a point moving away from a ! fixed point with a constant speed along a line which rotates ! with constant angular velocity. ! r=A+B*theta ! Changing the parameter A will turn the spiral, ! while B controls the distance between successive turnings. ! implicit none integer :: i real :: x,y,radius,theta real,parameter :: rotate=0.0, gap=2.0 call prefsize(400,400) call vinit('') call ortho2(-150.0,150.0,-150.0,150.0) call color(5) call clear() call move2(0.0,0.0) call color(0) call linewidth(40) do i=0,360*10,5 theta=d2r(i) ! equation in polar coordinates radius=rotate+gap*theta ! convert polar coordinates to cartesian call polar_to_cartesian(radius,theta,x,y) ! draw from current position to end of next segment call draw2(x,y) enddo ! write the pixel map array as a GIF image file call writegif('draw2.3.gif',P_pixel,P_colormap) ! exit graphics mode call vexit() end program demo_draw2
References line(), p_x, and p_y.
draw_line_single()
subroutine m_pixel::draw_line_single (integer, intent(in) x1, integer, intent(in) y1, integer, intent(in) x2, integer, intent(in) y2) private
NAME
draw_line_single(3fp) - [M_pixel] Bresenham's line algorithm
SYNOPSIS
definition:
subroutine draw_line_single(x1,y1, x2,y2) integer,intent(in) :: x1,y1,x2,y2
DESCRIPTION
From Wikipedia, the free encyclopedia
The Bresenham line algorithm is an algorithm that determines which points in an n-dimensional raster should be plotted in order to form a close approximation to a straight line between two given points. It is commonly used to draw lines on a computer screen, as it uses only integer addition, subtraction and bit shifting all of which are very cheap operations in standard computer architectures. It is one of the earliest algorithms developed in the field of computer graphics.
Through a minor expansion, the original algorithm for lines can also be used to draw circles. Also this can be done with simple arithmetic operations; quadratic or trigonometric expressions can be avoided or recursively dissolved into simpler steps.
The mentioned properties make it still an important algorithm, and it is used among others in plotters, in graphics chips of modern graphics cards, and in many graphics libraries. As it is so simple, it is not only implemented in the firmware of such devices, but is also cast into hardware of those graphics chips.
To be precise, the label "Bresenham" is today often used for a whole family of algorithms, which have actually been developed by others, later, yet in succession of Bresenham and with a similar basic approach. See deeper references below.
CONTENTS
1 The algorithm
2 Generalisation
3 Optimisation
4 Different approach to the algorithm
4.1 Generalized version for this approach
5 Circle Variant
5.1 Drawing incomplete octants
5.2 Ellipses
6 History
7 Similar Algorithms
8 References
9 See also
10 External links
The common conventions that pixel coordinates increase in the down and right directions and that pixel centers have integer coordinates will be used. The endpoints of the line are the pixels at (x[0], y[0]) and (x[1], y[1]), where the first coordinate of the pair is the column and the second is the row.
The algorithm will be initially presented only for the octant in which the segment goes down and to the right (x[0]?x[1] and y[0]?y [1]) , and its horizontal projection x[1] ? x[0] is longer than the vertical projection y[1] ? y0 In this octant, for each column x between x[0] and x[1], there is exactly one row y (computed by the algorithm) containing a pixel of the line, while each row between y[0] and y[1] contains multiple rasterized pixels.
Bresenham's algorithm chooses the integer y corresponding to the pixel center that is closest to the ideal (fractional) y for the same x; on successive columns y can remain the same or increase by 1. The general equation of the line through the endpoints is given by:
y - y_0 = \frac{y_1-y_0}{x_1-x_0} (x-x_0).
Since we know the column, x, the pixel's row, y, is given by rounding this quantity to the nearest integer:
\frac{y_1-y_0}{x_1-x_0} (x-x_0) + y_0.
The slope (y[1] ? y[0]) / (x[1] ? x[0]) depends on the endpoint coordinates only and can be precomputed, and the ideal y for successive integer values of x can be computed starting from y[0] and repeatedly adding the slope.
In practice, the algorithm can track, instead of possibly large y values, a small error value between ?0.5 and 0.5: the vertical distance between the rounded and the exact y values for the current x. Each time x is increased, the error is increased by the slope; if it exceeds 0.5, the rasterization y is increased by 1 (the line continues on the next lower row of the raster) and the error is decremented by 1.0.
In the following pseudocode sample plot(x,y) plots a point and abs returns absolute value:
function line(x0, x1, y0, y1) int deltax := x1 - x0 int deltay := y1 - y0 real error := 0 real deltaerr := deltay / deltax // Assume deltax != 0 (line is not vertical) int y := y0 for x from x0 to x1 plot(x,y) error := error + deltaerr if abs(error) ? 0.5 then y := y + 1 error := error - 1.0
GENERALISATION
This first version only handles lines that descend to the right. We would of course like to be able to draw all lines. The first case is allowing us to draw lines that still slope downwards but head in the opposite direction. This is a simple matter of swapping the initial points if x0 > x1. Trickier is determining how to draw lines that go up. To do this, we check if y[0] ? y[1]; if so, we step y by -1 instead of 1. Lastly, We still need to generalize the algorithm to drawing lines in all directions. Up until now we have only been able to draw lines with a slope less than one. To be able to draw lines with a steeper slope, we take advantage of the fact that a steep line can be reflected across the line y=x to obtain a line with a small slope. The effect is to switch the x and y variables throughout, including switching the parameters to plot. The code looks like this:
function line(x0, x1, y0, y1) boolean steep := abs(y1 - y0) > abs(x1 - x0) if steep then swap(x0, y0) swap(x1, y1) if x0 > x1 then swap(x0, x1) swap(y0, y1) int deltax := x1 - x0 int deltay := abs(y1 - y0) real error := 0 real deltaerr := deltay / deltax int ystep int y := y0 if y0 < y1 then ystep := 1 else ystep := -1 for x from x0 to x1 if steep then plot(y,x) else plot(x,y) error := error + deltaerr if error ? 0.5 then y := y + ystep error := error - 1.0
The function now handles all lines and implements the complete Bresenham's algorithm. A more standard C code for the algorithm is shown here:
void Bresenham(int x1, int y1, int x2, int y2) { int slope; int dx, dy, incE, incNE, d, x, y; // Reverse lines where x1 > x2 if (x1 > x2) { Bresenham(x2, y2, x1, y1); return; } dx = x2 - x1; dy = y2 - y1; // Adjust y-increment for negatively sloped lines if (dy < 0) { slope = -1; dy = -dy; } else { slope = 1; } // Bresenham constants incE = 2 * dy; incNE = 2 * dy - 2 * dx; d = 2 * dy - dx; y = y1; // Blit for (x = x1; x <= x2; x++) { putpixel(x, y); if (d <= 0) { d += incE; } else { d += incNE; y += slope; } } }
OPTIMISATION
The problem with this approach is that computers operate relatively slowly on fractional numbers like error and deltaerr; moreover, errors can accumulate over many floating-point additions. Working with integers will be both faster and more accurate. The trick we use is to multiply all the fractional numbers above by deltax, which enables us to express them as integers. The only problem remaining is the constant 0.5?to deal with this, we change the initialization of the variable error. The new program looks like this:
function line(x0, x1, y0, y1) boolean steep := abs(y1 - y0) > abs(x1 - x0) if steep then swap(x0, y0) swap(x1, y1) if x0 > x1 then swap(x0, x1) swap(y0, y1) int deltax := x1 - x0 int deltay := abs(y1 - y0) int error := -deltax / 2 int ystep int y := y0 if y0 < y1 then ystep := 1 else ystep := -1 for x from x0 to x1 if steep then plot(y,x) else plot(x,y) error := error + deltay if error > 0 then y := y + ystep error := error - deltax
DIFFERENT APPROACH TO THE ALGORITHM
A different approach to the Bresenham algorithm works more from the practical side. It was published by Pitteway ^[1] and confirmed by van Aken ^[2]. Again we first consider a line in the first octant, which means a slope between 0 and 1. Mathematicall y spoken, we want to draw a line from point (x[1],y[1]) to (x[2],y[2]). The intervals in the two directions are dx=x[2]-x[1] and dy=y[2]-y [1], and the slope is dy/dx. The line equation can be written as y=y[1]+(x-x[1])*dy/dx. In this first octant, we have 0<dy<=dx.
So, when working pixel-wise along this line, we have one "fast" direction, the positive x direction, and a "slow" direction, the positive y direction, where fewer steps have to be done than in the fast one. So the algorithm simply goes like this: a) Always do a single pixel step in the fast direction. b) Every now and then also do a step in the slow direction.
Bresenham's trick is the introduction of an error term, which deals with the decision, when to do also this extra step in the slow direction. The line equation is transformed into 0=dx*(y-y[1])-dy*(x-x[1]), and then the null on the left side is replaced by the error term. A step by 1 in the x direction (variable x) causes a decrement of the error term by one times dy. If the error term gets below zero due to this, it will be increased by one times dx through a step by 1 in the y direction (variable y). Because of dx>=dy, this will render the error term positive again in any case, at least brought back to zero.
You realize a cross-wise subtraction of dy from the error term for any x step and an addition of dx for any y step. This way, the division dy/dx for the slope is dissolved into a number of more elementary operations.
A critical issue is the initialisation of the error term. In this approach here, we simply consider a line with dy=1, so with only one single step in the y direction along the whole line. Of course for the best look of the line, we want this step to happen right in the middle of the line. This leads to initialising the error term to dx/2. (Rounding this term to integers in case of odd dx is no problem.)
This approach comes out a little different from the original, as it avoids the additional factor of 2 on both sides, which has to do with the initialisation.
To generalize this algorithm for all octants, you will again have to do role changes of x and y and consider the different signs of dx and dy.
A simple implementation of this approach is not very elegant, but demonstrates the principle of the algorithm fairly well.
REM Bresenham algorithm for a line in the first octant in Pseudo Basic dx = xend-xstart dy = yend-ystart REM in first octant, we have 0 < dy <= dx
REM Initialisations x = xstart y = ystart SETPIXEL x,y error = dx/2
REM Pixel loop: always do a step in fast direction, every now and then also one in the slow direction WHILE x < xend REM Step in fast direction x = x + 1 error = error-dy IF error < 0 THEN REM Step in slow direction y = y + 1 error = error + dx ENDIF SETPIXEL x,y WEND
GENERALIZED VERSION FOR THIS APPROACH
This generalized version in BASIC shall be valid for all octants. For this, all signs of the coordinate distances have to be considered, as well as the possible role change of x and y. If these if clauses would all be put into the innermost loop, which would mean a high number of executions, it would considerably increase the time consumption. A more efficient solution tries to put all these case differentiations into the initialisation phase of the procedure before the start of the inner main loop. Then the inner loop will still contain a single if clause for the Bresenham error term.
This version in BASIC introduces a number of abstractions: First the step in the "fast" direction is now considered a parallel step (parallel to one of the coordinate axis), and if additionally a step in the "slow" direction becomes necessary, it becomes a diagonal step. For these cases we can compute variable values during initialisation, in advance, which contain the step widths (including signs) in the coordinate directions and thus achieve the generalization for the eight octants. For example the step width in perpendicular direction to a parallel step is just zero. Secondly the error term is still computed like in the first octant by using the abolute values of the distances. In the innermost loop, no more the step in the fast direction is executed first, but the error term is updated, and only after that the step widths are added to the current coordinate values, depending on whether a parallel or a diagonal step has to be done:
REM Bresenham algorithm for a line in an arbitrary octant in pseudo Basic dx = xend-xstart dy = yend-ystart
REM Initialisations adx = ABS(dx): ady = ABS(dy) ' Absolute values of distances sdx = SGN(dx): sdy = SGN(dy) ' Signum of distances
IF adx > ady THEN ' x is fast direction pdx = sdx: pdy = 0 ' pd. is parallel step ddx = sdx: ddy = sdy ' dd. is diagonal step ef = ady: es = adx ' error steps fast, slow ELSE ' y is fast direction pdx = 0 : pdy = sdy ' pd. is parallel step ddx = sdx: ddy = sdy ' dd. is diagonal step ef = adx: es = ady ' error steps fast, slow ENDIF
x = xstart y = ystart SETPIXEL x,y error = es/2
REM Pixel loop: always a step in fast direction, every now and then also one in slow direction FOR i=1 TO es ' es also is the count of pixels zo be drawn REM update error term error = error - ef IF error < 0 THEN error = error + es ' make error term positive (>=0) again REM step in both slow and fast direction x = x + ddx: y = y + ddy ' Diagonal step ELSE REM step in fast direction x = x + pdx: y = y + pdy ' Parallel step ENDIF SETPIXEL x,y NEXT
RASTERISATION OF A CIRCLE BY THE BRESENHAM ALGORITHM
The approach for the Circle Variant shown here is also not originally from Bresenham, see again references to Pitteway and van Aken below. The algorithm starts accordingly with the circle equation x?+y?=r?. Again we consider first only the first octant. Here you want to draw a curve which starts at point (r,0) and then proceeds to the top left, up to reaching the angle of 45?.
The "fast" direction here is the y direction. You always do a step in the positive y direction (upwards), and every now and then you also have to do a step in the "slow" direction, the negative x direction.
The frequent computations of squares in the circle equation, trigonometric expressions or square roots can again be avoided by dissolving everything into single steps and recursive computation of the quadratic terms from the preceding ones.
From the circle equation you get to the transformed equation 0=x?+y?-r? with r? to be computed only a single time during initialisation, x?=(xpreceding-1)?=xpreceding?-2*xpreceding+1 (according for y), where x? (or xpreceding?) is kept as an own variable. Additionally you need to add the mid point coordinates when setting a pixel. These frequent integer additions do not limit the performance much, as you spare those square (root) computations in the inner loop in turn. Again the zero in the transformed circle equation is replaced by the error term.
The initialization of the error term is derived from an offset of ? pixel at the start. Until the intersection with the perpendicular line, this leads to an accumulated value of r in the error term, so that this value is used for initialisation.
The following implementation is shown here only for the first octant, and again the other octants need sign changes for x and/or y and the swapping of x and y. An easy expansion for full circles, as it is possible for graphics displays, but not for plotters, is added in the comments.
REM Bresenham Algorithm for one eighth of a circle in Pseudo-Basic
REM given: r, xmid, ymid
REM initialisations for the first octant
r2 = r*r : REM single multiplication
x = r
y = 0
error = r
SETPIXEL xmid + x, ymid + y
REM Pixel loop: always a step in fast direction, every now and then also in slow one
WHILE y <= x
   REM step in fast direction (positive y direction)
   dy = y*2+1 : REM in Assembler implementation *2 per Shift
   y = y+1
   error = error-dy
   IF error<0 THEN
      REM step in slow direction (here the negative x direction)
      dx = 1-x*2 : REM in Assembler implementation *2 per Shift
      x = x-1
      error = error-dx
      ENDIF
   SETPIXEL  xmid+x, ymid+y
   REM If this deals with a screen and not a mechanical plotter,
   REM you can cover simultaneously also the other octants:
   REM SETPIXEL xmid-x, ymid+y
   REM SETPIXEL xmid-x, ymid-y
   REM SETPIXEL xmid+x, ymid-y
   REM SETPIXEL xmid+y, ymid+x
   REM SETPIXEL xmid-y, ymid+x
   REM SETPIXEL xmid-y, ymid-x
   REM SETPIXEL xmid+y, ymid-x
   WEND
A possible implementation of the Bresenham Algorithm for a full circle in C. Here another variable for recursive computation of the quadratic terms is used, which corresponds with the term 2*n+1 above. It just has to be increased by 2 from one step to the next:
void rasterCircle(int x0, int y0, int radius) { int f = 1 - radius; int ddF_x = 0; int ddF_y = -2 * radius; int x = 0; int y = radius;
setPixel(x0, y0 + radius); setPixel(x0, y0 - radius); setPixel(x0 + radius, y0); setPixel(x0 - radius, y0);
while(x < y) { if(f >= 0) { y–; ddF_y += 2; f += ddF_y; } x++; ddF_x += 2; f += ddF_x + 1; setPixel(x0 + x, y0 + y); setPixel(x0 - x, y0 + y); setPixel(x0 + x, y0 - y); setPixel(x0 - x, y0 - y); setPixel(x0 + y, y0 + x); setPixel(x0 - y, y0 + x); setPixel(x0 + y, y0 - x); setPixel(x0 - y, y0 - x); } }
Note: There is correlation between this algorithm and the sum of first N odd numbers. Which this one basicall y does. Sum of N odd numbers, from 1 inclusive, is equal to the square of N (N squared). See Square number.
So. When we compare sum of N odd numbers to this algorithm we have. ddF_y = -2 * radius is connected to last member of of sum of N odd numbers. This member has index equal to value of radius (integral). Since odd number is 2*n + 1 there is 1 handled elsewhere or it should be -2*radius - 1 ddF_x = 0 should be 1. Because difference between two consecutive odd numbers is 2. If so f += ddF_y + 1 is f+= ddF_y. Saving one operation. f = - radius + 1 Initial error equal to half of "bigger" step. In case of saving one addition it should be either -radius or -radius + 2. In any case there should be addition of 1 driven out of outer loop. So. f += ddF_y Adding odd numbers from Nth to 1st. f += ddF_x Adding odd numbers from 1st to Nth. 1 is missing because it can be moved outside of loop.
DRAWING INCOMPLETE OCTANTS
The implementations above always only draw complete octants or circles. If you want to draw only a certain arc from an angle ? to an angle ?, you have to implement it in a way to first calculate the x and y coordinates of these end points, where you inevitably have to resort to trigonometric or square root computations (see Methods of computing square roots). Then you run the Bresenham algorithm over the complete octant or circle and set the pixels only if they fall into the wanted interval. After finishing this arc, you can abort the algorithm prematurely.
ELLIPSES
By scaling the drawn x and y values (and horizontal or vertical line expansion, respectively) you can produce even ellipses parallel to the x or y axis. For this, you use the circle algorithm with the smaller ellipse axis as radius and add a value in the other direction, which again is computed through another Bresenham line algorithm increasing from the pole to the equator. As the ellipse has to be elongated into the longer axis direction, you don't set single pixels anymore, but have to draw lines (though simple ones, only horizontal or vertical) from the previous to the next point.
A general ellipse can be derived from such an axis-parallel one by application of a shearing operation on it. Again you use an additional Bresenham line algorithm to compute the offset increasing in one of the axis directions and to let it contribute to every drawn coordinate.
HISTORY
The algorithm was developed by Jack E. Bresenham in 1962 at IBM. In 2001 Bresenham wrote:
"I was working in the computation lab at IBM's San Jose development lab. A Calcomp plotter had been attached to an IBM 1401 via
the 1407 typewriter console. [The algorithm] was in production use by summer 1962, possibly a month or so earlier. Programs in
those days were freely exchanged among corporations so Calcomp (Jim Newland and Calvin Hefte) had copies. When I returned to
Stanford in Fall 1962, I put a copy in the Stanford comp center library.
A description of the line drawing routine was accepted for presentation at the 1963 ACM national convention in Denver,
Colorado. It was a year in which no proceedings were published, only the agenda of speakers and topics in an issue of
Communications of the ACM. A person from the IBM Systems Journal asked me after I made my presentation if they could publish
the paper. I happily agreed, and they printed it in 1965."
Bresenham later modified his algorithm to produce circles.
SIMILAR ALGORITHMS
The principle of using an incremental error in place of division operations has other applications in graphics. It is possible to use this technique to calculate the U,V co-ordinates during raster scan of texture mapped polygons. The voxel heightmap software-rendering engines seen in some PC games also used this principle.
REFERENCES
"The Bresenham Line-Drawing Algorithm", by Colin Flanagan
Bresenham also published a Run-Slice (as opposed to the Run-Length) computational algorithm.
^ Pitteway, M.L.V., "Algorithm for Drawing Ellipses or Hyperbolae with a Digital Plotter", Computer J., 10(3) November 1967, pp 282-289
^ Van Aken, J.R., "An Efficient Ellipse Drawing Algorithm", CG&A, 4(9), September 1984, pp 24-35
SEE ALSO
Patrick-Gilles Maillot's Thesis an extension of the Bresenham line drawing algorithm to perform 3D hidden lines removal; also published in MICAD '87 proceedings on CAD/CAM and Computer Graphics, page 591 - ISBN 2-86601-084-1.
Xiaolin Wu's line algorithm, a similarly fast method of drawing lines with antialiasing.
EXTERNAL LINKS
Analyze Bresenham's line algorithm in an online Javascript IDE
Basic Graphics Programs
The Bresenham Line-Drawing Algorithm by Colin Flanagan
National Institute of Standards and Technology page on Bresenham's algorithm
Calcomp 563 Incremental Plotter Information
Bresenham's Original Paper
Implementations in Java, C, and O Caml at the Code Codex
Retrieved from "http://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm"
References if_init(), p_color_index, p_debug, p_pixel, and swapcoord().
drawchar()
subroutine, public m_pixel::drawchar (character(len=1), intent(in) ch)
NAME
drawchar(3f) - [M_pixel] Draw a character at the current position
SYNOPSIS
definition:
subroutine drawchar(ch) character(len=1),intent(in) :: ch
DESCRIPTION
Draw a character at the current position. Uses current line color and thickness and text justification mode.
EXAMPLE
Sample program:
program demo_drawchar use M_pixel use M_writegif_animated, only : write_animated_gif integer,parameter :: isize=600 integer :: movie(32:124,0:isize-1,0:isize-1) !! set up environment call prefsize(isize,isize) call vinit() call ortho2(-100.0,100.0,-100.0,100.0) call textsize(150.0,150.0) call centertext(.true.)
do i=33,124 !! draw reference circle and crosshairs call linewidth(100) call color(0) call clear() call color(4) call circle(0.0,0.0,75.0) call move2(-75.0,0.0) call draw2(75.0,0.0) call move2(0.0,-75.0) call draw2(0.0,75.0) call color(7) call linewidth(200) call textang(3.0*i) call move2(0.0,0.0) call drawchar(char(i)) movie(i,:,:)=P_pixel enddo call vexit() !! write to file and display with display(1) call write_animated_gif('drawchar.3.gif',movie,P_colormap) call execute_command_line('display drawchar.3.gif') end program demo_drawchar
References drawstr().
drawstr()
subroutine, public m_pixel::drawstr (character(len=*), intent(in) string)
NAME
drawstr(3f) - [M_pixel] Draw the text string at the current position
SYNOPSIS
definition:
subroutine drawstr(string) character(len=*),intent(in) :: string
DESCRIPTION
Draw a text string at the current position. Uses current line color and thickness and text centering mode.
References m_units::cosd(), hershey(), justfy(), move2(), p_text_angle, p_text_cosine, p_text_height, p_text_sine, p_x, p_x_centertext, p_y, p_y_centertext, m_units::sind(), and strlength().
font()
subroutine, public m_pixel::font (character(len=*), intent(in) fontname)
NAME
font(3f) - [M_pixel] select font style by name
SYNOPSIS:
definition:
   subroutine font(fontname)
   character(len=*),intent(in) :: fontname
DESCRIPTION
Set the current font. Allowed names are
o futura.l SIMPLEX o futura.m DUPLEX o times.r COMPLEX o times.i ITALIC
EXAMPLE
Sample Program:
program demo_font use :: M_pixel use :: M_writegif, only : writegif real :: left real :: baseline=80.0 integer :: icolor=1 !! set up drawing surface call prefsize(400, 400) call vinit() call viewport(0.0, 400.0, 400.0, 0.0) call ortho2(-100.0, 100.0, -100.0, 100.0) call color(7) call clear() call textsize(10.0, 10.0) !! place a vertical line along the edge call color(1) call move2(-90.0, -90.0) call draw2(-90.0, 90.0) !! make a centered title at top a bit bolder and bigger call xcentertext() call textsize(13.0, 13.0) call linewidth(90) left=0 call nextline('Font Samples') !! print the font samples left=-90 call linewidth(0) call textsize(10.0, 10.0) call centertext(.false.) icolor=icolor-1 call nextline('DEFAULT (ie. futura.l)') icolor=icolor-1 call nextline('now call font(3f) ...') call nextline('SIMPLEX, or futura.l') call nextline('COMPLEX, or times.r') call nextline('ITALIC, or times.i') call nextline('DUPLEX, or futura.m') call writegif('font.3.gif',P_pixel,P_colormap) !call execute_command_line('display font.3.gif') call vexit() contains subroutine nextline(string) character(len=*) :: string !! reduce some duplicate code; very specific to this example integer :: iend iend=index(string,',') ! if comma, assume font name found if(iend.ne.0)call font(string(:iend-1)) ! change font icolor=icolor+1 ! set pen color call color(icolor) baseline=baseline-20 ! move down before drawing line call move2(left, baseline) call drawstr(string) ! draw string end subroutine nextline
end program demo_font
References p_font.
getdisplaysize()
subroutine, public m_pixel::getdisplaysize (real, intent(out) w, real, intent(out) h)
NAME
getdisplaysize(3f) - [M_pixel] Returns the width and height of the device in pixels
SYNOPSIS
definition:
subroutine getdisplaysize(w, h) real,intent(in) :: w, h
DESCRIPTION
Returns the width and height of the device in pixels in w and h respectively.
References p_viewport_height, and p_viewport_width.
getgp2()
subroutine, public m_pixel::getgp2 (real, intent(out) x, real, intent(out) y)
NAME
getgp2(3f) - [M_pixel] Gets the current graphics position in world coords.
SYNOPSIS
definition:
subroutine getgp2(x, y) real,intent(out) :: x,y
DESCRIPTION
Gets the current graphics position in world coords.
RETURNS
X X coordinate of current position Y Y coordinate of current position
EXAMPLE
Sample program
program demo_getgp2 use M_pixel implicit none real :: X,Y call prefsize(20,20) call vinit() call ortho2(-100.0,100.0,-100.0,100.0) call move2(0.0,0.0) call draw2(96.5,98.333)
call getgp2(X,Y) write(*,*)'CURRENT POSITION (X,Y)=',X,Y
call vexit() end program demo_getgp2
Results
CURRENT POSITION (X,Y)= 96.5000000 98.3330002
References p_x, and p_y.
getviewport()
subroutine, public m_pixel::getviewport (real, intent(out) left, real, intent(out) right, real, intent(out) bottom, real, intent(out) top)
NAME
getviewport(3f) - [M_pixel] return viewport in screen pixel coordinates
SYNOPSIS
definition:
subroutine getviewport(left, right, bottom, top) real,intent(out) :: left real,intent(out) :: right real,intent(out) :: bottom real,intent(out) :: top
DESCRIPTIONS
Returns the left, right, bottom and top limits of the current viewport in screen coordinates (-1.0 to 1.0).
Fortran:
     subroutine getviewport(left, right, bottom, top)
     real left, right, bottom, top
If a pixel array has been declared to be real :: array(600,400)
 o-----> X                         (right=600,top=0)
 | #------------------------------------#
 | |                                    |
 | |                                    |
 V |                                    |
 Y |                                    |
   #------------------------------------#
(left=0,bottom=400)
OPTIONS
LEFT value for left side RIGHT value for right side BOTTOM value for bottom side TOP value for top side
References p_viewport_bottom, p_viewport_left, p_viewport_right, and p_viewport_top.
hershey()
subroutine, public m_pixel::hershey (real, intent(in) x, real, intent(in) y, real, intent(in) height, character(len=*), intent(in) itext, real, intent(in) theta, integer, intent(in) ntext)
NAME
hershey(3f) - [M_pixel] draw text string as Hershey software vector fonts
SYNOPSIS
definition:
subroutine hershey(x,y,height,itext,theta,ntext) character(len=*),intent(in) :: itext real,intent(in) :: x,y real,intent(in) :: height real,intent(in) :: theta integer,intent(in) :: ntext
OPTIONS
X,Y are the coordinates in inches from the current origin to the lower left corner of the 1st character to be plotted. If either is set to 999.0 then saved next character position is used. HEIGHT is the character height in inches ITEXT contains the text to be plotted THETA is the positive CCW angle W.R.T. the X-axis NTEXT is the number of characters in itext to plot o If NTEXT.lt.-1 the pen is down to (X,Y) and a single special centered symbol is plotted. o If NTEXT.eq.-1 the pen is up to (X,Y) and a single special centered symbol is plotted. o if NTEXT=0 a single Simplex Roman character from ITEXT, left-justified, is plotted. o if NTEXT.gt.0 NTEXT characters from ITEXT are decoded and NCHR characters are plotted where NCHR.le.NTEXT to remove backslashes, command codes, etc.
DESCRIPTION
FEATURES: 1) Four HERSHEY letter fonts–SIMPLEX,COMPLEX,ITALIC, and DUPLEX– are provided in upper and lower case ROMAN 2) Two hershey letter fonts–SIMPLEX and COMPLEX–are provided in upper and lower case GREEK 3) 47 special mathematical symbols, e.g. integral sign, del... are provided 4) SUPER- and SUB-scripting is possible within a character string without separate calls to HERSHEY
Change of font is made by enclosing the name of the font in upper case in backslashes, e.g . Three letters suffice to specify the font. SIMPLEX is the default font on the initial call to HERSHEY. A font remains in effect until explicitly changed. SUPER- or SUB-scripting is accomplished by enclosing the expression to be SUPER- or SUB-scripted in curly brackets and preceding it by SUP or SUB. the closing curly bracket terminates the SUPER- or SUB-scripting and returns to normal character plotting. Note that SUPER- and SUB-script letters are plotted with a different character size.
GREEK letters are drawn by enclosing the ENGLISH name of the letter in backslashes, e.g. . The case of the first letter determines the case of the GREEK letter. The closing backslash must be included.
Any symbol may be called by enclosing the symbol number+1000 in backslashes. This is the only way to call some symbols, especially special mathematical symbols.
The symbol numbers are
1-26 upper case ROMAN SIMPLEX 27-52 lower case ROMAN SIMPLEX 53-72 SIMPLEX numbers and symbols 73-96 upper case GREEK SIMPLEX 97-120 lower case GREEK SIMPLEX 121-146 upper case ROMAN COMPLEX 147-172 lower case ROMAN COMPLEX 173-192 COMPLEX numbers and symbols 193-216 upper case GREEK COMPLEX 217-240 lower case GREEK COMPLEX 241-266 upper case ROMAN ITALIC 267-292 lower case ROMAN ITALIC 293-312 ITALIC numbers and symbols 313-338 upper case ROMAN DUPLEX 339-364 lower case ROMAN DUPLEX 365-384 DUPLEX numbers and symbols 385-432 special mathematical symbols
Additional features added Feb 1982:
The pen may be moved back to the start point for the previous character by . This is useful, for example, in writing integral signs with limits above and below them.
Symbol parameters taken from N.M.Wolcott, FORTRAN IV Enhanced Character Graphics, NBS
A.CHAVE IGPP/UCSD Aug 1981, Modified Feb 1982 by A. Chave, R.L. Parker, and L. Shure
programmed in FORTRAN-77
EXAMPLE
Show all Hershey characters
program demo_hershey use M_pixel use M_writegif_animated, only : write_animated_gif use M_strings, only : v2s integer,parameter :: isize=600 integer,parameter :: topsym=432 integer :: movie(1:topsym,0:isize-1,0:isize-1) !! set up environment call prefsize(isize,isize) call vinit() call ortho2(-150.0,150.0,-150.0,150.0)
!! draw all characters using hershey numeric strings do i=1,topsym !! draw reference circle and crosshairs call color(0) call clear()
call color(4) call linewidth(100) call circle(0.0,0.0,75.0) call move2(-75.0,0.0) call draw2(75.0,0.0) call move2(0.0,-75.0) call draw2(0.0,75.0)
call centertext(.true.) call color(7) call linewidth(500) call textang(3.0*i) call textang(0.0) call move2(0.0,0.0) call textsize(150.0,150.0) call drawstr('\'//v2s(i+1000)//'\')
call centertext(.false.) call color(1) call move2(-120.0,120.0) call textsize(10.0,10.0) call linewidth(40) call drawstr(v2s(i+1000)//' ') movie(i,:,:)=P_pixel enddo call vexit() !! write to file and display with display(1) call write_animated_gif('hershey.3.gif',movie,P_colormap,delay=40) !call execute_command_line('display hershey.3.gif') end program demo_hershey
References chrcod(), m_units::cosd(), hstylus(), isstar, istart, p_ichr, p_ioff, p_just1, p_just2, p_nchr, m_units::sind(), ssymbc, symbcd, and width.
hstylus()
subroutine m_pixel::hstylus (real, intent(in) xi, real, intent(in) yi, integer, intent(in) ipen) private
References line(), p_x, and p_y.
if_init()
subroutine m_pixel::if_init () private
References p_vinit_called, and vinit().
justfy()
subroutine, public m_pixel::justfy (real, dimension(4), intent(out) s, real, intent(in) height, character(len=*), intent(in) text, integer, intent(in) ntext)
NAME
justfy(3f) - [M_pixel] return lengths used to justify a string when calling hershey
SYNOPSIS
definition:
subroutine justfy(s, height, text, ntext) real,intent(out) :: s(4) real,intent(in) :: height character(len=*),intent(in) :: text integer,intent(in) :: ntext
DESCRIPTION
Given the text string TEXT with NTEXT characters, height HEIGHT, this routine gives 4 distances in inches, all from the left end of the string -
o S(1) to the left edge of the 1st nonblank character o S(2) to the center of the string, blanks removed from the ends o S(3) to the right edge of the last nonblank character o S(4) to the right edge of the last character of the string.
EXAMPLE
References chrcod(), p_ichr, p_just2, p_nchr, and width.
line()
subroutine, public m_pixel::line (real, intent(in) x1, real, intent(in) y1, real, intent(in) x2, real, intent(in) y2)
NAME
line(3f) - [M_pixel] draw line between two points
SYNOPSIS
definition:
subroutine line(x1,y1, x2,y2) real,intent(in) :: x1,y1,x2,y2
DESCRIPTION
Draw line between two points using current line width and color
OPTIONS
X1,Y1 starting point for line segment X2,Y2 end point for line segment
References draw_line_single(), p_debug, p_inpolygon, p_maxverts, p_polypoints, p_polyvertex, p_width, p_x, p_y, ppm_draw_thick_line(), and world2viewport().
linewidth()
subroutine, public m_pixel::linewidth (integer, intent(in) iwidth)
NAME
linewidth(3f) - [M_pixel] set linewidth
SYNOPSIS
definition:
subroutine linewidth(iwidth) integer iwidth
DESCRIPTION
Set the current line width in units of 1/10,000 of the X size of the display surface
EXAMPLE
Sample program:
program demo_linewidth use M_pixel, only : prefsize, vinit, ortho2, clear, P_pixel, P_colormap use M_pixel, only : move2, draw2, vexit, color, linewidth use M_writegif, only : writegif use M_units, only : d2r, polar_to_cartesian implicit none integer :: i real :: x,y,r,a,b,theta ! The Archimedean spiral is the locus of points corresponding ! to the locations over time of a point moving away from a ! fixed point with a constant speed along a line which rotates ! with constant angular velocity. ! r=a+b*theta ! Changing the parameter a will turn the spiral, ! while b controls the distance between successive turnings. call prefsize(401,401) call vinit('') call ortho2(-150.0,150.0,-150.0,150.0) call clear() call move2(0.0,0.0) call color(2) a=0.0 b=2.0 do i=0,360*10,5 theta=d2r(i) r=a+b*theta call polar_to_cartesian(r,theta,x,y) call linewidth(i/5/3) call draw2(x,y) enddo call writegif('linewidth.3.gif',P_pixel,P_colormap) call vexit() end program demo_linewidth
References p_viewport_width, and p_width.
makepoly()
subroutine, public m_pixel::makepoly ()
NAME
makepoly(3f) - [M_pixel] opens polygon constructed by a series of move-draws and closed by closepoly |
SYNOPSIS
definition:
subroutine makepoly()
DESCRIPTION
MAKEPOLY(3f) opens up a polygon which will then be constructed by a series of move-draws and closed by a CLOSEPOLY(3f).
EXAMPLE
Sample program:
program demo_makepoly use :: M_pixel use :: M_writegif, only : writegif use :: M_writegif_animated, only : write_animated_gif implicit none integer,parameter :: wide=640, tall=640 integer :: rows, xoff, yoff, box_sz integer :: i20, i30, ncols, nrows, ilines real :: bottom, left, sun_radius, planet_radius, planet_offset character(len=40) :: filename integer :: movie(300,0:wide-1,0:tall-1) call prefsize(wide,tall) call vinit() call ortho2(0.0, real(wide), 0.0, real(tall)) ! call linewidth(3) ! really slows down pbm driver because all lines are polygons call color(7) call clear() call color(0) rows=1 box_sz=MIN(wide,tall)/rows ! size of biggest box to use and get specified number of rows nrows = tall/box_sz ! number of rows of objects to draw ncols = wide/box_sz ! number of columns of objects to draw xoff = (wide - ncols * box_sz)/2 ! initial x offset to begin row at to center drawings yoff = (tall - nrows * box_sz)/2 ! initial x offset to begin column at to center drawings sun_radius = 148 planet_radius = 1 do ilines = 1, 300 do i20 = 1, ncols left = (i20-1)*box_sz+xoff do i30 = 1, nrows bottom = (i30-1)*box_sz+yoff call color(0) call makepoly() call rect(left,bottom,left+box_sz,bottom+box_sz) call closepoly() planet_offset= sun_radius call color(mod(ilines,15)+1) call hypoc(left + box_sz/2.0, bottom + box_sz/2.0, & & sun_radius, planet_radius, planet_offset, & & box_sz/2.0, ilines, & & 0.0, 0.0, 1) enddo enddo movie(ilines,:,:)=P_pixel write(filename,'("hypoc.",i0,".gif")')ilines !!call writegif(filename,P_pixel,P_colormap) enddo call write_animated_gif('makepoly.3.gif',movie,P_colormap,delay=70) call vexit() contains ! ! Make shapes using hypocycloidal curves. ! subroutine hypoc(xcenter,ycenter,sunr0,planet0,offset0,radius,ilines,ang,angs,ifill) use M_pixel implicit none real,parameter :: PI= 3.14159265358979323846264338327950288419716939937510 real,intent(in) :: xcenter, ycenter ! center of curve real,intent(in) :: sunr0,planet0,offset0 ! radii of sun, planet, and planet offset real,intent(in) :: radius ! radius to fit the shape to (no fit if radius is 0) integer,intent(in) :: ilines ! number of points to sample along curve real,intent(in) :: ang ! angle to rotate the shape by, to orientate it. real,intent(in) :: angs ! angle to start sampling points at; ccw is +; 0 is East integer,intent(in) :: ifill ! 1 make a filled polygon, 2 make a hatched polygon integer :: i10 real :: ang1, con1, con2, factor real :: offset, planet, r, sunr, u real :: xpoin, xpoin1, ypoin, ypoin1 sunr=sunr0 offset=offset0 planet=planet0 if(ilines.eq.0.0) return if(planet.eq.0.0) return if(sunr.eq.0.0) return if(radius.ne.0.and.sunr-planet+offset.ne.0)then factor=radius/(sunr-planet+offset) sunr=factor*sunr planet=factor*planet offset=factor*offset endif u=0.0+ang con1=PI*2.*(sunr/planet)/real(ilines) con2=(1.0-planet/sunr)*u xpoin1=(sunr-planet)*cos(planet*u/sunr)+offset*cos(con2) ypoin1=(sunr-planet)*sin(planet*u/sunr)-offset*sin(con2) ang1=atan2(ypoin1,xpoin1)+angs r=sqrt(xpoin1**2+ypoin1**2) xpoin1=r*cos(ang1)+xcenter ypoin1=r*sin(ang1)+ycenter select case(ifill) case(:0) case(1:) call makepoly() end select call move2(xpoin1,ypoin1) do i10=1,ilines u=con1*i10+ang con2=(1.0-planet/sunr)*u if(con2.ge.2**24) con2=amod(con2,PI) xpoin=(sunr-planet)*cos(planet*u/sunr)+offset*cos(con2) ypoin=(sunr-planet)*sin(planet*u/sunr)-offset*sin(con2) ang1=atan2(ypoin,xpoin)+angs r=sqrt(xpoin**2+ypoin**2) xpoin=r*cos(ang1)+xcenter ypoin=r*sin(ang1)+ycenter call draw2(xpoin,ypoin) enddo call draw2(xpoin1,ypoin1) if(ifill.gt.0)then call closepoly() endif end subroutine hypoc end program demo_makepoly
References p_inpolygon, p_polyvertex, and true().
mapcolor()
subroutine, public m_pixel::mapcolor (integer, intent(in) indx, integer, intent(in) red, integer, intent(in) green, integer, intent(in) blue)
NAME
mapcolor(3f) - [M_pixel] set a color index using RGB values
SYNOPSIS
definition:
subroutine mapcolor(indx, red, green, blue) integer indx, red, green, blue
DESCRIPTION
Set the color map index indx to the color represented by (red, green, blue). rgb values are in the range of 0 to 255.
OPTIONS
INDX color index number, in range 0 to 255 RED red component of color being defined, in range 0 to 255 GREEN green component of color being defined, in range 0 to 255 BLUE blue component of color being defined, in range 0 to 255
EXAMPLE
Color wheel example:
! good program to exercise color tables, and look at differences ! when actual output device has a color table that is dynamic, ! or only has a small color table (a frame in this program takes ! at least SLICES*RINGS colors to produce accurately). ! program demo_mapcolor use M_pixel use m_color, only: hue use M_writegif, only : writegif use M_units, only : cosd, sind implicit none character(len=4096) :: filename real :: lightstep integer :: ii,iframe integer,parameter :: SLICES=30 integer,parameter :: RINGS= 8 real :: LIGHTNESS integer,parameter :: BOX=1200 call prefsize(BOX,BOX) call vinit(' ') call color(0) call clear() call color(7) call biggest_ortho2(-110./2.,85./2.,-110./2.,110./2.) LIGHTNESS=100.0 lightstep=-5 do ii=1,19 iframe=ii call color(0) call clear() call color(7) call wheel() write(filename,'("mapcolor.3_",i3.3,".gif")')int(LIGHTNESS) call writegif(filename,P_pixel,P_colormap) LIGHTNESS=LIGHTNESS+LIGHTSTEP enddo call vexit() contains !=======================================================================-----— subroutine wheel() ! draw an entire wheel character(len=40) :: inline real :: hue_val integer :: ii call textang(0.0) call color(7) call textsize(5.0,6.0) call font('times.r') call move2(0.0,103.0/2.0) call centertext(.true.) call linewidth(30) call drawstr('COLOR WHEEL') call linewidth(0) call textsize(2.5,2.5) call font('futura.l') call move2(0.0,90.0/2.0) write(inline,'("lightness=",f6.2)')LIGHTNESS call linewidth(30) call drawstr(inline) call linewidth(0) call textsize(1.5,1.5) hue_val=0 do ii=SLICES, 1,-1 call slice(hue_val) enddo call centertext(.false.) end subroutine wheel !=======================================================================-----— subroutine slice(hue_val) ! draw a slice integer :: buffer real :: hue_val, ang_inc character(len=40) :: inline real :: step real :: X1, X2, X3, X4 real :: Y1, Y2, Y3, Y4 ! integer :: maxcolors, current_color integer :: ir, ig, ib real :: r,g,b real :: saturation ! integer :: status integer :: icount real :: angle1, angle2 real :: radius1, radius2, radius3, radius4 ! integer,save :: color_count=0 ! buffer=8 ANG_INC=360.0/SLICES angle1=hue_val-ANG_INC/2 angle2=angle1+ANG_INC saturation=100 radius1=32 radius3=radius1+4 radius4=radius1+7 ! draw tic from wheel to start of angle label call color(7) call linewidth(40) call move2(radius1*cosd(hue_val), radius1*sind(hue_val)) call draw2(radius3*cosd(hue_val), radius3*sind(hue_val)) ! draw degree label at tic call textang(hue_val) call move2(radius4*cosd(hue_val), radius4*sind(hue_val)) write(inline,'(i0)')nint(hue_val) call linewidth(20) call drawstr(inline) call linewidth(0) step=radius1/(RINGS) radius2=radius1-step ! draw a chunk in a slice MAXCOLORS=(256)-buffer do icount=RINGS+1,2,-1 CURRENT_COLOR=MOD(color_count,MAXCOLORS)+buffer ! add buffer to leave base colors alone color_count=color_count+1 ! fancy mapcolor call hue("hls",hue_val,LIGHTNESS,saturation,"rgb",r,g,b,status) ir=int(r*255.0/100.0+0.50) ig=int(g*255.0/100.0+0.50) ib=int(b*255.0/100.0+0.50) call mapcolor(CURRENT_COLOR,ir,ig,ib) call color(CURRENT_COLOR) ! X1=cosd(angle1)*radius2 Y1=sind(angle1)*radius2 X2=cosd(angle1)*radius1 Y2=sind(angle1)*radius1 ! X3=cosd(angle2)*radius2 Y3=sind(angle2)*radius2 X4=cosd(angle2)*radius1 Y4=sind(angle2)*radius1 ! call makepoly() call move2(X1,Y1) call draw2(X2,Y2) call draw2(X4,Y4) call draw2(X3,Y3) call closepoly() ! saturation=saturation-100.0/RINGS radius1=radius2 radius2=radius1-step enddo hue_val=hue_val+ANG_INC end subroutine slice end program demo_mapcolor
References p_colormap.
mapping()
subroutine m_pixel::mapping () private
NAME
SYNOPSIS
definition:
DESCRIPTION
EXAMPLE
References p_a, p_b, p_c, p_d, p_viewport_bottom, p_viewport_left, p_viewport_right, p_viewport_top, p_window_bottom, p_window_left, p_window_right, and p_window_top.
move2()
subroutine, public m_pixel::move2 (real, intent(in) x, real, intent(in) y)
NAME
move2(3f) - [M_pixel] change current position
SYNOPSIS
definition:
subroutine move2(x, y) real x, y
DESCRIPTION
Update current position.
OPTIONS
X new X position Y new Y position
EXAMPLE
Sample program:
program demo_move2 use M_pixel, only : prefsize, vinit, ortho2, clear use M_pixel, only : move2, draw2, vexit use M_pixel, only : P_pixel,P_colormap use M_writegif, only : writegif call prefsize(60,40) call vinit() call ortho2(-300.0,300.0,-200.0,200.0) call clear(0) call move2(-300.0,-200.0) call draw2(300.0,200.0) call move2(300.0,-200.0) call draw2(-300.0,200.0) call writegif('move2.3.gif',P_pixel,P_colormap) call vexit() end program demo_move2
References p_x, and p_y.
ortho2()
subroutine, public m_pixel::ortho2 (real, intent(in) left, real, intent(in) right, real, intent(in) bottom, real, intent(in) top)
NAME
ortho2(3f) - [M_pixel] define the area of the virtual world coordinates to map to the viewport
SYNOPSIS
definition:
subroutine ortho2(left, right, bottom, top) real,intent(in) :: left, right, bottom, top
DESCRIPTION
Defines the section of the virtual world coordinates to map to the viewport. All the projection routines define a new transformation matrix, and consequently the world units. Parallel projections are defined by ortho2.
EXAMPLE
References mapping(), p_window_bottom, p_window_left, p_window_right, and p_window_top.
point2()
subroutine, public m_pixel::point2 (real, intent(in) x, real, intent(in) y)
NAME
point2(3f) - [M_pixel] Draw a point at x, y
SYNOPSIS
definition:
subroutine point2(x, y) real,intent(in) :: x, y
DESCRIPTION
Draw a point at x, y. Points are drawn with the current color as a circle with a diameter equal to the current linewidth.
EXAMPLE
Sample program:
program demo_point2 use :: M_pixel use :: M_writegif, only : writegif implicit none integer :: i call vinit() call color(5) do i=1,20 call linewidth(50*i) call point2(real(i*25),real(i*25)) enddo call writegif('point2.3.gif',P_pixel,P_colormap) call vexit() end program demo_point2
References line().
poly2()
subroutine, public m_pixel::poly2 (integer, intent(in) n, real, dimension(2, n), intent(in) points)
NAME
poly2(3f) - [M_pixel] construct a polygon from an array of points
SYNOPSIS
definition:
subroutine poly2(n, points) integer,intent(in) :: n real,intent(in) :: points(2, n)
DESCRIPTION
Construct a polygon from an array of points
EXAMPLE
Sample program:
program demo_poly2 use M_pixel use M_writegif, only : writegif integer :: i,j real :: xx,yy call prefsize(512,512) call vinit() call ortho2(0.0,256.0,0.0,256.0) call linewidth(1) ! step thru a series of rectangular cells icolor=0 xx=0.0 do i=1,16 yy=0.0 do j=1,16 yy=yy+16.0 icolor=icolor+1 call setcolor(icolor,xx,yy) enddo xx=xx+16.0 enddo call writegif('poly2.3.gif',P_pixel,P_colormap) call vexit() contains
subroutine setcolor(iset,xx,yy) use M_strings, only : v2s use M_color, only : color_name2rgb integer,intent(in) :: iset real,intent(in) :: xx,yy character(len=80) :: echoname real :: points(2,100) if(iset.gt.255)return ! determine coordinates of next square points(1:2,1)=[xx, yy ] points(1:2,2)=[xx, yy+16.0 ] points(1:2,3)=[xx+16.0, yy+16.0 ] points(1:2,4)=[xx+16.0, yy ] points(1:2,5)=[xx, yy ] ! get some nice RGB values to try from named colors known by M_color module call color_name2rgb(v2s(icolor),red,green,blue,echoname) if(echoname.eq.'Unknown') return ! set a color number to the new RGB values write(*,*)icolor, nint(red*2.55), nint(green*2.55), nint(blue*2.55),trim(echoname) call mapcolor(icolor, nint(red*2.55), nint(green*2.55), nint(blue*2.55)) ! set to the new color call color(icolor) ! fill the rectangle in that color call poly2(5,points) end subroutine setcolor
end program demo_poly2
References ppm_solid_fill(), and world2viewport().
polyline()
subroutine, public m_pixel::polyline (real, dimension(:), intent(in) x, real, dimension(:), intent(in) y)
NAME
polyline(3f) - [M_pixel] connect points with lines
SYNOPSIS
definition:
subroutine polyline(x,y) real,intent(in) :: x(:) real,intent(in) :: y(:)
DESCRIPTION
Draw a line through a series of points described by the arrays X and Y.
OPTIONS
X array of x-coordinates Y array of y-coordinates
EXAMPLE
References line().
ppm_draw_fill_line()
subroutine m_pixel::ppm_draw_fill_line (integer, intent(in) xstart, integer, intent(in) ystart, integer, intent(in) x, integer, intent(in) y) private
References p_color_index, and p_pixel.
ppm_draw_thick_line()
subroutine m_pixel::ppm_draw_thick_line (integer, intent(in) inx1, integer, intent(in) iny1, integer, intent(in) inx2, integer, intent(in) iny2) private
References p_width, ppm_endcap_circle(), and ppm_solid_fill().
ppm_endcap_circle()
subroutine m_pixel::ppm_endcap_circle (integer, intent(in) x, integer, intent(in) y)
References p_width, and ppm_solid_fill().
ppm_solid_fill()
subroutine m_pixel::ppm_solid_fill (integer, dimension(0:n-1), intent(in) x, integer, dimension(0:n-1), intent(in) y, integer, intent(in) n) private
References p_debug, p_viewport_height, p_viewport_width, ppm_draw_fill_line(), and ppm_yintercept().
ppm_yintercept()
logical function m_pixel::ppm_yintercept (integer yscan, integer x1, integer y1, integer x2, integer y2, integer xintercept, integer yprev) private
References false(), and true().
prefsize()
subroutine, public m_pixel::prefsize (integer, intent(in) x, integer, intent(in) y)
NAME
prefsize(3f) - [M_pixel] specify size of pixel array
SYNOPSIS
definition:
subroutine prefsize(width, height) integer width, height
DESCRIPTION
Specify the preferred width and height of the pixel array opened by the next vinit(3f). The pixel array is then available via the M_pixel(3fm) module as variable P_pixel. Note that the width corresponds to the number of rows in the array, and height to the number of columns.
OPTIONS
WIDTH width of pixel array to create when vinit(3f) is called HEIGHT height of pixel array to create when vinit(3f) is called
EXAMPLE
Sample program:
program demo_prefsize use M_pixel, only: prefsize, vinit, ortho2, clear use M_pixel, only: move2, draw2, vexit, color use M_pixel, only : P_pixel,P_colormap use M_writegif, only : writegif ! make first file with one size call prefsize(60*2,40*2) call vinit() call picture() call writegif('prefsize.3.gif',P_pixel,P_colormap) call vexit()
! make second file with another size call prefsize(60*3,40*3) call vinit() call picture() call writegif('prefsize_B.3.gif',P_pixel,P_colormap) call vexit() contains subroutine picture call ortho2(-300.0,300.0,-200.0,200.0) call clear(0) call color(1) call move2(-300.0,-200.0) call draw2(300.0,200.0) call move2(300.0,-200.0) call draw2(-300.0,200.0) end subroutine picture end program demo_prefsize
References p_viewport_height, and p_viewport_width.
print_ascii()
subroutine, public m_pixel::print_ascii (character(len=*), intent(in), optional filename)
NAME
print_ascii(3f) - [M_pixel] print small pixel array as ASCII text
SYNOPSIS
definition:
subroutine print_ascii(filename) character(len=*),intent(in) :: filename
DESCRIPTION
This driver prints the pixmap as a simple ASCII array. It assumes only single-digit colors are used. It is appropriate for inspecting small pixmaps.
OPTIONS
FILENAME name of output file. If blank write to stdout.
EXAMPLE
Sample Program:
program demo_print_ascii use M_pixel call prefsize(80,24) call vinit() call ortho2(0.0,80.0,0.0,24.0) call linewidth(400) call color(1) call circle(12.0,12.0,6.0) call color(2) call circle(72.0,12.0,6.0) call print_ascii() call vexit() end program demo_print_ascii
Results:
00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000111000000000000000000000000000000000000000000000000000000000000000000 00000000111111110000000000000000000000000000000000000000000000000000022222000000 00000001111111111000000000000000000000000000000000000000000000000002222222220000 00000001111001111100000000000000000000000000000000000000000000000022222222222000 00000011100000011110000000000000000000000000000000000000000000000222200000222200 00000111100000001111000000000000000000000000000000000000000000000222000000022200 00000111000000000111000000000000000000000000000000000000000000002220000000002220 00000111000000000111000000000000000000000000000000000000000000002220000000002220 00000111000000000111000000000000000000000000000000000000000000002220000000002220 00000111000000000111000000000000000000000000000000000000000000002220000000002220 00000111100000001110000000000000000000000000000000000000000000002222000000022220 00000011110000011110000000000000000000000000000000000000000000000222000000022200 00000001111111111100000000000000000000000000000000000000000000000020220002202000 00000000111111111000000000000000000000000000000000000000000000000002222222220000 00000000011111100000000000000000000000000000000000000000000000000000222222200000 00000000000000000000000000000000000000000000000000000000000000000000002220000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000
References file(), if_init(), only, p_pixel, unit(), and use.
print_ppm()
subroutine, public m_pixel::print_ppm (character(len=*), intent(in) filename)
NAME
print_ppm(3f) - [M_pixel] print pixel array as a ppm p3 file
SYNOPSIS
definition:
subroutine print_ppm(filename) character(len=*),intent(in) :: filename
DESCRIPTION
This driver makes an ASCII P3 portable pixmap file
OPTIONS
FILENAME name of output file to create or replace
EXAMPLE
Sample program:
program demo_print_ppm use M_pixel, only : prefsize,vinit,ortho2,vexit use M_pixel, only : linewidth,circle,color use M_pixel, only : print_ppm call prefsize(40,40) call vinit() call ortho2(-100.0,100.0,-100.0,100.0) call linewidth(400) call circle(0.0,0.0,45.0) call color(3) call circle(0.0,0.0,25.0) call print_ppm('demo_print_ppm.ppm') call vexit() end program demo_print_ppm
References file(), if_init(), j, p_colormap, p_pixel, and unit().
rdraw2()
subroutine, public m_pixel::rdraw2 (real, intent(in) xdelta, real, intent(in) ydelta)
NAME
rdraw2(3f) - [M_pixel] draw from current position to given point
SYNOPSIS
definition:
subroutine rdraw2(x, y) real,intent(in) :: x, y
DESCRIPTION
Relative draw from current position to specified point using current color and line width. Updates current position to new point. (x, y) is a point in world coordinates.
OPTIONS
X new X position Y new Y position
EXAMPLE
Sample program:
program demo_rdraw2 use M_pixel, only: vinit, prefsize, ortho2,linewidth use M_pixel, only: clear, move2, rdraw2, vexit,color use M_pixel, only: P_pixel, P_colormap use M_writegif, only : writegif
call prefsize(200,200) call vinit() call ortho2(-55.0, 55.0, -55.0, 55.0) call linewidth(400) call color(7) call clear()
call color(1) call move2(-50.0,0.0) call square(50.0)
call linewidth(200) call color(2) call move2(0.0,-50.0) call square(50.0)
call writegif('rdraw2.3.gif',P_pixel,P_colormap) call execute_command_line('display rdraw2.3.gif') call vexit()
contains
subroutine square(side) call rdraw2(side, 0.0) call rdraw2(0.0, side) call rdraw2(-side, 0.0) call rdraw2(0.0, -side) end subroutine square
end program demo_rdraw2
References line(), p_x, and p_y.
rect()
subroutine, public m_pixel::rect (real, intent(in) x1, real, intent(in) y1, real, intent(in) x2, real, intent(in) y2)
NAME
rect(3f) - [M_pixel] draw rectangle given two corners
SYNOPSIS
definition:
subroutine rect(x1,y1, x2,y2) real,intent(in) :: x1,y1,x2,y2
DESCRIPTION
Draw rectangle given two opposite corners.
OPTIONS
X1,Y1 coordinates of a corner of the rectangle X2,Y2 coordinates of corner point opposite first point
EXAMPLE
Sample program:
program demo_rect use M_pixel use M_writegif, only : writegif
!! set up graphics area call prefsize(400,400) call vinit() call ortho2(left=-100.0, right=100.0, bottom=-100.0, top=100.0)
!! draw some filled rectangles do i=95,5,-10 call makepoly() call color(i/10) call rect(-1.0*i, -1.0*i, 1.0*i, 1.0*i) call closepoly() enddo
!! draw some rectangles call linewidth(50) call color(7) do i=5,95,5 call rect(-1.0*i, -1.0*i, 1.0*i, 1.0*i) enddo
!! render pixel array to a file call writegif('rect.3.gif',P_pixel,P_colormap)
!! display graphic assuming display(1) is available call execute_command_line('display rect.3.gif')
!! wrap up graphics call vexit()
end program demo_rect
References draw2(), and move2().
rmove2()
subroutine, public m_pixel::rmove2 (real, intent(in) Xdelta, real, intent(in) Ydelta)
NAME
rmove2(3f) - [M_pixel] relative move
SYNOPSIS
definition:
subroutine rmove2(deltax, deltay) real,intent(in) :: deltax, deltay
DESCRIPTION
Update current position. Relative move2. deltax and deltay are offsets in world units.
OPTIONS
X new X position Y new Y position
EXAMPLE
Sample program:
program demo_rmove2 use M_pixel, only: prefsize, vinit, ortho2, clear use M_pixel, only: move2, rmove2, rdraw2, vexit use M_pixel, only: linewidth use M_pixel, only: P_pixel, P_colormap use M_writegif, only : writegif call prefsize(500,500) call vinit() call ortho2(-110.0,110.0,-110.0,110.0) call move2(-100.0,-100.0) call linewidth(70) do i=1,20 call rmove2(10.0, 0.0) call rdraw2(0.0,10.0) enddo call writegif('rmove2.3.gif',P_pixel,P_colormap) call execute_command_line('display rmove2.3.gif') call vexit() end program demo_rmove2
References p_x, and p_y.
state()
recursive subroutine, public m_pixel::state (character(len=*), intent(in), optional string)
NAME
state(3f) - [M_pixel] print graphics state of M_pixel graphics module
SYNOPSIS
definition:
recursive subroutine state(string) character(len=*),intent(in),optional :: string
DESCRIPTION
Print the state of the M_pixel graphics module. This is primarily used in debugging during program development and is not currently in the VOGLE library.
OPTIONS
STRING can have the following values o all o default o colormap
EXAMPLE
Sample program:
program demo_state use M_pixel call prefsize(640,400) call vinit() call state() call vexit() end program demo_state Results:
VINIT CALLED: T PREFSIZE: WIDTH= 640 HEIGHT= 400 CURRENT POSITION: X= 0.00000000 Y= 0.00000000 LINE WIDTH: 1 FONT: SIMPLEX COLOR NUMBER: 1 CIRCLE PRECISION: 60 TEXT: HEIGHT= 10.0000000 WIDTH= 7.00000000 ANGLE= 0.00000000 TEXT JUSTIFICATION: X_CENTER= F Y_CENTER= F VIEWPORT: LEFT= 0.00000000 RIGHT= 639.000000 BOTTOM= 399.000000 TOP= 0.00000000 WINDOW: LEFT= 0.00000000 RIGHT= 640.000000 BOTTOM= 0.00000000 TOP= 400.000000
References p_color_index, p_colormap, p_font, p_nsegs, p_text_angle, p_text_height, p_text_width, p_viewport_bottom, p_viewport_height, p_viewport_left, p_viewport_right, p_viewport_top, p_viewport_width, p_vinit_called, p_width, p_window_bottom, p_window_left, p_window_right, p_window_top, p_x, p_x_centertext, p_y, p_y_centertext, and state().
strlength()
real function, public m_pixel::strlength (character(len=*), intent(in) string)
NAME
strlength(3f) - [M_pixel] return length of string
SYNOPSIS
definition:
function strlength(string) character(len=*),intent(in) :: string
DESCRIPTION
RETURNS
STRLENGTH length of string using current font size
EXAMPLE
Sample Program:
program demo_strlength use :: M_pixel use :: M_writegif, only : writegif real :: left real :: baseline integer :: icolor=0 real :: texth=10.0 !! set up drawing surface call prefsize(800, 400) call vinit() call viewport(0.0, 800.0, 400.0, 0.0) call ortho2(-100.0, 300.0, -100.0, 100.0) call color(7) call clear() call linewidth(30) call textsize(texth, texth) call xcentertext() call color(1)
baseline=85.0 call move2(0.0,baseline) call drawstr('If I Can Stop One Heart') baseline= baseline-texth*1.20 call move2(0.0,baseline) call drawstr('by Emily Dickinson') call centertext(.false.)
texth=8.5 baseline=baseline-texth*1.50 call textsize(texth, texth) left=-90.0
call nextline('If I can stop one heart from breaking,') call nextline('I shall not live in vain;') call nextline('If I can ease one life the aching,') call nextline('Or cool one pain,') call nextline('Or help one fainting robin') call nextline('Unto his nest again,') call nextline('I shall not live in vain.')
call writegif('strlength.3.gif',P_pixel,P_colormap) call execute_command_line('display strlength.3.gif') call vexit() contains subroutine nextline(string) character(len=*) :: string real :: xx !! reduce some duplicate code; very specific to this example call color(icolor) baseline=baseline-texth*1.5 ! move down before drawing line call makepoly() xx=strlength(string) call rect(left,baseline-texth*0.3,left+xx,baseline+texth) call closepoly() call color(7) call move2(left, baseline) call drawstr(string) ! draw string icolor=icolor+1 ! set pen color end subroutine nextline
end program demo_strlength
References justfy(), and p_text_height.
swapcoord()
subroutine m_pixel::swapcoord (integer, intent(inout) p1, integer, intent(inout) p2) private
textang()
subroutine, public m_pixel::textang (real, intent(in) ang)
NAME
textang(3f) - [M_pixel] set text angle
SYNOPSIS
definition:
subroutine textang(ang) real,intent(in) :: ang
DESCRIPTION
Set the text angle. This angles strings and chars. This routine only affects software text.
OPTIONS
ANG The angle in degrees to draw text with when using drawstr(3f). Angles are measured counterclockwise with zero degrees at the horizontal line to the right of the original.
EXAMPLE
Sample program:
program demo_textang use :: M_pixel use :: M_units, only : cosd, sind use :: M_writegif, only : writegif !! set up drawing environment call prefsize(600,600) call vinit() call ortho2(-100.0,100.0,-100.0,100.0) call textsize(7.0,7.0) call linewidth(20) do i=1,30 !! draw radial lines call color(1) call move2(0.0,0.0) call draw2(100.0*cosd(i*12),100.0*sind(i*12)) !! draw rotated text call color(7) call move2(30.0*cosd(i*12),30.0*sind(i*12)) call textang(i*12.0) call drawstr('angled text') enddo
call writegif('textang.3.gif',P_pixel,P_colormap) call execute_command_line('display textang.3.gif')
call vexit()
end program demo_textang
References p_text_angle, p_text_cosine, and p_text_sine.
textsize()
subroutine, public m_pixel::textsize (real, intent(in) width, real, intent(in) height)
NAME
ppm - portable pixmap file format
DESCRIPTION
The portable pixmap format is a lowest common denominator color image file format. The definition is as follows:
A "magic number" for identifying the file type. A ppm file's magic number is the two characters "P3".
Whitespace (blanks, TABs, CRs, LFs).
A width, formatted as ASCII characters in decimal.
Whitespace.
A height, again in ASCII decimal.
Whitespace.
The maximum color-component value, again in ASCII decimal.
Whitespace.
Width * height pixels, each three ASCII decimal values between 0 and the specified maximum value, starting at the top-left corner of the pixmap, proceeding in normal English reading order. The three values for each pixel represent red, green, and blue, respectively; a value of 0 means that color is off, and the maximum value means that color is maxxed out.
Characters from a "#" to the next end-of-line are ignored (comments).
No line should be longer than 70 characters.
Here is an example of a small pixmap in this format: P3
feep.ppm
4 4 15 0 0 0 0 0 0 0 0 0 15 0 15 0 0 0 0 15 7 0 0 0 0 0 0 0 0 0 0 0 0 0 15 7 0 0 0 15 0 15 0 0 0 0 0 0 0 0 0
Programs that read this format should be as lenient as possible, accepting anything that looks remotely like a pixmap.
There is also a variant on the format, available by setting the RAWBITS option at compile time. This variant is different in the following ways:
The "magic number" is "P6" instead of "P3".
The pixel values are stored as plain bytes, instead of ASCII decimal.
Whitespace is not allowed in the pixels area, and only a single character of whitespace (typically a newline) is allowed after the maxval.
The files are smaller and many times faster to read and write.
Note that this raw format can only be used for maxvals less than or equal to 255. If you use the ppm library and try to write a file with a larger maxval, it will automatically fall back on the slower but more general plain format.
AUTHOR
Copyright (C) 1989, 1991 by Jef Poskanzer.
        Last change: 27 September 1991
NAME
textsize(3f) - [M_pixel] set text size in world units
SYNOPSIS
definition:
subroutine textsize(width, height) real,intent(in) :: width real,intent(in) :: height
DESCRIPTION
Set the maximum size of a character in the current font. Width and height
are values in world units. This only applies to software text. This must
be done after the font being scaled is loaded. To keep text of different
sizes aligned along the same baseline note that you typically need to
subtrace the decender height from the Y position.
EXAMPLE
Sample program:
program demo_textsize use M_pixel use M_writegif, only : writegif implicit none integer :: i,ii !! set up long bar as plotting area call prefsize(900,150) call vinit() call ortho2(-30.0, 30.0, -5.0, 5.0) call font('DUPLEX') call move2(-23.0,-4.5) call color(7) call textsize(2.0,2.0) call move2(-27.5,-3.0) call draw2(27.5,-3.0) call move2(-27.5,-3.0) do i=1,7 ii=nint((i*20)*0.30) call linewidth(nint(ii*2.35)) call textsize(real(i),real(i)) call color(5) call drawstr('aA') enddo ! write plot as GIF file call writegif('textsize.3.gif',P_pixel,P_colormap) call vexit() ! use system to display GIF file call execute_command_line('display textsize.3.gif') end program demo_textsize
References p_text_height, and p_text_width.
vexit()
subroutine, public m_pixel::vexit ()
NAME
vexit(3f) - [M_pixel] exit pixel graphics mode
SYNOPSIS
definition:
subroutine vexit()
DESCRIPTION
Used to terminate pixel graphics mode. Does any actions required to terminate graphics mode including unallocating the module pixel array P_pixel. Required before calling vinit(3f) more than once.
Resets the window/terminal (must be the last M_PIXEL routine called).
OPTIONS
EXAMPLE
Sample program:
program demo_vexit use M_pixel, only: prefsize, vexit, ortho2, clear use M_pixel, only: move2, draw2, color, vinit use M_pixel, only : P_pixel,P_colormap use M_writegif, only : writegif call prefsize(60,40) call vinit() call ortho2(-300.0,300.0,-200.0,200.0) call clear(0) call color(1) call move2(-300.0,-200.0) call draw2(300.0,200.0) call move2(300.0,-200.0) call draw2(-300.0,200.0) call writegif('vexit.3.gif',P_pixel,P_colormap) call vexit() end program demo_vexit
References false(), p_pixel, and p_vinit_called.
vflush()
subroutine, public m_pixel::vflush ()
viewport()
subroutine, public m_pixel::viewport (real, intent(in) left, real, intent(in) right, real, intent(in) bottom, real, intent(in) top)
NAME
viewport(3f) - [M_pixel] Specify which part of the screen to draw in.
SYNOPSIS
definition:
subroutine viewport(left, right, bottom, top) real,intent(in) :: left, right, bottom, top
DESCRIPTION
Specify which part of the screen to draw in. Left, right, bottom, and top are real values in screen coordinates (0:n,0:m).
If a pixel array has been declared to be real :: array(600,400)
 o-----> X                         (right=600,top=0)
 | #------------------------------------#
 | |                                    |
 | |                                    |
 V |                                    |
 Y |                                    |
   #------------------------------------#
(left=0,bottom=400)
References mapping(), p_viewport_bottom, p_viewport_left, p_viewport_right, and p_viewport_top.
viewport2world()
subroutine m_pixel::viewport2world (real, intent(in) xv, real, intent(in) yv, real, intent(out) xw, real, intent(out) yw) private
References p_a, p_b, p_c, and p_d.
vinit()
subroutine, public m_pixel::vinit (character(len=*), optional string)
NAME
vinit(3f) - [M_pixel] initialize pixel graphics module
SYNOPSIS
definition:
subroutine vinit()
DESCRIPTION
Initialize the pixel graphics module. The pixel array P_pixel and the colormap P_ColorMap are directly accessible after the call to allow display or printing
OPTIONS
EXAMPLE
Sample program:
program demo_vinit use M_pixel, only : prefsize, vinit, ortho2, clear use M_pixel, only : move2, draw2, vexit, color use M_pixel, only : P_pixel, P_colormap use M_writegif, only : writegif call prefsize(60,40) call vinit() call ortho2(-300.0,300.0,-200.0,200.0) call clear(0) call color(1) call move2(-300.0,-200.0) call draw2(300.0,200.0) call move2(300.0,-200.0) call draw2(-300.0,200.0) call writegif('vinit.3.gif',P_pixel,P_colormap) call vexit() end program demo_vinit
References false(), mapping(), p_color_index, p_font, p_inpolygon, p_nsegs, p_pixel, p_polyvertex, p_text_angle, p_text_cosine, p_text_height, p_text_sine, p_text_width, p_viewport_bottom, p_viewport_height, p_viewport_left, p_viewport_right, p_viewport_top, p_viewport_width, p_vinit_called, p_width, p_window_bottom, p_window_left, p_window_right, p_window_top, p_x, p_x_centertext, p_y, p_y_centertext, and true().
world2viewport()
subroutine m_pixel::world2viewport (real, intent(in) xw, real, intent(in) yw, real, intent(out) xv, real, intent(out) yv)
References p_a, p_b, p_c, and p_d.
xcentertext()
subroutine, public m_pixel::xcentertext ()
NAME
xcentertext(3f) - [M_pixel] set text centering mode on for drawstr(3f) and drawc(3f) in X direction
SYNOPSIS
definition:
subroutine xcentertext()
DESCRIPTION
Set text centering mode on in X direction. Y justification is turned off.
Centers text in the X direction. The text string will begin at a point to the notional left of the current position and finish at a point to the right of the current position. Left justification and Right justification are turned off.
EXAMPLE
References false(), p_x_centertext, p_y_centertext, and true().
ycentertext()
subroutine, public m_pixel::ycentertext ()
NAME
ycentertext(3f) - [M_pixel] set text centering mode on for drawstr(3f) and drawc(3f) in Y direction
SYNOPSIS
definition:
subroutine ycentertext()
DESCRIPTION
Centers text in the Y direction. The text string will be draw so that it's center line is aligned with the current y position. Top justification and Bottom justification are turned off.
EXAMPLE
References false(), p_x_centertext, p_y_centertext, and true().
Variable Documentation
d2r
real, parameter m_pixel::d2r =acos(-1.0)/180.0 private
isstar
integer, dimension(22), save m_pixel::isstar private
istart
integer, dimension(432), save m_pixel::istart private
j
integer m_pixel::j private
p_a
real, save m_pixel::p_a private
p_b
real, save m_pixel::p_b private
p_c
real, save m_pixel::p_c private
p_color_index
integer, save m_pixel::p_color_index =1 private
p_colormap
integer, dimension(3,0:255), save, public m_pixel::p_colormap
p_d
real, save m_pixel::p_d private
p_debug
logical, save, public m_pixel::p_debug =.false.
p_font
character(len=20) m_pixel::p_font ='SIMPLEX' private
p_ichr
integer, dimension(350) m_pixel::p_ichr private
p_inpolygon
logical, save m_pixel::p_inpolygon =.false. private
p_ioff
integer m_pixel::p_ioff =0 private
p_just1
integer m_pixel::p_just1 private
p_just2
integer m_pixel::p_just2 private
p_maxverts
integer, parameter m_pixel::p_maxverts =9999 private
p_nchr
integer m_pixel::p_nchr private
p_nsegs
integer, save m_pixel::p_nsegs =60 private
p_pixel
integer, dimension(:,:), allocatable, save, public m_pixel::p_pixel
p_polypoints
real, dimension(2,p_maxverts), save m_pixel::p_polypoints private
p_polyvertex
integer, save m_pixel::p_polyvertex =1 private
p_text_angle
real, save m_pixel::p_text_angle =0.0 private
p_text_cosine
real, save m_pixel::p_text_cosine =1.0 private
p_text_height
real, save m_pixel::p_text_height =10.0 private
p_text_sine
real, save m_pixel::p_text_sine =0.0 private
p_text_width
real, save m_pixel::p_text_width =7.0 private
p_viewport_bottom
real, save m_pixel::p_viewport_bottom =0.0 private
p_viewport_height
integer, save m_pixel::p_viewport_height =400 private
p_viewport_left
real, save m_pixel::p_viewport_left =0.0 private
p_viewport_right
real, save m_pixel::p_viewport_right =0.0 private
p_viewport_top
real, save m_pixel::p_viewport_top =0.0 private
p_viewport_width
integer, save m_pixel::p_viewport_width =400 private
p_vinit_called
logical, save m_pixel::p_vinit_called =.false. private
p_width
integer, save m_pixel::p_width =1 private
p_window_bottom
real, save m_pixel::p_window_bottom =0.0 private
p_window_left
real, save m_pixel::p_window_left =0.0 private
p_window_right
real, save m_pixel::p_window_right =0.0 private
p_window_top
real, save m_pixel::p_window_top =0.0 private
p_x
real, save m_pixel::p_x =0.0 private
p_x_centertext
logical, save m_pixel::p_x_centertext =.false. private
p_y
real, save m_pixel::p_y =0.0 private
p_y_centertext
logical, save m_pixel::p_y_centertext =.false. private
pi
real, parameter m_pixel::pi =3.14159265358979323844 private
ssymbc
integer, dimension(128), save m_pixel::ssymbc private
symbcd
integer, dimension(4711), save m_pixel::symbcd private
width
real, dimension(432), save m_pixel::width private