GeneralPurposeFortran: m_calculator Module Reference
m_calculator Module Reference
NAME
jucalc - [M_calculator] parse calculator expression and return numeric or string value
SYNOPSIS
Data Types
interface stuff
NAME
stuff(3f) - [M_calculator] directly store value into calculator directory for efficiency
Functions/Subroutines
recursive subroutine, public jucalc (inline, outlin, mssg, slast, ierr)
subroutine help_funcs ()
NAME
SYNOPSIS
recursive subroutine, private jupars (string, nchar, ier)
NAME
SYNOPSIS
subroutine, private jufuns (wstrng, nchars, ier)
NAME
SYNOPSIS
subroutine, private stufftok (fval, wstrng, nchars, string, iend, ier)
NAME
SYNOPSIS
subroutine, private juargs (line, ilen, array, itype, iarray, ier, mx)
NAME
SYNOPSIS
subroutine, private jucals (string, nchar, value, ier)
NAME
SYNOPSIS
subroutine, private jupows (wstrng, nchar, ier)
NAME
SYNOPSIS
subroutine, private jufacs (wstrng, nchr, fval1, ier)
NAME
SYNOPSIS
subroutine, private juator (chars, rval8, ierr)
NAME
juator(3f) - [M_calculator] returns a double precision value from a numeric character string specifically for M_calculator(3fm)
SYNOPSIS
subroutine, private jurtoa (rval, chars, ilen, ierr)
NAME
SYNOPSIS
subroutine, private jusqes (string, imax, nchars, varnam, nchar2, ier)
NAME
jusqes - [M_calculator] change +-[] to #=(),replace strings with placeholders,delete comments
subroutine, private jubous (varnam0, index, ixn, ier)
NAME
SYNOPSIS
subroutine, private juaddr (newnam, nchars, index, ier)
NAME
juaddr(3fp) - add new variable to numeric value dictionary at specified location
subroutine, private juadds (newnam, nchars, index, ier)
NAME
SYNOPSIS
subroutine, private given_name_get_stringvalue (chars, ierr)
NAME
[M_calculator] given_name_get_stringvalue(3fp) - return associated value for variable name"
SYNOPSIS
doubleprecision function, public getvalue (varnam)
NAME
getvalue(3f) - [M_calculator] given numeric variable name return doubleprecision value directly from calculator dictionary for efficiency
SYNOPSIS
integer function, public igetvalue (varnam)
NAME
igetvalue(3f) - [M_calculator] given numeric variable name return integer value directly from calculator dictionary for efficiency
SYNOPSIS
real function, public rgetvalue (varnam)
NAME
rgetvalue(3f) - [M_calculator] given numeric variable name return real value directly from calculator dictionary for efficiency
SYNOPSIS
subroutine integer_stuff (varnam0, int4, ioflag)
NAME
SYNOPSIS
subroutine real_stuff (varnam0, val4, ioflag)
NAME
SYNOPSIS
subroutine double_stuff (varnam0, val8, ioflag)
NAME
SYNOPSIS
subroutine, public stuffa (varnam0, string, index, ioflag)
NAME
stuffa(3f) - [M_calculator] stuffa(3f): directly store a string into calculator variable name table
SYNOPSIS
Variables
integer, parameter dp =kind(0.0d0)
integer, parameter ic_calc =25000
integer, parameter, public iclen_calc =512
integer, parameter, public ixy_calc =55555
integer, parameter, public icname_calc =20
real(kind=dp), dimension(ixy_calc), save, public x =0.0_dp
real(kind=dp), dimension(ixy_calc), save, public y =0.0_dp
integer, dimension(ic_calc), save, public valuer =0
character(len=iclen_calc), dimension(ic_calc), save, public values =' '
integer, parameter ixyc_calc =50
integer, parameter icbuf_calc =20*(iclen_calc/2+1)
character(len=iclen_calc) mssge
character(len=iclen_calc), dimension(ixyc_calc), save xc =' '
character(len=iclen_calc), dimension(ixyc_calc), save yc =' '
character(len=iclen_calc), dimension(ixyc_calc), save nc =' '
character(len=icname_calc), dimension(ic_calc), save ix2 =' '
character(len=icname_calc), dimension(ic_calc), save ix =' '
real(kind=dp), dimension(ic_calc), save value =0.0_dp
character(len=iclen_calc), save last ='0.0'
logical, save ownon =.false.
integer, save ktoken
Detailed Description
NAME
jucalc - [M_calculator] parse calculator expression and return numeric or string value
SYNOPSIS
subroutine jucalc(inline,outlin,mssg,slast,ierr)
character(len=*),intent=(in) :: inline character(len=iclen_calc),intent=(out) :: outlin character(len=iclen_calc),intent=(out) :: mssg doubleprecision, intent=(out) :: slast integer, intent=(out) :: ierr
DESCRIPTION
JUCALC() evaluates FORTRAN-like expressions. It can be used to add calculator-like abilities to your program.
inline INLINE is a string expression up to (iclen_calc=512) characters long. The syntax of an expression is described in the main document of the Calculator Library. outlin Returned numeric value as a string when IERR=0. mssg MSSG is a string that can serve several purposes o Returned string value when IERR=2 o Error message string when IERR=-1 o Message from 'funcs' or 'dump' command when IERR=1 slast SLAST has different meanings depending on whether a string or number is being returned o REAL value set to last successfully calculated value when IERR=0 o Number of characters in returned string variable when IERR=2 ierr status flag. o -1 ==> An error occurred o 0 ==> A numeric value was returned o 1 ==> A message was returned o 2 ==> A string value was returned
DEPENDENCIES
o ceiling o floor o change o modif o rand o len_trim o User-supplied routines: juown1, c
EXAMPLES
Example calculator program
program compute
!@(#)compute(1f): line mode calculator program (that calls jucalc(3f))
!     requires:
!     c()
use m_calculator, only: jucalc,iclen_calc
! iclen_calc : max length of expression or variable value as a string
implicit none
integer,parameter         :: dp=kind(0.0d0)
character(len=iclen_calc) :: line
character(len=iclen_calc) :: outlin
character(len=iclen_calc) :: event
real(kind=dp)             :: rvalue
integer                   :: ierr
ierr=0
call jucalc('ownmode(1)',outlin,event,rvalue,ierr)
! activate user-defined function interface
INFINITE: do
   read(*,'(a)',end=999)line
   if(line.eq.'.')stop
   call jucalc(line,outlin,event,rvalue,ierr)
   select case (ierr)
   ! several different meanings to the error flag returned by calculator
   case(0)
   ! a numeric value was returned without error
     write(*,'(a,a,a)')trim(outlin),' = ',trim(line)
   case(2)
   ! a string value was returned without error
     write(*,'(a)')trim(event(:int(rvalue)))
   case(1)
   ! a request for a message has been returned (from DUMP or FUNC)
     write(*,'(a,a)')'message===>',trim(event(:len_trim(event)))
   case(-1)
   ! an error has occurred
     write(*,'(a,a)')'error===>',trim(event(:len_trim(event)))
   case default
   ! this should not occur
     WRITE(6,'(A,i10)')'*JUCALC* UNEXPECTED IERR VALUE ',IERR
   end select
enddo INFINITE
999 continue
end program compute
SEE ALSO
see INUM0(),RNUM0(),SNUM0(),STRGAR2(),JUCALCX().
REFERENCES
NONE. AUTHOR John S. Urbn
VERSION 1.0 19971123,20161218
Function/Subroutine Documentation
double_stuff()
subroutine m_calculator::double_stuff (character(len=*), intent(in) varnam0, real(kind=dp), intent(in) val8, character(len=*), intent(in), optional ioflag) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References ix, juaddr(), jubous(), and value.
getvalue()
doubleprecision function, public m_calculator::getvalue (character(len=*), intent(in) varnam)
NAME
getvalue(3f) - [M_calculator] given numeric variable name return doubleprecision value directly from calculator dictionary for efficiency
SYNOPSIS
doubleprecision function getvalue(varnam)
character(len=*),intent(in) :: varnam
DEFINITION
Given numeric variable name return double precision value. Note this is breaking the rule of only accessing the calculator thru jucalc(3f). It should only be used from user JUOWN1(3f) routines to avoid recursion
OPTIONS
varnam name of calculator variable to look up that is assumed to be a valid defined name of a numeric variable. If it does not exist zero is returned.
EXAMPLE
Program:
program demo_getvalue use M_calculator_plus, only : rnum0 use M_calculator, only: getvalue value1=rnum0('A=100/2') ! store something into calculator write(*,*)value1,getvalue('A') end program demo_getvalue
Results:
50.0000000 50.000000000000000
References ix, jubous(), and value.
given_name_get_stringvalue()
subroutine, private m_calculator::given_name_get_stringvalue (character(len=*), intent(in) chars, integer, intent(out) ierr) private
NAME
[M_calculator] given_name_get_stringvalue(3fp) - return associated value for variable name"
SYNOPSIS
subroutine given_name_get_stringvalue(chars,ierr)
character(len=*),intent(in) :: chars integer,intent(out) :: ierr
DESCRIPTION
return the actual string when given a string variable name or token the returned string is passed thru the message/string/error GLOBAL variable
OPTIONS
CHARS IER ierr is set and returned as
      -1  an error occurs
       2  a string is returned
RETURNS
MSSGE when successful the variable value is returned through the global variable MSSGE
EXAMPLE
References icname_calc, ix2, jubous(), mssge, and values.
help_funcs()
subroutine m_calculator::help_funcs () private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
igetvalue()
integer function, public m_calculator::igetvalue (character(len=*), intent(in) varnam)
NAME
igetvalue(3f) - [M_calculator] given numeric variable name return integer value directly from calculator dictionary for efficiency
SYNOPSIS
integer function igetvalue(varnam)
character(len=*),intent(in) :: varnam
DEFINITION
Given numeric variable name return integer value. Note this is breaking the rule of only accessing the calculator thru jucalc(3f). It should only be used from user JUOWN1(3f) routines to avoid recursion
OPTIONS
varnam name of calculator variable to look up that is assumed to be a valid defined name of a numeric variable. If it does not exist zero is returned without an error being reported.
EXAMPLE
Program:
program demo_igetvalue use M_calculator_plus, only : rnum0 use M_calculator, only: igetvalue value1=rnum0('A=100/2') ! store something into calculator write(*,*)value1,igetvalue('A') end program demo_igetvalue
Results:
50.0000000 50
References getvalue().
integer_stuff()
subroutine m_calculator::integer_stuff (character(len=*), intent(in) varnam0, integer, intent(in) int4, character(len=*), intent(in), optional ioflag) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References double_stuff().
juaddr()
subroutine, private m_calculator::juaddr (character(len=*), intent(in) newnam, integer, intent(in) nchars, integer, intent(in) index, integer ier) private
NAME
juaddr(3fp) - add new variable to numeric value dictionary at specified location
SYNOPSIS
subroutine juaddr(newnam,nchars,index,ier)
character(len=*),intent(in) :: newnam integer,intent(in) :: nchars integer,intent(in) :: index integer :: ier
DESCRIPTION
given a new variable name and place to put it, pull down the character and value arrays and initialize the new variable's value to zero. variable names only up to (icname_calc) characters maximum.
References ic_calc, ix, mssge, and value.
juadds()
subroutine, private m_calculator::juadds (character(len=*), intent(in) newnam, integer, intent(in) nchars, integer, intent(in) index, integer ier) private
NAME
SYNOPSIS
DESCRIPTION
given a new string variable name and place to put it, pull down the character and value arrays and initialize the new variable's value to a blank string. variable names only up to (icname_calc) characters maximum. stored strings up to only (iclen_calc) characters long.
OPTIONS
RETURNS
EXAMPLE
References ic_calc, ix2, mssge, valuer, and values.
juargs()
subroutine, private m_calculator::juargs (character(len=*), intent(in) line, integer, intent(in) ilen, doubleprecision, dimension(mx), intent(out) array, integer, dimension(mx), intent(out) itype, integer, intent(out) iarray, integer ier, integer, intent(in) mx) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References jucals(), and mssge.
juator()
subroutine, private m_calculator::juator (character(len=*), intent(in) chars, doubleprecision, intent(out) rval8, integer, intent(out) ierr) private
NAME
juator(3f) - [M_calculator] returns a double precision value from a numeric character string specifically for M_calculator(3fm)
SYNOPSIS
subroutine juator(chars,rval,ierr)
character(len=*),intent(in) :: chars doubleprecision,intent(out) :: rval integer,intent(out) :: ierr
DESCRIPTION
Convert a string representing a numeric scalar value to a numeric value, specifically for the M_calculator(3fp) module.Works with any g-format input, including integer, real, and exponential forms.
if chars=? set rval to value stored as current value, return.
if the string starts with a $ assume it is the name of a string variable or token and return its location as a doubleprecision number.
try to read string into a doubleprecision value. if successful, return.
if not interpretable as a doubleprecision value, see if it is a defined variable name and use that name's value if it is.
if no value can be associated to the string and/or if an unexpected error has occurred, set error flag and error message and set rval to zero and return.
note that blanks are treated as null, not zero.
OPTIONS
chars is the input string rval is the doubleprecision output value ierr 0 if no error occurs
EXAMPLE
VERSION
o 07/15/1986 J. S. Urban o 12/28/1987 modified to specify bn in formats for reads. vax defaults to zero-fill on internal files. o 12/22/2016 Changed to generate man(1) pages via ufpp(1).
References icname_calc, ix, ix2, jubous(), last, mssge, and value.
jubous()
subroutine, private m_calculator::jubous (character(len=*), intent(in) varnam0, integer index, character(len=icname_calc), dimension(ic_calc) ixn, integer, intent(out) ier) private
NAME
SYNOPSIS
subroutine jubous(varnam0,index,ixn,ier)
character(len=*),intent(in) :: varnam0 integer :: index character(len=icname_calc) :: ixn(ic_calc) integer,intent(out) :: ier
DESCRIPTION
assuming an alphabetized array of character strings, find the location (index) where that name can be found, unless it is not found – in which case report where it should be placed as a negative index number. it is assumed all variable names are lexically greater than a blank string.
finds the index assigned to a specific variable name. assumes that the user index array is sorted in descending order (highest at top). if varnam is not found; return line number it should be placed at ; with a negative sign.
OPTIONS
VARNAME0 variable name to find the location for IXN sorted array of character strings of standard dictionary size
RETURNS
INDEX location variable name found at (if positive) or location it should be placed at (if negative) IER zero if no error occurred
EXAMPLE
References ic_calc, and mssge.
jucalc()
recursive subroutine, public m_calculator::jucalc (character(len=*), intent(in) inline, character(len=iclen_calc), intent(out) outlin, character(len=iclen_calc), intent(out) mssg, doubleprecision, intent(out) slast, integer, intent(out) ierr)
References dp, help_funcs(), ic_calc, ix, ix2, juaddr(), juadds(), juator(), jubous(), jupars(), jusqes(), last, mssge, value, valuer, and values.
jucals()
subroutine, private m_calculator::jucals (character(len=*) string, nchar, value, ier) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References given_name_get_stringvalue(), jufacs(), jupows(), jurtoa(), mssge, string, and temp().
jufacs()
subroutine, private m_calculator::jufacs (character(len=*) wstrng, nchr, fval1, ier) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References juator(), and mssge.
jufuns()
subroutine, private m_calculator::jufuns (character(len=*) wstrng, nchars, ier) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References m_strings::change(), m_time::d2o(), m_time::date_to_julian(), m_time::date_to_unix(), m_strings::delim(), m_time::dow(), m_math::dp_accdig(), false(), file(), fmtdate, m_time::fmtdate_usage(), form, ic_calc, in, m_random::init_random_seed(), ix, ix2, ixy_calc, ixyc_calc, juargs(), juator(), jubous(), juown1(), jurtoa(), m_strings::matchw(), m_strings::modif(), mssge, nc, m_time::now(), ownon, m_io::print_inquire(), m_time::realtime, round(), stufftok(), true(), unit(), m_time::unix_to_date(), valuer, values, x, xc, y, and yc.
jupars()
recursive subroutine, private m_calculator::jupars (character(len=*) string, integer, intent(inout) nchar, integer, intent(out) ier) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References jucals(), jufuns(), mssge, and string.
jupows()
subroutine, private m_calculator::jupows (character(len=*) wstrng, nchar, ier) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References juator(), jurtoa(), and mssge.
jurtoa()
subroutine, private m_calculator::jurtoa (rval, character(len=*) chars, ilen, ierr) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References mssge.
jusqes()
subroutine, private m_calculator::jusqes (character(len=*) string, imax, nchars, character(len=icname_calc) varnam, nchar2, ier) private
NAME
jusqes - [M_calculator] change +-[] to #=(),replace strings with placeholders,delete comments
DESCRIPTION
remove all blanks from input string and return position of last non-blank character in nchars using imax as the highest column number to search in. return a zero in nchars if the string is blank.
replace all + and - characters with the # and = characters which will be used to designate + and - operators, as opposed to value signs.
replace [] with ()
remove all strings from input string and replace them with string tokens and store the values for the string tokens. assumes character strings are (iclen_calc) characters max. if string is delimited with double quotes, the double quote character may be represented inside the string by putting two double quotes beside each other ("he said ""greetings"", i think" ==> he said "greetings", i think)
!!!! if an equal sign is followed by a colon the remainder of the input line is placed into a string as-is !!!! without the need for delimiting it. ($string1=: he said "greetings", i think ==> he said "greetings", i think)
anything past an # is considered a comment and ignored
assumes length of input string is less than (icbuf_calc) characters
if encounters more than one equal sign, uses right-most as the end of variable name and replaces others with & and makes a variable name out of it (ie a=b=10 ===> a&b=10)
!!!!the length of string could actually be increased by converting quoted strings to tokens
!!!!maybe change this to allow it or flag multiple equal signs?
!!!!no check if varnam is a number or composed of characters !!!!like ()+-*/. . maybe only allow a-z with optional numeric !!!!suffix and underline character?
!!!!variable names ending in letter e can be confused with !!!!e-format numbers (is 2e+20 the variable 2e plus 20 or !!!!the single number 200000000000000000000?). to reduce !!!!amount of resources used to check for this, and since !!!!words ending in e are so common, will assume + and - !!!!following an e are part of an e-format number if the !!!!character before the e is a period or digit (.0123456789). !!!!and won't allow variable names of digit-e format).
!!!!make sure variable called e and numbers like e+3 or .e+3 are handled satisfactorily
References ix2, juadds(), jubous(), ktoken, mssge, valuer, and values.
real_stuff()
subroutine m_calculator::real_stuff (character(len=*), intent(in) varnam0, real, intent(in) val4, character(len=*), intent(in), optional ioflag) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References double_stuff().
rgetvalue()
real function, public m_calculator::rgetvalue (character(len=*), intent(in) varnam)
NAME
rgetvalue(3f) - [M_calculator] given numeric variable name return real value directly from calculator dictionary for efficiency
SYNOPSIS
real function rgetvalue(varnam)
character(len=*),intent(in) :: varnam
DEFINITION
Given numeric variable name return real value. Note this is breaking the rule of only accessing the calculator thru jucalc(3f). It should only be used from user JUOWN1(3f) routines to avoid recursion
OPTIONS
varnam name of calculator variable to look up that is assumed to be a valid defined name of a numeric variable. If it does not exist zero is returned without an error being reported.
EXAMPLE
Program:
program demo_rgetvalue use M_calculator_plus, only : rnum0 use M_calculator, only: rgetvalue value1=rnum0('A=100/2') ! store something into calculator write(*,*)value1,rgetvalue('A') end program demo_rgetvalue
Results:
50.0000000 50.0000000
stuffa()
subroutine, public m_calculator::stuffa (character(len=*), intent(in) varnam0, character(len=*), intent(in) string, integer, intent(out) index, character(len=*), intent(in) ioflag)
NAME
stuffa(3f) - [M_calculator] stuffa(3f): directly store a string into calculator variable name table
SYNOPSIS
subroutine stuffa(varnam0,string,index,ioflag)
character(len=*),intent(in) :: varnam0 character(len=*),intent(in) :: string integer :: index character(len=*),intent(in) :: ioflag
DEFINITION
Breaking the rule of only accessing the calculator thru jucalc:
a direct deposit of a value into the calculator assumed to be used only by friendly calls, for efficiency and to avoid problems with recursion if a routine called by the calculator in JUOWN1(3f) wants to store something back into the calculator variable table.
OPTIONS
varnam0 variable name to create or replace in calculator module string string to associate with the calculator variable name varnam0 index if less ioflag journal logging type passed on to journal(3f) procedure. If it is blank, the journal(3f) routine is not evoked.
EXAMPLE
References iclen_calc, ix2, juadds(), jubous(), valuer, and values.
stufftok()
subroutine, private m_calculator::stufftok (fval, character(len=*) wstrng, nchars, character(len=*) string, iend, ier) private
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
RETURNS
EXAMPLE
References ktoken, mssge, and stuffa().
Variable Documentation
dp
integer, parameter m_calculator::dp =kind(0.0d0)
ic_calc
integer, parameter m_calculator::ic_calc =25000 private
icbuf_calc
integer, parameter m_calculator::icbuf_calc =20*(iclen_calc/2+1) private
iclen_calc
integer, parameter, public m_calculator::iclen_calc =512
icname_calc
integer, parameter, public m_calculator::icname_calc =20
ix
character(len=icname_calc), dimension(ic_calc), save m_calculator::ix =' ' private
ix2
character(len=icname_calc), dimension(ic_calc), save m_calculator::ix2 =' ' private
ixy_calc
integer, parameter, public m_calculator::ixy_calc =55555
ixyc_calc
integer, parameter m_calculator::ixyc_calc =50 private
ktoken
integer, save m_calculator::ktoken private
last
character(len=iclen_calc), save m_calculator::last ='0.0' private
mssge
character(len=iclen_calc) m_calculator::mssge private
nc
character(len=iclen_calc), dimension(ixyc_calc), save m_calculator::nc =' ' private
ownon
logical, save m_calculator::ownon =.false. private
value
real(kind=dp), dimension(ic_calc), save m_calculator::value =0.0_dp private
valuer
integer, dimension(ic_calc), save, public m_calculator::valuer =0
values
character(len=iclen_calc), dimension(ic_calc), save, public m_calculator::values =' '
x
real(kind=dp), dimension(ixy_calc), save, public m_calculator::x =0.0_dp
xc
character(len=iclen_calc), dimension(ixyc_calc), save m_calculator::xc =' ' private
y
real(kind=dp), dimension(ixy_calc), save, public m_calculator::y =0.0_dp
yc
character(len=iclen_calc), dimension(ixyc_calc), save m_calculator::yc =' ' private