GeneralPurposeFortran: m_io Module Reference
m_io Module Reference
Functions/Subroutines
character(len=:) function, allocatable, public uniq (name, istart, verbose, create)
NAME
uniq(3f) - [M_io] append a number to the end of filename to make a unique name if name exists
SYNOPSIS
subroutine, public print_inquire (iunit, name)
NAME
print_inquire(3f) - [M_io] Do INQUIRE on file by name/number and print results
SYNOPSIS
subroutine, public slurp (filename, text)
NAME
SLURP(3f) - [M_io] read a file into a character array
SYNOPSIS
integer function, public notopen (start, end, err)
NAME
notopen(3f) - [M_io] Find a FUN/LUN (Fortran-unit-number) that is not in use
SYNOPSIS
character(len=:) function, allocatable, public dirname (filename)
NAME
dirname(3f) - [M_io] strip last component from filename
subroutine, public splitpath (path, dir, name, basename, ext)
NAME
splitpath(3f) - [M_io] split a Unix pathname into components
logical function, public isdir (dirname)
NAME
isdir(3f) - [M_io] checks if argument is a directory path
SYNTAX
logical function isdir(path)
DESCRIPTION
isdir(3f) checks if path is a path to a directory.
OPTIONS
path a character string representing a directory pathname. Trailing spaces are ignored.
EXAMPLES
integer function, public readline (line, lun)
NAME
readline(3f) - [M_io] read a line from specified LUN into allocatable string up to line length limit
Function/Subroutine Documentation
dirname()
character(len=:) function, allocatable, public m_io::dirname (character(len=*), intent(in) filename)
NAME
dirname(3f) - [M_io] strip last component from filename
SYNOPSIS
function dirname(FILENAME) result (DIRECTORY)
  character(len=*),intent(in)  :: FILENAME
  character(len=:),allocatable :: DIRECTORY
DESCRIPTION
Output FILENAME with its last non-slash component and trailing slashes removed. if FILENAME contains no /'s, output '.' (meaning the current directory).
Assumes leaf separator is a slash ('/') and that filename does not contain trailing spaces.
OPTIONS
FILENAME pathname to remove the last leaf from
RETURNS
DIRECTORY directory name for pathname
EXAMPLES
Sample program:
program demo_dirname use M_io, only : dirname implicit none character(len=:),allocatable :: filename integer :: filename_length integer :: i ! get pathname from command line arguments do i = 1 , command_argument_count() call get_command_argument (i , length=filename_length) allocate(character(len=filename_length) :: filename) call get_command_argument (i , value=filename) write(*,'(a)')dirname(filename) deallocate(filename) enddo end program demo_dirname
Sample program executions:
demo_dirname /usr/bin/ -> "/usr" demo_dirname dir1/str dir2/str -> "dir1" followed by "dir2" demo_dirname stdio.h -> "."
SEE ALSO
dirname(3c), basename(3c), readlink(3c), realpath(3c) PRODUCT: CLI library utilities and examples PROGRAM: dirname(3f) DESCRIPTION: strip last component from filename
VERSION: 1.0.0
DATE: 2015-06-26
AUTHOR: John S. Urban REPORTING BUGS: http://www.urbanjost.altervista.org/ HOME PAGE: http://www.urbanjost.altervista.org/index.html LICENSE: Public Domain. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
References removetail(), and true().
isdir()
logical function, public m_io::isdir (character(len=*), intent(in) dirname)
NAME
isdir(3f) - [M_io] checks if argument is a directory path
SYNTAX
logical function isdir(path)
DESCRIPTION
isdir(3f) checks if path is a path to a directory.
OPTIONS
path a character string representing a directory pathname. Trailing spaces are ignored.
EXAMPLES
Sample program:
program demo_isdir Use M_io, only : isdir implicit none integer :: i character(len=80),parameter :: names(*)=[ & '/tmp ', & '/tmp/NOTTHERE ', & '/usr/local ', & '. ', & 'PROBABLY_NOT '] do i=1,size(names) write(*,*)' is ',trim(names(i)),' a directory? ', isdir(names(i)) enddo end program demo_isdir
Results:
is /tmp a directory? T is /tmp/NOTTHERE a directory? F is /usr/local a directory? T is . a directory? T is PROBABLY_NOT a directory? F
References false(), and file().
notopen()
integer function, public m_io::notopen (integer, intent(in), optional start, integer, intent(in), optional end, integer, intent(out), optional err)
NAME
notopen(3f) - [M_io] Find a FUN/LUN (Fortran-unit-number) that is not in use
SYNOPSIS
Usage
integer function notopen(start,end,err) integer,optional,intent(in) :: start integer,optional,intent(in) :: end integer,optional,intent(out) :: err
DESCRIPTION
A free FORTRAN unit number is needed to OPEN a file. NOTOPEN() returns a FORTRAN unit number from START to END not currently associated with an I/O unit. START and END are expected to be positive integers where END .ge. START.
If NOTOPEN() returns -1, then no free FORTRAN unit could be found in the specified range.
Otherwise, NOTOPEN() returns an integer representing a free FORTRAN logical unit number. Note that NOTOPEN() assumes the following unit numbers defined by the Fortran 2008 ISO_FORTRAN_ENV module
ERROR_UNIT,INPUT_UNIT,OUTPUT_UNIT
are special, and will never return those values.
OPTIONS
start optional logical unit number to start scan at, defaults to 10. end optional logical unit number to stop scan at, defaults to 99. err optional error flag returned. ERR will be non-zero if no errors. If not present and an error occurs the program will stop instead of returning.
NOTES
Why are the default START and END limits from 10 to 99? the Fortran 77
standard did not specify a specific limit on the upper range limit, but
the LUN range of 1 to 99 was almost always supported in conventional
programming environments. Additionally, units in the range 0-10 have
often been the units used for pre-assigned files. Occasionally 100,
101 and 102 are reserved (for files such as standard input, standard
output, standard error, ...). Therefore, the defaults for START and
END were selected to be 10 and 99. And most programs do not need
more than 90 files simultaneously open, so the defaults work well in
practice with many versions/vintages of Fortran.
Note that an environment may impose a limit on the number of
simultaneously open files (which some compilers work around).
Beginning with f2008, you can probably use OPEN(NEWUNIT=...) instead.
EXAMPLE
Sample program:
 program demo_notopen ! test the NOTOPEN(3f) function
 use m_io, only: notopen
 implicit none
 integer :: ii, ierr, igot
 write(*,*)'check for preassigned files from unit 0 to unit 1000'
 write(*,*)'(5 and 6 always return -1)'
 do ii=0,1000
    if(notopen(ii,ii,ierr) .ne. ii)then
       write(*,*)'INUSE:',ii, notopen(ii,ii,ierr)
    endif
 enddo
 ! open all files from UNIT=10 to UNIT=30 so have used units
 do ii=10,30,1
   open(unit=ii,status="scratch")
 enddo
 ! close UNIT=25
 close(25)
 ! find open file in range 10 to 30
 write(*,*)'Should get 25 for this ..',notopen(10,30,ierr)
 close(18)
 do ii=10,32
   igot=notopen(ii,ii,ierr)
   write(*,*)'For unit ',ii,' I got ',igot,' with ERR=',ierr
 enddo
 end program demo_notopen
Expected output(can vary with each programming environment):
   check for preassigned files from unit 0 to unit 1000
   (5 and 6 always return -1)
   INUSE:    0    -1
   INUSE:    5    -1
   INUSE:    6    -1
   Should get 25 for this .. 25
   For  unit  10  I  got  -1  with  ERR=  -1
   For  unit  11  I  got  -1  with  ERR=  -1
   For  unit  12  I  got  -1  with  ERR=  -1
   For  unit  13  I  got  -1  with  ERR=  -1
   For  unit  14  I  got  -1  with  ERR=  -1
   For  unit  15  I  got  -1  with  ERR=  -1
   For  unit  16  I  got  -1  with  ERR=  -1
   For  unit  17  I  got  -1  with  ERR=  -1
   For  unit  18  I  got  18  with  ERR=   0
   For  unit  19  I  got  -1  with  ERR=  -1
   For  unit  20  I  got  -1  with  ERR=  -1
   For  unit  21  I  got  -1  with  ERR=  -1
   For  unit  22  I  got  -1  with  ERR=  -1
   For  unit  23  I  got  -1  with  ERR=  -1
   For  unit  24  I  got  -1  with  ERR=  -1
   For  unit  25  I  got  25  with  ERR=   0
   For  unit  26  I  got  -1  with  ERR=  -1
   For  unit  27  I  got  -1  with  ERR=  -1
   For  unit  28  I  got  -1  with  ERR=  -1
   For  unit  29  I  got  -1  with  ERR=  -1
   For  unit  30  I  got  -1  with  ERR=  -1
   For  unit  31  I  got  31  with  ERR=   0
   For  unit  32  I  got  32  with  ERR=   0
AUTHORS
John S. Urban
References then(), and unit().
print_inquire()
subroutine, public m_io::print_inquire (integer, intent(in) iunit, character(len=*), intent(in) name)
NAME
print_inquire(3f) - [M_io] Do INQUIRE on file by name/number and print results
SYNOPSIS
Definition:
subroutine print_inquire(iunit,name) integer,intent(in) :: iunit character(len=*),intent(in) :: name
DESCRIPTION
Given either a Fortran file-unit-number or filename, call the INQUIRE(3f) intrinsic and print typical status information.
OPTIONS
iunit if >=0 then query by number and ignore filename name if IUNIT < 0 then query by this filename
EXAMPLE
Sample program:
   program demo_print_inquire
   use M_io, only : print_inquire
   call print_inquire(5,'')
   call print_inquire(19,'')
   open(unit=20)
   call print_inquire(20,'')
   open(unit=21,status='scratch')
   call print_inquire(21,'')
   open(unit=22,file='junko')
   write(22,*)'WRITE TO JUNKO'
   close(unit=22)
   call print_inquire(22,'')
   call print_inquire(-1,'junko')
   end program demo_print_inquire
Expected output:
print_inquire checking file: /dev/pty1 print_inquire file exists print_inquire using unit number 5
*print_inquire* access type SEQUENTIAL,FORMATTED
*print_inquire* unit number is not open ,unit= 19
print_inquire checking file: fort.20 print_inquire file exists print_inquire using unit number 20
*print_inquire* access type SEQUENTIAL,FORMATTED
*print_inquire* unit number is not named ,unit= 21
*print_inquire* unit number is not open ,unit= 22
print_inquire checking file: junko print_inquire file exists print_inquire file is not open
References file(), form, number, and unit().
readline()
integer function, public m_io::readline (character(len=:), intent(out), allocatable line, integer, intent(in), optional lun)
NAME
readline(3f) - [M_io] read a line from specified LUN into allocatable string up to line length limit
SYNTAX
function readline(line,lun) result(ier)
character(len=:),allocatable,intent(out) :: line integer,intent(in) :: lun integer,intent(out) :: ier
DESCRIPTION
Read a line of any length up to programming environment's maximum
line length. Requires Fortran 2003+.
It is primarily expected to be used when reading input which will
then be parsed.
o Append lines that end in a backslash with next line
o Expand tabs
o Replace unprintable characters with spaces
o Remove trailing carriage return characters and white space
The simple use of a loop that repeatedly re-allocates a character
variable in addition to reading the input file one buffer at a
time could (depending on the programming environment used) be
inefficient, as it could reallocate and allocate memory used for
the output string with each buffer read.
EXAMPLE
Sample program:
program demo_readline use M_io, only : readline implicit none character(len=:),allocatable :: line INFINITE: do while (readline(line)==0) write(*,'(a)')'['//line//']' enddo INFINITE end program demo_readline
References file(), is, name, m_strings::notabs(), size(), and the().
slurp()
subroutine, public m_io::slurp (character(len=*), intent(in) filename, character(len=1), dimension(:), intent(out), allocatable text)
NAME
SLURP(3f) - [M_io] read a file into a character array
SYNOPSIS
Usage
subroutine slurp(filename,text) character(len=*),intent(in) :: filename character(len=1),allocatable,intent(out) :: text(:)
DESCRIPTION
Read an entire file into memory as a stream, retaining line end terminals. Never casually read an entire file into memory if you can process it per line or in smaller units; as large files can consume unreasonable amounts of memory.
OPTIONS
filename filename to read into memory text array of characters to hold file
EXAMPLES
Sample program, assuming the input file "inputfile" exists:
 program demo_slurp
 use M_io, only      : slurp
 implicit none
 character(len=1),allocatable :: text(:) ! array to hold file in memory
 character(len=*),parameter :: FILENAME='inputfile' ! file to read
 ! create test file
 open(file=FILENAME,unit=10)
 write(10,'(a)') new_line('A')//'esrever lliw'
 write(10,'(a)') 'margorp elpmas eht taht'
 write(10,'(a)') 'elif elpmas a si sihT'
 close(unit=10)
 call slurp(FILENAME,text) ! allocate character array and copy file into it
 if(.not.allocated(text))then
    write(*,*)'*rever* failed to load file '//FILENAME
 else
    ! write file reversed to stdout
    write(*,'(*(a:))',advance='no')text(size(text):1:-1)
    deallocate(text)  ! release memory
 endif
 end program demo_slurp
Expected output:
 >This is a sample file
 >that the sample program
 >will reverse
References file(), notopen(), stderr(), and unit().
splitpath()
subroutine, public m_io::splitpath (character(len=*), intent(in) path, character(len=*), intent(out) dir, character(len=*), intent(out) name, character(len=*), intent(out) basename, character(len=*), intent(out) ext)
NAME
splitpath(3f) - [M_io] split a Unix pathname into components
SYNOPSIS
splitpath(path,dir,name,basename,ext)
integer,parameter :: maxlen=4096 character(len=maxlen),intent(in) :: path character(len=maxlen),intent(out) :: dir character(len=maxlen),intent(out) :: name character(len=maxlen),intent(out) :: basename character(len=maxlen),intent(out) :: ext
DESCRIPTION
splitpath(3f) splits given pathname assuming a forward slash separates filename components and that the right-most period in the last leaf of the pathname is considered the beginning of an extension. If an extension is found it is left present in NAME but removed from BASENAME.
This routine does not check the system for the existence or type of the filename components; it merely parses a string.
OPTIONS
path Path to be broken into components.
      o Forward slashes (/) are assumed to separate pathname components.
      o the name '.' is assumed to mean "current directory"
      o the name '..' is assumed to mean "up one directory
      o a pathname ending in a slash is assumed to be a directory name
      o a slash starting the pathname is assumed to represent the root
        directory.
      o trailing spaces are assumed insignificant.
Using these rules helps to reduce incorrect parsing, but the routine is only intended for simple parsing of names of the form "[dir/]name[.extension].
RESULTS
dir Path of directories, including the trailing slash. name Name of file leaf or, if no file is specified in path, name of the lowest directory. basename NAME with any extension removed ext File name extension, if any, including the leading period (.).
The path parameter can be a complete or partial file specification. The special name "." is assumed to mean the current directory, and the special name ".." is assumed to mean one directory above the current directory.
EXAMPLE
program demo_splitpath
use m_io, only : splitpath implicit none integer,parameter :: maxlen=4096 character(len=maxlen),parameter :: file(*)=[& & 'dirs/name.ext ', & & 'xx/IO/zz/NN.FF ', & & 'xx/IO/zz/NN ', & & '/xx/IO/zz/NN ', & & '/xx/IO/zz/ ', & & '/xx/IO/zz.A/ ', & & '/xx/IO/zz/. ', & & ' ', & & './ ', & & '/ ', & & '/.. ', & & './.. ', & & 'name. ', & & '.name ', & & '.name. ', & & '. ', & & '.. ', & & '... ']
character(len=maxlen) :: dir character(len=maxlen) :: name character(len=maxlen) :: basename character(len=maxlen) :: ext integer :: i integer :: longest longest=maxval(len_trim(file)) ! find longest filename
do i=1,size(file) call splitpath(file(i), dir, name, basename, ext) write(*,'(*("| ",a:))') & & file(i)(:longest), & & dir(:longest), & & name(:longest), & & basename(:longest), & & ext(:longest) enddo
Output
| dirs/name.ext | dirs | name.ext | name | .ext | xx/IO/zz/NN.FF| xx/IO/zz | NN.FF | NN | .FF | xx/IO/zz/NN | xx/IO/zz | NN | NN | | /xx/IO/zz/NN | /xx/IO/zz | NN | NN | | /xx/IO/zz/ | /xx/IO/zz | | | | /xx/IO/zz.A/ | /xx/IO/zz.A | | | | /xx/IO/zz/. | /xx/IO/zz/. | | | | | . | | | | ./ | . | | | | / | / | | | | /.. | / | | | | ./.. | ./.. | | | | name. | | name. | name | . | .name | | .name | .name | | .name. | | .name. | .name | . | . | . | | | | .. | | | | | ... | | ... | .. | .
References m_strings::split(), and true().
uniq()
character(len=:) function, allocatable, public m_io::uniq (character(len=*), intent(in) name, integer, intent(in), optional istart, logical, intent(in), optional verbose, logical, intent(in), optional create)
NAME
uniq(3f) - [M_io] append a number to the end of filename to make a unique name if name exists
SYNOPSIS
Usage
character(len=:),allocatable function uniq(name,istart,verbose,create) character(len=*),intent(in) :: name integer,intent(in),optional :: istart logical,intent(in),optional :: verbose logical,intent(in),optional :: create
DESCRIPTION
Given a filename test if it is in use or exists. If it is, or if it ends in a period add a four-digit number to the end of the name and test if the new name exists. If necessary, increment the number and try again up to the value 9999999. By default an empty file is created if an unused name is found.
o relatively non-generic; o does not try to detect io errors
OPTIONS
name base input name used to create output filename If name ends in "." a numeric suffix is always added. istart number to start with as a suffix. Default is 1. Must be a positive integer less than 9999999. verbose writes extra messages to stdout. Defaults to .false. create create file if new name is successfully found. Defaults to .true. .
RETURNS
uniq A unique filename that is the same as the NAME input parameter except with a number appended at the end if needed. If could not find a unique name a blank is returned.
EXAMPLE
Sample program
   program demo_uniq
   use M_io, only : uniq
   implicit none
   character(len=4096) :: myname
   integer             :: i
      myname=uniq('does_not_exist')
      open(unit=10,file='does_exist')
      write(*,*)'name stays the same ',trim(myname)
      myname=uniq('does_exist')
      write(*,*)'name has suffix added ',trim(myname)
      do i=1,10
         myname=uniq('does_exist')
         write(*,*) 'FILENAME:',trim(myname)
         open(unit=20+i,file=myname)
      enddo
   end program demo_uniq
Expected output
 name stays the same does_not_exist
 name has suffix added does_exist0001
 FILENAME:does_exist0002
 FILENAME:does_exist0003
 FILENAME:does_exist0004
 FILENAME:does_exist0005
 FILENAME:does_exist0006
 FILENAME:does_exist0007
 FILENAME:does_exist0008
 FILENAME:does_exist0009
 FILENAME:does_exist0010
 FILENAME:does_exist0011
AUTHOR
John S. Urban, 1993
References false(), file(), true(), and unit().