GeneralPurposeFortran: m_writegif Module Reference
m_writegif Module Reference
NAME
writegif(3f) - [M_writegif] Codes pixel-map with palette into GIF format. Optional transparent color
SYNOPSIS
Functions/Subroutines
character(len=2) function char2 (ival)
subroutine, private flushbuffer (F_unit)
subroutine, private giflzw (F_unit, Pixel)
subroutine, private inittable ()
subroutine open_for_write (Fname, Funit)
subroutine, private slicewrite (F_unit, code)
subroutine, public writegif (FileName, Pixel, ColorMap, Transparent)
Variables
character(len= *), parameter ident ="@(#)This module can write a GIF file in GIF89 format from raster data"
integer, parameter, private bufend =260
character(len=bufend), private buf
integer, private ibuf
integer, parameter, private maxcode = 4095
integer, parameter, private nocode = maxcode+1
character(len=1), dimension(0:maxcode+1), private endbyte
integer, dimension(0:maxcode), private follow
integer, dimension(0:maxcode), private next
integer, private ncod
integer, private curmaxcode
integer, private eoi
integer, private cc
integer, private p
integer, private k
integer, private child
integer, private maxbase
integer, private skip
integer, private slen
integer, private blen
integer, private accum
integer, private nout
Detailed Description
NAME
writegif(3f) - [M_writegif] Codes pixel-map with palette into GIF format. Optional transparent color
SYNOPSIS
subroutine writegif (FileName, Pixel, ColorMap, Transparent)
character(len=*), intent(in) :: FileName integer, intent(in), dimension(:,:) :: Pixel integer, intent(in), dimension(:,0:) :: ColorMap integer, intent(in), optional :: Transparent
DESCRIPTION
Write GIF file from pixel array and color map.
OPTIONS
FileName file to create or replace Pixel Pixel values 0 to ncol ColorMap Color map (RGB 0:255 for colours 0:ncol) Transparent Optional
EXAMPLE
Sample call:
program demo_writegif use M_writegif, only : writegif integer :: Pixel(100,100) integer :: Transparent = 0 integer, :: ColorMap (3,0:7) colormap(:,0)=[255,255,255] colormap(:,1)=[255, 0, 0] colormap(:,2)=[ 0,255, 0] colormap(:,3)=[ 0, 0,255] colormap(:,4)=[255,255, 0] colormap(:,5)=[255, 0,255] colormap(:,6)=[ 0,255,255] colormap(:,7)=[ 0, 0, 0]
! put some colored boxes into pixmap pixel(:,:)=0 pixel(1:80,1:80)=1 pixel(11:20,11:20)=2 pixel(21:40,21:40)=3
! write gif with a transparent background call writegif('boxes_t.gif',pixel,ColorMap,Transparent)
! change background color and write standard gif file where (pixel.eq.0) pixel=4 call writegif('boxes.gif',pixel,ColorMap)
end program demo_writegif
AUTHOR
o Version 1.01, 1999 August: Written by Jos Bergervoet o Version 2, 2008 Jan 28: Modified by Clive Page to use stream I/O, array as colourmap. o Version 3, 2017 July 6: Modified by John Urban to make it easier to use with M_PIXEL(3f) module.
LICENSE
License: public domain. PRODUCT: CLI library utilities and examples PROGRAM: M_writegif(3f) DESCRIPTION: This module can write a GIF file in GIF89 format from raster data
VERSION: 1.01, 19990808
AUTHOR: Jos Bergervoet
VERSION: 2.00, 20080128
AUTHOR: version by [[Clive Page]] makes use of Fortran stream I/O, array as colourmap
VERSION: 3.00, 20170706
AUTHOR: Modified by John Urban to make it easier to use with M_PIXEL(3f) module. LICENSE: Public Domain. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
Function/Subroutine Documentation
char2()
character(len=2) function m_writegif::char2 (integer, intent(in) ival) private
flushbuffer()
subroutine, private m_writegif::flushbuffer (integer, intent(in) F_unit) private
References ibuf, and skip.
giflzw()
subroutine, private m_writegif::giflzw (integer, intent(in) F_unit, integer, dimension(:,:), intent(in) Pixel) private
References blen, cc, child, curmaxcode, endbyte, eoi, flushbuffer(), follow, inittable(), k, maxbase, maxcode, ncod, next, nocode, nout, p, slen, and slicewrite().
inittable()
subroutine, private m_writegif::inittable () private
References blen, cc, curmaxcode, eoi, follow, maxbase, ncod, next, nocode, and slen.
open_for_write()
subroutine m_writegif::open_for_write (character(len=*), intent(in) Fname, integer, intent(out) Funit) private
References file(), and unit().
slicewrite()
subroutine, private m_writegif::slicewrite (integer, intent(in) F_unit, integer, intent(in) code) private
References accum, flushbuffer(), ibuf, nout, skip, and slen.
writegif()
subroutine, public m_writegif::writegif (character(len=*), intent(in) FileName, integer, dimension(:,:), intent(in) Pixel, integer, dimension(:,0:), intent(in) ColorMap, integer, intent(in), optional Transparent)
References blen, char2(), giflzw(), open_for_write(), and unit().
Variable Documentation
accum
integer, private m_writegif::accum private
blen
integer, private m_writegif::blen private
buf
character(len=bufend), private m_writegif::buf private
bufend
integer, parameter, private m_writegif::bufend =260 private
cc
integer, private m_writegif::cc private
child
integer, private m_writegif::child private
curmaxcode
integer, private m_writegif::curmaxcode private
endbyte
character(len=1), dimension(0:maxcode+1), private m_writegif::endbyte private
eoi
integer, private m_writegif::eoi private
follow
integer, dimension(0:maxcode), private m_writegif::follow private
ibuf
integer, private m_writegif::ibuf private
ident
character(len=*), parameter m_writegif::ident ="@(#)This module can write a GIF file in GIF89 format from raster data"
k
integer, private m_writegif::k private
maxbase
integer, private m_writegif::maxbase private
maxcode
integer, parameter, private m_writegif::maxcode = 4095 private
ncod
integer, private m_writegif::ncod private
next
integer, dimension(0:maxcode), private m_writegif::next private
nocode
integer, parameter, private m_writegif::nocode = maxcode+1 private
nout
integer, private m_writegif::nout private
p
integer, private m_writegif::p private
skip
integer, private m_writegif::skip private
slen
integer, private m_writegif::slen private