GeneralPurposeFortran: m_units Module Reference
m_units Module Reference
NAME
M_units(3fm) - [M_units] convert between various physical units
Functions/Subroutines
elemental real function, public c2f (celsius)
NAME
c2f - [M_units] convert Celsius to Fahrenheit
SYNOPSIS
elemental real function, public f2c (fahrenheit)
NAME
f2c - [M_units] convert Fahrenheit to Celsius
SYNOPSIS
elemental real function, public r2d (radians)
NAME
r2d - [M_units] convert radians to degrees
SYNOPSIS
elemental real function, public d2r (degrees)
NAME
d2r - [M_units] convert degrees to radians
SYNOPSIS
elemental real function, public sind (angle_in_degrees)
NAME
sind - [M_units] calculate sine of value in degrees
SYNOPSIS
elemental real function, public cosd (angle_in_degrees)
NAME
cosd - [M_units] calculate sine of value in degrees
SYNOPSIS
elemental real function, public tand (angle_in_degrees)
NAME
tand - [M_units] calculate tangent of value in degrees
SYNOPSIS
elemental real function, public asind (x)
elemental real function, public acosd (x)
elemental real function, public atand (x)
elemental real function, public atan2d (x, y)
elemental real function, public feet_to_meters (feet)
NAME
feet_to_meters - [M_units] converts a measurement in feet to meters
SYNOPSIS
elemental real function, public meters_to_feet (meters)
NAME
meters_to_feet - [M_units] converts a measurement in meters to feet
SYNOPSIS
subroutine, public cartesian_to_spherical (x, y, z, radius, inclination, azimuth)
NAME
cartesian_to_spherical(3f) - [M_units] convert Cartesian coordinates to ISO polar coordinates
SYNOPSIS
subroutine, public spherical_to_cartesian (radius, inclination, azimuth, x, y, z)
NAME
spherical_to_cartesian(3f) - [M_units] convert ISO polar coordinates to Cartesian coordinates
SYNOPSIS
subroutine, public cartesian_to_polar (x, y, radius, inclination)
NAME
cartesian_to_polar(3f) - [M_units] convert Cartesian coordinates to polar coordinates
SYNOPSIS
subroutine, public polar_to_cartesian (radius, inclination, x, y)
NAME
polar_to_cartesian(3f) - [M_units] convert polar coordinates to Cartesian coordinates
SYNOPSIS
subroutine, public atomnum2symbol (atomnum, symbol)
NAME
atomnum2symbol - [M_units] return element symbol given atomic number
SYNOPSIS
subroutine, public symbol2atomnum (symbol, atomnum)
NAME
symbol2atomnum - [M_units] return atomic number given element symbol name
SYNOPSIS
Variables
doubleprecision, parameter, public pi_d = 3.141592653589793238462643383279500d0
doubleprecision, parameter, public e_d = 2.718281828459045235360d0
doubleprecision, parameter, public radian_d = 57.29577951310d0
doubleprecision, parameter, public degree_d = 0.0174532925199430d0
real, parameter, public pi = 3.141592653589793238462643383279500d0
real, parameter, public e = 2.718281828459045235360d0
real, parameter, public radian = 57.29577951310d0
real, parameter, public degree = 0.0174532925199430d0
doubleprecision, parameter degrees_to_radians_d = PI_D / 180.0D+00
real, parameter degrees_to_radians = real(PI / 180.0D+00)
Detailed Description
NAME
M_units(3fm) - [M_units] convert between various physical units
SYNOPSIS
procedure definitions:
   elemental real function c2f(celsius)
   elemental real function f2c(fahrenheit)
   elemental real function r2d(radians)
   elemental real function d2r(degrees)
   elemental real function feet_to_meters(feet)
   elemental real function meters_to_feet(meters)
   elemental real function sind(angle_in_degrees)
   elemental real function cosd(angle_in_degrees)
   elemental real function tand(angle_in_degrees)
   elemental real function asind(x)
   elemental real function acosd(x)
   elemental real function atand(x)
   elemental real function atan2d(x,y)
   subroutine cartesian_to_spherical(x,y,z,radius,inclination,azimuth)
   subroutine spherical_to_cartesian(radius,inclination,azimuth,x,y,z)
   subroutine cartesian_to_polar(x,y,radius,inclination)
   subroutine polar_to_cartesian(radius,inclination,x,y)
Where the input values may be any standard scalar value supported by
the anyscalar_to_real(3f) function (real,integer,doubleprecision) within
the range allowed by the function.
Tables:
DESCRIPTION
M_units(3fm) is a Fortran module that collects together basic
procedures that are used to convert between various physical units
and common named constants.
   +---------------------------+
   |Angle|Area        |Base    |
   |-----+------------+--------|
   |Data |Energy      |Length  |
   |-----+------------+--------|
   |Mass |Power       |Pressure|
   |-----+------------+--------|
   |Speed|Temperature |Time    |
   +---------------------------+
Angular Units
 o d2r:  Convert degrees to radians
 o r2d:  Convert radians to degrees
Temperature
 o c2f:  Convert Celsius to Fahrenheit
 o f2c:  Convert Fahrenheit to Celsius
Distance
 o feet_to_meters:  Convert feet to meters
 o meters_to_feet:  Convert meters to feet
REAL trig functions where input is in angular degrees instead of radians
 o elemental real function sind(angle_in_degrees)
 o elemental real function cosd(angle_in_degrees)
 o elemental real function tand(angle_in_degrees)
 o elemental real function asind(x)
 o elemental real function acosd(x)
 o elemental real function atand(x)
 o elemental real function atan2d(x,y)
Coordinates
 o cartesian_to_spherical:  Convert cartesian coordinates to spherical
 o spherical:  Convert spherical coordinates to cartesian
 o cartesian_to_polar:  Convert cartesian coordinates to polar
 o polar:  Convert polar coordinates to cartesian
And the real constants PI, RADIAN, DEGREE, E. And the double_precision constants PI_D, RADIAN_D, DEGREE_D, E_D.
Note that your compiler is less likely to inline small procedures in a module than it would statement functions or CONTAINED functions.
EXAMPLES
Simple usage example:
program testit use M_units, only : r2d, d2r use M_units, only : f2c, c2f use M_units, only : sind, cosd, tand use M_units, only : asind, acosd, atand, atan2d use M_units, only : pi=>pi,radian,degree,e implicit none write(*,*)r2d([0.0,PI/4.0,PI/2.0,3.0*PI/2.0,PI]) write(*,*)d2r([0.0,45.0,90.0,135.0,180.0]) write(*,*)f2c([-40.0,32.0,212.0]) write(*,*)c2f([-40.0,0.0,100.0]) write(*,*)PI write(*,*)E end program testit
Results:
> 0.00000000 45.0000000 90.0000000 270.000000 180.000000 > 0.00000000 0.785398185 1.57079637 2.35619450 3.14159274 >-40.0000000 0.00000000 100.000000 >-40.0000000 32.0000000 212.000000 > 3.14159274 > 2.71828175
Function/Subroutine Documentation
acosd()
elemental real function, public m_units::acosd (class(*), intent(in) x)
References m_anyscalar::anyscalar_to_real(), and degrees_to_radians.
asind()
elemental real function, public m_units::asind (class(*), intent(in) x)
References m_anyscalar::anyscalar_to_real(), and degrees_to_radians.
atan2d()
elemental real function, public m_units::atan2d (class(*), intent(in) x, class(*), intent(in) y)
References m_anyscalar::anyscalar_to_real(), and degrees_to_radians.
atand()
elemental real function, public m_units::atand (class(*), intent(in) x)
References m_anyscalar::anyscalar_to_real(), and degrees_to_radians.
atomnum2symbol()
subroutine, public m_units::atomnum2symbol (integer, intent(in) atomnum, character(len=2), intent(out) symbol)
NAME
atomnum2symbol - [M_units] return element symbol given atomic number
SYNOPSIS
subroutine atomnum2symbol(atomnum,symbol)
integer,intent(in) :: atomnum character(len=2),intent(out) :: symbol
DESCRIPTION
Given an atomic number in the range of 1 to 109 return the corresponding element symbol name
OPTIONS
atomnum an atomic number from 1 to 109
RETURNS
symbol two-character symbol name corresponding to atomic number ATOMNUM
EXAMPLE
Sample program
program demo_atomnum2symbol use M_units, only : atomnum2symbol implicit none character(len=2) :: name integer :: i do i=1,109 call atomnum2symbol(i,name) write(*,*)i,name enddo end program demo_atomnum2symbol
Results:
     1 H
     2 He
     3 Li
     4 Be
     5 B
     6 C
     7 N
     8 O
     9 F
    10 Ne
    11 Na
    12 Mg
    13 Al
    14 Si
    15 P
    16 S
    17 Cl
    18 Ar
    19 K
    20 Ca
    21 Sc
    22 Ti
    23 V
    24 Cr
    25 Mn
    26 Fe
    27 Co
    28 Ni
    29 Cu
    30 Zn
    31 Ga
    32 Ge
    33 As
    34 Se
    35 Br
    36 Kr
    37 Rb
    38 Sr
    39 Y
    40 Zr
    41 Nb
    42 Mo
    43 Tc
    44 Ru
    45 Rh
    46 Pd
    47 Ag
    48 Cd
    49 In
    50 Sn
    51 Sb
    52 Te
    53 I
    54 Xe
    55 Cs
    56 Ba
    57 La
    58 Ce
    59 Pr
    60 Nd
    61 Pm
    62 Sm
    63 Eu
    64 Gd
    65 Tb
    66 Dy
    67 Ho
    68 Er
    69 Tm
    70 Yb
    71 Lu
    72 Hf
    73 Ta
    74 W
    75 Re
    76 Os
    77 Ir
    78 Pt
    79 Au
    80 Hg
    81 Tl
    82 Pb
    83 Bi
    84 Po
    85 At
    86 Rn
    87 Fr
    88 Ra
    89 Ac
    90 Th
    91 Pa
    92 U
    93 Np
    94 Pu
    95 Am
    96 Cm
    97 Bk
    98 Cf
    99 Es
   100 Fm
   101 Md
   102 No
   103 Lr
   104 Rf
   105 Db
   106 Sg
   107 Bh
   108 Hs
   109 Mt
c2f()
elemental real function, public m_units::c2f (class(*), intent(in) celsius)
NAME
c2f - [M_units] convert Celsius to Fahrenheit
SYNOPSIS
elemental real function c2f(celsius)
class(*),intent(in) :: celsius
DESCRIPTION
Converts Celsius temperatures to Fahrenheit using the formula:
fahrenheit=(celsius+40.0)*9.0/5.0 - 40.0
OPTIONS
celsius any standard scalar value supported by anyscalar_to_real(3f).
EXAMPLE
Sample program
program demo_c2f use M_units, only : c2f implicit none write(*,*)'With REAL array input ', c2f([ -40.0, 0.0, 100.0 ]) write(*,*)'With INTEGER array input ', c2f([ -40, 0, 100 ]) write(*,*)'With DOUBLEPRECISION ', c2f(-40.0d0),c2f(0.0d0),c2f(100.0d0) end program demo_c2f
Results
With REAL array input -40.0000000 32.0000000 212.000000 With INTEGER array input -40.0000000 32.0000000 212.000000 With DOUBLEPRECISION -40.0000000 32.0000000 212.000000
References m_anyscalar::anyscalar_to_real().
cartesian_to_polar()
subroutine, public m_units::cartesian_to_polar (real, intent(in) x, real, intent(in) y, real, intent(out) radius, real, intent(out) inclination)
NAME
cartesian_to_polar(3f) - [M_units] convert Cartesian coordinates to polar coordinates
SYNOPSIS
subroutine cartesian_to_polar(x,y,radius,inclination)
real,intent(in) :: y,z real,intent(out) :: radius,inclination
DESCRIPTION
 Convert a cartesian point <X,Y,Z> to polar coordinates <radius,
 inclination> with angles in radians using the formulas
   radius=sqrt(x**2+y**2)
   inclination=atan2(y,x)
OPTIONS
X The distance along the x-axis Y The distance along the y-axis
RESULTS
RADIUS       The radial distance from the origin (O) to the point (P)
INCLINATION  The inclination angle in radians between the inclination reference direction
             (x-axis) and the orthogonal projection of the line OP of the
             reference plane (x-y plane).
EXAMPLES
examples of usage
program demo_cartesian_to_polar use M_units, only : cartesian_to_polar implicit none real :: x,y real :: r,i integer :: ios INFINITE: do read(*,*,iostat=ios) x, y if(ios.ne.0)exit INFINITE call cartesian_to_polar(x,y,r,i) write(*,*)'x=',x,' y=',y,'radius=',r,'inclination=',i enddo INFINITE end program demo_cartesian_to_polar
cartesian_to_spherical()
subroutine, public m_units::cartesian_to_spherical (real, intent(in) x, real, intent(in) y, real, intent(in) z, real, intent(out) radius, real, intent(out) inclination, real, intent(out) azimuth)
NAME
cartesian_to_spherical(3f) - [M_units] convert Cartesian coordinates to ISO polar coordinates
SYNOPSIS
subroutine cartesian_to_spherical(x,y,z,radius,inclination,azimuth)
real,intent(in) :: x,y,z real,intent(out) :: radius,inclination,azimuth
DESCRIPTION
 Convert a cartesian point <X,Y,Z> to ISO 8000-2:2009 polar coordinates <radius,
 inclination, azimuth> with angles in radians using the formulas
   radius=sqrt(x**2+y**2+z**2)
   inclination=acos(z/radius)
   azimuth=atan2(y,x)
OPTIONS
X The distance along the x-axis Y The distance along the y-axis Z The distance along the z-axis
RESULTS
RADIUS       The radial distance from the origin (O) to the point (P)
INCLINATION  The zenith angle in radians between the zenith reference direction
             (z-axis) and the line OP
AZIMUTH      The azimuth angle in radians between the azimuth reference direction
             (x-axis) and the orthogonal projection of the line OP of the
             reference plane (x-y plane).
EXAMPLES
examples of usage
program demo_cartesian_to_spherical use M_units, only : cartesian_to_spherical implicit none real :: x,y,z real :: r,i,a integer :: ios INFINITE: do read(*,*,iostat=ios) x, y, z if(ios.ne.0)exit INFINITE call cartesian_to_spherical(x,y,z,r,i,a) write(*,*)'x=',x,' y=',y,' z=',z,'radius=',r,'inclination=',i,'azimuth=',a enddo INFINITE end program demo_cartesian_to_spherical
cosd()
elemental real function, public m_units::cosd (class(*), intent(in) angle_in_degrees)
NAME
cosd - [M_units] calculate sine of value in degrees
SYNOPSIS
elemental real function cosd(degrees)
class(*),intent(in) :: degrees
DESCRIPTION
Calculate cosine of input value in degrees
OPTIONS
degrees any standard scalar value supported by anyscalar_to_real(3f).
EXAMPLE
Sample program
program demo_cosd use M_units, only : cosd implicit none write(*,*)'With REAL array input ', & & cosd([ 0.0, 15.0, 30.0, 45.0, 60.0, 75.0, 90.0, 180.0, 270.0 ]) write(*,*)'With INTEGER array input ', & & cosd([0,15,30,45,60,75,90,180,270]) write(*,*)'With DOUBLEPRECISION ', & & cosd(0.0d0),cosd(15.0d0),cosd(90.0/3.0d0), & & cosd(90.0/2.0d0),cosd(60.0d0),cosd(75.0d0), & & cosd(90.0d0),cosd(180.0d0),cosd(270.0d0) end program demo_cosd
Results
With REAL array input 1.00000000 0.965925813 0.866025448 0.707106769 0.499999970 0.258819073 -4.37113883E-08 -1.00000000 1.19248806E-08 With INTEGER array input 1.00000000 0.965925813 0.866025448 0.707106769 0.499999970 0.258819073 -4.37113883E-08 -1.00000000 1.19248806E-08 With DOUBLEPRECISION 1.00000000 0.965925813 0.866025448 0.707106769 0.499999970 0.258819073 -4.37113883E-08 -1.00000000 1.19248806E-08
References m_anyscalar::anyscalar_to_real(), and degrees_to_radians.
d2r()
elemental real function, public m_units::d2r (class(*), intent(in) degrees)
NAME
d2r - [M_units] convert degrees to radians
SYNOPSIS
elemental real function d2r(degrees)
class(*),intent(in) :: radians
DESCRIPTION
Converts degrees to radians using the formula:
radians=real(degrees*acos(-1.0d0)/180.d0)
OPTIONS
degrees any standard scalar value supported by anyscalar_to_real(3f). This includes REAL, INTEGER, DOUBLEPRECISION, ... .
EXAMPLE
Sample program
program demo_d2r use M_units, only : d2r implicit none write(*,*)'With REAL array input ', d2r([0.0,45.0,90.0,135.0,180.0]) write(*,*)'With INTEGER array input ', d2r([0, 45, 90, 135, 180 ]) write(*,*)'With DOUBLEPRECISION ', & & d2r(0.0d0),d2r(45.0d0),d2r(90.0d0),d2r(135.0d0),d2r(180.0d0) end program demo_d2r
Results
With REAL array input 0.00000 0.785398185 1.57079637 2.35619450 3.14159274 With INTEGER array input 0.00000 0.785398185 1.57079637 2.35619450 3.14159274 With DOUBLEPRECISION 0.00000 0.785398185 1.57079637 2.35619450 3.14159274
References m_anyscalar::anyscalar_to_real(), and d2r().
f2c()
elemental real function, public m_units::f2c (class(*), intent(in) fahrenheit)
NAME
f2c - [M_units] convert Fahrenheit to Celsius
SYNOPSIS
elemental real function f2c(fahrenheit)
class(*),intent(in) :: fahrenheit
DESCRIPTION
Converts Fahrenheit temperatures to Celsius using the formula:
celsius=(fahrenheit+40.0)*5.0/9.0 - 40.0
OPTIONS
fahrenheit any standard scalar value supported by anyscalar_to_real(3f).
EXAMPLE
Sample program
program demo_f2c use M_units, only : f2c implicit none write(*,*)'With REAL array input ', f2c([ -40.0,32.0, 212.0 ]) write(*,*)'With INTEGER array input ', f2c([ -40, 32, 212 ]) write(*,*)'With DOUBLEPRECISION ', f2c(-40.0d0),f2c(32.0d0),f2c(212.0d0) end program demo_f2c
Results
With REAL array input -40.0000000 0.00000000 100.000000 With INTEGER array input -40.0000000 0.00000000 100.000000 With DOUBLEPRECISION -40.0000000 0.00000000 100.000000
References m_anyscalar::anyscalar_to_real().
feet_to_meters()
elemental real function, public m_units::feet_to_meters (class(*), intent(in) feet)
NAME
feet_to_meters - [M_units] converts a measurement in feet to meters
SYNOPSIS
elemental real function feet_to_meters(feet)
class(*),intent(in) :: feet
DESCRIPTION
Converts feet to meters using the formula:
meters = 0.0254 * 12.0 * feet
OPTIONS
feet any standard scalar value supported by anyscalar_to_real(3f). This at least includes REAL, INTEGER, and DOUBLEPRECISION.
EXAMPLE
Sample program
program demo_feet_to_meters use M_units, only : feet_to_meters implicit none write(*,*)'With REAL array input ', & & feet_to_meters([ -1.0, 0.0, 1.0 ,1.0/12.0]) write(*,*)'With INTEGER array input ', & & feet_to_meters([ -1, 0, 1 ]) write(*,*)'With DOUBLEPRECISION ', & & feet_to_meters(-1.0d0), & & feet_to_meters(0.0d0), & & feet_to_meters(1.0d0) end program demo_feet_to_meters
Results
With REAL array input -0.304800004 0.00000000 0.304800004 2.54000016E-02 With INTEGER array input -0.304800004 0.00000000 0.304800004 With DOUBLEPRECISION -0.304800004 0.00000000 0.304800004
References m_anyscalar::anyscalar_to_real().
meters_to_feet()
elemental real function, public m_units::meters_to_feet (class(*), intent(in) meters)
NAME
meters_to_feet - [M_units] converts a measurement in meters to feet
SYNOPSIS
elemental real function meters_to_feet(meters)
class(*),intent(in) :: meters
DESCRIPTION
Converts feet to meters using the formula:
feet= meters/12.0/0.0254
OPTIONS
feet any standard scalar value supported by anyscalar_to_real(3f). This at least includes REAL, INTEGER, and DOUBLEPRECISION.
EXAMPLE
Sample program
program demo_meters_to_feet use M_units, only : meters_to_feet implicit none write(*,*)'With REAL array input ', meters_to_feet([ -1.0, 0.0, 1.0 ]) write(*,*)'With INTEGER array input ', meters_to_feet([ -1, 0, 1 ]) write(*,*)'With DOUBLEPRECISION ', meters_to_feet(-1.0d0),meters_to_feet(0.0d0),meters_to_feet(1.0d0) end program demo_meters_to_feet
Results
With REAL array input -3.28083992 0.00000000 3.28083992 With INTEGER array input -3.28083992 0.00000000 3.28083992 With DOUBLEPRECISION -3.28083992 0.00000000 3.28083992
References m_anyscalar::anyscalar_to_real().
polar_to_cartesian()
subroutine, public m_units::polar_to_cartesian (real, intent(in) radius, real, intent(in) inclination, real, intent(out) x, real, intent(out) y)
NAME
polar_to_cartesian(3f) - [M_units] convert polar coordinates to Cartesian coordinates
SYNOPSIS
subroutine polar_to_cartesian(radius,inclination,x,y)
real,intent(in) :: radius,inclination real,intent(out) :: x,y
DESCRIPTION
 Convert polar coordinate <radius, inclination > with
 angles in radians to cartesian point <X,Y> using the formulas
   x=radius*cos(inclination)
   y=radius*sin(inclination)
OPTIONS
RADIUS       The radial distance from the origin (O) to the point (P)
INCLINATION  The INCLINATION angle in radians between the inclination reference direction
             (x-axis) and the orthogonal projection of the line OP of the
             reference plane (x-y plane).
RESULTS
X  The distance along the x-axis
Y  The distance along the y-axis
EXAMPLES
examples of usage
program demo_polar_to_cartesian use M_units, only : polar_to_cartesian implicit none real :: x,y real :: r,i integer :: ios INFINITE: do read(*,*,iostat=ios) x, y if(ios.ne.0)exit INFINITE call polar_to_cartesian(r,i,x,y) write(*,*)'x=',x,' y=',y,'radius=',r,'inclination=',i enddo INFINITE end program demo_polar_to_cartesian
r2d()
elemental real function, public m_units::r2d (class(*), intent(in) radians)
NAME
r2d - [M_units] convert radians to degrees
SYNOPSIS
elemental real function r2d(radians)
class(*),intent(in) :: degrees
DESCRIPTION
Converts radians to degrees using the formula:
degrees=real(radians * 180.d0 / acos(-1.0d0))
OPTIONS
radians any standard scalar value supported by anyscalar_to_real(3f).
EXAMPLE
Sample program
program demo_r2d use M_units, only : r2d use M_units, only : pi=>pi implicit none write(*,*)'With REAL array input ', r2d([ 0.0, PI/4.0, PI/2.0, 3.0*PI/2.0, PI ]) write(*,*)'With INTEGER array input ', r2d([0,1,2,3,4]) write(*,*)'With DOUBLEPRECISION ', r2d(0.0d0),r2d(PI/4.0d0),r2d(PI/2.0d0),r2d(3.0d0*PI/2.0d0),r2d(PI) end program demo_r2d
Results
With REAL array input 0.00000000 45.0000000 90.0000000 270.000000 180.000000 With INTEGER array input 0.00000000 57.2957802 114.591560 171.887344 229.183121 With DOUBLEPRECISION 0.00000000 45.0000000 90.0000000 270.000000 180.000000
References m_anyscalar::anyscalar_to_real(), and r2d().
sind()
elemental real function, public m_units::sind (class(*), intent(in) angle_in_degrees)
NAME
sind - [M_units] calculate sine of value in degrees
SYNOPSIS
elemental real function sind(degrees)
class(*),intent(in) :: degrees
DESCRIPTION
Calculate sine of input value in degrees
OPTIONS
degrees any standard scalar value supported by anyscalar_to_real(3f).
EXAMPLE
Sample program
program demo_sind use M_units, only : sind implicit none write(*,*)'With REAL array input ', sind([ 0.0, 15.0, 30.0, 45.0, & & 60.0, 75.0, 90.0, 180.0, 270.0 ]) write(*,*)'With INTEGER array input ', sind([0,15,30,45,60,75,90,180,270]) write(*,*)'With DOUBLEPRECISION ', & & sind(0.0d0),sind(15.0d0),sind(90.0/3.0d0), & & sind(90.0/2.0d0),sind(60.0d0),sind(75.0d0), & & sind(90.0d0),sind(180.0d0),sind(270.0d0) end program demo_sind
Results
With REAL array input 0.00000000 0.258819044 0.500000000 0.707106829 0.866025448 0.965925813 1.00000000 -8.74227766E-08 -1.00000000 With INTEGER array input 0.00000000 0.258819044 0.500000000 0.707106829 0.866025448 0.965925813 1.00000000 -8.74227766E-08 -1.00000000 With DOUBLEPRECISION 0.00000000 0.258819044 0.500000000 0.707106829 0.866025448 0.965925813 1.00000000 -8.74227766E-08 -1.00000000
References m_anyscalar::anyscalar_to_real(), and degrees_to_radians.
spherical_to_cartesian()
subroutine, public m_units::spherical_to_cartesian (real, intent(in) radius, real, intent(in) inclination, real, intent(in) azimuth, real, intent(out) x, real, intent(out) y, real, intent(out) z)
NAME
spherical_to_cartesian(3f) - [M_units] convert ISO polar coordinates to Cartesian coordinates
SYNOPSIS
subroutine spherical_to_cartesian(radius,inclination,azimuth,x,y,z)
real,intent(in) :: radius,inclination,azimuth real,intent(out) :: x,y,z
DESCRIPTION
 Convert ISO 8000-2:2009 polar coordinate <radius, inclination, azimuth> with
 angles in radians to cartesian point <X,Y,Z> using the formulas
   x=radius*sin(inclination)*cos(azimuth)
   y=radius*sin(inclination)*sin(azimuth)
   z=radius*cos(inclination)
OPTIONS
RADIUS       The radial distance from the origin (O) to the point (P)
INCLINATION  The zenith angle in radians between the zenith reference direction
             (z-axis) and the line OP
AZIMUTH      The azimuth angle in radians between the azimuth reference direction
             (x-axis) and the orthogonal projection of the line OP of the
             reference plane (x-y plane).
RESULTS
X  The distance along the x-axis
Y  The distance along the y-axis
Z  The distance along the z-axis
EXAMPLES
examples of usage
program demo_spherical_to_cartesian use M_units, only : spherical_to_cartesian implicit none real :: x,y,z real :: r,i,a integer :: ios INFINITE: do read(*,*,iostat=ios) x, y, z if(ios.ne.0)exit INFINITE call spherical_to_cartesian(r,i,a,x,y,z) write(*,*)'x=',x,' y=',y,' z=',z,'radius=',r,'inclination=',i,'azimuth=',a enddo INFINITE end program demo_spherical_to_cartesian
symbol2atomnum()
subroutine, public m_units::symbol2atomnum (character(len=2), intent(in) symbol, integer, intent(out) atomnum)
NAME
symbol2atomnum - [M_units] return atomic number given element symbol name
SYNOPSIS
subroutine symbol2atomnum(symbol,atomnum)
character(len=2),intent(in) :: symbol integer,intent(out) :: atomnum
DESCRIPTION
Given a two-character element symbol name return the corresponding atomic number
OPTIONS
symbol two-character symbol name corresponding to atomic number ATOMNUM
RETURNS
atomnum an atomic number from 1 to 109
EXAMPLE
Sample program
program demo_symbol2atomnum use M_units, only : symbol2atomnum implicit none integer :: atomnum character(len=2) :: name name='Ne' call symbol2atomnum(name,atomnum) write(*,*)atomnum,name end program demo_symbol2atomnum
Results:
10 Ne
tand()
elemental real function, public m_units::tand (class(*), intent(in) angle_in_degrees)
NAME
tand - [M_units] calculate tangent of value in degrees
SYNOPSIS
elemental real function tand(degrees)
class(*),intent(in) :: degrees
DESCRIPTION
Calculate tangent of input value in degrees
OPTIONS
degrees any standard scalar value supported by anyscalar_to_real(3f).
EXAMPLE
Sample program
program demo_tand use M_units, only : tand implicit none write(*,*)'With REAL array input ', & &tand([ 0.0, 15.0, 30.0, 45.0, 60.0, 75.0, 90.0, 180.0, 270.0 ]) write(*,*)'With INTEGER array input ', & &tand([0,15,30,45,60,75,90,180,270]) write(*,*)'With DOUBLEPRECISION ', & &tand(0.0d0),tand(15.0d0),tand(90.0/3.0d0),tand(90.0/2.0d0),& & tand(60.0d0),tand(75.0d0),& & tand(90.0d0),tand(180.0d0),tand(270.0d0) end program demo_tand
Results
References m_anyscalar::anyscalar_to_real(), and degrees_to_radians.
Variable Documentation
degree
real, parameter, public m_units::degree = 0.0174532925199430d0
degree_d
doubleprecision, parameter, public m_units::degree_d = 0.0174532925199430d0
degrees_to_radians
real, parameter m_units::degrees_to_radians = real(PI / 180.0D+00) private
degrees_to_radians_d
doubleprecision, parameter m_units::degrees_to_radians_d = PI_D / 180.0D+00 private
e
real, parameter, public m_units::e = 2.718281828459045235360d0
e_d
doubleprecision, parameter, public m_units::e_d = 2.718281828459045235360d0
pi
real, parameter, public m_units::pi = 3.141592653589793238462643383279500d0
pi_d
doubleprecision, parameter, public m_units::pi_d = 3.141592653589793238462643383279500d0
radian
real, parameter, public m_units::radian = 57.29577951310d0
radian_d
doubleprecision, parameter, public m_units::radian_d = 57.29577951310d0