GeneralPurposeFortran: m_getopt_long Module Reference
m_getopt_long Module Reference
NAME
M_getopt_long(3fm) - [ARGUMENTS:M_getopt_long] parse command line options like Sun getopt_long, including the Sun CLIP specification
SYNTAX
use M_getopt_long, only : getopt_new, getopt use M_getopt_long, only : getopt_type, getopt_option_type use M_getopt_long, only : getopt_argv
Data Types
type getopt_option_type
type getopt_string_type
type getopt_type
interface warn
Functions/Subroutines
subroutine getopt_new (self, optstring, long_opts, flags, status)
character(len=getopt_argv_len(self, argn)) function getopt_argv (self, argn)
character(len=1) function getopt (self, longindex)
pure integer function getopt_argv_len (self, argn)
subroutine, private warn_string (self, msg, arg)
subroutine, private warn_char_array (self, msg, arg)
subroutine, private permute_args (self)
character(len=1) function, private parse_longopts (self, longindex, short_too)
Variables
integer, parameter max_option_len = 15
character(len=1), parameter getopt_status_badch = '?'
character(len=1), parameter getopt_status_badarg = ':'
character(len=1), parameter getopt_status_inorder = char(1)
character(len=1), parameter getopt_status_end = char(255)
character(len=1), parameter getopt_status_nil = char(0)
integer, parameter getopt_no_arg = 0
integer, parameter getopt_req_arg = 1
integer, parameter getopt_opt_arg = 2
integer, parameter getopt_flag_permute = int(z'01')
integer, parameter getopt_flag_allargs = int(z'02')
integer, parameter getopt_flag_longonly = int(z'04')
integer, parameter getopt_flag_optional_args = int(z'08')
integer, parameter getopt_flag_require_equivalents = int(z'10')
integer, parameter getopt_flag_abbrev = int(z'20')
integer, parameter getopt_flag_w_semicolon = int(z'40')
integer, parameter getopt_flag_plus_dash_start = int(z'80')
integer, parameter getopt_flags_gnu = GETOPT_FLAG_PERMUTE + GETOPT_FLAG_OPTIONAL_ARGS + GETOPT_FLAG_ABBREV + GETOPT_FLAG_W_SEMICOLON + GETOPT_FLAG_PLUS_DASH_START
integer, parameter getopt_flags_posix = GETOPT_FLAG_ABBREV
integer, parameter getopt_flags_default = GETOPT_FLAG_PERMUTE + GETOPT_FLAG_ABBREV + GETOPT_FLAG_PLUS_DASH_START
integer, parameter getopt_flags_long = GETOPT_FLAG_PERMUTE + GETOPT_FLAG_OPTIONAL_ARGS + GETOPT_FLAG_ABBREV + GETOPT_FLAG_W_SEMICOLON + GETOPT_FLAG_PLUS_DASH_START
integer, parameter getopt_flags_long_only = GETOPT_FLAGS_LONG + GETOPT_FLAG_LONGONLY
integer, parameter getopt_flags_sun_clip = GETOPT_FLAG_W_SEMICOLON + GETOPT_FLAG_REQUIRE_EQUIVALENTS
character(len=1), dimension(0), target empty_string_array
Detailed Description
NAME
M_getopt_long(3fm) - [ARGUMENTS:M_getopt_long] parse command line options like Sun getopt_long, including the Sun CLIP specification
SYNTAX
use M_getopt_long, only : getopt_new, getopt use M_getopt_long, only : getopt_type, getopt_option_type use M_getopt_long, only : getopt_argv
DESCRIPTION
This is based on SunOS getopt_long(3), and includes the Sun CLIP specification, which requires matching short and long versions of all options.
Precise getopt functionality is not really desirable. The biggest drawback of getopt is the use of globals. (It was designed a long time ago.) This interface uses OOP with a derived-type data object,
EXAMPLE
Sample program:
program selftest_program use M_getopt_long implicit none character(len=1) :: c integer :: i integer :: digit_optind = 0 type(getopt_type), pointer :: opts
integer :: this_option_optind integer :: option_index character(len=1), parameter :: NIL = char(0)
type(getopt_option_type) :: long_options(6) = (/ & getopt_option_type("add", 1, NULL(), NIL), & getopt_option_type("append", 0, NULL(), NIL), & getopt_option_type("delete", 1, NULL(), NIL), & getopt_option_type("verbose", 0, NULL(), NIL), & getopt_option_type("create", 1, NULL(), 'c'), & getopt_option_type("file", 1, NULL(), NIL) /) character(len=*), parameter :: optstring = "abc:d:012"
call getopt_new(opts,optstring,long_options)
do this_option_optind = merge(optsindex,1,optsindex>0) option_index = 0 c = getopt(opts,option_index) write(*,*)'retval=',c select case(c) case (GETOPT_STATUS_END) exit case (GETOPT_STATUS_NIL) write(*,'(2A)',advance='no') "option ", trim(long_options(option_index)name) if (associated(optsoptarg)) & write(*,'(2A)',advance='no') "with arg ", optsoptarg write(*,*) !newline
case ('0','1','2') if (digit_optind /= 0 .and. digit_optind /= this_option_optind) & write(*,*) "digits occur in two different argv-elements." digit_optind = this_option_optind write(*,*)"option ",c
case ('a','b') write(*,*)"option ",c
case ('c','d') write(*,*)"option ",c," with value '",optsoptarg,'"'
case default write(*,*) "?? getopt returned character code ",ichar(c)," ??"
end select
end do
if (optsindex <= optsargc) then write(*,'(A)',advance='no') "non-option ARGV-elements: " do i=optsindex,optsargc write(*,'(A,1X)',advance='no') getopt_argv(opts,i) end do write(*,*) ! newline end if
stop end program selftest_program
AUTHOR
[[getopt_long_module]] by [[Joe Krahn]].
slightly modified from original - JSU
Function/Subroutine Documentation
getopt()
character(len=1) function m_getopt_long::getopt (type(getopt_type), pointer self, integer, intent(out), optional longindex)
References empty_string_array, false(), getopt_flag_allargs, getopt_flag_longonly, getopt_flag_optional_args, getopt_flag_permute, getopt_flag_w_semicolon, getopt_status_badarg, getopt_status_badch, getopt_status_end, getopt_status_inorder, getopt_status_nil, parse_longopts(), and true().
getopt_argv()
character(len=getopt_argv_len(self,argn)) function m_getopt_long::getopt_argv (type(getopt_type), pointer self, integer, intent(in) argn)
getopt_argv_len()
pure integer function m_getopt_long::getopt_argv_len (type(getopt_type), pointer self, integer, intent(in) argn)
getopt_new()
subroutine m_getopt_long::getopt_new (type(getopt_type), pointer self, character(len=*), intent(in), target optstring, type(getopt_option_type), dimension(:), intent(in), optional, target long_opts, integer, intent(in), optional flags, logical, intent(out), optional status)
References empty_string_array, false(), getopt_flag_allargs, getopt_flag_optional_args, getopt_flag_permute, getopt_flag_plus_dash_start, getopt_flag_require_equivalents, getopt_flags_default, getopt_flags_long, getopt_status_nil, length(), true(), and verify_short_long_equivalents().
parse_longopts()
character(len=1) function, private m_getopt_long::parse_longopts (type(getopt_type), pointer self, integer, intent(inout), optional longindex, logical, intent(in) short_too) private
References getopt_flag_abbrev, getopt_flag_optional_args, getopt_no_arg, getopt_opt_arg, getopt_req_arg, getopt_status_badarg, getopt_status_badch, getopt_status_end, and getopt_status_nil.
permute_args()
subroutine, private m_getopt_long::permute_args (type(getopt_type), pointer self) private
References gcd().
warn_char_array()
subroutine, private m_getopt_long::warn_char_array (type(getopt_type), pointer self, character(len=*), intent(in) msg, character(len=1), dimension(:), intent(in) arg) private
warn_string()
subroutine, private m_getopt_long::warn_string (type(getopt_type), pointer self, character(len=*), intent(in) msg, character(len=*), intent(in) arg) private
Variable Documentation
empty_string_array
character(len=1), dimension(0), target m_getopt_long::empty_string_array
getopt_flag_abbrev
integer, parameter m_getopt_long::getopt_flag_abbrev = int(z'20')
getopt_flag_allargs
integer, parameter m_getopt_long::getopt_flag_allargs = int(z'02')
getopt_flag_longonly
integer, parameter m_getopt_long::getopt_flag_longonly = int(z'04')
getopt_flag_optional_args
integer, parameter m_getopt_long::getopt_flag_optional_args = int(z'08')
getopt_flag_permute
integer, parameter m_getopt_long::getopt_flag_permute = int(z'01')
getopt_flag_plus_dash_start
integer, parameter m_getopt_long::getopt_flag_plus_dash_start = int(z'80')
getopt_flag_require_equivalents
integer, parameter m_getopt_long::getopt_flag_require_equivalents = int(z'10')
getopt_flag_w_semicolon
integer, parameter m_getopt_long::getopt_flag_w_semicolon = int(z'40')
getopt_flags_default
integer, parameter m_getopt_long::getopt_flags_default = GETOPT_FLAG_PERMUTE + GETOPT_FLAG_ABBREV + GETOPT_FLAG_PLUS_DASH_START
getopt_flags_gnu
integer, parameter m_getopt_long::getopt_flags_gnu = GETOPT_FLAG_PERMUTE + GETOPT_FLAG_OPTIONAL_ARGS + GETOPT_FLAG_ABBREV + GETOPT_FLAG_W_SEMICOLON + GETOPT_FLAG_PLUS_DASH_START
getopt_flags_long
integer, parameter m_getopt_long::getopt_flags_long = GETOPT_FLAG_PERMUTE + GETOPT_FLAG_OPTIONAL_ARGS + GETOPT_FLAG_ABBREV + GETOPT_FLAG_W_SEMICOLON + GETOPT_FLAG_PLUS_DASH_START
getopt_flags_long_only
integer, parameter m_getopt_long::getopt_flags_long_only = GETOPT_FLAGS_LONG + GETOPT_FLAG_LONGONLY
getopt_flags_posix
integer, parameter m_getopt_long::getopt_flags_posix = GETOPT_FLAG_ABBREV
getopt_flags_sun_clip
integer, parameter m_getopt_long::getopt_flags_sun_clip = GETOPT_FLAG_W_SEMICOLON + GETOPT_FLAG_REQUIRE_EQUIVALENTS
getopt_no_arg
integer, parameter m_getopt_long::getopt_no_arg = 0
getopt_opt_arg
integer, parameter m_getopt_long::getopt_opt_arg = 2
getopt_req_arg
integer, parameter m_getopt_long::getopt_req_arg = 1
getopt_status_badarg
character(len=1), parameter m_getopt_long::getopt_status_badarg = ':'
getopt_status_badch
character(len=1), parameter m_getopt_long::getopt_status_badch = '?'
getopt_status_end
character(len=1), parameter m_getopt_long::getopt_status_end = char(255)
getopt_status_inorder
character(len=1), parameter m_getopt_long::getopt_status_inorder = char(1)
getopt_status_nil
character(len=1), parameter m_getopt_long::getopt_status_nil = char(0)
max_option_len
integer, parameter m_getopt_long::max_option_len = 15