GeneralPurposeFortran: m_time Module Reference
m_time Module Reference
Functions/Subroutines
subroutine, public date_to_julian (dat, julian, ierr)
NAME
date_to_julian - [M_time] converts DAT date-time array to Julian Date
subroutine, public julian_to_date (julian, dat, ierr)
NAME
julian_to_date - [M_time] converts a JED(Julian Ephemeris Date) to a DAT date-time array.
subroutine, public date_to_unix (dat, unixtime, ierr)
NAME
date_to_unix - [M_time] converts DAT date-time array to Unix Epoch Time
subroutine, public unix_to_date (unixtime, dat, ierr)
NAME
unix_to_date - [M_time] converts Unix Epoch Time to DAT date-time array
integer function, public d2o (dat)
NAME
d2o - [M_time] converts DAT date-time array to Ordinal day
subroutine, public ordinal_to_date (yyyy, ddd, dat)
NAME
ordinal_to_date(3f) - [M_time] when given a valid year and day of the year returns the DAT array for the date
SYNOPSIS
integer function, dimension(8), public o2d (ordinal, year)
NAME
o2d - [M_time] converts Ordinal day to DAT date-time array
character(len=:) function, allocatable, public v2mo (imonth)
NAME
v2mo - [M_time] returns the month name of a Common month number
integer function, dimension(8), public mo2d (month_name)
NAME
mo2d - [M_time] given month name return DAT date-time array for beginning of that month in current year
integer function, public mo2v (month_name)
NAME
mo2v - [M_time] given month name return month number (1-12) of that month
character(len=:) function, allocatable, public now (format)
NAME
now - [M_time] return string representing current time given format
character(len=:) function, allocatable, public fmtdate (values, format)
NAME
fmtdate - [M_time] given DAT date-time array return date as string using specified format
subroutine, public fmtdate_usage (indent)
NAME
fmtdate_usage - [M_time] display macros recognized by fmtdate(3f) and now(3f)
subroutine, public guessdate (datestring, dat, ier)
NAME
guessdate - [M_time] reads in a date, in various formats
subroutine, public dow (values, weekday, day, ierr)
NAME
dow - [M_time] given a date-time array DAT return the day of the week
subroutine, public d2w (dat, iso_year, iso_week, iso_weekday, iso_name)
NAME
d2w - [M_time] calculate iso-8601 Week-numbering year date yyyy-Www-d given DAT date-time array
subroutine, public w2d (iso_year, iso_week, iso_weekday, dat)
NAME
w2d - [M_time] calculate DAT date-time array from iso-8601 Week-numbering year date yyyy-Www-d
subroutine, public box_month (dat, calen)
NAME
box_month - [M_time] create specified month in a character array
real(kind=realtime) function, public d2j (dat)
NAME
d2j - [M_time] given DAT date-time array returns Julian Date
integer function, dimension(8), public j2d (julian)
NAME
j2d - [M_time] given a JED (Julian Ephemeris Date) returns a date-time array DAT.
real(kind=realtime) function, public d2u (dat)
NAME
d2u - [M_time] given DAT date-time array returns Unix Epoch Time (UET starts at 0000 on 1 Jan. 1970, UTC)
integer function, dimension(8), public u2d (unixtime)
NAME
u2d - [M_time] given Unix Epoch Time returns DAT date-time array
integer function get_timezone ()
character(len=:) function, allocatable, public sec2days (seconds, crop)
NAME
sec2days - [M_time] convert seconds to string of form dd-hh:mm:ss
real(kind=realtime) function, public days2sec (str)
NAME
days2sec - [M_time] convert string of form [[-]dd-]hh:mm:ss.nn to seconds
character(len=:) function, allocatable, public phase_of_moon (datin)
NAME
phase_of_moon(3f) - [M_time] return name for phase of moon for given date
SYNOPSIS
integer function, public moon_fullness (datin)
NAME
moon_fullness(3f) - [M_time] return percentage of moon phase from new to full
SYNOPSIS
subroutine, public easter (year, month, day)
NAME
easter(3f) - [M_time] calculate date for Easter given a year
subroutine, public ephemeris (itime, planet, declination_d, declination_m, declination_compass, ascent_hours, ascent_minutes)
NAME
subroutine, public system_sleep (seconds)
NAME
system_sleep - [M_time] call C sleep(3c) or usleep(3c) procedure
SYNOPSIS
subroutine, private call_sleep (wait_seconds)
subroutine, private call_usleep (wait_seconds)
Variables
integer, parameter, public realtime =kind(0.0d0)
real(kind=realtime), parameter, private secday =86400.0d0
real(kind=realtime), parameter, public dt_minute =60.0d0
real(kind=realtime), parameter, public dt_hour =3600.0d0
real(kind=realtime), parameter, public dt_day =86400.0d0
real(kind=realtime), parameter, public dt_week =dt_day*7.0d0
Function/Subroutine Documentation
box_month()
subroutine, public m_time::box_month (integer, dimension(8), intent(in) dat, character(len=wklen), dimension(8) calen)
NAME
box_month - [M_time] create specified month in a character array
SYNOPSIS
subroutine box_month(dat,calen)
 integer,intent(in)    :: dat(8)
 character(len=21)     :: calen(8)
DESCRIPTION
box_month(3f) uses a year and month from a date array to populate a small character array with a calendar representing the month.
OPTIONS
dat "DAT" array (an integer array of the same format as the array returned by the intrinsic DATE_AND_TIME(3f)) describing the date to be used to specify what calendar month to produce.
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
calen returned character array holding a display of the specified month
EXAMPLE
Sample program:
 program demo_box_month
 use M_time, only : box_month
 implicit none
 integer           :: dat(8)
 character(len=21) :: calendar(8)
    call date_and_time(values=dat)
    call box_month(dat,calendar)
    write(*,'(a)')calendar
 end program demo_box_month
results:
  >     July 2016
  >Mo Tu We Th Fr Sa Su
  >             1  2  3
  > 4  5  6  7  8  9 10
  >11 12 13 14 15 16 17
  >18 19 20 21 22 23 24
  >25 26 27 28 29 30 31
References m_strings::adjustc(), date_to_julian(), dow(), julian_to_date(), and v2mo().
call_sleep()
subroutine, private m_time::call_sleep (integer(kind=c_int), intent(in) wait_seconds) private
References only, and use.
call_usleep()
subroutine, private m_time::call_usleep (integer(kind=c_int), intent(in) wait_seconds) private
References only, and use.
d2j()
real(kind=realtime) function, public m_time::d2j (integer, dimension(8), intent(in), optional dat)
NAME
d2j - [M_time] given DAT date-time array returns Julian Date
SYNOPSIS
function d2j(dat) result (julian)
 integer,intent(in)  :: dat(8)
 real(kind=realtime) :: julian
DESCRIPTION
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f). If not present, use current time.
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
julian The Julian Date.
EXAMPLE
Sample program:
 program demo_dj
 use M_time, only : d2j
 implicit none
 integer :: dat(8)
    call date_and_time(values=dat)
    write(*,'(" Today is:",*(i0:,":"))')dat
    write(*,*)'Julian Date is ',d2j(dat)
 end program demo_dj
results:
 Today is:2016:7:19:-240:2:11:50:885
 Julian Date is    2457588.7582278359
References date_to_julian().
d2o()
integer function, public m_time::d2o (integer, dimension(8), intent(in) dat)
NAME
d2o - [M_time] converts DAT date-time array to Ordinal day
SYNOPSIS
function d2o(dat) result (ordinal)
 integer,intent(in) :: dat(8)   ! date time array
 integer            :: ordinal  ! the returned day of the year
DESCRIPTION
Given a date in the form of a "DAT" array return the Ordinal Day, (ie. "the day of the year").
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
ordinal The day of the year calculated for the given input date, where Jan 1st=1.
EXAMPLE
Sample program:
 program demo_d2o
 use M_time, only : d2o, mo2d
 implicit none
 integer :: dat(8)
    call date_and_time(values=dat)
    write(*,'(" Today is:",*(i0:,":"))')dat
    write(*,*)'Day of year is:',d2o(dat)
    ! year, month, day, timezone, hour, minute, seconds, milliseconds
    dat=[2020,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
    dat=[2021,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
    dat=[2022,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
    dat=[2023,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
    dat=[2024,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
 end program demo_d2o
results:
 Today is:2016:7:19:-240:20:1:19:829
 Day of year is:         201
        2020  Days in year is:         366
        2021  Days in year is:         365
        2022  Days in year is:         365
        2023  Days in year is:         365
        2024  Days in year is:         366
References date_to_unix(), secday, and m_debug::stderr().
d2u()
real(kind=realtime) function, public m_time::d2u (integer, dimension(8), intent(in), optional dat)
NAME
d2u - [M_time] given DAT date-time array returns Unix Epoch Time (UET starts at 0000 on 1 Jan. 1970, UTC)
SYNOPSIS
function d2u(dat) result (unixtime)
   integer,intent(in),optional :: dat(8)
   real(kind=realtime)         :: unixtime
DESCRIPTION
Converts a DAT date-time array to a Unix Epoch Time value. Typically mathematical operations such as sums, sorting and comparison are performed with simple UET numeric values, and then they are converted back.
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f). If not present the current time is used
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC.
EXAMPLE
Sample program:
 program demo_du
 use M_time, only : d2u
 implicit none
 integer           :: dat(8)
    call date_and_time(values=dat)
    write(*,'(" Today is:",*(i0:,":"))')dat
    write(*,*)'Unix Epoch time is ',d2u(dat)
 end program demo_du
results:
 Today is:2016:7:19:-240:2:0:48:561
 Unix Epoch time is    1468908048.5610321
References date_to_unix().
d2w()
subroutine, public m_time::d2w (integer, dimension(8), intent(in) dat, integer, intent(out) iso_year, integer, intent(out) iso_week, integer, intent(out) iso_weekday, character(len=10), intent(out) iso_name)
NAME
d2w - [M_time] calculate iso-8601 Week-numbering year date yyyy-Www-d given DAT date-time array
SYNOPSIS
subroutine d2w(dat,iso_year,iso_week,iso_weekday,iso_name)
 integer,intent(in)              :: dat(8)     ! input date array
 integer,intent(out)             :: iso_year, iso_week, iso_weekday
 character(len=10),intent(out)   :: iso_name
DESCRIPTION
Given a "DAT" array defining a date and time, return the ISO-8601 Week in two formats – as three integer values defining the ISO year, week of year and weekday; and as a string of the form "yyyy-Www-d".
OPTIONS
dat "DAT" array (an integer array of the same format as the array returned by the intrinsic DATE_AND_TIME(3f)) describing the date, which is the basic time description used by the other M_time(3fm) module procedures.
RETURNS
iso_year ISO-8601 year number for the given date iso_week ISO-8601 week number for the given date iso_weekday ISO-8601 weekday number for the given date iso_name ISO-8601 Week string for the data in the form "yyyy-Www-d".
EXAMPLE
Sample program:
 program demo_d2w
 use M_time, only : d2w
 implicit none
 integer           :: dat(8)     ! input date array
 integer           :: iso_year, iso_week, iso_weekday
 character(len=10) :: iso_name
    call date_and_time(values=dat)
    call d2w(dat,iso_year,iso_week,iso_weekday,iso_name)
    write(*,'("ISO-8601 Week:   ",a)')iso_name
    write(*,'(a,i0)')'ISO-8601 year    ',iso_year
    write(*,'(a,i0)')'ISO-8601 week    ',iso_week
    write(*,'(a,i0)')'ISO-8601 weekday ',iso_weekday
 end program demo_d2w
results:
 ISO-8601 Week:   2016-W29-1
 ISO-8601 year    2016
 ISO-8601 week    29
 ISO-8601 weekday 1
DEFINITION
The ISO-8601 date and time standard was issued by the International Organization for Standardization (ISO). It is used (mainly) in government and business for fiscal years, as well as in timekeeping. The system specifies a week year atop the Gregorian calendar by defining a notation for ordinal weeks of the year.
An ISO week-numbering year (also called ISO year informally) has 52 or 53 full weeks. That is 364 or 371 days instead of the usual 365 or 366 days. The extra week is referred to here as a leap week, although ISO-8601 does not use this term. Weeks start with Monday. The first week of a year is the week that contains the first Thursday of the year (and, hence, always contains 4 January). ISO week year numbering therefore slightly deviates from the Gregorian for some days close to January 1st.
CALCULATION
The ISO-8601 week number of any date can be calculated, given its ordinal date (i.e. position within the year) and its day of the week.
METHOD
Using ISO weekday numbers (running from 1 for Monday to 7 for Sunday), subtract the weekday from the ordinal date, then add 10. Divide the result by 7. Ignore the remainder; the quotient equals the week number. If the week number thus obtained equals 0, it means that the given date belongs to the preceding (week-based) year. If a week number of 53 is obtained, one must check that the date is not actually in week 1 of the following year.
These two statements are assumed true when correcting the dates around January 1st:
o The number of weeks in a given year is equal to the corresponding week number of 28 December. o January 4th is always in the first week.
ISO_NAME
Week date representations are in the format YYYYWww-D.
o [YYYY] indicates the ISO week-numbering year which is slightly different from the traditional Gregorian calendar year. o [Www] is the week number prefixed by the letter W, from W01 through W53. o [D] is the weekday number, from 1 through 7, beginning with Monday and ending with Sunday.
For example, the Gregorian date 31 December 2006 corresponds to the Sunday of the 52nd week of 2006, and is written
2006-W52-7 (extended form) or 2006W527 (compact form).
REFERENCE
From Wikipedia, the free encyclopedia 2015-12-19
AUTHOR
John S. Urban, 2015-12-19
References uncorrected_week_of_year().
date_to_julian()
subroutine, public m_time::date_to_julian (integer, dimension(8), intent(in) dat, real(kind=realtime), intent(out) julian, integer, intent(out) ierr)
NAME
date_to_julian - [M_time] converts DAT date-time array to Julian Date
SYNOPSIS
subroutine date_to_julian(dat,juliandate,ierr)
 integer,intent(in)               :: dat(8)
 real(kind=realtime),intent(out)  :: juliandate
 integer,intent(out)              :: ierr
DESCRIPTION
Converts a DAT date-time array to a Unix Epoch Time (UET) value. UET is the number of seconds since 00:00 on January 1st, 1970, UTC.
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
juliandate A Julian Ephemeris Date (JED) is the number of days since noon (not midnight) on January 1st, 4713 BC. ierr Error code. If 0 no error occurred.
EXAMPLE
Sample Program:
 program demo_date_to_julian
 use M_time, only : date_to_julian,realtime
 implicit none
 integer             :: dat(8)
 real(kind=realtime) :: juliandate
 integer             :: ierr
    ! generate DAT array
    call date_and_time(values=dat)
    ! show DAT array
    write(*,'(" Today is:",*(i0:,":"))')dat
    ! convert DAT to Julian Date
    call date_to_julian(dat,juliandate,ierr)
    write(*,*)'Julian Date is ',juliandate
    write(*,*)'ierr is ',ierr
 end program demo_date_to_julian
results:
 Today is:2016:7:19:-240:11:3:13:821
 Julian Date is    2457589.1272432986
 ierr is            0
AUTHOR: John S. Urban
VERSION: 1.0 2015-12-21
REFERENCE: From Wikipedia, the free encyclopedia 2015-12-19
date_to_unix()
subroutine, public m_time::date_to_unix (integer, dimension(8), intent(in) dat, real(kind=realtime), intent(out) unixtime, integer, intent(out) ierr)
NAME
date_to_unix - [M_time] converts DAT date-time array to Unix Epoch Time
SYNOPSIS
subroutine date_to_unix(dat,unixtime,ierr)
 integer,intent(in)               :: dat(8)
 real(kind=realtime),intent(out)  :: unixtime
 integer,intent(out)              :: ierr
DESCRIPTION
Converts a DAT date-time array to a UET (Unix Epoch Time).
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC. ierr Error code. If 0 no error occurred.
EXAMPLE
Sample program:
 program demo_date_to_unix
 use M_time, only : date_to_unix, realtime
 implicit none
 integer             :: dat(8)
 real(kind=realtime) :: unixtime
 integer             :: ierr
    call date_and_time(values=dat)
    write(*,'(" Today is:",*(i0:,":"))')dat
    call date_to_unix(dat,unixtime,ierr)
    write(*,*)'Unix Epoch time is ',unixtime
    write(*,*)'ierr is ',ierr
 end program demo_date_to_unix
results:
 Today is:2016:7:18:-240:23:44:20:434
 Unix Epoch time is    1468899860.4340105
 ierr is            0
References date_to_julian(), false(), and secday.
days2sec()
real(kind=realtime) function, public m_time::days2sec (character(len=*), intent(in) str)
NAME
days2sec - [M_time] convert string of form [[-]dd-]hh:mm:ss.nn to seconds
SYNOPSIS
function days2sec(str) result(time)
 character(len=*),intent(in)       :: str
 real(kind=realtime)               :: time
DESCRIPTION
Given a string representing a duration of the form "[-][[[dd-]hh:]mm:]ss" or NNdNNhNNmNNsNNw return a value representing seconds
If "dd-" is present, units for the numbers are assumed to proceed from day to hour to minute to second. But if no day is present, the units are assumed to proceed from second to minutes to hour from left to right. That is ...
[-]dd-hh:mm:ss [-]dd-hh:mm [-]dd-hh
hh:mm:ss mm:ss ss
Where dd is days, hh hours, mm minutes and ss seconds.
A decimal fraction is supported on the seconds (Actually, any of the numeric values may represent positive floating point numbers). Spaces are ignored.
NNdNNhNNmNNs Simple numeric values may also be used with unit suffixes; where s,m,h, or d represents seconds, minutes, hours or days and w represents a week. Allowed aliases for w,d,h,m, and s units are
             d -  days,day
             m -  minutes,minute,min,mins
             h -  hours,hour,hr,hrs
             s -  seconds,second,sec,secs
             w -  week, weeks, wk, wks
The numeric values may represent floating point numbers.
Spaces, commas and case are ignored.
OPTIONS
str string of the general form dd-hh:mm:ss.nn
RETURNS
time the number of seconds represented by the input string
EXAMPLE
Sample program:
 program demo_days2sec
 use M_time, only : days2sec
 implicit none
    write(*,*)days2sec('1-12:04:20')
    write(*,*)'one second ',days2sec('1')
    write(*,*)'one minute ',days2sec('1:00')
    write(*,*)'one hour ',days2sec('1:00:00')
    write(*,*)'one day ',days2sec('1-00:00:00')
    write(*,*)nint(days2sec(' 1-12:04:20              ')) .eq. 129860
    write(*,*)nint(days2sec(' 1.5 days                ')) .eq. 129600
    write(*,*)nint(days2sec(' 1.5 days 4hrs 30minutes ')) .eq. 145800
    write(*,*)nint(days2sec(' 1.5d                    ')) .eq. 129600
    write(*,*)nint(days2sec(' 1d2h3m4s                ')) .eq. 93784
    ! duplicates
    write(*,*)nint(days2sec(' 1d1d1d                  ')) .eq. 259200
    ! negative values
    write(*,*)nint(days2sec(' 4d-12h                  ')) .eq. 302400
 end program demo_days2sec
Results:
 129860.00000000000
 one second    1.0000000000000000
 one minute    60.000000000000000
 one hour    3600.0000000000000
 one day    86400.000000000000
 T
 T
 T
 T
 T
 T
 T
References m_strings::compact(), false(), m_strings::s2v(), m_strings::split(), m_strings::transliterate(), and true().
dow()
subroutine, public m_time::dow (integer, dimension(8), intent(in) values, integer, intent(out), optional weekday, character(len=*), intent(out), optional day, integer, intent(out), optional ierr)
NAME
dow - [M_time] given a date-time array DAT return the day of the week
SYNOPSIS
subroutine dow(values, weekday, day, ierr)
 integer,intent(in) :: values(8)
 integer,intent(out),optional :: weekday
 character(len=*),intent(out),optional :: day
 integer,intent(out),optional :: ierr
DESCRIPTION
Given a date array DAT return the day of the week as a number and a name, Mon=1.
OPTIONS
values "DAT" array (an integer array of the same format as the array returned by the intrinsic DATE_AND_TIME(3f)) describing the date to be used to calculate the day of the week.
RETURNS
weekday The numeric day of the week, starting with Monday=1. Optional. day The name of the day of the week. Optional. ierr Error code
     o [ 0] correct
     o [-1] invalid input date
     o [-2] neither day nor weekday return values specified
     If the error code is not returned and an error occurs,
     the program is stopped.
EXAMPLE
Sample program:
 program demo_dow
 use M_time, only : dow
 implicit none
 integer          :: dat(8)     ! input date array
 integer          :: weekday
 character(len=9) :: day
 integer          :: ierr
   call date_and_time(values=dat)
   call dow(dat, weekday, day, ierr)
   write(*,'(a,i0)')'weekday=',weekday
   write(*,'(a,a)')'day=',trim(day)
   write(*,'(a,i0)')'ierr=',ierr
 end program demo_dow
results:
 weekday=1
 day=Monday
 ierr=0
References date_to_julian().
easter()
subroutine, public m_time::easter (integer, intent(in) year, integer, intent(out) month, integer, intent(out) day)
NAME
easter(3f) - [M_time] calculate date for Easter given a year
SYNOPSIS
subroutine easter(year,month,day)
integer, intent(in) :: year integer, intent(out) :: day, month
DESCRIPTION
The Date of Easter (Sunday)
The algorithm is due to J.-M. Oudin (1940) and is reprinted in the Explanatory Supplement to the Astronomical Almanac, ed. P. K. Seidelmann (1992). See Chapter 12, "Calendars", by L. E. Doggett.
The following are dates of Easter from 1980 to 2024:
1980 April 6 1995 April 16 2010 April 4 1981 April 19 1996 April 7 2011 April 24 1982 April 11 1997 March 30 2012 April 8 1983 April 3 1998 April 12 2013 March 31 1984 April 22 1999 April 4 2014 April 20 1985 April 7 2000 April 23 2015 April 5 1986 March 30 2001 April 15 2016 March 27 1987 April 19 2002 March 31 2017 April 16 1988 April 3 2003 April 20 2018 April 1 1989 March 26 2004 April 11 2019 April 21 1990 April 15 2005 March 27 2020 April 12 1991 March 31 2006 April 16 2021 April 4 1992 April 19 2007 April 8 2022 April 17 1993 April 11 2008 March 23 2023 April 9 1994 April 3 2009 April 12 2024 March 31
N.B. The date of Easter for the Eastern Orthodox Church may be different.
OPTIONS
year Year for which to calculate day that Easter falls on
RESULTS
month Month on which Easter falls for a given year day Day of month on which Easter falls for a given year
EXAMPLE
Sample program:
program demo_easter use m_time, only : easter, fmtdate implicit none integer :: year, month, day integer :: dat(8) ! year,month,day,tz,hour,minute,second,millisecond call date_and_time(values=dat) ! get current year year=dat(1) call easter(year, month, day) ! fill out a date_and_time array dat=[dat(1),month,day,dat(4),12,0,0,0] write(*,*)fmtdate(dat,& "Easter day: the %d day of %L in the year of our Lord %Y") end program demo_easter
Sample output:
Easter day: the 16th day of April in the year of our Lord 2017 U.S. Naval Observatory Astronomical Applications Department
This code assembled by Alan Miller Reference web site: http://aa.usno.navy.mil/faq/docs/easter.html Latest revision 8 April 2002
ephemeris()
subroutine, public m_time::ephemeris (integer, dimension(8), intent(in) itime, class(*), intent(in) planet, integer, intent(out) declination_d, integer, intent(out) declination_m, character(len=1), intent(out) declination_compass, integer, intent(out) ascent_hours, integer, intent(out) ascent_minutes)
NAME
ephemeris(3f) - [M_time] ephemeris position of planets for adjusting an equatorial telescope
SYNOPSIS
subroutine ephemeris(itime,planet,declination_,declination_m,declination_compass,ascent_hours,ascent_minutes)
 integer,parameter            :: dp=kind(0.0d0)
 integer,intent(in)           :: itime(8)
 class(*),intent(in)          :: planet
  !!integer                   :: planet
  !!character(len=*)          :: planet
 integer,intent(out)          :: declination_d, declination_m
 character(len=1),intent(out) :: declination_compass
 integer,intent(out)          :: ascent_hours,ascent_minutes
DESCRIPTION
ephemeris(3f) calculates the ephemeris of a planet in our solar system
in order to adjust an equatorial telescope.
 Ref.: "Mathematiques par l'informatique individuelle
       - Programmes en BASIC, MASSON,
       Paris, 1982, p 100 - 105" [BIBLI 06].
OPTIONS
  itime   provide the date and time using the same eight values used
          by the DATE_AND_TIME(3f) intrinsic.
          1. The year
          2. The month
          3. The day of the month
          4. Time difference with UTC in minutes
          5. The hour of the day
          6. The minutes of the hour
          7. The seconds of the minute
          8. The milliseconds of the second
  planet  Planet number  1 to 8  or planet name (Mercury:1 Venus:2
          Mars:4 Jupiter:5 Saturn:6 Uranus:7 Neptune:8)
RESULTS
declination_d,        :
declination_m,        :
declination_compass   Declination in degrees and minutes (-90 to 90 North or South)
ascent_hours,         :
ascent_minutes        Ascent in hours (0 to 24) and minutes
EXAMPLE
Find ascent and declination of planet Mars on March 10th, 1982 at 6h UT
  program demo_ephemeris
  use M_time, only : ephemeris, fmtdate
  integer,parameter   :: dp=kind(0.0d0)
  integer             :: itime(8)
  class(*),intent(in) :: planet
  integer            :: declination_d, declination_m
  character(len=1)   :: declination_compass
  integer            :: ascent_hours, ascent_minutes
  planet=4
  itime=[1982,3,10,0,6,0,0,0]
  call ephemeris(itime, planet,                    &
  declination_d,declination_m,declination_compass, &
  ascent_hours,ascent_minutes)
  write(*, '(" For: ",a)')fmtdate(itime)
  write(*, "(' Planet: ',I1,1X)",advance='no')                       &
          planet
  write(*, "(' Ascent: ',I2,' H ',I2,' MN',1X)",advance='no')        &
          ascent_hours, ascent_minutes
  write(*, "(' Declination: ',I2,' D ',I2,' MN ',A1)",advance='yes') &
          declination_d, declination_m, declination_compass
  end program demo_ephemeris
Expected output:
  For: Wednesday, March 10th, 1982 6:00:00 AM UTC+00:00
  Planet: 4  Ascent: 13 H  8 MN  Declination:  3 D 45 MN S
AUTHOR
o F90 Version By J-P Moreau, Paris. (www.jpmoreau.fr)
o Revised By John S. Urban, 20170910
References m_strings::lower(), and planet_coordinates().
fmtdate()
character(len=:) function, allocatable, public m_time::fmtdate (integer, dimension(8), intent(in) values, character(len=*), intent(in), optional format)
NAME
fmtdate - [M_time] given DAT date-time array return date as string using specified format
SYNOPSIS
function fmtdate(values,format) RESULT (timestr)
 integer,dimension(8),intent(in)      :: values
 character(len=*),intent(in),optional :: format
 character(len=:),allocatable         :: timestr
DESCRIPTION
The fmtdate(3f) procedure lets you reformat a DAT array in many common formats using a special string containing macro names beginning with ''. To see the allowable macros call or see the fmtdate_usage(3f) routine.
OPTIONS
values date in a "DAT" array, which is the same format as the values returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
format string describing how to format the "DAT" array. For a complete description of the formatting macros supported see fmtdate_usage(3f).
RETURNS
timestr formatted output string representing date
EXAMPLE
Sample program:
 program demo_fmtdate
 use M_time, only : fmtdate
 implicit none
 integer :: dat(8)
    call date_and_time(values=dat)
    write(*,*)fmtdate(dat,"current date: %w, %l %d, %Y %H:%m:%s %N")
    call showme()
 contains
 subroutine showme()
    use M_time, only : fmtdate_usage
    call fmtdate_usage() ! see all formatting options
 end subroutine showme
 end program demo_fmtdate
results:
   The current date is Sun, Jul 17th, 2016 01:21:35 PM
    ::
    :: An up-to-date description of all the
    :: formatting options will appear here
    ::
AUTHOR
John S. Urban, 2015-12-19
References d2o(), d2w(), date_to_julian(), date_to_unix(), dow(), easter(), false(), moon_fullness(), phase_of_moon(), m_strings::substitute(), true(), and v2mo().
fmtdate_usage()
subroutine, public m_time::fmtdate_usage (integer, intent(in), optional indent)
NAME
fmtdate_usage - [M_time] display macros recognized by fmtdate(3f) and now(3f)
SYNOPSIS
subroutine fmtdate_usage(indent)
 integer,intent(in),optional      :: indent
DESCRIPTION
 The fmtdate_usage(3f) subroutine displays the formatting options
 available for use in procedures such as fmtdate(3f) and now(3f).
 It is typically used to produce up-to-date help text in commands
 that use the M_time(3fm) module, so that the formatting information
 only needs maintained in one place (this routine) and is easily
 displayed so users can quickly obtain a description of the formatting
 macros.
OPTIONS
indent how many spaces to prefix the output with, so that calling programs can position the output. Default for this optional parameter is three (3).
EXAMPLE
Sample Program:
 program demo_fmtdate_usage
 use M_time, only : fmtdate_usage
 implicit none
    call fmtdate_usage() ! see all formatting options
 end program demo_fmtdate_usage
results (actually call the routine to ensure this is up to date):
 Description                                        Example
 Base time array:
 (1) %Y -- year, yyyy                                2016
 (2) %M -- month of year, 01 to 12                   07
 (3) %D -- day of month, 01 to 31                    29
     %d -- day of month, with suffix (1st, 2nd,...)  29th
 (4) %Z -- minutes from UTC                          -0240
     %z -- -+hh:mm from UTC                          -04:00
     %T -- -+hhmm  from UTC                          -0400
 (5) %h -- hours, 00 to 23                           10
     %H -- hour (1 to 12, or twelve-hour clock)      10
     %N -- midnight< AM <=noon; noon<= PM <midnight  AM
 (6) %m -- minutes, 00 to 59                         54
 (7) %s -- sec, 00 to 59                             08
 (8) %x -- milliseconds 000 to 999                   521
 Conversions:
     %E -- Unix Epoch time                           1469804048.5220029
     %e -- integer value of Unix Epoch time          1469804049
     %J -- Julian  date                              2457599.121
     %j -- integer value of Julian Date(Julian Day)  2457599
     %O -- Ordinal day (day of year)                 211
     %o -- Whole days since Unix Epoch date          17011
     %U -- day of week, 1..7 Sunday=1                6
     %u -- day of week, 1..7 Monday=1                5
     %i -- ISO week of year 1..53                    30
     %I -- iso-8601 week-numbering date(yyyy-Www-d)  2016-W30-5
  Names:
     %l -- abbreviated month name                    Jul
     %L -- full month name                           July
     %w -- first three characters of weekday         Fri
     %W -- weekday name                              Friday
     %p -- phase of moon                             New
     %P -- percent of way from new to full moon      -1%
  Literals:
     %% -- a literal %                               %
     %t -- tab character
     %b -- blank character
     %B -- exclamation(bang) character
     %n -- new line (system dependent)
     %q -- single quote (apostrophe)
     %Q -- double quote
  Program timing:
     %c -- CPU_TIME(3f) output                       .21875000000000000
     %C -- number of times this routine is used      1
     %S -- seconds since last use of this format     .0000000000000000
     %k -- time in seconds from SYSTEM_CLOCK(3f)     723258.812
If no percent (%) is found in the format one of several
alternate substitutions occurs.
If the format is composed entirely of one of the following
keywords the following substitutions occur:
  "iso-8601",
  "iso"        ==> %Y-%M-%DT%h:%m:%s%z
  "iso-8601W",
  "isoweek"    ==> %I 2016-W30-5
  "sql"        ==> "%Y-%M-%D %h:%m:%s.%x"
  "sqlday"     ==> "%Y-%M-%D"
  "sqltime"    ==> "%h:%m:%s.%x"
  "rfc-2822"   ==> %w, %D %l %Y %h:%m:%s %T
  "rfc-3339"   ==> %Y-%M-%DT%h:%m:%s%z
  "date"       ==> %w %l %D %h:%m:%s UTC%z %Y
  "short"      ==> %w, %l %d, %Y %H:%m:%s %N UTC%z
  "long"," "   ==> %W, %L %d, %Y %H:%m:%s %N UTC%z
  "suffix"     ==> %Y%D%M%h%m%s
  "formal"     ==> The %d of %L %Y
  "lord"       ==> the %d day of %L in the year of our Lord %Y
  "easter"     ==> FOR THE YEAR OF THE CURRENT DATE:
                   Easter day: the %d day of %L in the year of our Lord %Y
  "all"        ==> A SAMPLE OF DATE FORMATS
otherwise the following words are replaced with the most
common macros:
   year     %Y  2016
   month    %M  07
   day      %D  29
   hour     %h  10
   minute   %m  54
   second   %s  08
   epoch    %e  1469804049
   julian   %j  2457599
   ordinal  %O  211
   weekday  %u  5
if none of these keywords are found then every letter that
is a macro is assumed to have an implied percent in front
of it. For example:
   YMDhms ==> %Y%M%D%h%m%s ==> 20160729105408
References now().
get_timezone()
integer function m_time::get_timezone () private
guessdate()
subroutine, public m_time::guessdate (character(len=*), intent(in) datestring, integer, dimension(8), intent(out) dat, integer, optional ier)
NAME
guessdate - [M_time] reads in a date, in various formats
SYNOPSIS
subroutine guessdate(anot,dat)
 character(len=*),intent(in) :: anot
 integer,intent(out)         :: dat(8)
DESCRIPTION
Read in strings and except for looking for month names remove
non-numeric characters and try to convert a string assumed to represent
a date to a date-time array.
Years should always be expressed as four-digit numbers, and except for
the special format yyyy-mm-dd the day should come after the year. Named
months are preferred. If ambiguous the order is assumed to be day -
month - year. Times are assumed to be of the form HH:MM:SS
It is planned that this routine will be superseded. As an alternative,
a C routine exists in the standard C libraries that allows for
expansive features when reading dates that can be called via the
ISO_C_BINDING interface.
OPTIONS
anot A string assumed to represent a date including a year, month and day.
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
EXAMPLE
Sample program:
 program demo_guessdate
 use M_time, only : guessdate, fmtdate
 implicit none
 character(len=20),allocatable :: datestrings(:)
 character(len=:),allocatable  :: answer
 integer                       :: dat(8)
 integer                       :: i
    datestrings=[ &
    & 'January 9th, 2001   ',&
    & ' Tue Jul 19 2016    ',&
    & ' 21/12/2016         ',&
    & ' 4th of Jul 2004    ' ]
    do i=1,size(datestrings)
       write(*,'(a)')repeat('-',80)
       write(*,*)'TRYING ',datestrings(i)
       call guessdate(datestrings(i),dat)
       write(*,*)'DAT ARRAY ',dat
       answer=fmtdate(dat)
       write(*,*)'FOR '//datestrings(i)//' GOT '//trim(answer)
    enddo
 end program demo_guessdate
results:
 ---------------------------------------------------------------------
 TRYING January 9th, 2001
 DAT ARRAY         2001  1  9   -240    0   0   0    0
 FOR January 9th, 2001    GOT Tuesday, January 9th, 2001 12:00:00 AM
 ---------------------------------------------------------------------
 TRYING  Tue Jul 19 2016
 DAT ARRAY         2016  7  19  -240    0   0   0    0
 FOR  Tue Jul 19 2016     GOT Tuesday, July 19th, 2016 12:00:00 AM
 ---------------------------------------------------------------------
 TRYING  21/12/2016
 DAT ARRAY         2016  12 21  -240    0   0   0    0
 FOR  21/12/2016          GOT Wednesday, December 21st, 2016 12:00:00 AM
 ---------------------------------------------------------------------
 TRYING  4th of Jul 2004
 DAT ARRAY         2004  7  4   -240    0   0   0    0
 FOR  4th of Jul 2004     GOT Sunday, July 4th, 2004 12:00:00 AM
AUTHOR
JRH 1991-03-19
References false(), m_strings::s2v(), m_strings::split(), m_strings::string_to_values(), and true().
j2d()
integer function, dimension(8), public m_time::j2d (real(kind=realtime), intent(in) julian)
NAME
j2d - [M_time] given a JED (Julian Ephemeris Date) returns a date-time array DAT.
SYNOPSIS
function j2d(julian) result (dat)
 real(kind=realtime),intent(in),optional :: julian
 integer                                 :: dat(8)
DESCRIPTION
 Converts a Julian Ephemeris Date to a DAT date-time array.
OPTIONS
julian A Julian Ephemeris Date (JED) is the number of days since noon (not midnight) on January 1st, 4713 BC. If not present, use current time.
RETURNS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
EXAMPLE
Sample program:
 program demo_jd
 use M_time, only : j2d, d2j, fmtdate, realtime
 implicit none
 real(kind=realtime) :: today
 integer :: dat(8)
    call date_and_time(values=dat) ! get the date using intrinsic
    today=d2j(dat)                  ! convert today to Julian Date
    write(*,*)'Today=',fmtdate(j2d(today))
    ! math is easy with Julian Days and Julian Dates
    write(*,*)'Yesterday=',fmtdate(j2d(today-1.0d0))
    write(*,*)'Tomorrow=',fmtdate(j2d(today+1.0d0))
 end program demo_jd
results:
 Today=Tuesday, July 19th, 2016 08:48:20 AM
 Yesterday=Monday, July 18th, 2016 08:48:20 AM
 Tomorrow=Wednesday, July 20th, 2016 08:48:20 AM
References julian_to_date().
julian_to_date()
subroutine, public m_time::julian_to_date (real(kind=realtime), intent(in) julian, integer, dimension(8), intent(out) dat, integer, intent(out) ierr)
NAME
julian_to_date - [M_time] converts a JED(Julian Ephemeris Date) to a DAT date-time array.
SYNOPSIS
subroutine julian_to_date(julian,dat,ierr)
 real(kind=realtime),intent(in) :: julian
 integer,intent(out)            :: dat(8)
 integer,intent(out)            :: ierr
DESCRIPTION
Converts a Unix Epoch Time (UET) value to a DAT date-time array. UET is the number of seconds since 00:00 on January 1st, 1970, UTC.
OPTIONS
julian Julian Date (days) dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f). ier 0 for successful execution
      dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC. ierr Error code. If 0 no error occurred.
EXAMPLE
Sample program:
 program demo_julian_to_date
 use M_time, only : julian_to_date, fmtdate, realtime
 implicit none
 real(kind=realtime)     :: juliandate
 integer                 :: dat(8)
 integer                 :: ierr
    ! set sample Julian Date
    juliandate=2457589.129d0
    ! create DAT array for this date
    call julian_to_date(juliandate,dat,ierr)
    write(*,*)'Sample Date=',fmtdate(dat)
    ! go back one day
    call julian_to_date(juliandate-1.0d0,dat,ierr)
    write(*,*)'Day Before =',fmtdate(dat)
    ! go forward one day
    call julian_to_date(juliandate+1.0d0,dat,ierr)
    write(*,*)'Day After  =',fmtdate(dat)
 end program demo_julian_to_date
results:
 Sample Date=Tuesday, July 19th, 2016 02:00:00 PM
 Day Before =Monday, July 18th, 2016 02:00:00 PM
 Day After  =Wednesday, July 20th, 2016 02:00:00 PM
References get_timezone(), idint(), and secday.
mo2d()
integer function, dimension(8), public m_time::mo2d (character(len=*), intent(in) month_name)
NAME
mo2d - [M_time] given month name return DAT date-time array for beginning of that month in current year
SYNOPSIS
   function mo2d(month_name) result (dat)
    character(len=*),intent(in) :: month_name
    integer                     :: dat(8)
DESCRIPTION
Given a Common Calendar month name, return the date as a "DAT" array in the current year, for the 1st day of the month.
OPTIONS
month_name A string representing a Common Calendar month name.
RETURNS
dat An integer array that has the same structure as the array returned by the Fortran intrinsic DATE_AND_TIME(3f).
EXAMPLE
Sample program:
 program demo_mo2d
 use M_time, only : mo2d
 implicit none
    write(*,'(*(i0:,":"))')mo2d('March')
 end program demo_mo2d
results:
   2016:3:1:-240:0:0:0:0
References mo2v(), and m_debug::stderr().
mo2v()
integer function, public m_time::mo2v (character(len=*), intent(in) month_name)
NAME
mo2v - [M_time] given month name return month number (1-12) of that month
SYNOPSIS
function mo2v(month_name) result(imonth)
  character(len=*),intent(in):: month_name ! month name
  integer                    :: imonth     ! month number
DESCRIPTION
Given a string representing the name or abbreviation of a Gregorian Calendar month return a number representing the position of the month in the calendar starting with 1 for January and ending with 12 for December.
OPTIONS
month_name name or abbreviation of month. Case is ignored Once enough characters are found to uniquely identify a month the rest of the name is ignored.
RETURNS
imonth month number returned. If the name is not recognized a -1 is returned.
EXAMPLE
Sample program:
 program demo_mo2v
 use M_time, only : mo2v
 implicit none
    write(*,*)mo2v("April")
    write(*,*)mo2v('Apr')
    ! NOTE: still matches September, as "SE" was enough
    write(*,*)mo2v('sexember')
    write(*,*)mo2v('unknown')  ! returns -1
 end program demo_mo2v
results:
   >  4
   >  4
   >  9
   > -1
References m_strings::upper().
moon_fullness()
integer function, public m_time::moon_fullness (integer, dimension(8), intent(in) datin)
NAME
moon_fullness(3f) - [M_time] return percentage of moon phase from new to full
SYNOPSIS
function moon_fullness(datin)
integer,intent(in) :: datin(8) integer :: moon_fullness
DESCRIPTION
This is a private procedure used to support the P field descriptor for the fmtdate(3f) routine.
The moon circles the earth every 29.530588853 days on average, so pick a starting point and count. A new moon occurred at January 6, 2000, 18:14 UTC. Then it is easy to count the number of days since the last new moon. This is an approximate calculation.
OPTIONS
dat DAT Date array describing input date
RESULTS
moon_fullness 0 is a new or dark moon, 100 is a full moon, + for waxing and - for waning.
References d2j.
now()
character(len=:) function, allocatable, public m_time::now (character(len=*), intent(in), optional format)
NAME
now - [M_time] return string representing current time given format
SYNOPSIS
function now(format) RESULT (timestr)
 character(len=*),intent(in)     :: format  ! input format string
 character(len=:),allocatable    :: timestr ! formatted date
DESCRIPTION
The now(3f) function is a call to the fmtdate(3f) function using the current date and time. That is, it is a convenient way to print the current date and time.
OPTIONS
format string describing how to format the current date and time. For a complete description of the formatting macros supported see fmtdate_usage(3f).
RETURNS
timestr formatted output string representing date
EXAMPLE
Sample Program:
 program demo_now
 use M_time, only : now
 implicit none
    write(*,*)now("The current date is %w, %l %d, %Y %H:%m:%s %N")
 contains
 subroutine showme() ! see all formatting options
    use M_time, only : fmtdate_usage
    call fmtdate_usage() ! see all formatting options
 end subroutine showme
 end program demo_now
results:
   The current date is Sun, Jul 17th, 2016 01:21:35 PM
    ::
    :: description of all formatting options will appear here
    ::
References fmtdate.
o2d()
integer function, dimension(8), public m_time::o2d (integer, intent(in) ordinal, integer, optional year)
NAME
o2d - [M_time] converts Ordinal day to DAT date-time array
SYNOPSIS
function o2d(ordinal,[year]) result (dat)
 integer,intent(in) :: ordinal  ! the day of the year
 integer,optional   :: year     ! year
 integer            :: dat(8)   ! date time array
DESCRIPTION
Given an Ordinal day of the year return a date in the form of a "DAT" array.
OPTIONS
ordinal The day of the year for the given year, where Jan 1st=1.
year An optional year for the ordinal day. If not present the current year is assumed.
RETURNS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f). The timezone value is from the current time on the current platform.
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
EXAMPLE
Sample program:
 program demo_o2d
 use M_time, only : o2d,fmtdate
 implicit none
 integer :: year
    do year=2004,2008
       write(*,*)'100th day of ',year,' is ',fmtdate(o2d(100,year))
    enddo
    write(*,*)'100th day of this year is ',fmtdate(o2d(100))
 end program demo_o2d
results:
 100th day of 2004 is Friday, April 9th, 2004 00:00:00 PM UTC-02:40
 100th day of 2005 is Sunday, April 10th, 2005 00:00:00 PM UTC-02:40
 100th day of 2006 is Monday, April 10th, 2006 00:00:00 PM UTC-02:40
 100th day of 2007 is Tuesday, April 10th, 2007 00:00:00 PM UTC-02:40
 100th day of 2008 is Wednesday, April 9th, 2008 00:00:00 PM UTC-02:40
 100th day of this year is Saturday, April 9th, 2016 00:00:00 PM UTC-02:40
References date_to_unix(), get_timezone(), m_debug::stderr(), and u2d.
ordinal_to_date()
subroutine, public m_time::ordinal_to_date (integer, intent(in) yyyy, integer, intent(in) ddd, integer, dimension(8), intent(out) dat)
NAME
ordinal_to_date(3f) - [M_time] when given a valid year and day of the year returns the DAT array for the date
SYNOPSIS
subroutine ordinal_to_date(yyyy, ddd, dat)
integer, intent(in) :: yyyy integer, intent(in) :: ddd integer, intent(out) :: dat
DESCRIPTION
When given a valid year, YYYY, and day of the year, DDD, returns the date as a DAT date array
OPTIONS
yyyy known year ddd known ordinal day of the year
RETURNS
dat DAT array describing the date
EXAMPLE
Sample program:
program demo_datesub use m_time, only : ordinal_to_date implicit none INTEGER :: yyyy, ddd, mm, dd integer :: dat(8) integer :: ios
INFINITE: do write(*,'(a)',advance='no')'Enter year YYYY and ordinal day of year DD ' read(*,*,iostat=ios)yyyy,ddd if(ios.ne.0)exit INFINITE ! recover month and day from year and day number. call ordinal_to_date(yyyy, ddd, dat) mm=dat(2) dd=dat(3) enddo INFINITE
end program demo_datesub
REFERENCE
See ACM algorithm 398, Tableless Date Conversion, by Dick Stone, CACM 13(10):621.
phase_of_moon()
character(len=:) function, allocatable, public m_time::phase_of_moon (integer, dimension(8), intent(in) datin)
NAME
phase_of_moon(3f) - [M_time] return name for phase of moon for given date
SYNOPSIS
function phase_of_moon(datin)
integer,intent(in) :: datin(8) character(len=:),allocatable :: phase_of_moon
DESCRIPTION
Phases Of The Moon
This is a private procedure used to support the p field descriptor for the fmtdate(3f) routine.
The moon circles the earth every 29.530588853 days on average, so pick a starting point and count. A new moon occurred at Julian date 2451550.1 (January 6, 2000, 18:14 UTC). Then it is easy to count the number of days since the last new moon. This is an approximate calculation.
There are eight generally recognized phases of the moon in common use
o new or dark o waxing crescent o first quarter o waxing gibbous o full o waning gibbous o laster quarter o waning crescent
To calculate the phase of the moon simply divide the days since the last new moon by eight and select the appropriate phase.
Note that technically the four states (new, first quarter, full, third quarter) are events not phases. That is to say, the moon is technically only new for an instant.
References d2j.
sec2days()
character(len=:) function, allocatable, public m_time::sec2days (class(*), intent(in) seconds, logical, intent(in), optional crop)
NAME
sec2days - [M_time] convert seconds to string of form dd-hh:mm:ss
SYNOPSIS
function sec2days(seconds,crop) result(dhms)
 real(kind=realtime),intent(in) :: seconds
   or
 integer,intent(in)             :: seconds
   or
 real,intent(in)                :: seconds
   or
 character(len=*)               :: seconds
 logical,intent(in),optional    :: crop
 character(len=:),allocatable   :: dhms
DESCRIPTION
Given a number of seconds convert it to a string of the form
dd-hh:mm:ss
where dd is days, hh hours, mm minutes and ss seconds.
OPTIONS
seconds number of seconds to convert to string of form dd-hh:mm:ss. May be of type INTEGER, REAL, REAL(KIND=REALTIME), or CHARACTER.
CHARACTER strings may be of the form NNdNNhNNmNNs. Case,spaces and underscores are ignored. Allowed aliases for d,h,m, and s units are
d -  days,day
m -  minutes,minute,min
h -  hours,hour,hrs,hr
s -  seconds,second,sec
The numeric values may represent floating point numbers.
crop if .true., remove leading zero day values or day and hour values. Optional, defaults to .false. .
RETURNS
dmhs the returned string of form [d:h:]m:s
EXAMPLE
Sample Program:
 program demo_sec2days
 use M_time, only : sec2days
 implicit none
    write(*,*)sec2days(129860)
    write(*,*)sec2days(80000.0d0)
    write(*,*)sec2days(80000.0,crop=.true.)
    write(*,*)sec2days('1 day 2.0hr 100 min 300.0seconds')
 end program demo_sec2days
results:
 1-12:04:20
 0-22:13:20
 22:13:20
 1-03:45:00
References m_strings::compact(), false(), real, m_strings::s2v(), m_strings::split(), m_strings::transliterate(), and true().
system_sleep()
subroutine, public m_time::system_sleep (class(*), intent(in) seconds)
NAME
system_sleep - [M_time] call C sleep(3c) or usleep(3c) procedure
SYNOPSIS
subroutine system_sleep(wait_seconds)
integer,intent(in) :: wait_seconds or real,intent(in) :: wait_seconds
DESCRIPTION
The system_sleep(3f) routine uses the intrinsic ISO_C_BINDING interface to call the C sleep(3c) procedure or usleep(3c) routine.
OPTIONS
wait_seconds integer,real or doubleprecision number of seconds for process to sleep.
EXAMPLE
Sample program:
 program demo_system_sleep
 use M_time, only : system_sleep, now
 implicit none
 integer :: i
    !
    write(*,*)"Time before integer call is: ",now()
    call system_sleep(4)
    write(*,*)"Time after  integer call is: ",now()
    !
    write(*,*)"Time before real call is: ",now()
    call system_sleep(4.0)
    write(*,*)"Time after  real call is: ",now()
    !
    write(*,*)"Time before loop is: ",now()
    do i=1,1000
       call system_sleep(4.0/1000.0)
    enddo
    write(*,*)"Time after loop  is: ",now()
    !
 end program demo_system_sleep
results
 Time before integer call is: Sunday, July 17th, 2016 2:29:45 AM UTC-0240
 Time after integer call is: Sunday, July 17th, 2016 2:29:49 AM UTC-0240
 Time before real call is: Sunday, July 17th, 2016 2:29:49 AM UTC-0240
 Time after  real call is: Sunday, July 17th, 2016 2:29:53 AM UTC-0240
 Time before loop is: Sunday, July 17th, 2016 2:29:53 AM UTC-0240
 Time after loop  is: Sunday, July 17th, 2016 2:30:09 AM UTC-0240
References call_sleep(), call_usleep(), only, real, and use.
u2d()
integer function, dimension(8), public m_time::u2d (class(*), intent(in), optional unixtime)
NAME
u2d - [M_time] given Unix Epoch Time returns DAT date-time array
SYNOPSIS
function u2d(unixtime) result (dat)
 class(*),intent(in),optional      :: unixtime
 ! integer
 ! real
 ! real(kind=realtime)
 integer                           :: dat(8)
DESCRIPTION
OPTIONS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC. If not present, use current time.
RETURNS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
EXAMPLE
Sample program:
 program demo_ud
 use M_time, only : u2d, d2u, fmtdate, realtime
 implicit none
 real(kind=realtime) :: today
 integer :: dat(8)
    call date_and_time(values=dat) ! get the date using intrinsic
    today=d2u(dat)                 ! convert today to Julian Date
    write(*,*)'Today=',fmtdate(u2d(today))
    write(*,*)'Yesterday=',fmtdate(u2d(today-86400.0d0)) ! subtract day
    write(*,*)'Tomorrow=',fmtdate(u2d(today+86400.0d0))  ! add day
 end program demo_ud
results:
 Today=Tuesday, July 19th, 2016 11:10:08 AM
 Yesterday=Monday, July 18th, 2016 11:10:08 AM
 Tomorrow=Wednesday, July 20th, 2016 11:10:08 AM
References d2u, real, and unix_to_date().
unix_to_date()
subroutine, public m_time::unix_to_date (class(*), intent(in) unixtime, integer, dimension(8), intent(out) dat, integer, intent(out) ierr)
NAME
unix_to_date - [M_time] converts Unix Epoch Time to DAT date-time array
SYNOPSIS
subroutine unix_to_date(unixtime,dat,ierr)
 real(kind=realtime),intent(in) :: unixtime ! Unix time (seconds)
 integer,intent(out)            :: dat(8)   ! date and time array
 integer,intent(out)            :: ierr     ! 0 for successful execution
DESCRIPTION
Converts a Unix Epoch Time (UET) to a DAT date-time array.
OPTIONS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC; of type real(kind=realtime).
RETURNS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
ierr Error code. If 0 no error occurred.
EXAMPLE
Sample program:
 program demo_unix_to_date
 use M_time, only : unix_to_date, u2d, fmtdate, realtime
 implicit none
 real(kind=realtime)           :: unixtime
 real(kind=realtime),parameter :: DAY=86400.0d0 ! seconds in a day
 integer                       :: dat(8)
 integer                       :: ierr
    unixtime=1468939038.4639933d0            ! sample Unix Epoch time
    call unix_to_date(unixtime,dat,ierr)     ! create DAT array for today
    write(*,*)'Sample Date=',fmtdate(dat)
    call unix_to_date(unixtime-DAY,dat,ierr) ! go back one day
    write(*,*)'Day Before =',fmtdate(dat)    ! subtract day and print
    call unix_to_date(unixtime+DAY,dat,ierr) ! go forward one day
    write(*,*)'Day After  =',fmtdate(dat)    ! add day print
 end program demo_unix_to_date
results:
 Sample Date=Tuesday, July 19th, 2016 10:37:18 AM
 Day Before =Monday, July 18th, 2016 10:37:18 AM
 Day After  =Wednesday, July 20th, 2016 10:37:18 AM
References date_to_julian(), false(), julian_to_date(), real, and secday.
v2mo()
character(len=:) function, allocatable, public m_time::v2mo (integer, intent(in) imonth)
NAME
v2mo - [M_time] returns the month name of a Common month number
SYNOPSIS
function v2mo(imonth) result(month_name)
 integer,intent(in)           :: imonth      ! month number (1-12)
 character(len=:),allocatable :: month_name  ! month name
DESCRIPTION
Given a Common Calendar month number, return the name of the month as a string.
OPTIONS
imonth Common month number (1-12). If out of the allowable range the month name returned will be 'UNKNOWN'.
RETURNS
month_name A string representing a month name or the word 'UNKNOWN'
EXAMPLE
Sample program:
 program demo_v2mo
 use M_time, only : v2mo
 implicit none
 integer :: i
    do i=1,13
       write(*,*)v2mo(i)
    enddo
 end program demo_v2mo
results:
 January
 February
 March
 April
 May
 June
 July
 August
 September
 October
 November
 December
 UNKNOWN.
w2d()
subroutine, public m_time::w2d (integer, intent(in) iso_year, integer, intent(in) iso_week, integer, intent(in) iso_weekday, integer, dimension(8), intent(out) dat)
NAME
w2d - [M_time] calculate DAT date-time array from iso-8601 Week-numbering year date yyyy-Www-d
SYNOPSIS
subroutine w2d(iso_year,iso_week,iso_weekday,dat)
 integer,intent(in)      :: iso_year, iso_week, iso_weekday
 integer,intent(out)     :: dat(8)     ! output date array
DESCRIPTION
Given an ISO-8601 week return a "DAT" array defining a date and time, The ISO-8601 is supplied as three integer values defining the ISO year, week of year and weekday.
OPTIONS
iso_year ISO-8601 year number for the given date iso_week ISO-8601 week number for the given date iso_weekday ISO-8601 weekday number for the given date iso_name ISO-8601 Week string for the data in the form "yyyy-Www-d".
RETURNS
dat "DAT" array (an integer array of the same format as the array returned by the intrinsic DATE_AND_TIME(3f)) describing the date to be used, which is the basic time description used by the other M_time(3fm) module procedures.
EXAMPLE
Sample program:
 program demo_w2d
 use M_time, only : w2d, fmtdate
 implicit none
    write(*,'(a)')Given Monday 29 December 2008 is written "2009-W01-1"'
    call printit(2009,1,1)
    write(*,'(a)')Given Sunday 3 January 2010 is written "2009-W53-7"'
    call printit(2009,53,7)
    write(*,'(a)')Given the Gregorian date Sun 31 December 2006 is written 2006-W52-7'
    call printit(2006,52,7)
    write(*,'(a)')Given 27 September 2008 is 2008-W39-6'
    call printit(2008,39,6)
 contains
 subroutine printit(iso_year,iso_week,iso_weekday)
 integer  :: iso_year, iso_week, iso_weekday ! ISO-8601 Week:   2016-W29-1
 integer  :: dat(8)                          ! input date array
    call w2d(iso_year,iso_week,iso_weekday,dat)
    write(*,'(a,i0)')'GIVEN:           '
    write(*,'(a,i0)')'ISO-8601 year    ',iso_year
    write(*,'(a,i0)')'ISO-8601 week    ',iso_week
    write(*,'(a,i0)')'ISO-8601 weekday ',iso_weekday
    write(*,'(a,i0)')'RESULT:          '
    write(*,'(a,*(i0:,","))')'   DAT array        ',dat
    write(*,'(a,/,77("="))')'    '//fmtdate(dat,'long')
 end subroutine printit
 end program demo_w2d
Results:
 Given Monday 29 December 2008 is written "2009-W01-1"
 GIVEN:
 ISO-8601 year    2009
 ISO-8601 week    1
 ISO-8601 weekday 1
 RESULT:
    DAT array        2008,12,29,-240,0,0,0,0
     Monday, December 29th, 2008 12:00:00 AM UTC-04:00
 =============================================================================
 Given Sunday 3 January 2010 is written "2009-W53-7"
 GIVEN:
 ISO-8601 year    2009
 ISO-8601 week    53
 ISO-8601 weekday 7
 RESULT:
    DAT array        2010,1,3,-240,0,0,0,0
     Sunday, January 3rd, 2010 12:00:00 AM UTC-04:00
 =============================================================================
 Given the Gregorian date Sun 31 December 2006 is written 2006-W52-7
 GIVEN:
 ISO-8601 year    2006
 ISO-8601 week    52
 ISO-8601 weekday 7
 RESULT:
    DAT array        2006,12,31,-240,0,0,0,0
     Sunday, December 31st, 2006 12:00:00 AM UTC-04:00
 =============================================================================
 Given 27 September 2008 is 2008-W39-6
 GIVEN:
 ISO-8601 year    2008
 ISO-8601 week    39
 ISO-8601 weekday 6
 RESULT:
    DAT array        2008,9,27,-240,0,0,0,0
     Saturday, September 27th, 2008 12:00:00 AM UTC-04:00
 =============================================================================
DEFINITION
The ISO-8601 date and time standard was issued by the International Organization for Standardization (ISO). It is used (mainly) in government and business for fiscal years, as well as in timekeeping. The system specifies a week year atop the Gregorian calendar by defining a notation for ordinal weeks of the year.
An ISO week-numbering year (also called ISO year informally) has 52 or 53 full weeks. That is 364 or 371 days instead of the usual 365 or 366 days. The extra week is referred to here as a leap week, although ISO-8601 does not use this term. Weeks start with Monday. The first week of a year is the week that contains the first Thursday of the year (and, hence, always contains 4 January). ISO week year numbering therefore slightly deviates from the Gregorian for some days close to January 1st.
METHOD
Calculating a date given the year, week number and weekday
This method requires that one know the weekday of 4 January of the year in question. Add 3 to the number of this weekday, giving a correction to be used for dates within this year.
Method: Multiply the week number by 7, then add the weekday. From this sum subtract the correction for the year. The result is the ordinal date, which can be converted into a calendar date. If the ordinal date thus obtained is zero or negative, the date belongs to the previous calendar year; if greater than the number of days in the year, to the following year.
Example: year 2008, week 39, Saturday (day 6) Correction for 2008: 5 + 3 = 8 (39 x 7) + 6 = 279 279 - 8 = 271 Ordinal day 271 of a leap year is day 271 - 244 = 27 September Result: 27 September 2008
ISO_NAME
Week date representations are in the format YYYYWww-D.
o [YYYY] indicates the ISO week-numbering year which is slightly different from the traditional Gregorian calendar year. o [Www] is the week number prefixed by the letter W, from W01 through W53. o [D] is the weekday number, from 1 through 7, beginning with Monday and ending with Sunday.
For example, the Gregorian date 31 December 2006 corresponds to the Sunday of the 52nd week of 2006, and is written
2006-W52-7 (extended form) or 2006W527 (compact form).
REFERENCE
From Wikipedia, the free encyclopedia 2016-08-08
AUTHOR
John S. Urban
References dow(), and o2d().
Variable Documentation
dt_day
real(kind=realtime), parameter, public m_time::dt_day =86400.0d0
dt_hour
real(kind=realtime), parameter, public m_time::dt_hour =3600.0d0
dt_minute
real(kind=realtime), parameter, public m_time::dt_minute =60.0d0
dt_week
real(kind=realtime), parameter, public m_time::dt_week =dt_day*7.0d0
realtime
integer, parameter, public m_time::realtime =kind(0.0d0)
secday
real(kind=realtime), parameter, private m_time::secday =86400.0d0 private