GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/nc_printunicode.f90 File Reference
nc_printunicode.f90 File Reference
Functions/Subroutines
subroutine nc_printunicode (win, filename)
Function/Subroutine Documentation
nc_printunicode()
subroutine nc_printunicode (type(c_ptr), intent(in) win, character(len=*), intent(in) filename)
References false(), file(), form, nc_errmessage(), true(), and unit().