GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/note.f90 File Reference
note.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
note - print large block letters
program block_letters
subroutine callfont (string)
Function/Subroutine Documentation
block_letters()
program block_letters ()
References blocks(), callfont(), help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_kracken::sget(), and m_messages::signs().
callfont()
subroutine block_letters::callfont (character(len=*) string)
References blocks(), m_kracken::sget(), and m_messages::signs().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
note - print large block letters
SYNOPSIS
 note STRING(S) [-font FontName] |-test|-help|-version
DESCRIPTION
Print strings as large block letters using the blocks(3f) or signs(3f) procedure.
OPTIONS
STRING(S) strings to print as large block letters –font alpha|banner select font style –test the selected character set is printed, one letter at a time. –help display this help and exit –version output version information and exit
EXAMPLE
 To generate a large banner enter
    note HELLO
    >  HH      HH  EEEEEEEEEE  LL          LL           OOOOOOOO
    >  HH      HH  EEEEEEEEEE  LL          LL          OOOOOOOOOO
    >  HH      HH  EE          LL          LL          OO     OOO
    >  HH      HH  EE          LL          LL          OO    O OO
    >  HHHHHHHHHH  EEEEE       LL          LL          OO   O  OO
    >  HHHHHHHHHH  EEEEE       LL          LL          OO  O   OO
    >  HH      HH  EE          LL          LL          OO O    OO
    >  HH      HH  EE          LL          LL          OOO     OO
    >  HH      HH  EEEEEEEEEE  LLLLLLLLLL  LLLLLLLLLL  OOOOOOOOOO
    >  HH      HH  EEEEEEEEEE  LLLLLLLLLL  LLLLLLLLLL   OOOOOOOO
References false().