GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/now.f90 File Reference
now.f90 File Reference
Functions/Subroutines
program display_date
subroutine usage ()
subroutine help_version (l_version)
Function/Subroutine Documentation
display_date()
program display_date ()
References d2u, m_time::days2sec(), m_kracken::dget(), fmtdate, m_time::fmtdate_usage(), m_time::guessdate(), help_version(), m_strings::isdigit(), m_strings::isspace(), m_time::j2d(), m_kracken::kracken(), m_kracken::lget(), m_time::now(), m_time::realtime, m_kracken::retrev(), m_kracken::sget(), m_strings::string_to_values(), u2d, and usage().
help_version()
subroutine display_date::help_version (logical, intent(in) l_version)
References false().
usage()
subroutine display_date::usage ()
References m_time::fmtdate_usage().