GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/paws.f90 File Reference
paws.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
paws - [TIME] pause until specified time or for specified duration
program demo_system_sleep
Function/Subroutine Documentation
demo_system_sleep()
program demo_system_sleep ()
References d2u, m_time::days2sec(), m_kracken::dget(), false(), fmtdate, m_time::guessdate(), help_usage(), help_version(), m_kracken::iget(), m_kracken::igets(), m_time::j2d(), m_kracken::kracken(), m_kracken::lget(), m_time::now(), m_time::realtime, m_kracken::sget(), m_time::system_sleep(), true(), and u2d.
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
paws - [TIME] pause until specified time or for specified duration
SYNOPSIS
paws [dd-hh:mm:ss[.xxx]|xxx.yyy[s|m|h|d]][-msg message][-cmd command][-repeat TIMES[-fmt ]]|...
[-uet|-jed|-dat|[-date|-until]]
paws --version|--help
DESCRIPTION
Given a duration in the form dd-hh:mm:ss.xxx where dd is days, hh hours, mm minutes and ss.xxx seconds convert it to seconds. Then, pause for that many seconds. Alternatively, pause until specified date has passed. If no duration is specified wait until a carriage return is entered.
OPTIONS
dd-hh:mm:ss Given a string representing a duration of time in the following forms:
dd-hh:mm:ss[.xx] hh:mm:ss[.xx] mm:ss[.xx] ss[.xx] or xx[.yy]SUFFIX
convert it to seconds and pause for that amount of time. Suffix may be s for seconds, m for minutes, h for hours, or d for days. -date|-until wait until the specified date has passed (before starting optional pause). See guessdate(3f) for syntax allowed for the date. -uet wait until the specified Unix Epoch Time has passed -jed wait until the specified Julian Ephemeris Date has passed -dat wait until the specified date vector has passed (year month day timezone hour minutes seconds milliseconds) -repeat NNN The duration is repeated NNN times with the date displayed at the end of each pause. –msg message to display before pausing –cmd command to execute after a pause –fmt date format (see fmtdate(3f) for details) –help display this help and exit –version output version information and exit
For more information on the format of the dates, see the now(1) command.
EXAMPLE
Typical usage:
paws 2:00:00 # pause for two hours paws 3600 # pause one hour paws 0.10 # pause one tenth of a second paws 1 -repeat 60 # pause sixty seconds, display the date each second paws -until 23:59:59 # pause until midnight paws 15:00 -date 23:59:59 # pause till midnight then an additional 15 minutes
References false().