GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/pendulum.f90 File Reference
pendulum.f90 File Reference
Modules
module m_geometry
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
pendulum(1f) - [PHYSICS] calculate pendulum period
subroutine, public m_geometry::pendulum_period (L, f, T, VERBOSE)
subroutine, public m_geometry::pendulum_time (L, f, T, VERBOSE)
program pendulum_test
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
pendulum(1f) - [PHYSICS] calculate pendulum period
SYNOPSIS
pendulum [-length Length_In_Feet ][-verbose]|[--help]|[--version]
DESCRIPTION
Given the length to the center of gravity from the fulcrum (pivot point) of a pendulum in feet calculate the pendulum frequency in swings/sec, and how long the swing takes (the period of the pendulum).
If the pendulum weight or bob of a simple pendulum is pulled to a relatively small angle and let go, it will swing back and forth at a regular frequency. If damping effects from air resistance and friction are negligible, equations concerning the frequency and period of the the pendulum, as well as the length of the string can be calculated.
The period of the motion for a pendulum is how long it takes to swing back-and-forth, measured in seconds. The period equation is:
T = 2*PI*sqrt(L/g)
The frequency of a pendulum is how many back-and-forth swings there are in a second, measured in hertz. Frequency f is the reciprocal of the period T:
f = 1/T
Therefore in terms of the length the frequency is
f = [âsqrt(g/L)]/2
The length equations are:
L = g/(4*PI**2*f**2) and
L = (g*T**2)/(4*PI**2)
The generally accepted length of a seconds pendulum at sea level, lat. 45 degrees, is 99.356 cm or 39.116 in. = 3.25966 feet.
OPTIONS
-length Length_In_Feet distance from pivot point to center of gravity of pendulum. -verbose [T|F] verbose mode, default is .true. . –help display this help and exit –version output version information and exit
EXAMPLES
Sample command lines ...
A 1/4 of a meter pendulum has a period of about 1 second.
pendulum -length 0.820209980 For a pendulum with length 0.820209980 feet The frequency of the pendulum is 0.996806502 swings/sec. Each swing takes 1.00320375 sec.
pendulum -length 3.00 For a pendulum with length 3.00000000 feet The frequency of the pendulum is 0.287753224 swings/sec. Each swing takes 3.47519994 sec.
References false().
pendulum_test()
program pendulum_test ()
References help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_geometry::pendulum_period(), m_kracken::rget(), m_kracken::sget(), and true().