GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/penv.f90 File Reference
penv.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
penv(1f) - print all or part of environment in formats readable by various shells
SYNOPSIS
program penv
subroutine printformatted ()
character(len=:) function, allocatable printquoted_sh (string)
character(len=:) function, allocatable printquoted_csh (string)
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
penv(1f) - print all or part of environment in formats readable by various shells
SYNOPSIS
penv [variable...] [-C|-B] [-p PREFIX] [-v] penv [–help|–version]
DESCRIPTION
If no arguments are given, penv(1f) prints the entire environment. If one or more variable names are given, it prints the value of each one that is set, and nothing for each one that is not set.
If the -p switch is used variables beginning with that prefix will be displayed.
OPTIONS
-C print output in a form that can be sourced into a C shell (eg. as a setenv(1) command). -B print output in a form that can be sourced into a Bourne shell. -p print only variables with the given prefix -v values only. Do not print variable names variable(s) if variable names are given, print the value for each one that is set. –help display this help and exit –version output version information and exit
USAGE
Example commands:
penv # print entire environment penv -p PREFIX # print environment variables beginning with PREFIX penv HOME TMP LOGNAME USER # print selected variables
csh(1)/tcsh(1) example:
% penv -C > readme.csh % source readme.csh
sh(1)/bash(1)/zsh(1) ... example:
$ penv -B > readme.sh $ . readme.sh
print specified variable names
% penv TMP TEMPDIR TMPDIR TEMP
print variables starting with A or H
% penv -p A H
EXIT STATUS
The exit status is:
0 if all variables specified were found 1 otherwise
SEE ALSO
env(1), printenv(1)
References false().
penv()
program penv ()
References false(), help_usage(), help_version(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), printformatted(), m_kracken::sget(), m_kracken::sgets(), m_system::system_clearenv(), m_system::system_putenv(), m_system::system_readenv(), m_system::system_unsetenv(), and true().
printformatted()
subroutine penv::printformatted ()
References printquoted_csh(), and printquoted_sh().
printquoted_csh()
character(len=:) function, allocatable penv::printquoted_csh (character(len=*), intent(in) string)
printquoted_sh()
character(len=:) function, allocatable penv::printquoted_sh (character(len=*), intent(in) string)