GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/pixel_slice.f90 File Reference
pixel_slice.f90 File Reference
Functions/Subroutines
subroutine pixel_slice (surfdat, kix, kiz, nx, nz, a0, b0)
NAME
pixel_slice(3f) - [M_pixel] simplified call of DL_SLICES(3f) to make a plot of a 3-d surface
Function/Subroutine Documentation
pixel_slice()
subroutine pixel_slice (real, dimension(kix,kiz), intent(in) surfdat, integer, intent(in) kix, integer, intent(in) kiz, integer, intent(in) nx, integer, intent(in) nz, real, intent(in) a0, real, intent(in) b0)
NAME
pixel_slice(3f) - [M_pixel] simplified call of DL_SLICES(3f) to make a plot of a 3-d surface
SYNOPSIS
subroutine pixel_SLICE(surfdat,kix,kiz,nx,nz,a0,b0)
real,intent(in) :: SURFDAT(kix,kiz) integer,intent(in) :: kix integer,intent(in) :: kiz integer,intent(in) :: nx integer,intent(in) :: nz real,intent(in) :: a0 real,intent(in) :: b0
DESCRIPTION
Simplified call to DL_SLICES(3f) to make a plot of a 3-d surface
OPTIONS
SURFDAT(kix,kiz) array of y values KIX,KIZ dimension of surfdat array NX,NZ size of surface to plot A0 initial angle of x axis from horizontal 0-80 degrees B0 initial angle of z axis from horizontal 5-80 degrees
EXAMPLE
References m_pixel::clear(), m_pixel::color(), m_pixel_slices::dl_init(), m_pixel_slices::dl_slices(), m_pixel_slices::dl_symbol(), and m_pixel::linewidth().