GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/planets.f90 File Reference
planets.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
program planets
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
planets(1f) - [FUNIX] ephemeris position of planets for adjusting an equatorial telescope
SYNOPSIS
planets yyyy mm dd utc hh mm ss [-planet [N|name] ]
DESCRIPTION
planets(1) calculates the ephemeris of a planet in our solar system
in order to  adjust an equatorial telescope. See ephemeris(3f) for
more details. The outputs are
  o Ascent in hours (0 to 24) and minutes (0 to 60)
  o Declination in degrees and minutes (-90 to 90 North or South)
OPTIONS
  date    provide the same eight values used by the DATE_AND_TIME(3f) intrinsic.
    ·     value(1)  The year
       ·  value(2)  The month
       ·  value(3)  The day of the month
       ·  value(4)  Time difference with UTC in minutes
       ·  value(5)  The hour of the day
       ·  value(6)  The minutes of the hour
       ·  value(7)  The seconds of the minute
       ·  value(8)  The milliseconds of the second
  N|Name  Planet numbers in range 1 to 8 (Mercury:1 Venus:2 Mars:4
          Jupiter:5 Saturn:6 Uranus:7 Neptune:8). If not specified
          the default is "1 2 4 5 6 7 8".
EXAMPLE
(Find ascent and declination of planet Mars on March 10th, 1982 at 6h UT)
 planets 1982 03 10 00 06 00 00 00  -planet  4
  Wednesday, March 10th, 1982 6:00:00 AM UTC+00:00
  Planet: 4  Ascent: 13 H  8 MN  Declination:  3 D 45 MN S
 no planet number(s) specified:
 planets 1982 03 10 00 06 00 00 00
  Wednesday, March 10th, 1982 6:00:00 AM UTC+00:00
  Planet: 1  Ascent: 21 H 51 MN  Declination: 14 D 45 MN S
  Planet: 2  Ascent: 20 H 26 MN  Declination: 14 D 57 MN S
  Planet: 4  Ascent: 13 H  8 MN  Declination:  3 D 45 MN S
  Planet: 5  Ascent: 14 H 32 MN  Declination: 13 D 30 MN S
  Planet: 6  Ascent: 13 H 22 MN  Declination:  5 D 42 MN S
  Planet: 7  Ascent: 16 H 11 MN  Declination: 20 D 54 MN S
  Planet: 8  Ascent: 17 H 46 MN  Declination: 22 D  7 MN S
References false().
planets()
program planets ()
References m_time::ephemeris(), fmtdate, m_time::guessdate(), help_usage(), help_version(), m_kracken::iget(), m_kracken::igets(), m_kracken::kracken(), m_kracken::lget(), and m_kracken::sget().