GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/quadratic.f90 File Reference
quadratic.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
quadratic(1f) - [MATH] Calculate and print the roots of a quadratic formula even if they are complex
program demo_quadratic
Function/Subroutine Documentation
demo_quadratic()
program demo_quadratic ()
References c(), help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_math::quadratic(), and m_kracken::rgets().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
quadratic(1f) - [MATH] Calculate and print the roots of a quadratic formula even if they are complex
SYNOPSIS
    quadratic A B C |[--help|--version]
DESCRIPTION
Given the equation
A*x**2 + B*x + C = 0
Use the quadratic formula to determine the root values of the equation.
OPTIONS
A,B,C coefficients
EXAMPLE
Sample usage:
quadratic 1.0 5.0 2.0 for 1.00000000 *x**2+ 5.00000000 *x+ 2.00000000 =0 the roots are real: z1 = -0.438447237 z2 = -4.56155300 discriminant = 17.0000000
quadratic 1.0 2.0 5.0 # There are no real roots (Discriminant = -16)! for 1.00000000 *x**2+ 2.00000000 *x+ 5.00000000 =0 the roots are complex: z1 = (-1.00000000 , 2.00000000) z2 = (-1.00000000 , -2.00000000) discriminant = -16.0000000
quadratic 9 12 4 for 9*x**2 + 12*x + 4 = 0 the roots are real and equal: z1 = z2 = -0.666666687 discriminant = 0.00000000
References false().