GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/rep.f90 File Reference
rep.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
rep(1) - [FILE FILTER] replace fixed strings in files
SYNOPSIS
program rep
subroutine dofile ()
Function/Subroutine Documentation
dofile()
subroutine rep::dofile ()
References file(), form, m_io::readline(), m_strings::replace(), m_debug::stderr(), m_system::system_perror(), m_system::system_remove(), m_system::system_rename(), and unit().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
rep(1) - [FILE FILTER] replace fixed strings in files
SYNOPSIS
rep filenames -c /from/to/ [-verbose][-dryrun]|[-help|-version]
DESCRIPTION
This is an example program for the REPLACE(3f) function. It still has some flaws.
The rep(1) utility changes strings in-place in files.
files named on the command are modified in-place, so you may want to make a copy of the original before converting it. rep(1) prints a message indicating which of the input files it actually modifies.
Do not change binary files with this program, which uses sequential access to read and write the files. It can corrupt binary files.
It does not yet create unique scratch filenames in a way that will work if more than one instance of the command is running and file leaves are the same.
OPTIONS
-c /from/to/ "from" represents a string to look for and "to" represents its replacement. -verbose Print information about what the program does. –help Display a help message and exit. –version Display version information and exit. –dryrun Does all file operations except for moving the changed file back to the original. Implies –version.
References false().
rep()
program rep ()
References dofile(), help_usage(), help_version(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::kracken_comment, m_kracken::lget(), m_strings::replace(), m_kracken::sget(), m_kracken::sgets(), and true().