GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/rever.f90 File Reference
rever.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
rever(1f) - [FILE FILTER] print file in reverse
program rever
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
rever(1f) - [FILE FILTER] print file in reverse
SYNOPSIS
    rever INPUT_FILE [OUTPUT_FILE] [-help][-version]
DESCRIPTION
Read entire file into memory as a stream and write it in reverse byte order
SEE ALSO
tac(1), rev(1)
References false().
rever()
program rever ()
References file(), help_usage(), help_version(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), m_io::notopen(), m_kracken::sgets(), m_io::slurp(), m_strings::split(), m_debug::stderr(), and unit().