GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/sec2days.f90 File Reference
sec2days.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
sec2days - [TIME] Convert seconds to string of form dd-hh:mm:ss
program demo_sec2days
Function/Subroutine Documentation
demo_sec2days()
program demo_sec2days ()
References help_usage(), help_version(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), m_time::realtime, m_time::sec2days(), m_kracken::sget(), and m_strings::substitute().
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
sec2days - [TIME] Convert seconds to string of form dd-hh:mm:ss
SYNOPSIS
sec2days nnnn[.xxx] [-crop]| --version| --help
DESCRIPTION
Given a numeric string representing seconds convert it to a string of the form
dd-hh:mm:ss
where dd is days, hh hours, mm minutes and ss seconds.
OPTIONS
nnnn[.xxx] number of seconds to convert to string of form dd-hh:mm:ss. nnnn may be interspersed with unit codes d,h,m,s. Spaces, commas and case are ignored. Allowed aliases for the unit codes are d days and day h hours,hour,hrs, and hr m minutes,minute and min s seconds,second and sec
-crop trim leading zero values from output -radix character used as decimal separator –help display this help and exit –version output version information and exit
EXAMPLE
usage
sec2days 129860 1-12:04:20 sec2days 1d2h3m4s 1-02:03:04 sec2days 1.0 days 2 hours 3 minutes 4 seconds 1-02:03:04 sec2days 1.5d 1-12:00:00
References false().