GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/sparanoia.f90 File Reference
sparanoia.f90 File Reference
Functions/Subroutines
subroutine sparanoia ()
subroutine runtests ()
subroutine commut (NUMTRY)
subroutine random (X, Y, X9, R9)
subroutine extra
subroutine guard
subroutine intro (MILES)
subroutine logit (MILE)
subroutine cmpxy (X, Y, Z, Q, N)
subroutine prt2 (N, MILES)
subroutine pwrcmp (X, Z, I, M, N)
subroutine prtcnt (N)
subroutine badsqr (SFLAG, Z, Y)
subroutine overf (MILES, FROM)
subroutine page (MILE)
subroutine partuf (Z, ZNAME, MILES, PARTU, RESTRT)
subroutine power (MILES, FROM)
subroutine radx (MILES)
subroutine round (MILES)
subroutine smlint (MILES, FROM)
subroutine square (FROM, MILES, NUMTRY)
subroutine sqrerr (X, U, J, E5, E7, SEROUS)
subroutine newd (X, Z1, Q, Z, D)
subroutine sqrtdx (X, Z2, I, D, Y2, Y, X8, E5, E7)
subroutine underf (MILES, NUMTRY, FROM)
subroutine zeros (MILES, FROM)
subroutine badmil
Function/Subroutine Documentation
badmil()
subroutine sparanoia::badmil ()
badsqr()
subroutine sparanoia::badsqr (integer SFLAG, real Z, real Y)
cmpxy()
subroutine sparanoia::cmpxy (real X, real Y, real Z, integer Q, integer N)
commut()
subroutine sparanoia::commut (integer NUMTRY)
References random().
extra()
subroutine sparanoia::extra ()
guard()
subroutine sparanoia::guard ()
intro()
subroutine sparanoia::intro (integer MILES)
References page().
logit()
subroutine sparanoia::logit (integer MILE)
newd()
subroutine sparanoia::newd (real X, real Z1, real Q, real Z, real D)
overf()
subroutine sparanoia::overf (integer MILES, integer FROM)
References badmil(), badsqr(), logit(), and page().
page()
subroutine sparanoia::page (integer MILE)
partuf()
subroutine sparanoia::partuf (real Z, character(len=8) ZNAME, integer MILES, integer PARTU, logical RESTRT)
References logit(), and page().
power()
subroutine sparanoia::power (integer MILES, integer FROM)
References badmil(), prt2(), prtcnt(), and pwrcmp().
prt2()
subroutine sparanoia::prt2 (integer N, integer MILES)
References page().
prtcnt()
subroutine sparanoia::prtcnt (integer N)
pwrcmp()
subroutine sparanoia::pwrcmp (real X, real Z, integer I, integer M, integer N)
References cmpxy().
radx()
subroutine sparanoia::radx (integer MILES)
random()
subroutine sparanoia::random (real X, real Y, real X9, real R9)
round()
subroutine sparanoia::round (integer MILES)
runtests()
subroutine sparanoia::runtests ()
References badmil(), commut(), extra(), file(), form, guard(), intro(), overf(), page(), power(), radx(), round(), smlint(), square(), underf(), and zeros().
smlint()
subroutine sparanoia::smlint (integer MILES, integer FROM)
References badmil(), and partuf().
sparanoia()
subroutine sparanoia ()
References runtests().
sqrerr()
subroutine sparanoia::sqrerr (real X, real U, integer J, real E5, real E7, logical SEROUS)
sqrtdx()
subroutine sparanoia::sqrtdx (real X, real Z2, integer I, real D, real Y2, real Y, real X8, real E5, real E7)
square()
subroutine sparanoia::square (integer FROM, integer MILES, integer NUMTRY)
References badmil(), false(), logit(), newd(), page(), sqrerr(), sqrtdx(), and true().
underf()
subroutine sparanoia::underf (integer MILES, integer NUMTRY, integer FROM)
References badmil(), cmpxy(), logit(), page(), partuf(), prt2(), and prtcnt().
zeros()
subroutine sparanoia::zeros (integer MILES, integer FROM)
References badmil(), and logit().