GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/splitname.f90 File Reference
splitname.f90 File Reference
Functions/Subroutines
program demosplitname
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
splitname(1f) - [FUNIX] strip pathname into components {dir,name,basename,extension}
Function/Subroutine Documentation
demosplitname()
program demosplitname ()
References help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_kracken::sgets(), m_strings::split(), and m_io::splitpath().
help_usage()
subroutine demosplitname::help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine demosplitname::help_version (logical, intent(in) l_version)
NAME
splitname(1f) - [FUNIX] strip pathname into components {dir,name,basename,extension}
SYNOPSIS
splitname [NAME1 NAME2 ... |-help|-version]
DESCRIPTION
Output each pathname broken into components dir, name, basename, extension
OPTIONS
NAMES pathnames to split -help display this help and exit -version output version information and exit
EXAMPLES
Sample program executions:
  splitname /usr/bin/          -> "/usr/bin" "" "" ""
  splitname /usr/bin           -> "/usr" "bin" "" ""
  splitname stdio.h            -> "" "studio.h" "studio" ".h"
SEE ALSO
splitname(1), basename(1), readlink(1), realpath(1)
References false().