GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/strgar3.f90 File Reference
strgar3.f90 File Reference
Functions/Subroutines
subroutine strgar3 (line, iread, default, numbrs, inums, delims, delimc, ierr)
subroutine common ()
doubleprecision function errc (curve, top, bottom)
Function/Subroutine Documentation
common()
subroutine strgar3::common ()
References m_calculator_plus::jucalcx().
errc()
doubleprecision function errc (real(kind=dp), intent(in) curve, real(kind=dp), intent(in) top, real(kind=dp), intent(in) bottom)
strgar3()
subroutine strgar3 (character(len=*), intent(in) line, integer, intent(in) iread, real, intent(in) default, real, dimension(iread,4), intent(out) numbrs, integer, intent(out) inums, character(len=1), intent(in) delims, character(len=1), intent(in) delimc, integer, intent(out) ierr)
References common(), m_calculator::iclen_calc, and m_calculator_plus::jucalcx().