GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/t2m.f90 File Reference
t2m.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
t2m - [DEVELOPER] basic markup of text to a man(1) page
program test_t2m
subroutine t2m (table, title, section, product)
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
t2m - [DEVELOPER] basic markup of text to a man(1) page
SYNOPSIS
t2m FILE -cmd -section 1 -product "" -help .F. -version .F.
DESCRIPTION
Minimalist conversion of a text file to a man page. Lines that are all upper-case starting in column 1 start a section. Otherwise the sections are printed essentially as-is.
OPTIONS
FILE The input filename
-section N N is the man(1) section number. Typically the following categories are used:
User Commands 1 Executable programs or shell commands System Calls 2 System calls (functions provided by the kernel) Library Calls 3 Library calls (functions within program libraries) Special Files 4 Special files (usually found in /dev) File Formats 5 File formats and conventions (eg. /etc/passwd) Games 6 Games Miscellaneous 7 Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7) System Admin. 8 System administration commands (usually only for root) Kernel Extensions 9 Kernel routines [Non standard]
See the man(1) page for man(1) for further details.
-cmd -product -help display help and exit -version display version information and exit
References false().
t2m()
subroutine test_t2m::t2m (character(len=*), dimension(:), intent(in) table, character(len=*), intent(in) title, integer, intent(in) section, character(len=*), intent(in) product)
References m_strings::indent(), m_strings::notabs(), m_time::now(), m_strings::s2v(), m_strings::substitute(), and m_strings::upper().
test_t2m()
program test_t2m ()
References file(), help_usage(), help_version(), m_kracken::iget(), m_kracken::ipvalue, m_kracken::kracken(), m_kracken::lget(), m_kracken::sget(), m_kracken::sgets(), t2m(), and unit().