GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/temp.f90 File Reference
temp.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
subroutine help_version (l_version)
NAME
temp - [CONVERT] Convert between Fahrenheit and Celsius temperature values
program temp
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
temp - [CONVERT] Convert between Fahrenheit and Celsius temperature values
SYNOPSIS
temp [-C values] [-F values] [--help] [--version]
DESCRIPTION
-C values  Display the given Celsius values as both Celsius and
           Fahrenheit values
-F values  Display the given Fahrenheit values as both Celsius and
           Fahrenheit values. If no values are given a small table of
           common temperatures is displayed.
--help     display this help and exit
--version  output version information and exit
At the physically impossible-to-reach temperature of zero Kelvin,
or minus 459.67 degrees Fahrenheit (minus 273.15 degrees Celsius),
atoms would stop moving. As such, nothing can be colder than absolute
zero on the Kelvin scale.
EXAMPLE
Sample program runs:
temp -C -40 0 37 100 Celsius Fahrenheit -40.00C -40.00F 0.00C 32.00F 37.00C 98.60F 100.00C 212.00F
temp -F -459.67 32 98.60 212 Fahrenheit Celsius -459.67F -273.15C 32.00F 0.00C 98.60F 37.00C 212.00F 100.00C
References false().
temp()
program temp ()
References help_usage(), help_version(), m_kracken::kracken(), m_kracken::lget(), m_kracken::rgets(), m_kracken::sget(), and true().