GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/today.f90 File Reference
today.f90 File Reference
Functions/Subroutines
subroutine help_version (l_version)
NAME
today(1f) - [TIME] output current time for uses such as file suffixes.
SYNOPSIS
program today
Function/Subroutine Documentation
help_version()
subroutine help_version (logical, intent(in) l_version)
NAME
today(1f) - [TIME] output current time for uses such as file suffixes.
SYNOPSIS
today [format]
DESCRIPTION
Outputs the current date using the specified format. Typically used to generate a string to be used in building filenames containing date information.
OPTIONS
format any allowable format for the fmtdate(3) routine. Enter "-" to get a list on stdout. defaults to "YMD".
EXAMPLE
    Sample commands:
     cp myfile myfile.`today`
     find . -ls > MANIFEST.`today epoch`
     mkdir `today YMDhms`
     today -                              # show formatting options
References false().
today()
program today ()
References m_time::fmtdate_usage(), and m_time::now().