GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/ufpp.f90 File Reference
ufpp.f90 File Reference
Data Types
type m_fpp::file_stack
Modules
module m_fpp
<html> <head> <title> ufpp </title> <link rel="stylesheet" type="text/css" href="StyleSheets/man.css" title="Local"> <meta name="description" content="Fortran module containing library of date and time procedures"> <meta name="keywords" content="date_and_time,date,time,gregorian,julian,epoch time,day of week, ordinal day"> <meta name="keywords" content="week of year"> <meta name="keywords" content="Fortran,module,library,repository,collection"> <script src="../../../javascript/toggleHidden.js" type="text/javascript"></script> </head> <body>
Functions/Subroutines
subroutine m_fpp::cond ()
subroutine m_fpp::exe ()
subroutine m_fpp::ident (opts)
subroutine m_fpp::output_case (opts)
subroutine m_fpp::define (opts, ireset)
character(len=17) function m_fpp::getdatetimestr ()
subroutine m_fpp::printenv (opts)
subroutine m_fpp::name (line)
subroutine m_fpp::getval (line, ipos1, ipos2, value)
subroutine m_fpp::undef (opts)
subroutine m_fpp::if (opts, noelse, eb)
subroutine m_fpp::def (verb, opts, noelse, eb)
subroutine m_fpp::ifdef (line, ipos1)
subroutine m_fpp::else (verb, opts, noelse, eb)
subroutine m_fpp::endif (noelse, eb)
subroutine m_fpp::parens (line)
subroutine m_fpp::math (line, ipos1, ipos2)
subroutine m_fpp::domath (line, ipos2)
subroutine m_fpp::doop (line, ipos1, ipos2)
logical function m_fpp::trufal (line, ipos1, ipos2)
subroutine m_fpp::logic (line, ipos1, ipos2)
subroutine m_fpp::eval (line)
integer function m_fpp::get_integer_from_string (line, ipos1, ipos2)
subroutine m_fpp::rewrit (line, temp, j, j1, l, l1)
subroutine m_fpp::document (opts)
subroutine m_fpp::stop (opts)
subroutine m_fpp::print_comment_block ()
subroutine m_fpp::format_g_man ()
subroutine m_fpp::stops (iexit)
subroutine m_fpp::debug (msg)
subroutine m_fpp::write_arguments ()
subroutine m_fpp::include (line, iunit)
subroutine m_fpp::findit (line)
subroutine m_fpp::opens ()
subroutine m_fpp::includes ()
subroutine m_fpp::defines ()
subroutine m_fpp::stop_ufpp (message)
subroutine m_fpp::help_usage (l_help)
subroutine m_fpp::help_version (l_version)
NAME
ufpp(1) - [DEVELOPER] pre-process FORTRAN source files
subroutine m_fpp::write_out (line)
subroutine m_fpp::www (line)
program ufpp
Variables
integer, parameter m_fpp::num =2048
integer, parameter, public m_fpp::g_line_length =4096
integer, parameter, public m_fpp::g_var_len =31
integer, public m_fpp::g_numdef =0
character(len=g_line_length), public m_fpp::g_source
character(len=g_line_length), public m_fpp::g_outline
character(len=g_var_len), dimension(num), public m_fpp::g_defval
character(len=g_var_len), dimension(num), public m_fpp::g_defvar
type(file_stack), dimension(50) m_fpp::g_file_dictionary
type(streampointer) m_fpp::g_fp
character(len=:), allocatable m_fpp::g_scratch_filename
integer, public m_fpp::g_iocount =0
integer, public m_fpp::g_io_total_lines =0
integer, public m_fpp::g_iwidth
logical, public m_fpp::g_noenv =.false.
integer, public m_fpp::g_iout
integer, save, public m_fpp::g_iout_init
integer, public m_fpp::g_ihelp =OUTPUT_UNIT
character(len=10), public m_fpp::g_outtype ='asis'
integer, public m_fpp::g_inc_count =0
character(len=g_line_length), dimension(50), public m_fpp::g_inc_files
character(len=:), allocatable, save m_fpp::g_man
logical, save m_fpp::g_man_collect =.false.
logical, save m_fpp::g_man_print =.false.
character(len=:), allocatable m_fpp::g_man_file
character(len=10) m_fpp::g_man_file_position ='ASIS '
integer, public m_fpp::g_nestl =0
integer, parameter, public m_fpp::g_nestl_max =20
logical, save, public m_fpp::g_html_switch =.false.
logical, save, public m_fpp::g_write_what =.false.
logical, save, public m_fpp::g_system_on =.false.
logical, dimension(0:g_nestl_max), save, public m_fpp::g_condop
logical, public m_fpp::g_dc
logical, public m_fpp::g_write =.true.
logical, public m_fpp::g_llwrite =.true.
integer, public m_fpp::g_comment_count =0
character(len=10), public m_fpp::g_comment_style =' '
Function/Subroutine Documentation
ufpp()
program ufpp ()
References m_fpp::cond(), m_fpp::defines(), false(), file(), m_fpp::g_comment_style, m_fpp::g_file_dictionary, m_fpp::g_html_switch, m_fpp::g_ihelp, m_fpp::g_inc_files, m_fpp::g_io_total_lines, m_fpp::g_iocount, m_fpp::g_iout, m_fpp::g_iout_init, m_fpp::g_iwidth, m_fpp::g_line_length, m_fpp::g_llwrite, m_fpp::g_nestl, m_fpp::g_noenv, m_fpp::g_source, m_fpp::g_system_on, m_fpp::g_write, m_fpp::g_write_what, help_usage(), help_version(), m_kracken::iget(), m_fpp::includes(), m_strings::isdigit(), m_kracken::kracken(), m_kracken::kracken_comment, m_kracken::lget(), m_strings::notabs(), m_fpp::opens(), m_fpp::print_comment_block(), m_kracken::retrev(), m_kracken::rget(), m_kracken::sget(), m_fpp::stop_ufpp(), unit(), and m_fpp::write_out().