GeneralPurposeFortran: LIBRARY/libGPF/download/tmp/PROGRAMS/xauth_key.f90 File Reference
xauth_key.f90 File Reference
Functions/Subroutines
subroutine help_usage (l_help)
program xauth_key
NAME
xauth_key - generate magic cookies for xauth
SYNOPSIS
subroutine help_version (l_version)
Function/Subroutine Documentation
help_usage()
subroutine help_usage (logical, intent(in) l_help)
References false().
help_version()
subroutine xauth_key::help_version (logical, intent(in) l_version)
References false().
xauth_key()
program xauth_key ()
NAME
xauth_key - generate magic cookies for xauth
SYNOPSIS
xauth_key [characters] [-n number_of_characters]
DESCRIPTION
xauth_key generates a random hexadecimal number
characters Set of letters to compose string from. Defaults to '0123456789abcdef'. -n Number of digits. Defaults to 128 –version Display version information and exit. –help Display help text and exit.
EXAMPLE
# generate a value for use with the X authority system.
xauth add :0 . `xauth_key`
SEE ALSO
X(1), xauth(1)
References help_usage(), help_version(), m_kracken::iget(), m_random::init_random_seed_by_dat(), m_kracken::kracken(), m_kracken::lget(), m_random::random_hex(), m_random::random_string(), and m_kracken::sget().